import { defineDict } from '@/i18n';

/** Strings for the CMS collections list + editor (PDF p.14) — ME / SQ / EN. */
export const cd = defineDict({
  me: {
    title: 'Kolekcije',
    create: 'Kreiraj kolekciju',
    tab_all: 'Sve',
    tab_manual: 'Ručne',
    tab_smart: 'Po uslovima',
    searchPh: 'Pretraži kolekcije…',
    col_title: 'Kolekcija',
    col_type: 'Tip',
    col_conditions: 'Uslovi / izbor',
    col_products: 'Proizvodi',
    col_status: 'Status',
    col_usage: 'Koristi se',
    type_manual: 'Ručna',
    type_smart: 'Po uslovima',
    st_published: 'Objavljena',
    st_draft: 'Nacrt',
    manualCount: '{n} izabranih proizvoda',
    matchAll: 'svi uslovi',
    matchAny: 'bilo koji uslov',
    publicCount: '{n} javno',
    hiddenCount: '+{n} skriveno',
    usageN: '{n}×',
    footerCount: '{n} kolekcija',
    emptyTitle: 'Još nema kolekcija',
    emptyText: 'Kolekcije grupišu proizvode za katalog, ponude i početnu stranicu — ručno ili po uslovima.',
    noResults: 'Nema kolekcija za ovu pretragu',
    noResultsText: 'Promijenite pretragu ili tab.',
    viewOnSite: 'Pogledaj na sajtu',
    edit: 'Uredi',
    open: 'Otvori',
    duplicate: 'Dupliraj',
    duplicated: 'Kopija je kreirana kao nacrt',
    copySuffix: '(kopija)',
    delete: 'Obriši',
    moreActions: 'Više akcija',
    deleteTitle: 'Obrisati kolekciju „{name}“?',
    deleteText: 'Proizvodi ostaju u katalogu; kolekcija nestaje sa sajta. Ova radnja se ne može poništiti.',
    deleteUsed: 'Pažnja — koristi je: {list}.',
    deleted: 'Kolekcija je obrisana',
    noPerm: 'Vaša uloga nema ovu dozvolu',
    newTitle: 'Nova kolekcija',
    notFound: 'Kolekcija nije pronađena',
    notFoundText: 'Možda je obrisana ili link nije ispravan.',
    backToList: 'Nazad na kolekcije',
    c_title: 'Naziv i opis',
    f_title: 'Naziv',
    f_desc: 'Opis',
    f_desc_h: 'Prikazuje se na vrhu stranice kolekcije.',
    c_type: 'Tip kolekcije',
    manual_title: 'Ručna',
    manual_h: 'Sami birate proizvode i njihov redoslijed — urednički izbor.',
    smart_title: 'Po uslovima',
    smart_h: 'Proizvodi koji ispunjavaju uslove ulaze sami — i izlaze kad se cijena ili oznake promijene.',
    copyMatches: 'Prenesi {n} proizvoda koji sada ispunjavaju uslove',
    copied: 'Preneseno proizvoda: {n}',
    c_conditions: 'Uslovi',
    match_label: 'Proizvodi moraju ispuniti',
    match_all: 'sve uslove',
    match_any: 'bilo koji uslov',
    addRule: 'Dodaj uslov',
    noRules: 'Dodajte bar jedan uslov — npr. Kategorija je Podovi.',
    field_category: 'Kategorija',
    field_price: 'Cijena',
    field_compareAt: 'Referentna cijena',
    field_stock: 'Zalihe',
    field_status: 'Status proizvoda',
    field_tag: 'Oznaka',
    field_title: 'Naziv',
    field_vendor: 'Dobavljač',
    field_onSale: 'Na akciji',
    field_badge: 'Oznaka na kartici',
    op_eq: 'je',
    op_neq: 'nije',
    op_gt: 'veće od',
    op_lt: 'manje od',
    op_contains: 'sadrži',
    yes: 'Da',
    no: 'Ne',
    valuePh: 'Vrijednost',
    removeRule: 'Ukloni uslov',
    liveNote: 'Promjena cijene ili oznake proizvoda automatski ažurira ovu kolekciju — bez ručnog dodavanja.',
    c_products: 'Proizvodi',
    sort_label: 'Redoslijed',
    sort_manual: 'Ručno',
    sort_bestselling: 'Najprodavanije',
    'sort_price-asc': 'Cijena: niža prvo',
    'sort_price-desc': 'Cijena: viša prvo',
    sort_newest: 'Najnovije',
    sortNote: 'Za ručni redoslijed izaberite „Ručno“.',
    pickerSearch: 'Dodaj proizvode — pretraga po nazivu ili SKU…',
    pickerEmpty: 'Nema proizvoda za ovu pretragu',
    added: 'Dodato',
    manualEmpty: 'Još nema proizvoda — dodajte ih pretragom iznad.',
    notPublic: 'nije javno',
    notPublicNote: 'Nacrti i arhivirani proizvodi nikad se ne prikazuju javno, čak i kad su u kolekciji ili ispunjavaju uslove.',
    preview_count: '{n} aktivnih proizvoda ispunjava uslove',
    preview_one: '1 aktivan proizvod ispunjava uslove',
    preview_hidden: 'Još {n} u nacrtu ili arhivi ispunjava uslove — ne prikazuju se javno.',
    preview_none: 'Nijedan aktivni proizvod ne ispunjava uslove.',
    preview_rulesFirst: 'Dodajte uslov da vidite pregled.',
    showMore: 'Prikaži još {n}',
    showLess: 'Prikaži manje',
    moveUp: 'Pomjeri gore',
    moveDown: 'Pomjeri dolje',
    remove: 'Ukloni',
    c_publish: 'Objava',
    published_on: 'Objavljena na Online Store',
    published_h: 'Vidljiva na /kolekcija/{slug} i dostupna za menije, banere i ponude.',
    unpublished_h: 'Sakrivena sa sajta — možete je pripremiti unaprijed.',
    needPublishPerm: 'Objava zahtijeva dozvolu „Objavi“.',
    c_image: 'Slika',
    c_summary: 'Sažetak',
    sum_public: 'Javno vidljivih',
    sum_total: 'Ukupno u kolekciji',
    sum_type: 'Tip',
    c_usage: 'Gdje se koristi',
    usage_none: 'Još se ne koristi u popustima, ponudama ni menijima.',
    usage_discount: 'Popust',
    usage_offer: 'Ponuda',
    usage_menu: 'Meni',
    usage_dynamic: 'Članstvo se prati dinamički — popust važi za proizvode koji ispunjavaju uslove u trenutku kupovine.',
    usage_static: 'Članstvo je sačuvan izbor — važi samo za proizvode navedene u kolekciji.',
    c_seo: 'SEO i URL',
    f_slug: 'URL adresa',
    slugAuto: 'Generiše se automatski iz crnogorskog naziva.',
    slugManual: 'Ručno uređena adresa.',
    slugReset: 'Vrati automatsku',
    f_metaTitle: 'Meta naslov',
    f_metaTitle_h: 'Prazno = naziv kolekcije.',
    f_metaDesc: 'Meta opis',
    f_metaDesc_h: 'Prazno = opis kolekcije.',
    e_title: 'Unesite naziv na crnogorskom (ME).',
    e_slug: 'Ova adresa je već zauzeta.',
    e_rules: 'Svaki uslov mora imati vrijednost.',
    e_noRules: 'Dodajte bar jedan uslov.',
    fixErrors: 'Provjerite označena polja',
    saved: 'Kolekcija je sačuvana',
    created: 'Kolekcija je kreirana',
    leaveTitle: 'Napustiti bez čuvanja?',
    leaveText: 'Nesačuvane promjene na ovoj kolekciji biće izgubljene.',
    leave: 'Napusti',
    readOnly: 'Samo pregled — vaša uloga ne može mijenjati kolekcije.',
    description: 'Grupišite proizvode za katalog, ponude i početnu stranicu — ručno ili po uslovima.',
    col_sort: 'Redoslijed',
    hiddenTitle: '{n} u nacrtu ili arhivi — ne prikazuju se javno',
    c_preview: 'Pregled proizvoda',
    c_preview_d: 'Aktivni proizvodi koji sada ispunjavaju uslove, redoslijedom kao na sajtu.',
    c_products_d: 'Izabrani proizvodi i njihov redoslijed na sajtu.',
    dragHint: 'Prevucite ili koristite strelice za redoslijed.',
    sortedBy: 'Na sajtu se ređaju: {sort}.',
    previewOnSite: 'Pregled na sajtu',
    shortcutTip: 'Ctrl/⌘ + S čuva promjene',
    hiddenList: 'Ispunjavaju uslove, ali nisu javni',
    createdOn: 'Kreirana {date}',
    image_h: 'Prikazuje se u zaglavlju stranice kolekcije i na karticama.',
    seo_d: 'Kako se kolekcija prikazuje u Google pretrazi.',
    googlePreview: 'Pregled u pretrazi',
    unpublishedNote: 'Nije objavljena — vidljiva samo u CMS-u i u pregledu.',
    productsN: '{n} proizvoda',
    or: 'ili',
  },
  sq: {
    title: 'Koleksionet',
    create: 'Krijo koleksion',
    tab_all: 'Të gjitha',
    tab_manual: 'Manuale',
    tab_smart: 'Me kushte',
    searchPh: 'Kërko koleksione…',
    col_title: 'Koleksioni',
    col_type: 'Lloji',
    col_conditions: 'Kushtet / përzgjedhja',
    col_products: 'Produktet',
    col_status: 'Statusi',
    col_usage: 'Përdoret',
    type_manual: 'Manual',
    type_smart: 'Me kushte',
    st_published: 'Publikuar',
    st_draft: 'Draft',
    manualCount: '{n} produkte të zgjedhura',
    matchAll: 'të gjitha kushtet',
    matchAny: 'cilido kusht',
    publicCount: '{n} publike',
    hiddenCount: '+{n} të fshehura',
    usageN: '{n}×',
    footerCount: '{n} koleksione',
    emptyTitle: 'Ende nuk ka koleksione',
    emptyText: 'Koleksionet grupojnë produktet për katalogun, ofertat dhe faqen kryesore — manualisht ose me kushte.',
    noResults: 'Asnjë koleksion për këtë kërkim',
    noResultsText: 'Ndryshoni kërkimin ose skedën.',
    viewOnSite: 'Shiko në faqe',
    edit: 'Ndrysho',
    open: 'Hap',
    duplicate: 'Dupliko',
    duplicated: 'Kopja u krijua si draft',
    copySuffix: '(kopje)',
    delete: 'Fshij',
    moreActions: 'Më shumë veprime',
    deleteTitle: 'Të fshihet koleksioni „{name}“?',
    deleteText: 'Produktet mbeten në katalog; koleksioni zhduket nga faqja. Ky veprim nuk mund të zhbëhet.',
    deleteUsed: 'Kujdes — e përdor: {list}.',
    deleted: 'Koleksioni u fshi',
    noPerm: 'Roli juaj nuk e ka këtë leje',
    newTitle: 'Koleksion i ri',
    notFound: 'Koleksioni nuk u gjet',
    notFoundText: 'Mund të jetë fshirë ose lidhja nuk është e saktë.',
    backToList: 'Kthehu te koleksionet',
    c_title: 'Titulli & përshkrimi',
    f_title: 'Titulli',
    f_desc: 'Përshkrimi',
    f_desc_h: 'Shfaqet në krye të faqes së koleksionit.',
    c_type: 'Lloji i koleksionit',
    manual_title: 'Manual',
    manual_h: 'Ju zgjidhni produktet dhe renditjen e tyre — përzgjedhje editoriale.',
    smart_title: 'Me kushte',
    smart_h: 'Produktet që plotësojnë kushtet hyjnë vetë — dhe dalin kur ndryshon çmimi ose etiketat.',
    copyMatches: 'Kopjo {n} produktet që përputhen tani',
    copied: 'U kopjuan {n} produkte',
    c_conditions: 'Kushtet',
    match_label: 'Produktet duhet të plotësojnë',
    match_all: 'të gjitha kushtet',
    match_any: 'cilindo kusht',
    addRule: 'Shto kusht',
    noRules: 'Shtoni të paktën një kusht — p.sh. Kategoria është Dysheme.',
    field_category: 'Kategoria',
    field_price: 'Çmimi',
    field_compareAt: 'Çmimi referues',
    field_stock: 'Stoku',
    field_status: 'Statusi i produktit',
    field_tag: 'Etiketa',
    field_title: 'Titulli',
    field_vendor: 'Furnitori',
    field_onSale: 'Në zbritje',
    field_badge: 'Etiketa në kartë',
    op_eq: 'është',
    op_neq: 'nuk është',
    op_gt: 'më i madh se',
    op_lt: 'më i vogël se',
    op_contains: 'përmban',
    yes: 'Po',
    no: 'Jo',
    valuePh: 'Vlera',
    removeRule: 'Hiq kushtin',
    liveNote: 'Ndryshimi i çmimit ose etiketës së produktit e përditëson automatikisht këtë koleksion — pa shtim manual.',
    c_products: 'Produktet',
    sort_label: 'Renditja',
    sort_manual: 'Manuale',
    sort_bestselling: 'Më të shiturat',
    'sort_price-asc': 'Çmimi: më i ulëti',
    'sort_price-desc': 'Çmimi: më i larti',
    sort_newest: 'Më të rejat',
    sortNote: 'Për renditje me dorë zgjidhni „Manuale“.',
    pickerSearch: 'Shto produkte — kërko sipas emrit ose SKU-së…',
    pickerEmpty: 'Asnjë produkt për këtë kërkim',
    added: 'Shtuar',
    manualEmpty: 'Ende nuk ka produkte — shtojini me kërkimin më sipër.',
    notPublic: 'jo publik',
    notPublicNote: 'Produktet draft/arkivuar nuk shfaqen kurrë publikisht, edhe nëse janë në koleksion ose përputhen me kushtin.',
    preview_count: '{n} produkte aktive plotësojnë kushtet',
    preview_one: '1 produkt aktiv plotëson kushtet',
    preview_hidden: 'Edhe {n} draft ose të arkivuara përputhen — nuk shfaqen publikisht.',
    preview_none: 'Asnjë produkt aktiv nuk i plotëson kushtet.',
    preview_rulesFirst: 'Shtoni një kusht për të parë parapamjen.',
    showMore: 'Shfaq edhe {n}',
    showLess: 'Shfaq më pak',
    moveUp: 'Lëviz lart',
    moveDown: 'Lëviz poshtë',
    remove: 'Hiq',
    c_publish: 'Publikimi',
    published_on: 'Publikuar në Online Store',
    published_h: 'E dukshme te /kolekcija/{slug} dhe e gatshme për menutë, bannerët dhe ofertat.',
    unpublished_h: 'E fshehur nga faqja — mund ta përgatitni paraprakisht.',
    needPublishPerm: 'Publikimi kërkon lejen „Publiko“.',
    c_image: 'Imazhi',
    c_summary: 'Përmbledhje',
    sum_public: 'Të dukshme publikisht',
    sum_total: 'Gjithsej në koleksion',
    sum_type: 'Lloji',
    c_usage: 'Ku përdoret',
    usage_none: 'Ende nuk përdoret në zbritje, oferta apo menu.',
    usage_discount: 'Zbritje',
    usage_offer: 'Ofertë',
    usage_menu: 'Menu',
    usage_dynamic: 'Anëtarësia ndiqet dinamikisht — zbritja vlen për produktet që plotësojnë kushtet në momentin e blerjes.',
    usage_static: 'Anëtarësia ruhet si përzgjedhje — vlen vetëm për produktet e listuara në koleksion.',
    c_seo: 'SEO & URL',
    f_slug: 'Adresa URL',
    slugAuto: 'Krijohet automatikisht nga titulli në malazezisht.',
    slugManual: 'Adresë e ndryshuar manualisht.',
    slugReset: 'Rikthe adresën automatike',
    f_metaTitle: 'Titulli meta',
    f_metaTitle_h: 'Bosh = titulli i koleksionit.',
    f_metaDesc: 'Përshkrimi meta',
    f_metaDesc_h: 'Bosh = përshkrimi i koleksionit.',
    e_title: 'Shkruani titullin në malazezisht (ME).',
    e_slug: 'Kjo adresë është tashmë e zënë.',
    e_rules: 'Çdo kusht duhet të ketë vlerë.',
    e_noRules: 'Shtoni të paktën një kusht.',
    fixErrors: 'Kontrolloni fushat e shënuara',
    saved: 'Koleksioni u ruajt',
    created: 'Koleksioni u krijua',
    leaveTitle: 'Të dilet pa ruajtur?',
    leaveText: 'Ndryshimet e paruajtura në këtë koleksion do të humbasin.',
    leave: 'Dil',
    readOnly: 'Vetëm lexim — roli juaj nuk mund të ndryshojë koleksionet.',
    description: 'Gruponi produktet për katalogun, ofertat dhe faqen kryesore — manualisht ose me kushte.',
    col_sort: 'Renditja',
    hiddenTitle: '{n} draft ose të arkivuara — nuk shfaqen publikisht',
    c_preview: 'Parapamja e produkteve',
    c_preview_d: 'Produktet aktive që i plotësojnë kushtet tani, me renditjen si në faqe.',
    c_products_d: 'Produktet e zgjedhura dhe renditja e tyre në faqe.',
    dragHint: 'Tërhiqni ose përdorni shigjetat për renditjen.',
    sortedBy: 'Në faqe renditen: {sort}.',
    previewOnSite: 'Parapamje në faqe',
    shortcutTip: 'Ctrl/⌘ + S ruan ndryshimet',
    hiddenList: 'Përputhen, por nuk janë publike',
    createdOn: 'Krijuar më {date}',
    image_h: 'Shfaqet në krye të faqes së koleksionit dhe në karta.',
    seo_d: 'Si shfaqet koleksioni në kërkimin e Google.',
    googlePreview: 'Parapamja në kërkim',
    unpublishedNote: 'Pa publikuar — duket vetëm në CMS dhe në parapamje.',
    productsN: '{n} produkte',
    or: 'ose',
  },
  en: {
    title: 'Collections',
    create: 'Create collection',
    tab_all: 'All',
    tab_manual: 'Manual',
    tab_smart: 'Automated',
    searchPh: 'Search collections…',
    col_title: 'Collection',
    col_type: 'Type',
    col_conditions: 'Conditions / selection',
    col_products: 'Products',
    col_status: 'Status',
    col_usage: 'Used in',
    type_manual: 'Manual',
    type_smart: 'Automated',
    st_published: 'Published',
    st_draft: 'Draft',
    manualCount: '{n} hand-picked products',
    matchAll: 'all conditions',
    matchAny: 'any condition',
    publicCount: '{n} public',
    hiddenCount: '+{n} hidden',
    usageN: '{n}×',
    footerCount: '{n} collections',
    emptyTitle: 'No collections yet',
    emptyText: 'Collections group products for the catalogue, offers and the homepage — by hand or by rules.',
    noResults: 'No collections match this search',
    noResultsText: 'Change the search or the tab.',
    viewOnSite: 'View on site',
    edit: 'Edit',
    open: 'Open',
    duplicate: 'Duplicate',
    duplicated: 'Copy created as a draft',
    copySuffix: '(copy)',
    delete: 'Delete',
    moreActions: 'More actions',
    deleteTitle: 'Delete the collection “{name}”?',
    deleteText: 'Products stay in the catalogue; the collection disappears from the website. This cannot be undone.',
    deleteUsed: 'Careful — used by: {list}.',
    deleted: 'Collection deleted',
    noPerm: 'Your role does not have this permission',
    newTitle: 'New collection',
    notFound: 'Collection not found',
    notFoundText: 'It may have been deleted, or the link is not correct.',
    backToList: 'Back to collections',
    c_title: 'Title & description',
    f_title: 'Title',
    f_desc: 'Description',
    f_desc_h: 'Shown at the top of the collection page.',
    c_type: 'Collection type',
    manual_title: 'Manual',
    manual_h: 'You pick the products and their order — an editorial selection.',
    smart_title: 'Automated',
    smart_h: 'Products that meet the rules join by themselves — and leave when the price or tags change.',
    copyMatches: 'Copy the {n} products that match now',
    copied: 'Copied {n} products',
    c_conditions: 'Conditions',
    match_label: 'Products must match',
    match_all: 'all conditions',
    match_any: 'any condition',
    addRule: 'Add condition',
    noRules: 'Add at least one condition — e.g. Category is Flooring.',
    field_category: 'Category',
    field_price: 'Price',
    field_compareAt: 'Compare-at price',
    field_stock: 'Stock',
    field_status: 'Product status',
    field_tag: 'Tag',
    field_title: 'Title',
    field_vendor: 'Vendor',
    field_onSale: 'On sale',
    field_badge: 'Card badge',
    op_eq: 'is',
    op_neq: 'is not',
    op_gt: 'greater than',
    op_lt: 'less than',
    op_contains: 'contains',
    yes: 'Yes',
    no: 'No',
    valuePh: 'Value',
    removeRule: 'Remove condition',
    liveNote: 'Changing a product’s price or tag updates this collection automatically — no manual adding.',
    c_products: 'Products',
    sort_label: 'Sort',
    sort_manual: 'Manual',
    sort_bestselling: 'Best selling',
    'sort_price-asc': 'Price: low to high',
    'sort_price-desc': 'Price: high to low',
    sort_newest: 'Newest',
    sortNote: 'Choose “Manual” to order by hand.',
    pickerSearch: 'Add products — search by name or SKU…',
    pickerEmpty: 'No products for this search',
    added: 'Added',
    manualEmpty: 'No products yet — add them with the search above.',
    notPublic: 'not public',
    notPublicNote: 'Draft and archived products never show publicly, even when they are in the collection or match the rules.',
    preview_count: '{n} active products match',
    preview_one: '1 active product matches',
    preview_hidden: '{n} more draft or archived products match — they never show publicly.',
    preview_none: 'No active product matches.',
    preview_rulesFirst: 'Add a condition to see the preview.',
    showMore: 'Show {n} more',
    showLess: 'Show less',
    moveUp: 'Move up',
    moveDown: 'Move down',
    remove: 'Remove',
    c_publish: 'Publishing',
    published_on: 'Published on Online Store',
    published_h: 'Visible at /kolekcija/{slug} and ready for menus, banners and offers.',
    unpublished_h: 'Hidden from the website — you can prepare it in advance.',
    needPublishPerm: 'Publishing requires the “Publish” permission.',
    c_image: 'Image',
    c_summary: 'Summary',
    sum_public: 'Publicly visible',
    sum_total: 'Total in collection',
    sum_type: 'Type',
    c_usage: 'Where it is used',
    usage_none: 'Not used by discounts, offers or menus yet.',
    usage_discount: 'Discount',
    usage_offer: 'Offer',
    usage_menu: 'Menu',
    usage_dynamic: 'Membership is followed dynamically — the discount applies to products that match at the time of purchase.',
    usage_static: 'Membership is a saved selection — it applies only to the products listed in the collection.',
    c_seo: 'SEO & URL',
    f_slug: 'URL handle',
    slugAuto: 'Generated automatically from the Montenegrin title.',
    slugManual: 'Edited manually.',
    slugReset: 'Reset to automatic',
    f_metaTitle: 'Meta title',
    f_metaTitle_h: 'Empty = collection title.',
    f_metaDesc: 'Meta description',
    f_metaDesc_h: 'Empty = collection description.',
    e_title: 'Enter the Montenegrin (ME) title.',
    e_slug: 'This address is already taken.',
    e_rules: 'Every condition needs a value.',
    e_noRules: 'Add at least one condition.',
    fixErrors: 'Please check the highlighted fields',
    saved: 'Collection saved',
    created: 'Collection created',
    leaveTitle: 'Leave without saving?',
    leaveText: 'Unsaved changes to this collection will be lost.',
    leave: 'Leave',
    readOnly: 'Read only — your role cannot edit collections.',
    description: 'Group products for the catalogue, offers and the homepage — by hand or by rules.',
    col_sort: 'Sort',
    hiddenTitle: '{n} draft or archived — not shown publicly',
    c_preview: 'Product preview',
    c_preview_d: 'Active products that match right now, in storefront order.',
    c_products_d: 'Selected products and their order on the website.',
    dragHint: 'Drag or use the arrows to reorder.',
    sortedBy: 'On the website they are sorted: {sort}.',
    previewOnSite: 'Preview on site',
    shortcutTip: 'Ctrl/⌘ + S saves changes',
    hiddenList: 'Match, but not public',
    createdOn: 'Created {date}',
    image_h: 'Shown in the collection page header and on cards.',
    seo_d: 'How the collection appears in Google search.',
    googlePreview: 'Search preview',
    unpublishedNote: 'Not published — visible only in the CMS and in preview.',
    productsN: '{n} products',
    or: 'or',
  },
});

export type CdKey = keyof typeof cd.me;
