import { defineDict } from '@/i18n';

/**
 * Storefront chrome copy (header, mega menu, mobile menu, search, footer) that is not in the shared
 * `site` dictionary. `me` = Serbian (Latin), `sq` Albanian (default), `en` English.
 */
export const chrome = defineDict({
  me: {
    productsN: '{n} proizvoda',
    soon: 'Uskoro',
    madeToOrder: 'Po narudžbi',
    browseAll: 'Svi proizvodi',
    printEyebrow: 'Za vaš brend',
    printTitle: 'Štampa *logotipa*',
    printText: 'Čaše, kutije i etikete sa vašim logotipom. Min. 1 karton · izrada 7–10 radnih dana.',
    printCta: 'Zatraži ponudu',
    samplesTitle: 'Probajte prije narudžbe',
    samplesText: 'Pošaljemo vam besplatne uzorke čaša, poklopaca i posuda.',
    delivery: 'Mitrovica 24h · Kosovo 1–3 dana',
    searchShort: 'Traži proizvode…',
    openSearch: 'Otvori pretragu',
    closeSearch: 'Zatvori pretragu',
    perPiece: '/kom',
    quickLinks: 'Brzi linkovi',
    pressSlash: 'Pritisnite / za pretragu',
    payments: 'Načini plaćanja',
    pay_cod: 'Plaćanje pouzećem',
    pay_bank: 'Bankovni transfer',
    pay_card: 'Kartica',
    shipping: 'Dostava',
    pickup: 'Preuzimanje u magacinu',
    nui: 'NUI',
    madeIn: 'Mitrovica, Kosovo',
    newsEyebrow: 'Bilten',
    newsNote: 'Bez spama. Odjava jednim klikom.',
    follow: 'Pratite nas',
    tagline: 'it’s packaging',
    bizTitle: 'Za biznis',
    bizText: 'Veleprodajne cijene, karton po povoljnijoj cijeni i ponuda za vaš lokal.',
    callNow: 'Pozovite',
  },
  sq: {
    productsN: '{n} produkte',
    soon: 'Së shpejti',
    madeToOrder: 'Me porosi',
    browseAll: 'Të gjitha produktet',
    printEyebrow: 'Për markën tuaj',
    printTitle: 'Printim me *logo*',
    printText: 'Gota, kuti dhe etiketa me logon tuaj. Min. 1 karton · gati për 7–10 ditë pune.',
    printCta: 'Kërko ofertë',
    samplesTitle: 'Provoni para porosisë',
    samplesText: 'Ju dërgojmë mostra falas të gotave, kapakëve dhe enëve.',
    delivery: 'Mitrovicë 24 orë · Kosovë 1–3 ditë',
    searchShort: 'Kërko produkte…',
    openSearch: 'Hap kërkimin',
    closeSearch: 'Mbyll kërkimin',
    perPiece: '/copë',
    quickLinks: 'Lidhje të shpejta',
    pressSlash: 'Shtyp / për të kërkuar',
    payments: 'Mënyrat e pagesës',
    pay_cod: 'Pagesë në dorëzim',
    pay_bank: 'Transfertë bankare',
    pay_card: 'Kartelë',
    shipping: 'Dërgesa',
    pickup: 'Marrje në depo',
    nui: 'NUI',
    madeIn: 'Mitrovicë, Kosovë',
    newsEyebrow: 'Buletini',
    newsNote: 'Pa spam. Çabonohu me një klik.',
    follow: 'Na ndiqni',
    tagline: 'it’s packaging',
    bizTitle: 'Për biznese',
    bizText: 'Çmime shumice, karton me çmim më të mirë dhe ofertë për lokalin tuaj.',
    callNow: 'Telefononi',
  },
  en: {
    productsN: '{n} products',
    soon: 'Coming soon',
    madeToOrder: 'Made to order',
    browseAll: 'All products',
    printEyebrow: 'For your brand',
    printTitle: 'Logo *print*',
    printText: 'Cups, boxes and labels with your logo. Min. 1 carton · ready in 7–10 working days.',
    printCta: 'Request a quote',
    samplesTitle: 'Try before you order',
    samplesText: 'We send you free samples of cups, lids and containers.',
    delivery: 'Mitrovica 24h · Kosovo 1–3 days',
    searchShort: 'Search products…',
    openSearch: 'Open search',
    closeSearch: 'Close search',
    perPiece: '/pc',
    quickLinks: 'Quick links',
    pressSlash: 'Press / to search',
    payments: 'Payment methods',
    pay_cod: 'Cash on delivery',
    pay_bank: 'Bank transfer',
    pay_card: 'Card',
    shipping: 'Delivery',
    pickup: 'Warehouse pickup',
    nui: 'NUI',
    madeIn: 'Mitrovica, Kosovo',
    newsEyebrow: 'Newsletter',
    newsNote: 'No spam. Unsubscribe in one click.',
    follow: 'Follow us',
    tagline: 'it’s packaging',
    bizTitle: 'For business',
    bizText: 'Wholesale prices, better carton pricing and a quote for your venue.',
    callNow: 'Call',
  },
});
