import { defineDict } from '@/i18n';

/** Strings for the CMS product list, CSV import/export, delete dialog and product editor (ME / SQ / EN). */
export const pd = defineDict({
  me: {
    /* ---------------- list (PDF p.09 / p.12) ---------------- */
    title: 'Proizvodi',
    addProduct: 'Dodaj proizvod',
    import: 'Uvezi',
    export: 'Izvezi',
    tab_all: 'Svi',
    tab_active: 'Aktivni',
    tab_draft: 'Nacrti',
    tab_archived: 'Arhivirani',
    st_active: 'Aktivan',
    st_draft: 'Nacrt',
    st_archived: 'Arhiviran',
    searchPh: 'Pretraži po nazivu, SKU-u, barkodu ili oznaci…',
    f_category_all: 'Kategorija',
    f_collection_all: 'Kolekcija',
    f_vendor_all: 'Dobavljač',
    f_stock_all: 'Zalihe',
    f_stock_in: 'Na stanju',
    f_stock_low: 'Malo zaliha (≤ 5)',
    f_stock_out: 'Nema na stanju',
    f_stock_untracked: 'Zalihe se ne prate',
    f_channel_all: 'Kanal',
    ch_online: 'Online Store',
    ch_pos: 'POS (salon)',
    ch_none: 'Bez kanala',
    filters: 'Filteri',
    clearFilters: 'Očisti filtere',
    sort_newest: 'Najnovije prvo',
    sort_updated: 'Nedavno ažurirano',
    sort_name: 'Naziv A–Ž',
    sort_price_asc: 'Cijena: niža prvo',
    sort_price_desc: 'Cijena: viša prvo',
    sort_stock: 'Zalihe: manje prvo',
    sort_sold: 'Najprodavanije',
    col_product: 'Proizvod',
    col_status: 'Status',
    col_inventory: 'Inventar',
    col_category: 'Kategorija',
    col_price: 'Cijena',
    col_vendor: 'Dobavljač',
    col_channels: 'Kanali',
    col_sold: 'Prodato',
    col_cost: 'Trošak i marža',
    col_updated: 'Ažurirano',
    columns: 'Kolone',
    columnsHint: 'Prikazane kolone',
    inv_in_one: '{n} u 1 varijanti',
    inv_in_many: '{n} u {v} varijanti',
    variantsN: '{n} varijanti',
    madeToOrder: 'Po narudžbi',
    lowStock: 'Malo zaliha',
    outOfStock: 'Nema na stanju',
    blockedN: '{n} blokirano',
    incomingN: '+{n} stiže',
    noCategory: 'Bez kategorije',
    onRequest: 'Na upit',
    fromPrice: 'od {price}',
    footerCount: '{n} proizvoda',
    footerBulkHint: 'Grupne akcije nakon izbora',
    pageOf: '{from}–{to} od {total}',
    prevPage: 'Prethodna strana',
    nextPage: 'Sljedeća strana',
    selectAll: 'Izaberi sve na strani',
    selectRow: 'Izaberi proizvod',
    selectedN: 'Izabrano: {n}',
    selectAllFiltered: 'Izaberi svih {n} po filteru',
    allSelected: 'Izabrani su svi proizvodi po filteru ({n}).',
    clearSelection: 'Poništi izbor',
    bulk_publish: 'Objavi',
    bulk_draft: 'U nacrt',
    bulk_archive: 'Arhiviraj',
    bulk_restore: 'Vrati iz arhive',
    bulk_export: 'Izvezi CSV',
    bulk_delete: 'Obriši',
    toast_published: 'Objavljeno proizvoda: {n}',
    toast_publishSkipped: 'Nije objavljeno: {n} — nedostaju obavezna polja',
    toast_drafted: 'Prebačeno u nacrt: {n}',
    toast_archived: 'Arhivirano: {n}',
    toast_restored: 'Vraćeno iz arhive kao nacrt: {n}',
    toast_exported: 'Izvezeno proizvoda: {n}',
    toast_status: '„{name}“ → {status}',
    noPerm: 'Vaša uloga nema ovu dozvolu',
    noPermPublish: 'Objava zahtijeva dozvolu „Objavi“',
    edit: 'Uredi',
    duplicate: 'Dupliraj',
    viewOnSite: 'Pogledaj na sajtu',
    publish: 'Objavi',
    toDraft: 'Prebaci u nacrt',
    archive: 'Arhiviraj',
    restore: 'Vrati iz arhive',
    delete: 'Obriši',
    moreActions: 'Više akcija',
    duplicated: 'Kopija je kreirana kao nacrt',
    emptyTitle: 'Nema proizvoda za zadate filtere',
    emptyText: 'Promijenite pretragu ili očistite filtere da vidite cijeli katalog.',
    emptyArchived: 'Arhiva je prazna',
    emptyArchivedText: 'Arhivirani proizvodi ostaju u narudžbama, ali nisu vidljivi na sajtu.',
    emptyCatalogTitle: 'Katalog je još prazan',
    emptyCatalogText: 'Dodajte prvi proizvod ili uvezite katalog iz CSV fajla.',

    /* ---------------- delete dialog (p.09) ---------------- */
    del_title_one: 'Obrisati „{name}“?',
    del_title_many: 'Obrisati {n} proizvoda?',
    del_intro: 'Provjerite posljedice prije potvrde.',
    del_willDelete: 'Briše se trajno',
    del_willArchive: 'Arhivira se umjesto brisanja',
    del_staysArchived: 'Ostaje arhiviran',
    del_hasOrders: 'u {n} narudžbi',
    del_hasDrafts: 'u {n} nacrta narudžbi',
    del_hasQuotes: 'u {n} B2B ponuda',
    del_hasPOs: 'u {n} nabavki',
    del_noHistory: 'Bez narudžbi i dokumenata',
    del_usedIn: 'Nalazi se',
    del_inCollections: 'Uklanja se iz kolekcija: {list}',
    del_inDiscounts: 'Pominje se u popustima: {list}',
    del_inOffers: 'Dio ponuda: {list}',
    del_note: 'Narudžbe čuvaju kopiju artikla, SKU-a, cijene i poreza, zato se prodati proizvodi arhiviraju. Trajno brisanje se bilježi u audit log.',
    del_confirm: 'Potvrdi',
    del_confirmDelete: 'Obriši {n}',
    del_confirmArchive: 'Arhiviraj {n}',
    del_done: 'Obrisano: {d} · Arhivirano: {a}',

    /* ---------------- CSV import / export ---------------- */
    imp_title: 'Uvoz proizvoda iz CSV-a',
    imp_desc: 'Mapiranje polja, pregled i provjera prije uvoza — ništa se ne mijenja dok ne potvrdite.',
    imp_step1: 'Fajl',
    imp_step2: 'Mapiranje',
    imp_step3: 'Pregled i provjera',
    imp_drop: 'Prevucite CSV fajl ovdje ili kliknite za izbor',
    imp_dropHint: 'Separator: zarez, tačka-zarez ili tab · UTF-8',
    imp_paste: 'ili nalijepite sadržaj CSV-a',
    imp_template: 'Preuzmi šablon',
    imp_sample: 'Učitaj primjer',
    imp_detected: '{rows} redova · {cols} kolona · separator „{sep}“',
    imp_noRows: 'Fajl nema redova sa podacima ispod zaglavlja.',
    imp_next: 'Dalje',
    imp_back: 'Nazad',
    imp_csvColumn: 'Kolona u CSV-u',
    imp_example: 'Primjer',
    imp_field: 'Polje u CMS-u',
    imp_ignore: '— Ne uvozi —',
    imp_required: 'Obavezno mapirajte naziv i cijenu.',
    imp_existing: 'Kada SKU već postoji u katalogu',
    imp_update: 'Ažuriraj postojeći proizvod',
    imp_skip: 'Preskoči red',
    imp_newStatus: 'Status novih proizvoda',
    imp_asDraft: 'Nacrt (preporučeno)',
    imp_fromColumn: 'Iz kolone „Status“',
    imp_sumNew: 'Novi',
    imp_sumUpdate: 'Ažuriranja',
    imp_sumSkip: 'Preskočeno',
    imp_sumErrors: 'Sa greškom',
    imp_dupReport: 'Izvještaj o duplim SKU-ovima',
    imp_dupInFile: '{sku} se ponavlja u fajlu (redovi {a} i {b}) — uvozi se samo prvi.',
    imp_dupInCatalog: '{sku} već postoji: {name} — {action}.',
    imp_actUpdate: 'biće ažuriran',
    imp_actSkip: 'biće preskočen',
    imp_noDups: 'Nema duplih SKU-ova — svaki red je jedinstven.',
    imp_colLine: 'Red',
    imp_colResult: 'Rezultat',
    imp_colNote: 'Napomena',
    imp_res_create: 'Novi',
    imp_res_update: 'Ažuriranje',
    imp_res_skip: 'Preskače se',
    imp_res_error: 'Greška',
    imp_ok: 'Spremno',
    imp_confirm: 'Uvezi {n} proizvoda',
    imp_nothing: 'Nema redova za uvoz',
    imp_done: 'Uvezeno: {c} novih · {u} ažurirano',
    imp_doneHint: 'Novi proizvodi su u nacrtu — provjerite ih i objavite.',
    imp_showDrafts: 'Prikaži nacrte',
    imp_moreRows: '+ još {n} redova',
    imp_readError: 'Fajl nije moguće pročitati',
    exp_handle: 'URL',
    exp_variants: 'Varijante',
    fld_name_me: 'Naziv (ME)',
    fld_name_sq: 'Naziv (SQ)',
    fld_name_en: 'Naziv (EN)',
    fld_sku: 'SKU',
    fld_barcode: 'Barkod',
    fld_price: 'Cijena',
    fld_compareAt: 'Referentna cijena',
    fld_cost: 'Trošak / kom',
    fld_category: 'Kategorija',
    fld_vendor: 'Dobavljač',
    fld_tags: 'Oznake',
    fld_stock: 'Zalihe',
    fld_status: 'Status',
    fld_unit: 'Jedinica',
    fld_description: 'Opis',
    fld_image: 'Slika (URL)',
    issue_noName: 'Nedostaje naziv',
    issue_noPrice: 'Nedostaje cijena',
    issue_badNumber: '„{value}“ nije broj ({field})',
    issue_negative: 'Negativna vrijednost ({field})',
    issue_dupFile: 'Dupli SKU u fajlu',
    issue_exists: 'SKU postoji u katalogu',
    issue_noCategory: 'Bez kategorije — ostaje nacrt',
    issue_unknownCategory: 'Kategorija „{value}“ nije pronađena',
    issue_compareLow: 'Referentna cijena nije veća od cijene — popust se ne prikazuje',
    issue_badStatus: 'Nepoznat status „{value}“ — nacrt',
    issue_notPublishable: 'Nedostaju polja za objavu — uvozi se kao nacrt',
    issue_nameFromOther: 'Naziv (ME) preuzet iz drugog jezika',

    /* ---------------- editor (p.10 / p.11 / p.13) ---------------- */
    newTitle: 'Novi proizvod',
    notFound: 'Proizvod nije pronađen',
    notFoundText: 'Možda je obrisan ili link nije ispravan.',
    backToList: 'Nazad na proizvode',
    createdOn: 'Kreirano {date}',
    updatedAgo: 'ažurirano {ago}',
    soldN: 'Prodato: {n}',
    save: 'Sačuvaj',
    saved: 'Promjene su sačuvane',
    created: 'Proizvod je kreiran',
    readOnly: 'Samo pregled — vaša uloga ne može mijenjati proizvode.',
    archivedBanner: 'Proizvod je arhiviran — nije vidljiv na sajtu, a narudžbe ga i dalje prikazuju.',
    c_title: 'Naziv i opis',
    f_title: 'Naziv',
    f_short: 'Kratak opis',
    f_short_h: 'Jedna rečenica ispod naziva na stranici proizvoda.',
    f_desc: 'Opis',
    f_desc_h: 'Materijal, ugradnja i održavanje — prikazuje se na stranici proizvoda.',
    c_media: 'Mediji',
    c_media_d: 'Prva slika je naslovna. Prevucite slike da promijenite redoslijed.',
    c_price: 'Cijena',
    c_price_d: 'Sve cijene uključuju PDV {vat}%.',
    f_price: 'Cijena',
    f_compareAt: 'Referentna cijena',
    f_compareAt_h: 'Veća od cijene → prikazuje se popust.',
    f_cost: 'Trošak / kom',
    f_cost_h: 'Interno — kupci ga ne vide.',
    margin: 'Marža',
    profit: 'Zarada',
    price_discount: 'Kupac vidi popust {pct}% — štedi {amount}.',
    price_compareLow: 'Referentna cijena nije veća od cijene — popust se neće prikazati.',
    price_regular: 'Bez popusta — kupac plaća prikazanu cijenu.',
    price_note: 'Akcijska cijena i kod za popust su dva različita mehanizma — kodovi se podešavaju u „Popusti“.',
    f_unit: 'Jedinica prodaje',
    f_pack: 'm² u paketu',
    f_pack_h: 'Kupac naručuje cijele pakete.',
    unit_kom: 'Komad (kom)',
    unit_m2: 'Kvadratni metar (m²)',
    unit_m: 'Dužni metar (m)',
    unit_set: 'Set / komplet',
    packHint: 'Paket od {size} m² košta {price}',
    c_variants: 'Varijante i inventar',
    c_variants_d: 'Opcije generišu kombinacije — svaka ima svoj SKU i zalihu.',
    options: 'Opcije',
    editOptions: 'Uredi opcije',
    doneOptions: 'Gotovo',
    f_track: 'Prati količinu',
    f_track_h: 'Isključite za proizvode po mjeri i po narudžbi.',
    untracked_note: 'Zalihe se ne prate — proizvod se izrađuje po narudžbi i uvijek je dostupan za naručivanje.',
    f_sku: 'SKU',
    f_sku_h: 'Osnova za SKU varijanti.',
    f_barcode: 'Barkod (EAN)',
    f_stock: 'Dostupno',
    v_variant: 'Varijanta',
    v_price: 'Cijena',
    v_sku: 'SKU',
    v_available: 'Dostupno',
    v_total: 'Ukupno',
    v_combos: '{n} kombinacija · {on} u prodaji',
    v_groupBy: 'Grupiši po',
    v_noGroup: 'Bez grupisanja',
    v_setStock: 'Postavi zalihu',
    v_apply: 'Primijeni',
    v_genSku: 'Generiši SKU',
    v_disable: 'Isključi iz prodaje',
    v_enable: 'Vrati u prodaju',
    v_disabled: 'Nije u prodaji',
    v_selected: 'Izabrano: {n}',
    v_selectAll: 'Izaberi sve varijante',
    v_dupSku: 'SKU se ponavlja',
    v_showAll: 'Prikaži sve ({n})',
    v_showLess: 'Prikaži manje',
    inv_incoming: 'Stiže: {n}',
    inv_blocked: 'Blokirano: {n}',
    inv_link: 'Inventar i kretanja',
    lowStockWarn: 'Malo na stanju — vrijeme je za dopunu.',
    outOfStockWarn: 'Nema na stanju — na sajtu se prikazuje kao „po narudžbi“.',
    stockPacksH: 'Za m² proizvode zalihe se vode u paketima.',
    packsUnit: 'pak.',
    c_shipping: 'Isporuka',
    f_physical: 'Fizički proizvod',
    f_physical_h: 'Isporučuje se kupcu — težina i dimenzije su opcione.',
    f_physicalOff: 'Usluga ili digitalni proizvod — bez isporuke.',
    f_weight: 'Težina',
    f_dims: 'Dimenzije pakovanja',
    dim_l: 'Dužina',
    dim_w: 'Širina',
    dim_h: 'Visina',
    optional: 'opciono',
    c_seo: 'SEO i URL',
    c_seo_d: 'Kako se proizvod prikazuje u Google pretrazi.',
    f_slug: 'URL adresa',
    slugAuto: 'Generiše se automatski iz crnogorskog naziva.',
    slugManual: 'Ručno uređena adresa.',
    slugReset: 'Vrati automatsku',
    f_metaTitle: 'Meta naslov',
    f_metaTitle_h: 'Prazno = naziv proizvoda.',
    f_metaDesc: 'Meta opis',
    f_metaDesc_h: 'Prazno = kratak opis.',
    googlePreview: 'Pregled u pretrazi',
    inStock: 'Na stanju',
    redirect: 'Preusmjeri staru adresu /proizvod/{old}',
    redirect_h: 'Linkovi iz Google-a i sa društvenih mreža nastavljaju da rade.',
    c_status: 'Status',
    status_active_h: 'Vidljiv na izabranim kanalima prodaje.',
    status_draft_h: 'Sakriven — dovršite ga i objavite kad bude spreman.',
    status_archived_h: 'Povučen iz prodaje; narudžbe i istorija ostaju.',
    ready: 'Spreman za objavu',
    missingTitle: 'Za objavu nedostaje:',
    req_name: 'Naziv (ME)',
    req_category: 'Kategorija',
    req_price: 'Cijena veća od 0',
    req_image: 'Bar jedna slika',
    publishBlocked: 'Objava je blokirana',
    publishBlockedText: 'Nedostaje: {list}. Dopunite polja ili sačuvajte kao nacrt.',
    saveAsDraft: 'Sačuvaj kao nacrt',
    needPublishPerm: 'Za aktivaciju je potrebna dozvola objave.',
    translations: 'Prevodi',
    c_publishing: 'Objava',
    ch_online_h: 'Sajt — katalog, pretraga i kolekcije.',
    ch_pos_h: 'Prodaja u salonu.',
    channelsInactive: 'Kanali se aktiviraju kad je status „Aktivan“.',
    noChannel: 'Bez kanala proizvod nije vidljiv nigdje.',
    c_org: 'Organizacija',
    f_category: 'Kategorija',
    chooseCategory: 'Izaberite kategoriju…',
    f_vendor: 'Dobavljač',
    f_vendor_ph: 'npr. Porta Lux',
    f_tags: 'Oznake',
    f_tags_ph: 'Dodaj oznaku + Enter',
    f_collections: 'Kolekcije',
    col_manual: 'Ručne',
    col_smart: 'Automatske (po uslovima)',
    col_smart_h: 'Proizvod ulazi sam kad ispuni uslove — prati cijenu, oznake i kategoriju.',
    col_none: 'Nije ni u jednoj automatskoj kolekciji.',
    col_noManual: 'Nema ručnih kolekcija.',
    col_unpublished: 'nije objavljena',
    col_noPerm: 'Za izmjenu kolekcija potrebna je dozvola.',
    c_template: 'Šablon',
    tpl_standard: 'Standardni proizvod',
    tpl_standard_h: 'Cijena, opcije i „Dodaj u korpu“.',
    tpl_quote: 'Zahtjev za ponudu',
    tpl_quote_h: 'Po mjeri — kupac šalje upit umjesto kupovine.',
    c_install: 'Ugradnja i rok',
    f_install: 'Nudimo ugradnju',
    f_install_h: 'Kupac može dodati ugradnju u korpi.',
    f_installPrice: 'Cijena ugradnje',
    f_lead: 'Rok isporuke',
    daysUnit: 'dana',
    f_warranty: 'Garancija',
    yearsUnit: 'god.',
    c_display: 'Prikaz u prodavnici',
    f_badges: 'Oznake na kartici',
    f_featured: 'Istaknut proizvod',
    f_featured_h: 'Prikazuje se u izdvojenim sekcijama početne.',
    c_preview: 'Pregled na sajtu',
    c_preview_d: 'Kartica se mijenja dok kucate.',
    shortcutTip: 'Savjet: Ctrl + S čuva promjene.',
    e_name: 'Unesite naziv na crnogorskom (ME).',
    e_skuDup: 'SKU „{sku}“ već koristi „{name}“.',
    e_variantSkuDup: 'SKU-ovi varijanti se ponavljaju.',
    fixErrors: 'Provjerite označena polja',
    leaveTitle: 'Napustiti bez čuvanja?',
    leaveText: 'Nesačuvane promjene na ovom proizvodu biće izgubljene.',
    leave: 'Napusti',
    c_options: 'Opcije / varijante',
    c_options_d: 'Dimenzije, boje i izvedbe između kojih kupac bira.',
    addOption: 'Dodaj opciju',
    addValue: 'Dodaj vrijednost',
    optionName: 'Naziv opcije',
    type_swatch: 'Boje',
    type_button: 'Dugmad',
    valueLabel: 'Vrijednost',
    priceDelta: 'Doplata',
    noOptions: 'Bez opcija — proizvod se prodaje u jednoj izvedbi.',
    quickAdd: 'Brzo dodaj',
    moveUp: 'Pomjeri gore',
    moveDown: 'Pomjeri dolje',
    remove: 'Ukloni',
    pickColor: 'Izaberi boju',
    langHint: 'Jezik unosa',
    c_specs: 'Specifikacije',
    c_specs_d: 'Tehnički podaci u tabeli na stranici proizvoda.',
    specLabel: 'Svojstvo',
    specValue: 'Vrijednost',
    addSpec: 'Dodaj red',
    noSpecs: 'Još nema specifikacija — dodajte materijal, dimenzije ili garanciju.',
  },
  sq: {
    title: 'Produktet',
    addProduct: 'Shto produkt',
    import: 'Importo',
    export: 'Eksporto',
    tab_all: 'Të gjitha',
    tab_active: 'Aktive',
    tab_draft: 'Draft',
    tab_archived: 'Arkivuara',
    st_active: 'Aktiv',
    st_draft: 'Draft',
    st_archived: 'Arkivuar',
    searchPh: 'Kërko sipas emrit, SKU-së, barkodit ose etiketës…',
    f_category_all: 'Kategoria',
    f_collection_all: 'Koleksioni',
    f_vendor_all: 'Furnitori',
    f_stock_all: 'Stoku',
    f_stock_in: 'Në stok',
    f_stock_low: 'Stok i ulët (≤ 5)',
    f_stock_out: 'Pa stok',
    f_stock_untracked: 'Stoku nuk ndiqet',
    f_channel_all: 'Kanali',
    ch_online: 'Online Store',
    ch_pos: 'POS (salloni)',
    ch_none: 'Pa kanal',
    filters: 'Filtrat',
    clearFilters: 'Pastro filtrat',
    sort_newest: 'Më të rejat',
    sort_updated: 'Përditësuar së fundi',
    sort_name: 'Emri A–Zh',
    sort_price_asc: 'Çmimi: më i ulëti',
    sort_price_desc: 'Çmimi: më i larti',
    sort_stock: 'Stoku: më i vogli',
    sort_sold: 'Më të shiturat',
    col_product: 'Produkti',
    col_status: 'Statusi',
    col_inventory: 'Inventari',
    col_category: 'Kategoria',
    col_price: 'Çmimi',
    col_vendor: 'Furnitori',
    col_channels: 'Kanalet',
    col_sold: 'Shitur',
    col_cost: 'Kosto & marzha',
    col_updated: 'Përditësuar',
    columns: 'Kolonat',
    columnsHint: 'Kolonat e shfaqura',
    inv_in_one: '{n} në 1 variant',
    inv_in_many: '{n} në {v} variante',
    variantsN: '{n} variante',
    madeToOrder: 'Me porosi',
    lowStock: 'Stok i ulët',
    outOfStock: 'Pa stok',
    blockedN: '{n} e bllokuar',
    incomingN: '+{n} në ardhje',
    noCategory: 'Pa kategori',
    onRequest: 'Me kërkesë',
    fromPrice: 'nga {price}',
    footerCount: '{n} produkte',
    footerBulkHint: 'Veprime në grup pas përzgjedhjes',
    pageOf: '{from}–{to} nga {total}',
    prevPage: 'Faqja e mëparshme',
    nextPage: 'Faqja tjetër',
    selectAll: 'Zgjidh të gjitha në faqe',
    selectRow: 'Zgjidh produktin',
    selectedN: '{n} të zgjedhur',
    selectAllFiltered: 'Zgjidh të {n} produktet sipas filtrit',
    allSelected: 'Janë zgjedhur të gjitha produktet sipas filtrit ({n}).',
    clearSelection: 'Anulo zgjedhjen',
    bulk_publish: 'Publiko',
    bulk_draft: 'Kalo në draft',
    bulk_archive: 'Arkivo',
    bulk_restore: 'Rikthe nga arkivi',
    bulk_export: 'Eksporto CSV',
    bulk_delete: 'Fshij',
    toast_published: 'U publikuan {n} produkte',
    toast_publishSkipped: '{n} nuk u publikuan — mungojnë fushat e detyrueshme',
    toast_drafted: 'U kaluan në draft: {n}',
    toast_archived: 'U arkivuan: {n}',
    toast_restored: 'U rikthyen nga arkivi si draft: {n}',
    toast_exported: 'U eksportuan {n} produkte',
    toast_status: '„{name}“ → {status}',
    noPerm: 'Roli juaj nuk e ka këtë leje',
    noPermPublish: 'Publikimi kërkon lejen „Publiko“',
    edit: 'Ndrysho',
    duplicate: 'Dupliko',
    viewOnSite: 'Shiko në faqe',
    publish: 'Publiko',
    toDraft: 'Kalo në draft',
    archive: 'Arkivo',
    restore: 'Rikthe nga arkivi',
    delete: 'Fshij',
    moreActions: 'Më shumë veprime',
    duplicated: 'Kopja u krijua si draft',
    emptyTitle: 'Asnjë produkt për këto filtra',
    emptyText: 'Ndryshoni kërkimin ose pastroni filtrat për të parë gjithë katalogun.',
    emptyArchived: 'Arkivi është bosh',
    emptyArchivedText: 'Produktet e arkivuara mbeten në porosi, por nuk shfaqen në faqe.',
    emptyCatalogTitle: 'Katalogu është ende bosh',
    emptyCatalogText: 'Shtoni produktin e parë ose importoni katalogun nga një skedar CSV.',

    del_title_one: 'Të fshihet „{name}“?',
    del_title_many: 'Të fshihen {n} produkte?',
    del_intro: 'Kontrolloni pasojat para se të konfirmoni.',
    del_willDelete: 'Fshihet përfundimisht',
    del_willArchive: 'Arkivohet në vend të fshirjes',
    del_staysArchived: 'Mbetet i arkivuar',
    del_hasOrders: 'në {n} porosi',
    del_hasDrafts: 'në {n} drafte porosish',
    del_hasQuotes: 'në {n} oferta B2B',
    del_hasPOs: 'në {n} furnizime',
    del_noHistory: 'Pa porosi dhe dokumente',
    del_usedIn: 'Gjendet',
    del_inCollections: 'Hiqet nga koleksionet: {list}',
    del_inDiscounts: 'Përmendet në zbritjet: {list}',
    del_inOffers: 'Pjesë e ofertave: {list}',
    del_note: 'Porositë ruajnë kopjen e artikullit, SKU-së, çmimit dhe taksave, prandaj produktet e shitura arkivohen. Fshirja përfundimtare regjistrohet në audit.',
    del_confirm: 'Konfirmo',
    del_confirmDelete: 'Fshij {n}',
    del_confirmArchive: 'Arkivo {n}',
    del_done: 'U fshinë: {d} · U arkivuan: {a}',

    imp_title: 'Importo produkte nga CSV',
    imp_desc: 'Mapim fushash, parapamje dhe validim para importit — asgjë nuk ndryshon pa konfirmimin tuaj.',
    imp_step1: 'Skedari',
    imp_step2: 'Mapimi',
    imp_step3: 'Parapamja & validimi',
    imp_drop: 'Tërhiqni skedarin CSV këtu ose klikoni për ta zgjedhur',
    imp_dropHint: 'Ndarësi: presje, pikëpresje ose tab · UTF-8',
    imp_paste: 'ose ngjitni përmbajtjen CSV',
    imp_template: 'Shkarko shabllonin',
    imp_sample: 'Ngarko shembullin',
    imp_detected: '{rows} rreshta · {cols} kolona · ndarësi „{sep}“',
    imp_noRows: 'Skedari nuk ka rreshta me të dhëna nën kokë.',
    imp_next: 'Vazhdo',
    imp_back: 'Kthehu',
    imp_csvColumn: 'Kolona në CSV',
    imp_example: 'Shembull',
    imp_field: 'Fusha në CMS',
    imp_ignore: '— Mos e importo —',
    imp_required: 'Duhet të mapohen emri dhe çmimi.',
    imp_existing: 'Kur SKU ekziston në katalog',
    imp_update: 'Përditëso produktin ekzistues',
    imp_skip: 'Kapërce rreshtin',
    imp_newStatus: 'Statusi i produkteve të reja',
    imp_asDraft: 'Draft (rekomandohet)',
    imp_fromColumn: 'Sipas kolonës „Statusi“',
    imp_sumNew: 'Të reja',
    imp_sumUpdate: 'Përditësime',
    imp_sumSkip: 'Kapërcehen',
    imp_sumErrors: 'Me gabime',
    imp_dupReport: 'Raporti i SKU-ve të dyfishta',
    imp_dupInFile: '{sku} përsëritet në skedar (rreshtat {a} dhe {b}) — importohet vetëm i pari.',
    imp_dupInCatalog: '{sku} ekziston: {name} — {action}.',
    imp_actUpdate: 'do të përditësohet',
    imp_actSkip: 'do të kapërcehet',
    imp_noDups: 'Nuk ka SKU të dyfishta — çdo rresht është unik.',
    imp_colLine: 'Rreshti',
    imp_colResult: 'Rezultati',
    imp_colNote: 'Shënim',
    imp_res_create: 'I ri',
    imp_res_update: 'Përditësim',
    imp_res_skip: 'Kapërcehet',
    imp_res_error: 'Gabim',
    imp_ok: 'Gati',
    imp_confirm: 'Importo {n} produkte',
    imp_nothing: 'Nuk ka rreshta për import',
    imp_done: 'U importuan: {c} të reja · {u} u përditësuan',
    imp_doneHint: 'Produktet e reja janë në draft — kontrollojini dhe publikojini.',
    imp_showDrafts: 'Shfaq draftet',
    imp_moreRows: '+ edhe {n} rreshta',
    imp_readError: 'Skedari nuk mund të lexohej',
    exp_handle: 'URL',
    exp_variants: 'Variantet',
    fld_name_me: 'Emri (ME)',
    fld_name_sq: 'Emri (SQ)',
    fld_name_en: 'Emri (EN)',
    fld_sku: 'SKU',
    fld_barcode: 'Barkodi',
    fld_price: 'Çmimi',
    fld_compareAt: 'Çmimi referues',
    fld_cost: 'Kosto / copë',
    fld_category: 'Kategoria',
    fld_vendor: 'Furnitori',
    fld_tags: 'Etiketat',
    fld_stock: 'Stoku',
    fld_status: 'Statusi',
    fld_unit: 'Njësia',
    fld_description: 'Përshkrimi',
    fld_image: 'Imazhi (URL)',
    issue_noName: 'Mungon emri',
    issue_noPrice: 'Mungon çmimi',
    issue_badNumber: '„{value}“ nuk është numër ({field})',
    issue_negative: 'Vlerë negative ({field})',
    issue_dupFile: 'SKU e dyfishtë në skedar',
    issue_exists: 'SKU ekziston në katalog',
    issue_noCategory: 'Pa kategori — mbetet draft',
    issue_unknownCategory: 'Kategoria „{value}“ nuk u gjet',
    issue_compareLow: 'Çmimi referues nuk është më i madh se çmimi — zbritja nuk shfaqet',
    issue_badStatus: 'Status i panjohur „{value}“ — draft',
    issue_notPublishable: 'Mungojnë fushat për publikim — importohet si draft',
    issue_nameFromOther: 'Emri (ME) u mor nga gjuha tjetër',

    newTitle: 'Produkt i ri',
    notFound: 'Produkti nuk u gjet',
    notFoundText: 'Mund të jetë fshirë ose lidhja nuk është e saktë.',
    backToList: 'Kthehu te produktet',
    createdOn: 'Krijuar më {date}',
    updatedAgo: 'përditësuar {ago}',
    soldN: 'Shitur: {n}',
    save: 'Ruaj',
    saved: 'Ndryshimet u ruajtën',
    created: 'Produkti u krijua',
    readOnly: 'Vetëm lexim — roli juaj nuk mund të ndryshojë produktet.',
    archivedBanner: 'Produkti është i arkivuar — nuk shfaqet në faqe, ndërsa porositë e ruajnë.',
    c_title: 'Titulli & përshkrimi',
    f_title: 'Titulli',
    f_short: 'Përshkrim i shkurtër',
    f_short_h: 'Një fjali nën emrin në faqen e produktit.',
    f_desc: 'Përshkrimi',
    f_desc_h: 'Materiali, montimi dhe mirëmbajtja — shfaqet në faqen e produktit.',
    c_media: 'Media',
    c_media_d: 'Imazhi i parë është kopertina. Tërhiqni imazhet për të ndryshuar renditjen.',
    c_price: 'Çmimi',
    c_price_d: 'Të gjitha çmimet përfshijnë TVSH {vat}%.',
    f_price: 'Çmimi',
    f_compareAt: 'Çmimi referues',
    f_compareAt_h: 'Më i madh se çmimi → shfaqet zbritja.',
    f_cost: 'Kosto / copë',
    f_cost_h: 'E brendshme — klientët nuk e shohin.',
    margin: 'Marzha',
    profit: 'Fitimi',
    price_discount: 'Klienti sheh zbritje {pct}% — kursen {amount}.',
    price_compareLow: 'Çmimi referues nuk është më i madh se çmimi — zbritja nuk do të shfaqet.',
    price_regular: 'Pa zbritje — klienti paguan çmimin e shfaqur.',
    price_note: 'Çmimi promocional dhe kodi i zbritjes janë dy mekanizma të ndryshëm — kodet caktohen te „Zbritjet“.',
    f_unit: 'Njësia e shitjes',
    f_pack: 'm² në pako',
    f_pack_h: 'Klienti porosit pako të plota.',
    unit_kom: 'Copë',
    unit_m2: 'Metër katror (m²)',
    unit_m: 'Metër linear (m)',
    unit_set: 'Set / komplet',
    packHint: 'Pakoja prej {size} m² kushton {price}',
    c_variants: 'Variantet & inventari',
    c_variants_d: 'Opsionet krijojnë kombinime — secili ka SKU dhe stok të vetin.',
    options: 'Opsionet',
    editOptions: 'Ndrysho opsionet',
    doneOptions: 'Gati',
    f_track: 'Ndiq sasinë',
    f_track_h: 'Çaktivizojeni për produktet sipas masës dhe me porosi.',
    untracked_note: 'Stoku nuk ndiqet — produkti prodhohet me porosi dhe është gjithmonë i disponueshëm për porosi.',
    f_sku: 'SKU',
    f_sku_h: 'Baza për SKU-të e varianteve.',
    f_barcode: 'Barkodi (EAN)',
    f_stock: 'Disponueshëm',
    v_variant: 'Varianti',
    v_price: 'Çmimi',
    v_sku: 'SKU',
    v_available: 'Disponueshëm',
    v_total: 'Totali',
    v_combos: '{n} kombinime · {on} në shitje',
    v_groupBy: 'Grupo sipas',
    v_noGroup: 'Pa grupim',
    v_setStock: 'Vendos stokun',
    v_apply: 'Zbato',
    v_genSku: 'Gjenero SKU',
    v_disable: 'Hiq nga shitja',
    v_enable: 'Rikthe në shitje',
    v_disabled: 'Jo në shitje',
    v_selected: '{n} të zgjedhura',
    v_selectAll: 'Zgjidh të gjitha variantet',
    v_dupSku: 'SKU e përsëritur',
    v_showAll: 'Shfaq të gjitha ({n})',
    v_showLess: 'Shfaq më pak',
    inv_incoming: 'Në ardhje: {n}',
    inv_blocked: 'E bllokuar: {n}',
    inv_link: 'Inventari & lëvizjet',
    lowStockWarn: 'Stok i ulët — është koha për rimbushje.',
    outOfStockWarn: 'Pa stok — në faqe shfaqet si „me porosi“.',
    stockPacksH: 'Për produktet në m² stoku mbahet në pako.',
    packsUnit: 'pako',
    c_shipping: 'Dërgesa',
    f_physical: 'Produkt fizik',
    f_physical_h: 'I dërgohet klientit — pesha dhe dimensionet janë opsionale.',
    f_physicalOff: 'Shërbim ose produkt digjital — pa dërgesë.',
    f_weight: 'Pesha',
    f_dims: 'Dimensionet e paketimit',
    dim_l: 'Gjatësia',
    dim_w: 'Gjerësia',
    dim_h: 'Lartësia',
    optional: 'opsionale',
    c_seo: 'SEO & URL',
    c_seo_d: 'Si shfaqet produkti në kërkimin e Google.',
    f_slug: 'Adresa URL',
    slugAuto: 'Krijohet automatikisht nga emri në malazezisht.',
    slugManual: 'Adresë e ndryshuar manualisht.',
    slugReset: 'Rikthe adresën automatike',
    f_metaTitle: 'Titulli meta',
    f_metaTitle_h: 'Bosh = emri i produktit.',
    f_metaDesc: 'Përshkrimi meta',
    f_metaDesc_h: 'Bosh = përshkrimi i shkurtër.',
    googlePreview: 'Parapamja në kërkim',
    inStock: 'Në stok',
    redirect: 'Ridrejto adresën e vjetër /proizvod/{old}',
    redirect_h: 'Lidhjet nga Google dhe rrjetet sociale vazhdojnë të funksionojnë.',
    c_status: 'Statusi',
    status_active_h: 'I dukshëm në kanalet e zgjedhura të shitjes.',
    status_draft_h: 'I fshehur — përfundojeni dhe publikojeni kur të jetë gati.',
    status_archived_h: 'I tërhequr nga shitja; porositë dhe historia ruhen.',
    ready: 'Gati për publikim',
    missingTitle: 'Për publikim mungojnë:',
    req_name: 'Titulli (ME)',
    req_category: 'Kategoria',
    req_price: 'Çmimi mbi 0',
    req_image: 'Të paktën një imazh',
    publishBlocked: 'Publikimi u bllokua',
    publishBlockedText: 'Mungon: {list}. Plotësoni fushat ose ruajeni si draft.',
    saveAsDraft: 'Ruaj si draft',
    needPublishPerm: 'Për aktivizim nevojitet leja e publikimit.',
    translations: 'Përkthimet',
    c_publishing: 'Publikimi',
    ch_online_h: 'Faqja — katalogu, kërkimi dhe koleksionet.',
    ch_pos_h: 'Shitja në sallon.',
    channelsInactive: 'Kanalet aktivizohen kur statusi është „Aktiv“.',
    noChannel: 'Pa kanal produkti nuk shfaqet askund.',
    c_org: 'Organizimi',
    f_category: 'Kategoria',
    chooseCategory: 'Zgjidhni kategorinë…',
    f_vendor: 'Furnitori',
    f_vendor_ph: 'p.sh. Porta Lux',
    f_tags: 'Etiketat',
    f_tags_ph: 'Shto etiketë + Enter',
    f_collections: 'Koleksionet',
    col_manual: 'Manuale',
    col_smart: 'Automatike (me kushte)',
    col_smart_h: 'Produkti hyn vetë kur plotëson kushtet — ndjek çmimin, etiketat dhe kategorinë.',
    col_none: 'Nuk është në asnjë koleksion automatik.',
    col_noManual: 'Nuk ka koleksione manuale.',
    col_unpublished: 'e papublikuar',
    col_noPerm: 'Për të ndryshuar koleksionet nevojitet leje.',
    c_template: 'Template',
    tpl_standard: 'Produkt standard',
    tpl_standard_h: 'Çmimi, opsionet dhe „Shto në shportë“.',
    tpl_quote: 'Kërkesë oferte',
    tpl_quote_h: 'Sipas masës — klienti dërgon kërkesë në vend të blerjes.',
    c_install: 'Montimi & afati',
    f_install: 'Ofrojmë montim',
    f_install_h: 'Klienti mund ta shtojë montimin në shportë.',
    f_installPrice: 'Çmimi i montimit',
    f_lead: 'Afati i dorëzimit',
    daysUnit: 'ditë',
    f_warranty: 'Garancia',
    yearsUnit: 'vjet',
    c_display: 'Shfaqja në dyqan',
    f_badges: 'Etiketat në kartë',
    f_featured: 'Produkt i veçuar',
    f_featured_h: 'Shfaqet në seksionet e veçuara të faqes kryesore.',
    c_preview: 'Parapamja në faqe',
    c_preview_d: 'Karta ndryshon ndërsa shkruani.',
    shortcutTip: 'Këshillë: Ctrl + S ruan ndryshimet.',
    e_name: 'Shkruani titullin në malazezisht (ME).',
    e_skuDup: 'SKU „{sku}“ përdoret nga „{name}“.',
    e_variantSkuDup: 'SKU-të e varianteve përsëriten.',
    fixErrors: 'Kontrolloni fushat e shënuara',
    leaveTitle: 'Të dilet pa ruajtur?',
    leaveText: 'Ndryshimet e paruajtura në këtë produkt do të humbasin.',
    leave: 'Dil',
    c_options: 'Opsionet / variantet',
    c_options_d: 'Dimensionet, ngjyrat dhe versionet që zgjedh klienti.',
    addOption: 'Shto opsion',
    addValue: 'Shto vlerë',
    optionName: 'Emri i opsionit',
    type_swatch: 'Ngjyra',
    type_button: 'Butona',
    valueLabel: 'Vlera',
    priceDelta: 'Shtesë',
    noOptions: 'Pa opsione — produkti shitet në një version të vetëm.',
    quickAdd: 'Shto shpejt',
    moveUp: 'Lëviz lart',
    moveDown: 'Lëviz poshtë',
    remove: 'Hiq',
    pickColor: 'Zgjidh ngjyrën',
    langHint: 'Gjuha e shkrimit',
    c_specs: 'Specifikimet',
    c_specs_d: 'Të dhënat teknike në tabelën e faqes së produktit.',
    specLabel: 'Vetia',
    specValue: 'Vlera',
    addSpec: 'Shto rresht',
    noSpecs: 'Ende nuk ka specifikime — shtoni materialin, dimensionet ose garancinë.',
  },
  en: {
    title: 'Products',
    addProduct: 'Add product',
    import: 'Import',
    export: 'Export',
    tab_all: 'All',
    tab_active: 'Active',
    tab_draft: 'Draft',
    tab_archived: 'Archived',
    st_active: 'Active',
    st_draft: 'Draft',
    st_archived: 'Archived',
    searchPh: 'Search by name, SKU, barcode or tag…',
    f_category_all: 'Category',
    f_collection_all: 'Collection',
    f_vendor_all: 'Vendor',
    f_stock_all: 'Stock',
    f_stock_in: 'In stock',
    f_stock_low: 'Low stock (≤ 5)',
    f_stock_out: 'Out of stock',
    f_stock_untracked: 'Not tracked',
    f_channel_all: 'Channel',
    ch_online: 'Online Store',
    ch_pos: 'POS (showroom)',
    ch_none: 'No channel',
    filters: 'Filters',
    clearFilters: 'Clear filters',
    sort_newest: 'Newest first',
    sort_updated: 'Recently updated',
    sort_name: 'Name A–Z',
    sort_price_asc: 'Price: low to high',
    sort_price_desc: 'Price: high to low',
    sort_stock: 'Stock: lowest first',
    sort_sold: 'Bestselling',
    col_product: 'Product',
    col_status: 'Status',
    col_inventory: 'Inventory',
    col_category: 'Category',
    col_price: 'Price',
    col_vendor: 'Vendor',
    col_channels: 'Channels',
    col_sold: 'Sold',
    col_cost: 'Cost & margin',
    col_updated: 'Updated',
    columns: 'Columns',
    columnsHint: 'Visible columns',
    inv_in_one: '{n} in 1 variant',
    inv_in_many: '{n} in {v} variants',
    variantsN: '{n} variants',
    madeToOrder: 'Made to order',
    lowStock: 'Low stock',
    outOfStock: 'Out of stock',
    blockedN: '{n} blocked',
    incomingN: '+{n} incoming',
    noCategory: 'Uncategorised',
    onRequest: 'On request',
    fromPrice: 'from {price}',
    footerCount: '{n} products',
    footerBulkHint: 'Bulk actions after selecting',
    pageOf: '{from}–{to} of {total}',
    prevPage: 'Previous page',
    nextPage: 'Next page',
    selectAll: 'Select all on page',
    selectRow: 'Select product',
    selectedN: '{n} selected',
    selectAllFiltered: 'Select all {n} matching',
    allSelected: 'All {n} matching products are selected.',
    clearSelection: 'Clear selection',
    bulk_publish: 'Publish',
    bulk_draft: 'Set as draft',
    bulk_archive: 'Archive',
    bulk_restore: 'Restore',
    bulk_export: 'Export CSV',
    bulk_delete: 'Delete',
    toast_published: 'Published {n} products',
    toast_publishSkipped: '{n} not published — required fields missing',
    toast_drafted: 'Moved to draft: {n}',
    toast_archived: 'Archived: {n}',
    toast_restored: 'Restored as draft: {n}',
    toast_exported: 'Exported {n} products',
    toast_status: '“{name}” → {status}',
    noPerm: 'Your role does not have this permission',
    noPermPublish: 'Publishing requires the “Publish” permission',
    edit: 'Edit',
    duplicate: 'Duplicate',
    viewOnSite: 'View on site',
    publish: 'Publish',
    toDraft: 'Set as draft',
    archive: 'Archive',
    restore: 'Restore',
    delete: 'Delete',
    moreActions: 'More actions',
    duplicated: 'Copy created as a draft',
    emptyTitle: 'No products match these filters',
    emptyText: 'Change the search or clear the filters to see the full catalogue.',
    emptyArchived: 'The archive is empty',
    emptyArchivedText: 'Archived products stay in orders but are not shown on the website.',
    emptyCatalogTitle: 'The catalogue is still empty',
    emptyCatalogText: 'Add your first product or import a catalogue from a CSV file.',

    del_title_one: 'Delete “{name}”?',
    del_title_many: 'Delete {n} products?',
    del_intro: 'Review the consequences before confirming.',
    del_willDelete: 'Deleted permanently',
    del_willArchive: 'Archived instead of deleted',
    del_staysArchived: 'Stays archived',
    del_hasOrders: 'in {n} orders',
    del_hasDrafts: 'in {n} draft orders',
    del_hasQuotes: 'in {n} B2B quotes',
    del_hasPOs: 'in {n} purchase orders',
    del_noHistory: 'No orders or documents',
    del_usedIn: 'Found',
    del_inCollections: 'Removed from collections: {list}',
    del_inDiscounts: 'Referenced by discounts: {list}',
    del_inOffers: 'Part of offers: {list}',
    del_note: 'Orders keep a copy of the item, SKU, price and taxes, so sold products are archived. Permanent deletion is recorded in the audit log.',
    del_confirm: 'Confirm',
    del_confirmDelete: 'Delete {n}',
    del_confirmArchive: 'Archive {n}',
    del_done: 'Deleted: {d} · Archived: {a}',

    imp_title: 'Import products from CSV',
    imp_desc: 'Field mapping, preview and validation before importing — nothing changes until you confirm.',
    imp_step1: 'File',
    imp_step2: 'Mapping',
    imp_step3: 'Preview & validation',
    imp_drop: 'Drop a CSV file here or click to choose one',
    imp_dropHint: 'Separator: comma, semicolon or tab · UTF-8',
    imp_paste: 'or paste the CSV content',
    imp_template: 'Download template',
    imp_sample: 'Load sample',
    imp_detected: '{rows} rows · {cols} columns · separator “{sep}”',
    imp_noRows: 'The file has no data rows under the header.',
    imp_next: 'Continue',
    imp_back: 'Back',
    imp_csvColumn: 'CSV column',
    imp_example: 'Example',
    imp_field: 'CMS field',
    imp_ignore: '— Don’t import —',
    imp_required: 'Map at least the name and the price.',
    imp_existing: 'When the SKU already exists',
    imp_update: 'Update the existing product',
    imp_skip: 'Skip the row',
    imp_newStatus: 'Status of new products',
    imp_asDraft: 'Draft (recommended)',
    imp_fromColumn: 'From the “Status” column',
    imp_sumNew: 'New',
    imp_sumUpdate: 'Updates',
    imp_sumSkip: 'Skipped',
    imp_sumErrors: 'With errors',
    imp_dupReport: 'Duplicate SKU report',
    imp_dupInFile: '{sku} appears twice in the file (rows {a} and {b}) — only the first is imported.',
    imp_dupInCatalog: '{sku} already exists: {name} — {action}.',
    imp_actUpdate: 'it will be updated',
    imp_actSkip: 'it will be skipped',
    imp_noDups: 'No duplicate SKUs — every row is unique.',
    imp_colLine: 'Row',
    imp_colResult: 'Result',
    imp_colNote: 'Note',
    imp_res_create: 'New',
    imp_res_update: 'Update',
    imp_res_skip: 'Skipped',
    imp_res_error: 'Error',
    imp_ok: 'Ready',
    imp_confirm: 'Import {n} products',
    imp_nothing: 'Nothing to import',
    imp_done: 'Imported: {c} new · {u} updated',
    imp_doneHint: 'New products are drafts — review and publish them.',
    imp_showDrafts: 'Show drafts',
    imp_moreRows: '+ {n} more rows',
    imp_readError: 'The file could not be read',
    exp_handle: 'URL',
    exp_variants: 'Variants',
    fld_name_me: 'Name (ME)',
    fld_name_sq: 'Name (SQ)',
    fld_name_en: 'Name (EN)',
    fld_sku: 'SKU',
    fld_barcode: 'Barcode',
    fld_price: 'Price',
    fld_compareAt: 'Compare-at price',
    fld_cost: 'Cost per item',
    fld_category: 'Category',
    fld_vendor: 'Vendor',
    fld_tags: 'Tags',
    fld_stock: 'Stock',
    fld_status: 'Status',
    fld_unit: 'Unit',
    fld_description: 'Description',
    fld_image: 'Image (URL)',
    issue_noName: 'Name missing',
    issue_noPrice: 'Price missing',
    issue_badNumber: '“{value}” is not a number ({field})',
    issue_negative: 'Negative value ({field})',
    issue_dupFile: 'Duplicate SKU in the file',
    issue_exists: 'SKU exists in the catalogue',
    issue_noCategory: 'No category — stays draft',
    issue_unknownCategory: 'Category “{value}” not found',
    issue_compareLow: 'Compare-at is not above the price — no discount shown',
    issue_badStatus: 'Unknown status “{value}” — draft',
    issue_notPublishable: 'Fields missing for publishing — imported as draft',
    issue_nameFromOther: 'Name (ME) taken from another language',

    newTitle: 'New product',
    notFound: 'Product not found',
    notFoundText: 'It may have been deleted, or the link is not correct.',
    backToList: 'Back to products',
    createdOn: 'Created {date}',
    updatedAgo: 'updated {ago}',
    soldN: 'Sold: {n}',
    save: 'Save',
    saved: 'Changes saved',
    created: 'Product created',
    readOnly: 'Read only — your role cannot edit products.',
    archivedBanner: 'This product is archived — hidden from the website, while orders keep showing it.',
    c_title: 'Title & description',
    f_title: 'Title',
    f_short: 'Short description',
    f_short_h: 'One sentence below the name on the product page.',
    f_desc: 'Description',
    f_desc_h: 'Material, installation and care — shown on the product page.',
    c_media: 'Media',
    c_media_d: 'The first image is the cover. Drag images to reorder them.',
    c_price: 'Pricing',
    c_price_d: 'All prices include {vat}% VAT.',
    f_price: 'Price',
    f_compareAt: 'Compare-at price',
    f_compareAt_h: 'Higher than the price → a discount is shown.',
    f_cost: 'Cost per item',
    f_cost_h: 'Internal — customers never see it.',
    margin: 'Margin',
    profit: 'Profit',
    price_discount: 'Customers see {pct}% off — they save {amount}.',
    price_compareLow: 'The compare-at price is not above the price — no discount will show.',
    price_regular: 'No discount — customers pay the price shown.',
    price_note: 'A promotional price and a discount code are two different mechanisms — codes live under “Discounts”.',
    f_unit: 'Sold per',
    f_pack: 'm² per pack',
    f_pack_h: 'Customers order whole packs.',
    unit_kom: 'Piece (pc)',
    unit_m2: 'Square metre (m²)',
    unit_m: 'Linear metre (m)',
    unit_set: 'Set',
    packHint: 'A {size} m² pack costs {price}',
    c_variants: 'Variants & inventory',
    c_variants_d: 'Options generate combinations — each has its own SKU and stock.',
    options: 'Options',
    editOptions: 'Edit options',
    doneOptions: 'Done',
    f_track: 'Track quantity',
    f_track_h: 'Turn off for made-to-measure and made-to-order products.',
    untracked_note: 'Stock is not tracked — the product is made to order and can always be ordered.',
    f_sku: 'SKU',
    f_sku_h: 'Base for the variant SKUs.',
    f_barcode: 'Barcode (EAN)',
    f_stock: 'Available',
    v_variant: 'Variant',
    v_price: 'Price',
    v_sku: 'SKU',
    v_available: 'Available',
    v_total: 'Total',
    v_combos: '{n} combinations · {on} for sale',
    v_groupBy: 'Group by',
    v_noGroup: 'No grouping',
    v_setStock: 'Set stock',
    v_apply: 'Apply',
    v_genSku: 'Generate SKUs',
    v_disable: 'Remove from sale',
    v_enable: 'Put back on sale',
    v_disabled: 'Not for sale',
    v_selected: '{n} selected',
    v_selectAll: 'Select all variants',
    v_dupSku: 'Duplicate SKU',
    v_showAll: 'Show all ({n})',
    v_showLess: 'Show less',
    inv_incoming: 'Incoming: {n}',
    inv_blocked: 'Blocked: {n}',
    inv_link: 'Inventory & movements',
    lowStockWarn: 'Low stock — time to restock.',
    outOfStockWarn: 'Out of stock — shown as “made to order” on the website.',
    stockPacksH: 'Stock for m² products is counted in packs.',
    packsUnit: 'packs',
    c_shipping: 'Shipping',
    f_physical: 'Physical product',
    f_physical_h: 'Shipped to the customer — weight and dimensions are optional.',
    f_physicalOff: 'Service or digital product — nothing is shipped.',
    f_weight: 'Weight',
    f_dims: 'Package dimensions',
    dim_l: 'Length',
    dim_w: 'Width',
    dim_h: 'Height',
    optional: 'optional',
    c_seo: 'SEO & URL',
    c_seo_d: 'How the product appears in Google search.',
    f_slug: 'URL handle',
    slugAuto: 'Generated automatically from the Montenegrin name.',
    slugManual: 'Edited manually.',
    slugReset: 'Reset to automatic',
    f_metaTitle: 'Meta title',
    f_metaTitle_h: 'Empty = product name.',
    f_metaDesc: 'Meta description',
    f_metaDesc_h: 'Empty = short description.',
    googlePreview: 'Search preview',
    inStock: 'In stock',
    redirect: 'Redirect the old address /proizvod/{old}',
    redirect_h: 'Links from Google and social media keep working.',
    c_status: 'Status',
    status_active_h: 'Visible on the selected sales channels.',
    status_draft_h: 'Hidden — finish it and publish when it is ready.',
    status_archived_h: 'Withdrawn from sale; orders and history are kept.',
    ready: 'Ready to publish',
    missingTitle: 'Missing to publish:',
    req_name: 'Title (ME)',
    req_category: 'Category',
    req_price: 'Price above 0',
    req_image: 'At least one image',
    publishBlocked: 'Publishing blocked',
    publishBlockedText: 'Missing: {list}. Complete the fields or save as draft.',
    saveAsDraft: 'Save as draft',
    needPublishPerm: 'Activating requires the publish permission.',
    translations: 'Translations',
    c_publishing: 'Publishing',
    ch_online_h: 'Website — catalogue, search and collections.',
    ch_pos_h: 'Sales in the showroom.',
    channelsInactive: 'Channels go live when the status is “Active”.',
    noChannel: 'Without a channel the product is not shown anywhere.',
    c_org: 'Organisation',
    f_category: 'Category',
    chooseCategory: 'Choose a category…',
    f_vendor: 'Vendor',
    f_vendor_ph: 'e.g. Porta Lux',
    f_tags: 'Tags',
    f_tags_ph: 'Add a tag + Enter',
    f_collections: 'Collections',
    col_manual: 'Manual',
    col_smart: 'Automatic (rules)',
    col_smart_h: 'The product joins by itself when it meets the rules — it follows price, tags and category.',
    col_none: 'Not in any automatic collection.',
    col_noManual: 'No manual collections.',
    col_unpublished: 'unpublished',
    col_noPerm: 'Changing collections requires permission.',
    c_template: 'Template',
    tpl_standard: 'Standard product',
    tpl_standard_h: 'Price, options and “Add to cart”.',
    tpl_quote: 'Quote request',
    tpl_quote_h: 'Made to measure — customers send a request instead of buying.',
    c_install: 'Installation & lead time',
    f_install: 'We offer installation',
    f_install_h: 'Customers can add installation in the cart.',
    f_installPrice: 'Installation price',
    f_lead: 'Lead time',
    daysUnit: 'days',
    f_warranty: 'Warranty',
    yearsUnit: 'yrs',
    c_display: 'Storefront display',
    f_badges: 'Card badges',
    f_featured: 'Featured product',
    f_featured_h: 'Shown in highlighted sections on the homepage.',
    c_preview: 'Storefront preview',
    c_preview_d: 'The card updates as you type.',
    shortcutTip: 'Tip: Ctrl + S saves your changes.',
    e_name: 'Enter the Montenegrin (ME) title.',
    e_skuDup: 'SKU “{sku}” is already used by “{name}”.',
    e_variantSkuDup: 'Variant SKUs repeat.',
    fixErrors: 'Please check the highlighted fields',
    leaveTitle: 'Leave without saving?',
    leaveText: 'Unsaved changes to this product will be lost.',
    leave: 'Leave',
    c_options: 'Options / variants',
    c_options_d: 'Sizes, colours and versions the customer can choose from.',
    addOption: 'Add option',
    addValue: 'Add value',
    optionName: 'Option name',
    type_swatch: 'Swatches',
    type_button: 'Buttons',
    valueLabel: 'Value',
    priceDelta: 'Surcharge',
    noOptions: 'No options — the product is sold in a single version.',
    quickAdd: 'Quick add',
    moveUp: 'Move up',
    moveDown: 'Move down',
    remove: 'Remove',
    pickColor: 'Pick colour',
    langHint: 'Editing language',
    c_specs: 'Specifications',
    c_specs_d: 'Technical data shown in the table on the product page.',
    specLabel: 'Property',
    specValue: 'Value',
    addSpec: 'Add row',
    noSpecs: 'No specifications yet — add material, dimensions or warranty.',
  },
});

export type PdKey = keyof typeof pd.me;
