import type { ComponentType } from 'react';
import { FileText, FolderTree, Layers, Link2, Megaphone, Package } from 'lucide-react';
import { defineDict } from '@/i18n';
import type { MenuItemType } from '@/lib/types';

export const TYPE_ICON: Record<MenuItemType, ComponentType<{ className?: string }>> = {
  page: FileText,
  product: Package,
  collection: Layers,
  category: FolderTree,
  offer: Megaphone,
  url: Link2,
};

/** Menu editor strings (PDF p.36 "Menu dhe media"). */
export const mn = defineDict({
  me: {
    description: 'Navigacija prodavnice: glavni meni u zaglavlju (desktop, mega meni „Proizvodi“ i mobilni meni) i kolone podnožja. Linkovi vode na stranicu, proizvod, kolekciju, kategoriju, ponudu ili URL.',
    menus: 'Meniji',
    main: 'Glavni meni',
    mainWhere: 'Zaglavlje · desktop, mega meni i mobilni',
    footer: 'Podnožje',
    footerWhere: 'Kolone u podnožju sajta',
    account: 'Korisnički nalog',
    accountWhere: 'Uključuje se sa modulom naloga kupaca',
    links: '{n} linkova',
    menuName: 'Naziv menija',
    handle: 'Oznaka',
    addLink: 'Dodaj link',
    addChild: 'Dodaj podlink',
    newLink: 'Novi link',
    editLink: 'Uredi link',
    label: 'Naziv linka',
    labelHint: 'Prikazuje se u meniju — na sva tri jezika.',
    useEntityName: 'Preuzmi naziv',
    linkType: 'Vodi na',
    target: 'Odredište',
    search: 'Pretraga…',
    urlLabel: 'Adresa',
    urlPh: '/kontakt ili https://…',
    urlHint: 'Interna putanja (/kontakt) ili puna adresa (https://…). Prazno = naslov kolone bez linka.',
    urlInvalid: 'Unesite putanju koja počinje sa / ili punu adresu https://…',
    targetRequired: 'Izaberite odredište.',
    labelRequired: 'Unesite naziv na crnogorskom.',
    apply: 'Primijeni',
    resolved: 'Adresa na sajtu',
    noLink: 'Bez linka (naslov kolone)',
    hasChildren: 'Ima {n} podlinkova — prikazuje se kao padajući meni / kolona.',
    moveUp: 'Pomjeri gore',
    moveDown: 'Pomjeri dolje',
    indent: 'Uvuci (podlink)',
    outdent: 'Izvuci na prvi nivo',
    removeTitle: 'Ukloniti link „{name}“?',
    removeText: 'Link se uklanja iz menija.',
    removeTextKids: 'Uklanjaju se i njegovi podlinkovi ({n}).',
    emptyMenu: 'Meni je prazan',
    emptyMenuText: 'Dodajte prvi link — stranicu, kategoriju, kolekciju, ponudu ili URL.',
    dragHint: 'Prevucite za redosljed · jedan nivo podlinkova',
    saved: 'Meni je sačuvan i objavljen',
    preview: 'Pregled',
    previewText: 'Ovako se meni prikazuje na sajtu (samo vidljivi linkovi).',
    readOnlyMenus: 'Izmjene menija se odmah objavljuju — potrebna je dozvola za uređivanje i objavu.',
    noMenu: 'Meni ne postoji',
    fallbackNote: 'Bez vidljivih linkova sajt prikazuje podrazumijevani meni.',
    type_page: 'Stranica',
    type_product: 'Proizvod',
    type_collection: 'Kolekcija',
    type_category: 'Kategorija',
    type_offer: 'Ponuda',
    type_url: 'URL',
    issue_missing: 'Odredište ne postoji',
    issue_draft: 'Nacrt — ne prikazuje se',
    issue_hidden: 'Skriveno — ne prikazuje se',
    issue_scheduled: 'Zakazano — prikazuje se kasnije',
    issue_expired: 'Isteklo — ne prikazuje se',
    issue_paused: 'Pauzirano — ne prikazuje se',
    issue_archived: 'Arhivirano — ne prikazuje se',
    issue_invalid: 'Neispravan URL',
    nothing: 'Nema rezultata',
    desktop: 'Desktop',
    mobile: 'Mobilni',
    viewOnSite: 'Pogledaj na sajtu',
    saveErrors: 'Ispravite označene linkove prije čuvanja.',
    off: 'Isključeno',
    visibleCount: '{n} vidljivih',
    hiddenCount: '{n} se ne prikazuje',
    previewHint: 'Kliknite stavku sa podlinkovima da otvorite padajući meni.',
    topLevel: 'Prvi nivo',
    subOf: 'Podlink stavke „{name}“',
    quickPaths: 'Brze putanje',
    change: 'Promijeni',
    keyboardHint: 'Alt + ↑/↓ pomjera link u fokusu',
    unsavedHere: 'Nesačuvano',
    errorsCount: '{n} za ispravku',
    shown: 'Prikazuje se',
    whereShown: 'Gdje se prikazuje',
    moreResults: 'Još {n} — suzite pretragu',
    columns: '{n} kolone',
    noTarget: 'Odredište nije izabrano',
    dropdown: 'Padajući meni',
    dragItem: 'Prevuci',
    seeAll: 'Pogledaj sve',
    allProducts: 'Svi proizvodi',
    home: 'Početna',
    categories: 'Kategorije',
    linkFixed: 'Link je ažuriran',
    removed: 'Link je uklonjen',
  },
  sq: {
    description: 'Navigimi i dyqanit: menuja kryesore në header (desktop, mega-menuja „Produktet“ dhe celulari) dhe kolonat e footer-it. Lidhje te faqe, produkt, koleksion, kategori, ofertë ose URL.',
    menus: 'Menutë',
    main: 'Menuja kryesore',
    mainWhere: 'Header · desktop, mega-menu dhe celular',
    footer: 'Footer',
    footerWhere: 'Kolonat në fund të faqes',
    account: 'Llogaria e klientit',
    accountWhere: 'Aktivizohet me modulin e llogarive të klientëve',
    links: '{n} lidhje',
    menuName: 'Emri i menusë',
    handle: 'Identifikuesi',
    addLink: 'Shto lidhje',
    addChild: 'Shto nënlidhje',
    newLink: 'Lidhje e re',
    editLink: 'Ndrysho lidhjen',
    label: 'Emri i lidhjes',
    labelHint: 'Shfaqet në menu — në të tri gjuhët.',
    useEntityName: 'Merr emrin',
    linkType: 'Lidhet me',
    target: 'Destinacioni',
    search: 'Kërko…',
    urlLabel: 'Adresa',
    urlPh: '/kontakt ose https://…',
    urlHint: 'Shteg i brendshëm (/kontakt) ose adresë e plotë (https://…). Bosh = titull kolone pa lidhje.',
    urlInvalid: 'Shkruani një shteg që fillon me / ose adresë të plotë https://…',
    targetRequired: 'Zgjidhni destinacionin.',
    labelRequired: 'Shkruani emrin në malazezisht.',
    apply: 'Zbato',
    resolved: 'Adresa në faqe',
    noLink: 'Pa lidhje (titull kolone)',
    hasChildren: 'Ka {n} nënlidhje — shfaqet si menu zbritëse / kolonë.',
    moveUp: 'Lëviz lart',
    moveDown: 'Lëviz poshtë',
    indent: 'Fut brenda (nënlidhje)',
    outdent: 'Nxirr në nivelin e parë',
    removeTitle: 'Të hiqet lidhja „{name}“?',
    removeText: 'Lidhja hiqet nga menuja.',
    removeTextKids: 'Hiqen edhe nënlidhjet e saj ({n}).',
    emptyMenu: 'Menuja është bosh',
    emptyMenuText: 'Shtoni lidhjen e parë — faqe, kategori, koleksion, ofertë ose URL.',
    dragHint: 'Tërhiqni për renditjen · një nivel nënlidhjesh',
    saved: 'Menuja u ruajt dhe u publikua',
    preview: 'Parapamja',
    previewText: 'Kështu shfaqet menuja në faqe (vetëm lidhjet e dukshme).',
    readOnlyMenus: 'Ndryshimet e menusë publikohen menjëherë — kërkohet leje redaktimi dhe publikimi.',
    noMenu: 'Menuja nuk ekziston',
    fallbackNote: 'Pa lidhje të dukshme, faqja shfaq menunë e paracaktuar.',
    type_page: 'Faqe',
    type_product: 'Produkt',
    type_collection: 'Koleksion',
    type_category: 'Kategori',
    type_offer: 'Ofertë',
    type_url: 'URL',
    issue_missing: 'Destinacioni nuk ekziston',
    issue_draft: 'Draft — nuk shfaqet',
    issue_hidden: 'Fshehur — nuk shfaqet',
    issue_scheduled: 'Planifikuar — shfaqet më vonë',
    issue_expired: 'Ka skaduar — nuk shfaqet',
    issue_paused: 'Pezulluar — nuk shfaqet',
    issue_archived: 'Arkivuar — nuk shfaqet',
    issue_invalid: 'URL e pavlefshme',
    nothing: 'Asnjë rezultat',
    desktop: 'Desktop',
    mobile: 'Celular',
    viewOnSite: 'Shiko në faqe',
    saveErrors: 'Rregulloni lidhjet e shënuara para ruajtjes.',
    off: 'Joaktiv',
    visibleCount: '{n} të dukshme',
    hiddenCount: '{n} nuk shfaqen',
    previewHint: 'Klikoni një element me nënlidhje për të hapur menunë zbritëse.',
    topLevel: 'Niveli i parë',
    subOf: 'Nënlidhje e „{name}“',
    quickPaths: 'Shtigje të shpejta',
    change: 'Ndrysho',
    keyboardHint: 'Alt + ↑/↓ lëviz lidhjen në fokus',
    unsavedHere: 'Pa ruajtur',
    errorsCount: '{n} për t’u rregulluar',
    shown: 'Shfaqet',
    whereShown: 'Ku shfaqet',
    moreResults: 'Edhe {n} — ngushtoni kërkimin',
    columns: '{n} kolona',
    noTarget: 'Destinacioni nuk është zgjedhur',
    dropdown: 'Menu zbritëse',
    dragItem: 'Tërhiq',
    seeAll: 'Shiko të gjitha',
    allProducts: 'Të gjitha produktet',
    home: 'Ballina',
    categories: 'Kategoritë',
    linkFixed: 'Lidhja u përditësua',
    removed: 'Lidhja u hoq',
  },
  en: {
    description: 'Store navigation: the main menu in the header (desktop, the “Products” mega menu and mobile) and the footer columns. Links go to a page, product, collection, category, offer or URL.',
    menus: 'Menus',
    main: 'Main menu',
    mainWhere: 'Header · desktop, mega menu and mobile',
    footer: 'Footer',
    footerWhere: 'Footer link columns',
    account: 'Customer account',
    accountWhere: 'Enabled with the customer accounts module',
    links: '{n} links',
    menuName: 'Menu name',
    handle: 'Handle',
    addLink: 'Add link',
    addChild: 'Add sub-link',
    newLink: 'New link',
    editLink: 'Edit link',
    label: 'Link label',
    labelHint: 'Shown in the menu — in all three languages.',
    useEntityName: 'Use its name',
    linkType: 'Links to',
    target: 'Destination',
    search: 'Search…',
    urlLabel: 'Address',
    urlPh: '/kontakt or https://…',
    urlHint: 'An internal path (/kontakt) or a full address (https://…). Empty = column heading without a link.',
    urlInvalid: 'Enter a path starting with / or a full https://… address',
    targetRequired: 'Choose a destination.',
    labelRequired: 'Enter the Montenegrin label.',
    apply: 'Apply',
    resolved: 'Address on site',
    noLink: 'No link (column heading)',
    hasChildren: 'Has {n} sub-links — shown as a dropdown / column.',
    moveUp: 'Move up',
    moveDown: 'Move down',
    indent: 'Indent (sub-link)',
    outdent: 'Move to top level',
    removeTitle: 'Remove the link “{name}”?',
    removeText: 'The link is removed from the menu.',
    removeTextKids: 'Its sub-links ({n}) are removed too.',
    emptyMenu: 'This menu is empty',
    emptyMenuText: 'Add the first link — a page, category, collection, offer or URL.',
    dragHint: 'Drag to reorder · one level of sub-links',
    saved: 'Menu saved and published',
    preview: 'Preview',
    previewText: 'How the menu appears on the site (visible links only).',
    readOnlyMenus: 'Menu changes go live immediately — edit and publish permissions are required.',
    noMenu: 'Menu not found',
    fallbackNote: 'Without visible links the site shows the default menu.',
    type_page: 'Page',
    type_product: 'Product',
    type_collection: 'Collection',
    type_category: 'Category',
    type_offer: 'Offer',
    type_url: 'URL',
    issue_missing: 'Destination not found',
    issue_draft: 'Draft — not shown',
    issue_hidden: 'Hidden — not shown',
    issue_scheduled: 'Scheduled — shown later',
    issue_expired: 'Expired — not shown',
    issue_paused: 'Paused — not shown',
    issue_archived: 'Archived — not shown',
    issue_invalid: 'Invalid URL',
    nothing: 'No results',
    desktop: 'Desktop',
    mobile: 'Mobile',
    viewOnSite: 'View on site',
    saveErrors: 'Fix the highlighted links before saving.',
    off: 'Off',
    visibleCount: '{n} visible',
    hiddenCount: '{n} not shown',
    previewHint: 'Click an item with sub-links to open its dropdown.',
    topLevel: 'Top level',
    subOf: 'Sub-link of “{name}”',
    quickPaths: 'Quick paths',
    change: 'Change',
    keyboardHint: 'Alt + ↑/↓ moves the focused link',
    unsavedHere: 'Unsaved',
    errorsCount: '{n} to fix',
    shown: 'Shown',
    whereShown: 'Where it appears',
    moreResults: '{n} more — refine the search',
    columns: '{n} columns',
    noTarget: 'No destination selected',
    dropdown: 'Dropdown',
    dragItem: 'Drag',
    seeAll: 'See all',
    allProducts: 'All products',
    home: 'Home',
    categories: 'Categories',
    linkFixed: 'Link updated',
    removed: 'Link removed',
  },
});
