import { defineDict } from '@/i18n';

/** Inventory + purchase orders (PDF pp.15–16) — PrintWorks: stock-kept items vs. made-to-order print products. */
export const inv = defineDict({
  sq: {
    title: 'Inventari',
    subtitle: 'Stoku i artikujve që mbahen në magazinë — gjendja fizike, e rezervuar dhe e disponueshme. Produktet me porosi prodhohen sipas tirazhit dhe nuk kanë stok. Çdo ndryshim krijon lëvizje me arsye, dokument burim dhe përdorues.',
    col_product: 'Produkti',
    col_sku: 'SKU',
    col_onHand: 'Në dorë',
    col_committed: 'Të rezervuara',
    col_unavailable: 'Të bllokuara',
    col_available: 'Të disponueshme',
    col_incoming: 'Në ardhje',
    col_location: 'Lokacioni',
    hint_onHand: 'Fizikisht në lokacion, përfshirë të rezervuarat',
    hint_committed: 'Në porosi që ende nuk janë përmbushur',
    hint_unavailable: 'Të dëmtuara, mostra për panaire ose në kontroll cilësie',
    hint_available: 'Në dorë − të rezervuara − të bllokuara',
    hint_incoming: 'Nga furnizimet e dërguara dhe pjesërisht të pranuara',
    formula: 'Të disponueshme = Në dorë − Të rezervuara − Të bllokuara',
    f_all: 'Të gjitha',
    f_stocked: 'Në stok',
    f_mto: 'Me porosi',
    f_low: 'Stok i ulët',
    f_out: 'Pa stok',
    f_incoming: 'Në ardhje',
    allLocations: 'Të gjitha lokacionet',
    searchPh: 'Kërko sipas emrit, SKU-së ose kategorisë…',
    mto: 'Me porosi',
    mtoHint: 'Prodhohet për çdo porosi sipas tirazhit — nuk mbahet stok',
    leadDays: 'afati: {n} ditë pune',
    leadDay1: 'afati: 1 ditë pune',
    moqShort: 'min. {n} {u}',
    lowTag: 'I ulët',
    outTag: 'Pa stok',
    adjust: 'Korrigjo',
    adjustStock: 'Korrigjo stokun',
    history: 'Historiku',
    movements: 'Lëvizjet e stokut',
    allMovements: 'Të gjitha lëvizjet',
    exportCsv: 'Eksporto CSV',
    exported: 'CSV u shkarkua',
    newPo: 'Furnizim i ri',
    kpi_value: 'Vlera e stokut',
    kpi_valueHint: 'me koston e blerjes · {n} njësi',
    kpi_units: 'Njësi në dorë',
    kpi_unitsHint: '{n} artikuj në stok',
    kpi_mto: 'Produkte me porosi',
    kpi_mtoHint: 'afati {a}–{b} ditë pune',
    kpi_mtoHintNoLead: 'prodhim sipas tirazhit',
    kpi_low: 'Stok i ulët',
    kpi_lowHint: '1–{n} të disponueshme',
    kpi_out: 'Pa stok',
    kpi_outHint: 'nuk mund të shiten',
    kpi_incoming: 'Në ardhje',
    kpi_incomingHint: 'nga {n} furnizime të hapura',
    emptyTitle: 'Asnjë produkt për këtë filtër',
    emptyText: 'Ndryshoni kërkimin, lokacionin ose filtrin.',
    clearFilters: 'Pastro filtrat',
    showing: 'Shfaqen {n} nga {total}',
    archivedHidden: 'Produktet e arkivuara nuk shfaqen ({n})',
    variants: '{n} variante',
    draftTag: 'Draft',
    noPermInventory: 'Roli juaj nuk mund të ndryshojë stokun',
    noPermExport: 'Roli juaj nuk mund të eksportojë të dhëna',
    noPermPurchasing: 'Roli juaj nuk ka qasje te furnizimet',
    sortBy: 'Rendit',
    sort_name: 'Emri A–Zh',
    sort_available: 'Më pak të disponueshme',
    sort_onHand: 'Më shumë në dorë',
    sort_incoming: 'Më shumë në ardhje',
    defaultLoc: 'kryesor',

    r_correction: 'Korrigjim',
    r_received: 'Pranim nga furnitori',
    r_damaged: 'E dëmtuar / e skartuar',
    r_return: 'Kthim nga klienti',
    r_sale: 'Shitje',
    r_count: 'Numërim inventari',

    mv_time: 'Koha',
    mv_variant: 'Varianti',
    mv_qty: 'Sasia',
    mv_reason: 'Arsyeja',
    mv_doc: 'Dokumenti burim',
    mv_user: 'Përdoruesi',
    mv_location: 'Lokacioni',
    mv_note: 'Shënim',
    mv_allVariants: 'Të gjitha variantet',
    mv_web: 'Dyqani online',
    mv_removed: 'Produkt i hequr nga katalogu',
    mv_empty: 'Ende nuk ka lëvizje',
    mv_emptyText: 'Shitjet, pranimet nga furnitorët dhe korrigjimet do të shfaqen këtu.',
    mv_count: '{n} lëvizje',
    mv_allTitle: 'Të gjitha lëvizjet e stokut',
    mv_allSub: '{n} ndryshimet e fundit në të gjitha produktet',
    reservedBy: 'E rezervuar në porosi',
    inOpenOrders: 'Në porosi të hapura',
    mto_lead: 'Afati i prodhimit',
    mto_moq: 'Sasia minimale',
    mto_inOrders: 'Në porosi të hapura',
    mto_days: '{n} ditë pune',
    mto_note: 'Prodhohet për çdo porosi (tirazh) — nuk ka stok, rezervime apo korrigjime stoku. Sasitë në porosi të hapura janë radha e prodhimit.',
    incomingFrom: 'Në ardhje nga furnizimet',
    expectedOn: 'pritet më {d}',
    openProduct: 'Hap produktin',
    noOpenOrders: 'Asnjë porosi e hapur me këtë produkt.',
    f_mvAll: 'Të gjitha',
    f_mvIn: 'Hyrje',
    f_mvOut: 'Dalje',
    mv_more: 'Shfaq më shumë',

    adj_desc: 'Çdo ndryshim krijon një lëvizje me arsye, shënim dhe përdorues.',
    adj_tabOnHand: 'Në dorë',
    adj_tabBlocked: 'Të bllokuara',
    adj_by: 'Ndrysho me ±',
    adj_set: 'Sasia e re (e numëruar)',
    adj_qtyBy: 'Sasia (+ hyrje, − dalje)',
    adj_qtySet: 'Të numëruara në dorë',
    adj_reason: 'Arsyeja',
    adj_note: 'Shënim',
    adj_noteOpt: 'opsional',
    adj_notePh: 'p.sh. Numërim mujor — 2 kuti të dëmtuara në depo',
    adj_preview: 'Parapamja e ndryshimit',
    adj_save: 'Ruaj korrigjimin',
    adj_saved: 'Stoku u përditësua',
    adj_belowCommitted: 'Nuk mund të jetë nën të rezervuarat ({n}) — fillimisht anuloni ose përmbushni porosinë.',
    adj_noChange: 'Shkruani ndryshimin e sasisë',
    adj_blockedHint: 'Njësitë e bllokuara mbeten në dorë, por nuk mund të shiten (të dëmtuara, mostra për panaire, në kontroll cilësie).',
    adj_blockedQty: 'Njësi të bllokuara',
    adj_blockedMax: 'Maksimumi {n} (në dorë pa të rezervuarat)',
    adj_blockedSaved: 'Njësitë e bllokuara u përditësuan',
    adj_untracked: 'Ky produkt prodhohet me porosi, sipas tirazhit, dhe nuk mban stok. Nëse do ta mbani në magazinë, vendosni sasinë e stokut te kartela e produktit.',
    adj_damagedHint: 'Malli i dëmtuar zakonisht e ul stokun — shkruani numër negativ.',
    adj_movement: 'Lëvizje: {reason} · {user}',

    po_title: 'Furnizimet',
    po_subtitle: 'Porositë te furnitorët — artikuj që mbahen në stok, mostra dhe produkte të prodhuara nga partnerët. Stoku ndryshon vetëm kur pranohet malli.',
    po_new: 'Furnizim i ri',
    po_number: 'Numri',
    po_supplier: 'Furnitori',
    po_destination: 'Destinacioni',
    po_status: 'Statusi',
    po_received: 'Pranuar',
    po_expected: 'Pritet',
    po_total: 'Vlera',
    po_created: 'Krijuar',
    st_draft: 'Draft',
    st_sent: 'Dërguar',
    st_partial: 'Pjesërisht pranuar',
    st_closed: 'Mbyllur',
    po_overdue: 'Me vonesë',
    po_searchPh: 'Kërko numrin, furnitorin ose referencën…',
    po_kpiOpen: 'Furnizime të hapura',
    po_kpiOpenHint: 'të dërguara ose pjesërisht të pranuara',
    po_kpiUnits: 'Njësi në ardhje',
    po_kpiUnitsHint: 'ende të papranuara',
    po_kpiValue: 'Vlera e hapur',
    po_kpiValueHint: 'malli i papranuar me koston e blerjes',
    po_kpiOverdue: 'Me vonesë',
    po_kpiOverdueHint: 'ka kaluar data e pritjes',
    po_emptyTitle: 'Nuk ka furnizime',
    po_emptyText: 'Krijoni një furnizim kur porositni mall nga një furnitor — materiale ambalazhimi, mostra ose artikuj nga partnerët.',
    po_lines: '{n} artikuj',
    po_costHidden: 'E fshehur',

    ed_supplierCard: 'Furnitori dhe destinacioni',
    ed_supplierPh: 'p.sh. furnitori i letrës & kartonit',
    ed_supplierHint: 'Furnitori nuk është klient; kostot e tij shihen vetëm nga role me leje.',
    ed_products: 'Artikujt',
    ed_addProduct: 'Shto artikull',
    ed_searchProduct: 'Kërko artikuj në stok ose produkte nga partnerët…',
    ed_noMatch: 'Asnjë produkt për këtë kërkim.',
    ed_outsourced: 'Me porosi · nga partneri',
    ed_noLines: 'Shtoni artikujt që po porositni nga furnitori.',
    ed_ordered: 'E porositur',
    ed_received: 'E pranuar',
    ed_rejected: 'E refuzuar',
    ed_cost: 'Kosto / njësi',
    ed_lineTotal: 'Totali',
    ed_summary: 'Përmbledhje kostoje',
    ed_subtotal: 'Vlera e furnizimit (pa TVSH)',
    ed_receivedValue: 'E pranuar me kosto',
    ed_unitsTotal: 'Njësi gjithsej',
    ed_details: 'Detajet',
    ed_reference: 'Referenca e furnitorit',
    ed_referencePh: 'p.sh. numri i profaturës',
    ed_expected: 'Data e pritjes',
    ed_note: 'Shënim',
    ed_notePh: 'Kushtet e pagesës, transporti, paletat, shënime për pranimin…',
    ed_markSent: 'Shëno si të dërguar',
    ed_receive: 'Prano mallin',
    ed_close: 'Mbyll furnizimin',
    ed_closeTitle: 'Të mbyllet furnizimi pa pjesën e mbetur?',
    ed_closeText: '{n} njësi nuk do të pranohen. Stoku nuk ndryshon dhe pjesa e mbetur nuk shfaqet më „në ardhje“.',
    ed_closed: 'Furnizimi u mbyll',
    ed_sent: 'Furnizimi u shënua si i dërguar',
    ed_created: 'Furnizimi u krijua',
    ed_saved: 'Furnizimi u ruajt',
    ed_deleteTitle: 'Të fshihet drafti {n}?',
    ed_deleted: 'Drafti u fshi',
    ed_saveFirst: 'Ruani ndryshimet fillimisht',
    ed_needLines: 'Shtoni të paktën një artikull',
    ed_needSupplier: 'Shkruani furnitorin',
    ed_needQty: 'Sasia e porositur duhet të jetë më e madhe se 0',
    ed_receipts: 'Pranimet',
    ed_receiptsEmpty: 'Malli ende nuk është pranuar.',
    ed_differences: 'Diferencat',
    ed_noDifferences: 'Pa diferenca — gjithçka u pranua siç u porosit.',
    ed_missing: 'mungojnë {n}',
    ed_rejectedN: 'refuzuar {n}',
    ed_notReceived: 'të papranuara {n}',
    ed_stockHint: 'Stoku ndryshon vetëm kur pranohet malli.',
    ed_notFound: 'Furnizimi nuk u gjet',
    ed_notFoundText: 'Mund të jetë fshirë. Kthehuni te lista e furnizimeve.',
    ed_progress: '{r} nga {o} të pranuara',
    ed_remove: 'Hiq artikullin',
    ed_lockedLine: 'Artikulli me mall të pranuar nuk mund të hiqet',
    ed_minOrdered: 'Minimumi {n} (tashmë të pranuara/refuzuara)',
    ed_readOnly: 'Furnizimi i mbyllur është vetëm për lexim.',
    ed_noPermEdit: 'Roli juaj mund vetëm t’i shikojë furnizimet',
    ed_noPermDelete: 'Vetëm pronari mund të fshijë furnizime',
    ed_backToList: 'Kthehu te furnizimet',
    ed_steps: 'Rrjedha e furnizimit',
    ed_available: '{n} të disponueshme',
    ed_suggest: 'Artikujt e furnitorit {v}:',
    ed_receivedOn: 'pranuar më {d}',
    ed_receiveDisabled: 'Malli pranohet vetëm pasi furnizimi të jetë dërguar',
    ed_unknownItem: 'Artikull jashtë katalogut',

    rc_title: 'Prano mallin — {n}',
    rc_desc: 'Shkruani çfarë mbërriti tani. Stoku rritet vetëm për njësitë e pranuara; të refuzuarat regjistrohen si diferencë.',
    rc_remaining: 'Mbetet',
    rc_acceptNow: 'Prano tani',
    rc_rejectNow: 'Refuzo',
    rc_all: 'Prano gjithë të mbeturat',
    rc_confirm: 'Konfirmo pranimin',
    rc_done: 'U pranuan {n} njësi — stoku u përditësua',
    rc_nothing: 'Asgjë e re — ky pranim është regjistruar tashmë',
    rc_idempotent: 'Pranimi ruhet si total kumulativ për çdo artikull: i njëjti dokument i pranuar dy herë nuk e shton stokun dy herë.',
    rc_diffTitle: 'Diferencat pas këtij pranimi',
    rc_willClose: 'Të gjithë artikujt janë zgjidhur — furnizimi do të mbyllet.',
    rc_willPartial: 'Pjesa e mbetur mbetet e hapur si „në ardhje“.',
    rc_tooMany: 'Më shumë se sa mbetet ({n})',
    rc_stockAfter: 'në dorë pas: {n}',
    rc_noStock: 'me porosi — pa stok',
    rc_rejectedHint: 'Të refuzuarat nuk hyjnë në stok',
    rc_nothingEntered: 'Shkruani sasinë e pranuar ose të refuzuar',
    rc_allDone: 'Të gjithë artikujt e këtij furnizimi janë zgjidhur tashmë.',

    tr_title: 'Transferimet',
    tr_badge: 'Joaktiv · sipas nevojës',
    tr_text: 'Lëvizja e mallit mes lokacioneve: origjinë, destinacion, artikuj, datë, referencë, shënim dhe lidhje me furnizimin. Lëvizjet në origjinë dhe destinacion ruajnë një dokument të përbashkët dhe nuk krijojnë stok nga hiçi.',
    tr_small: 'Sot mjafton korrigjimi i stokut me arsye. Transferimet aktivizohen kur ka nevojë reale — p.sh. kur malli lëviz rregullisht mes fabrikës dhe depos.',
    tr_flow: 'Rrjedha e transferimit',
    tr_s1: 'Draft',
    tr_s2: 'Gati',
    tr_s3: 'Në transit',
    tr_s4: 'Pjesërisht pranuar',
    tr_s5: 'Mbyllur',
    tr_locations: 'Lokacionet',
    tr_ready: '{n} lokacione të konfiguruara — transferimet mund të aktivizohen.',
    tr_one: 'Është konfiguruar një lokacion — transferimet nuk nevojiten.',
    tr_manage: 'Menaxho lokacionet',
    tr_rule: 'Një transferim nuk lejon të dërgohet më shumë se sasia e lejuar.',
    tr_pickup: 'marrje e porosive',
  },
  en: {
    title: 'Inventory',
    subtitle: 'Stock of the items kept in the warehouse — physical, committed and available. Made-to-order products are produced per print run and carry no stock. Every change leaves a movement with reason, source document and user.',
    col_product: 'Product',
    col_sku: 'SKU',
    col_onHand: 'On hand',
    col_committed: 'Committed',
    col_unavailable: 'Unavailable',
    col_available: 'Available',
    col_incoming: 'Incoming',
    col_location: 'Location',
    hint_onHand: 'Physically at the location, including committed',
    hint_committed: 'In orders that are not fulfilled yet',
    hint_unavailable: 'Damaged, trade-fair samples or in quality control',
    hint_available: 'On hand − committed − unavailable',
    hint_incoming: 'From sent and partially received purchase orders',
    formula: 'Available = On hand − Committed − Unavailable',
    f_all: 'All',
    f_stocked: 'In stock',
    f_mto: 'Made to order',
    f_low: 'Low stock',
    f_out: 'Out of stock',
    f_incoming: 'Incoming',
    allLocations: 'All locations',
    searchPh: 'Search by name, SKU or category…',
    mto: 'Made to order',
    mtoHint: 'Produced for every order per print run — no stock is kept',
    leadDays: 'lead time: {n} working days',
    leadDay1: 'lead time: 1 working day',
    moqShort: 'min. {n} {u}',
    lowTag: 'Low',
    outTag: 'Out',
    adjust: 'Adjust',
    adjustStock: 'Adjust stock',
    history: 'History',
    movements: 'Stock movements',
    allMovements: 'All movements',
    exportCsv: 'Export CSV',
    exported: 'CSV downloaded',
    newPo: 'New purchase order',
    kpi_value: 'Stock value',
    kpi_valueHint: 'at cost · {n} units',
    kpi_units: 'Units on hand',
    kpi_unitsHint: '{n} stock items',
    kpi_mto: 'Made-to-order products',
    kpi_mtoHint: 'lead time {a}–{b} days',
    kpi_mtoHintNoLead: 'produced per print run',
    kpi_low: 'Low stock',
    kpi_lowHint: '1–{n} available',
    kpi_out: 'Out of stock',
    kpi_outHint: 'cannot be sold',
    kpi_incoming: 'Incoming',
    kpi_incomingHint: 'from {n} open purchase orders',
    emptyTitle: 'No products match this filter',
    emptyText: 'Change the search, location or filter.',
    clearFilters: 'Clear filters',
    showing: 'Showing {n} of {total}',
    archivedHidden: 'Archived products are hidden ({n})',
    variants: '{n} variants',
    draftTag: 'Draft',
    noPermInventory: 'Your role cannot change stock',
    noPermExport: 'Your role cannot export data',
    noPermPurchasing: 'Your role has no access to purchase orders',
    sortBy: 'Sort',
    sort_name: 'Name A–Z',
    sort_available: 'Least available',
    sort_onHand: 'Most on hand',
    sort_incoming: 'Most incoming',
    defaultLoc: 'default',

    r_correction: 'Correction',
    r_received: 'Received from supplier',
    r_damaged: 'Damaged / scrapped',
    r_return: 'Customer return',
    r_sale: 'Sale',
    r_count: 'Stock count',

    mv_time: 'Time',
    mv_variant: 'Variant',
    mv_qty: 'Qty',
    mv_reason: 'Reason',
    mv_doc: 'Source document',
    mv_user: 'User',
    mv_location: 'Location',
    mv_note: 'Note',
    mv_allVariants: 'All variants',
    mv_web: 'Online store',
    mv_removed: 'Product removed from the catalogue',
    mv_empty: 'No movements yet',
    mv_emptyText: 'Sales, supplier receipts and adjustments will appear here.',
    mv_count: '{n} movements',
    mv_allTitle: 'All stock movements',
    mv_allSub: 'Latest {n} changes across all products',
    reservedBy: 'Committed in orders',
    inOpenOrders: 'In open orders',
    mto_lead: 'Lead time',
    mto_moq: 'Minimum order',
    mto_inOrders: 'In open orders',
    mto_days: '{n} working days',
    mto_note: 'Produced for every order (print run) — no stock, reservations or stock adjustments. Quantities in open orders are the production queue.',
    incomingFrom: 'Incoming from purchase orders',
    expectedOn: 'expected {d}',
    openProduct: 'Open product',
    noOpenOrders: 'No open orders with this product.',
    f_mvAll: 'All',
    f_mvIn: 'In',
    f_mvOut: 'Out',
    mv_more: 'Show more',

    adj_desc: 'Every change creates a movement with reason, note and user.',
    adj_tabOnHand: 'On hand',
    adj_tabBlocked: 'Unavailable',
    adj_by: 'Adjust by ±',
    adj_set: 'New quantity (counted)',
    adj_qtyBy: 'Quantity (+ in, − out)',
    adj_qtySet: 'Counted on hand',
    adj_reason: 'Reason',
    adj_note: 'Note',
    adj_noteOpt: 'optional',
    adj_notePh: 'e.g. Monthly count — 2 damaged boxes in the warehouse',
    adj_preview: 'Change preview',
    adj_save: 'Save adjustment',
    adj_saved: 'Stock updated',
    adj_belowCommitted: 'Cannot go below committed ({n}) — cancel or fulfil the order first.',
    adj_noChange: 'Enter a quantity change',
    adj_blockedHint: 'Unavailable units stay on hand but cannot be sold (damaged, trade-fair samples, in quality control).',
    adj_blockedQty: 'Unavailable units',
    adj_blockedMax: 'At most {n} (on hand minus committed)',
    adj_blockedSaved: 'Unavailable units updated',
    adj_untracked: 'This product is made to order, per print run, and keeps no stock. To keep it in the warehouse, set a stock quantity in the product form.',
    adj_damagedHint: 'Damaged goods usually reduce stock — enter a negative number.',
    adj_movement: 'Movement: {reason} · {user}',

    po_title: 'Purchase orders',
    po_subtitle: 'Orders placed with suppliers — stock items, samples and products made by partners. Stock changes only when goods are received.',
    po_new: 'New purchase order',
    po_number: 'Number',
    po_supplier: 'Supplier',
    po_destination: 'Destination',
    po_status: 'Status',
    po_received: 'Received',
    po_expected: 'Expected',
    po_total: 'Value',
    po_created: 'Created',
    st_draft: 'Draft',
    st_sent: 'Sent',
    st_partial: 'Partially received',
    st_closed: 'Closed',
    po_overdue: 'Overdue',
    po_searchPh: 'Search number, supplier or reference…',
    po_kpiOpen: 'Open purchase orders',
    po_kpiOpenHint: 'sent or partially received',
    po_kpiUnits: 'Units incoming',
    po_kpiUnitsHint: 'not received yet',
    po_kpiValue: 'Open value',
    po_kpiValueHint: 'unreceived goods at cost',
    po_kpiOverdue: 'Overdue',
    po_kpiOverdueHint: 'past the expected date',
    po_emptyTitle: 'No purchase orders',
    po_emptyText: 'Create a purchase order when you order goods from a supplier — packaging materials, samples or partner-made items.',
    po_lines: '{n} items',
    po_costHidden: 'Hidden',

    ed_supplierCard: 'Supplier & destination',
    ed_supplierPh: 'e.g. paper & board supplier',
    ed_supplierHint: 'A supplier is not a customer; its costs are visible only to permitted roles.',
    ed_products: 'Items',
    ed_addProduct: 'Add item',
    ed_searchProduct: 'Search stock items or partner-made products…',
    ed_noMatch: 'No products match this search.',
    ed_outsourced: 'Made to order · by a partner',
    ed_noLines: 'Add the items you are ordering from the supplier.',
    ed_ordered: 'Ordered',
    ed_received: 'Received',
    ed_rejected: 'Rejected',
    ed_cost: 'Cost / unit',
    ed_lineTotal: 'Total',
    ed_summary: 'Cost summary',
    ed_subtotal: 'Order value (excl. VAT)',
    ed_receivedValue: 'Received at cost',
    ed_unitsTotal: 'Total units',
    ed_details: 'Details',
    ed_reference: 'Supplier reference',
    ed_referencePh: 'e.g. pro-forma number',
    ed_expected: 'Expected date',
    ed_note: 'Note',
    ed_notePh: 'Payment terms, transport, pallets, notes for receiving…',
    ed_markSent: 'Mark as sent',
    ed_receive: 'Receive items',
    ed_close: 'Close purchase order',
    ed_closeTitle: 'Close without the remaining items?',
    ed_closeText: '{n} units will not be received. Stock does not change and the rest no longer shows as incoming.',
    ed_closed: 'Purchase order closed',
    ed_sent: 'Purchase order marked as sent',
    ed_created: 'Purchase order created',
    ed_saved: 'Purchase order saved',
    ed_deleteTitle: 'Delete draft {n}?',
    ed_deleted: 'Draft deleted',
    ed_saveFirst: 'Save your changes first',
    ed_needLines: 'Add at least one item',
    ed_needSupplier: 'Enter the supplier',
    ed_needQty: 'Ordered quantity must be greater than 0',
    ed_receipts: 'Receipts',
    ed_receiptsEmpty: 'Nothing received yet.',
    ed_differences: 'Differences',
    ed_noDifferences: 'No differences — everything arrived as ordered.',
    ed_missing: '{n} missing',
    ed_rejectedN: '{n} rejected',
    ed_notReceived: '{n} not received',
    ed_stockHint: 'Stock changes only when goods are received.',
    ed_notFound: 'Purchase order not found',
    ed_notFoundText: 'It may have been deleted. Go back to the purchase order list.',
    ed_progress: '{r} of {o} received',
    ed_remove: 'Remove item',
    ed_lockedLine: 'An item with received goods cannot be removed',
    ed_minOrdered: 'At least {n} (already received/rejected)',
    ed_readOnly: 'A closed purchase order is read-only.',
    ed_noPermEdit: 'Your role can only view purchase orders',
    ed_noPermDelete: 'Only the owner can delete purchase orders',
    ed_backToList: 'Back to purchase orders',
    ed_steps: 'Purchase order flow',
    ed_available: '{n} available',
    ed_suggest: 'Items from {v}:',
    ed_receivedOn: 'received {d}',
    ed_receiveDisabled: 'Goods can be received once the order is sent',
    ed_unknownItem: 'Item outside the catalogue',

    rc_title: 'Receive items — {n}',
    rc_desc: 'Enter what arrived now. Stock increases only by received units; rejected units are recorded as a difference.',
    rc_remaining: 'Remaining',
    rc_acceptNow: 'Receive now',
    rc_rejectNow: 'Reject',
    rc_all: 'Receive all remaining',
    rc_confirm: 'Confirm receipt',
    rc_done: '{n} units received — stock updated',
    rc_nothing: 'Nothing new — this receipt is already recorded',
    rc_idempotent: 'Receipts are stored as cumulative totals per line: the same document received twice never adds stock twice.',
    rc_diffTitle: 'Differences after this receipt',
    rc_willClose: 'Every line is settled — the purchase order will be closed.',
    rc_willPartial: 'The rest stays open as incoming.',
    rc_tooMany: 'More than remaining ({n})',
    rc_stockAfter: 'on hand after: {n}',
    rc_noStock: 'made to order — no stock',
    rc_rejectedHint: 'Rejected units do not enter stock',
    rc_nothingEntered: 'Enter a received or rejected quantity',
    rc_allDone: 'Every line of this purchase order is already settled.',

    tr_title: 'Transfers',
    tr_badge: 'Inactive · when needed',
    tr_text: 'Moving goods between locations: origin, destination, items, date, reference, note and a link to the purchase order. Movements at both ends share one document and never create stock from nothing.',
    tr_small: 'Stock adjustments with a reason are enough today. Transfers are switched on when there is a real need — e.g. when goods move regularly between the factory and the warehouse.',
    tr_flow: 'Transfer flow',
    tr_s1: 'Draft',
    tr_s2: 'Ready',
    tr_s3: 'In transit',
    tr_s4: 'Partially received',
    tr_s5: 'Closed',
    tr_locations: 'Locations',
    tr_ready: '{n} locations configured — transfers can be enabled.',
    tr_one: 'One location configured — transfers are not needed.',
    tr_manage: 'Manage locations',
    tr_rule: 'A transfer never ships more than the allowed quantity.',
    tr_pickup: 'order pickup',
  },
});

export type InvKey = keyof (typeof inv)['sq'];
