import { defineDict } from '@/i18n';

/** Content models strings (PDF p.36 "Modele dhe fusha"). */
export const md = defineDict({
  me: {
    description: 'Strukturisani modeli za sadržaj koji se ponavlja — realizacije, česta pitanja, usluge, lokacije. Definicija modela (polja, tipovi, pravila) odvojena je od njegovih unosa.',
    c1Title: 'Definicija modela',
    c1Text: 'Polja, tipovi, obavezna polja, prevod i pravila validacije — uređuju se ovdje.',
    c2Title: 'Unosi',
    c2Text: 'Stvarni sadržaj (npr. {n} realizacija) uređuje se u modulu kojem pripada — „Pogledaj unose“.',
    c3Title: 'Funkcionalni moduli',
    c3Text: 'Termini, narudžbe i popusti imaju sopstvenu logiku — raspored, kapacitet, pravila — ne samo polja.',
    c3Link: 'Usluge termina',
    definitions: 'Definicije',
    definitionsText: 'Kliknite model da vidite polja, pravila i primjere unosa.',
    colModel: 'Model',
    colFields: 'Polja',
    colEntries: 'Unosi',
    colEditor: 'Uređuje se u',
    colStatus: 'Status',
    fieldsN: '{n} polja',
    entriesN: '{n} unosa',
    viewEntries: 'Pogledaj unose',
    active: 'Aktivan',
    draft: 'Nacrt',
    public: 'Javno',
    private: 'Samo u CMS-u',
    ed_projects: 'Realizacije',
    ed_editor: 'Editor početne',
    ed_locations: 'Konfiguracija · Lokacije',
    usedOn: 'Koristi se na',
    fields: 'Polja',
    fieldsText: 'Struktura svakog unosa — ključ, naziv, tip i pravila.',
    addField: 'Dodaj polje',
    newField: 'Novo polje',
    editField: 'Uredi polje',
    colKey: 'Ključ',
    colLabel: 'Naziv',
    colType: 'Tip',
    colRules: 'Pravila',
    required: 'Obavezno',
    requiredHint: 'Unos se ne može sačuvati bez ovog polja.',
    translatable: 'Prevodi se',
    translatableHint: 'Posebna vrijednost za ME, SQ i EN.',
    notTranslatable: 'Ovaj tip se ne prevodi.',
    system: 'Sistemsko',
    systemHint: 'Sistemsko polje koristi tema — možete mijenjati naziv i pravila, ali ne ključ i tip.',
    custom: 'Prilagođeno',
    customHint: 'Prilagođena polja čuvaju se u definiciji modela; tema ih prikazuje kada se dodaju u šablon.',
    key: 'Ključ (API)',
    keyHint: 'Počinje slovom, bez razmaka — npr. garancija, rokIsporuke.',
    keyInvalid: 'Ključ počinje slovom i sadrži samo slova, brojeve i _.',
    keyTaken: 'Ključ već postoji u ovom modelu.',
    label: 'Naziv polja',
    labelRequired: 'Unesite naziv na crnogorskom.',
    type: 'Tip polja',
    help: 'Uputstvo za urednika',
    helpHint: 'Prikazuje se ispod polja u formi unosa (opciono).',
    maxLen: 'Maks. broj znakova',
    min: 'Minimum',
    max: 'Maksimum',
    options: 'Opcije',
    optionsPh: 'Dodajte opciju i pritisnite Enter',
    optionsMin: 'Dodajte najmanje dvije opcije.',
    multiple: 'Više izbora',
    multipleHint: 'Unos može imati više opcija istovremeno.',
    refTarget: 'Vodi na',
    refRequired: 'Izaberite na šta polje upućuje.',
    validation: 'Validacija',
    fieldSaved: 'Polje je sačuvano',
    fieldAdded: 'Polje je dodato',
    fieldDeleted: 'Polje je uklonjeno',
    deleteField: 'Ukloni polje',
    deleteFieldTitle: 'Ukloniti polje „{name}“?',
    deleteFieldText: 'Vrijednosti ovog polja u postojećim unosima više se ne prikazuju.',
    saveField: 'Sačuvaj polje',
    fixErrors: 'Ispravite označena polja.',
    settings: 'Postavke modela',
    statusLabel: 'Aktivan model',
    statusHint: 'Isključeno = nacrt: model se priprema i unosi se ne prikazuju na sajtu.',
    publicLabel: 'Javna dozvola',
    publicHint: 'Unosi su vidljivi na sajtu i u javnom API-ju.',
    modelSaved: 'Model je ažuriran',
    entriesSample: 'Unosi',
    entriesText: 'Unosi se uređuju u modulu: {where}',
    moreEntries: '+ još {n}',
    noEntries: 'Još nema unosa.',
    pdfNote: 'Modeli sadržaja odvajaju definiciju modela od njegovih unosa.',
    pdfNote2: 'Funkcionalni moduli poput termina imaju sopstvenu logiku, ne samo polja.',
    readOnly: 'Samo pregled — vaša uloga ne može mijenjati modele.',
    noPublish: 'Status i javnu dozvolu mijenja urednik ili menadžer.',
    notFound: 'Model ne postoji',
    empty: 'Nema modela',
    source: 'Izvor',
    t_text: 'Tekst',
    t_number: 'Broj',
    t_choice: 'Izbor',
    t_image: 'Slika',
    t_link: 'Link',
    t_date: 'Datum',
    t_boolean: 'Da / Ne',
    t_reference: 'Referenca',
    td_text: 'Red ili pasus teksta',
    td_number: 'Cijeli ili decimalni broj',
    td_choice: 'Ponuđene opcije',
    td_image: 'Iz biblioteke medija',
    td_link: 'Putanja ili URL',
    td_date: 'Kalendarski datum',
    td_boolean: 'Uključeno / isključeno',
    td_reference: 'Veza na drugi zapis',
    v_required: 'Obavezno',
    v_optional: 'Opciono',
    v_text3: 'tekst na 3 jezika',
    v_text1: 'tekst',
    v_maxLen: 'do {n} znakova',
    v_number: 'broj',
    v_range: 'od {min} do {max}',
    v_min: 'najmanje {n}',
    v_maxN: 'najviše {n}',
    v_choice: 'jedna od {n} opcija',
    v_choiceMulti: 'jedna ili više od {n} opcija',
    v_image: 'JPG/PNG/WebP iz biblioteke + alt tekst',
    v_link: 'putanja /… ili https://…',
    v_date: 'datum DD.MM.GGGG',
    v_boolean: 'da / ne',
    v_ref: 'veza → {target}',
    r_products: 'Proizvodi',
    r_categories: 'Kategorije',
    r_collections: 'Kolekcije',
    r_pages: 'Stranice',
    r_services: 'Usluge termina',
    r_projects: 'Realizacije',
    r_staff: 'Osoblje',
    md_projects: 'Realizovani projekti na /projekti i na početnoj.',
    md_faq: 'Česta pitanja — sekcija na početnoj stranici.',
    md_services: 'Kartice usluga na početnoj i /usluge, povezane sa uslugama termina.',
    md_locations: 'Saloni i skladišta — preuzimanje, adresa, mapa.',
    md_custom: 'Prilagođeni model sadržaja.',
  },
  sq: {
    description: 'Modele të strukturuara për përmbajtje të ripërdorshme — projekte, pyetje të shpeshta, shërbime, lokacione. Përkufizimi i modelit (fushat, llojet, rregullat) ndahet nga regjistrimet e tij.',
    c1Title: 'Përkufizimi i modelit',
    c1Text: 'Fushat, llojet, fushat e detyrueshme, përkthimi dhe rregullat e validimit — redaktohen këtu.',
    c2Title: 'Regjistrimet',
    c2Text: 'Përmbajtja reale (p.sh. {n} projekte) redaktohet në modulin që e zotëron — „Shiko regjistrimet“.',
    c3Title: 'Modulet funksionale',
    c3Text: 'Terminet, porositë dhe zbritjet kanë logjikë më vete — orar, kapacitet, rregulla — jo vetëm fusha.',
    c3Link: 'Shërbimet e termineve',
    definitions: 'Përkufizimet',
    definitionsText: 'Klikoni një model për të parë fushat, rregullat dhe shembuj regjistrimesh.',
    colModel: 'Modeli',
    colFields: 'Fushat',
    colEntries: 'Regjistrimet',
    colEditor: 'Redaktohet te',
    colStatus: 'Statusi',
    fieldsN: '{n} fusha',
    entriesN: '{n} regjistrime',
    viewEntries: 'Shiko regjistrimet',
    active: 'Aktiv',
    draft: 'Draft',
    public: 'Publik',
    private: 'Vetëm në CMS',
    ed_projects: 'Projektet',
    ed_editor: 'Editori i ballinës',
    ed_locations: 'Konfigurimet · Lokacionet',
    usedOn: 'Përdoret në',
    fields: 'Fushat',
    fieldsText: 'Struktura e çdo regjistrimi — çelësi, emri, lloji dhe rregullat.',
    addField: 'Shto fushë',
    newField: 'Fushë e re',
    editField: 'Ndrysho fushën',
    colKey: 'Çelësi',
    colLabel: 'Emri',
    colType: 'Lloji',
    colRules: 'Rregullat',
    required: 'E detyrueshme',
    requiredHint: 'Regjistrimi nuk ruhet pa këtë fushë.',
    translatable: 'Përkthehet',
    translatableHint: 'Vlerë e veçantë për ME, SQ dhe EN.',
    notTranslatable: 'Ky lloj nuk përkthehet.',
    system: 'Sistemi',
    systemHint: 'Fushë sistemi që e përdor tema — mund të ndryshoni emrin dhe rregullat, jo çelësin dhe llojin.',
    custom: 'E personalizuar',
    customHint: 'Fushat e personalizuara ruhen në përkufizimin e modelit; tema i shfaq kur shtohen në shabllon.',
    key: 'Çelësi (API)',
    keyHint: 'Fillon me shkronjë, pa hapësira — p.sh. garancia, afatiDergeses.',
    keyInvalid: 'Çelësi fillon me shkronjë dhe përmban vetëm shkronja, numra dhe _.',
    keyTaken: 'Çelësi ekziston tashmë në këtë model.',
    label: 'Emri i fushës',
    labelRequired: 'Shkruani emrin në malazezisht.',
    type: 'Lloji i fushës',
    help: 'Udhëzim për redaktorin',
    helpHint: 'Shfaqet poshtë fushës në formularin e regjistrimit (opsionale).',
    maxLen: 'Maks. karaktere',
    min: 'Minimumi',
    max: 'Maksimumi',
    options: 'Opsionet',
    optionsPh: 'Shtoni opsion dhe shtypni Enter',
    optionsMin: 'Shtoni të paktën dy opsione.',
    multiple: 'Disa zgjedhje',
    multipleHint: 'Regjistrimi mund të ketë disa opsione njëkohësisht.',
    refTarget: 'Lidhet me',
    refRequired: 'Zgjidhni me çfarë lidhet fusha.',
    validation: 'Validimi',
    fieldSaved: 'Fusha u ruajt',
    fieldAdded: 'Fusha u shtua',
    fieldDeleted: 'Fusha u hoq',
    deleteField: 'Hiq fushën',
    deleteFieldTitle: 'Të hiqet fusha „{name}“?',
    deleteFieldText: 'Vlerat e kësaj fushe në regjistrimet ekzistuese nuk shfaqen më.',
    saveField: 'Ruaj fushën',
    fixErrors: 'Rregulloni fushat e shënuara.',
    settings: 'Cilësimet e modelit',
    statusLabel: 'Model aktiv',
    statusHint: 'Joaktiv = draft: modeli në përgatitje, regjistrimet nuk shfaqen në faqe.',
    publicLabel: 'Leje publike',
    publicHint: 'Regjistrimet shihen në faqe dhe në API-në publike.',
    modelSaved: 'Modeli u përditësua',
    entriesSample: 'Regjistrimet',
    entriesText: 'Regjistrimet redaktohen te moduli: {where}',
    moreEntries: '+ edhe {n}',
    noEntries: 'Ende nuk ka regjistrime.',
    pdfNote: 'Modelet e përmbajtjes ndajnë përkufizimin e modelit nga regjistrimet e tij.',
    pdfNote2: 'Modulet funksionale si terminet kanë logjikë më vete, jo vetëm fusha.',
    readOnly: 'Vetëm shikim — roli juaj nuk mund të ndryshojë modelet.',
    noPublish: 'Statusin dhe lejen publike i ndryshon redaktori ose menaxheri.',
    notFound: 'Modeli nuk ekziston',
    empty: 'Nuk ka modele',
    source: 'Burimi',
    t_text: 'Tekst',
    t_number: 'Numër',
    t_choice: 'Zgjedhje',
    t_image: 'Foto',
    t_link: 'Lidhje',
    t_date: 'Datë',
    t_boolean: 'Po / Jo',
    t_reference: 'Referencë',
    td_text: 'Një rresht ose paragraf',
    td_number: 'Numër i plotë ose dhjetor',
    td_choice: 'Opsione të paracaktuara',
    td_image: 'Nga biblioteka e mediave',
    td_link: 'Shteg ose URL',
    td_date: 'Datë kalendarike',
    td_boolean: 'Çelës po / jo',
    td_reference: 'Lidhje me regjistrim tjetër',
    v_required: 'E detyrueshme',
    v_optional: 'Opsionale',
    v_text3: 'tekst në 3 gjuhë',
    v_text1: 'tekst',
    v_maxLen: 'deri në {n} karaktere',
    v_number: 'numër',
    v_range: 'nga {min} deri në {max}',
    v_min: 'të paktën {n}',
    v_maxN: 'jo më shumë se {n}',
    v_choice: 'një nga {n} opsione',
    v_choiceMulti: 'një ose më shumë nga {n} opsione',
    v_image: 'JPG/PNG/WebP nga biblioteka + tekst alternativ',
    v_link: 'shteg /… ose https://…',
    v_date: 'datë DD.MM.VVVV',
    v_boolean: 'po / jo',
    v_ref: 'lidhje → {target}',
    r_products: 'Produktet',
    r_categories: 'Kategoritë',
    r_collections: 'Koleksionet',
    r_pages: 'Faqet',
    r_services: 'Shërbimet e termineve',
    r_projects: 'Projektet',
    r_staff: 'Stafi',
    md_projects: 'Projektet e realizuara te /projekti dhe në ballinë.',
    md_faq: 'Pyetjet e shpeshta — seksion në ballinë.',
    md_services: 'Kartat e shërbimeve në ballinë dhe /usluge, të lidhura me shërbimet e termineve.',
    md_locations: 'Sallonet dhe depot — marrja në vend, adresa, harta.',
    md_custom: 'Model i personalizuar përmbajtjeje.',
  },
  en: {
    description: 'Structured models for repeatable content — projects, FAQ, services, locations. A model’s definition (fields, types, rules) is kept separate from its entries.',
    c1Title: 'Model definition',
    c1Text: 'Fields, types, required fields, translation and validation rules — edited here.',
    c2Title: 'Entries',
    c2Text: 'The actual content (e.g. {n} projects) is edited in the module that owns it — “View entries”.',
    c3Title: 'Functional modules',
    c3Text: 'Appointments, orders and discounts have their own logic — schedules, capacity, rules — not just fields.',
    c3Link: 'Appointment services',
    definitions: 'Definitions',
    definitionsText: 'Click a model to see its fields, rules and sample entries.',
    colModel: 'Model',
    colFields: 'Fields',
    colEntries: 'Entries',
    colEditor: 'Edited in',
    colStatus: 'Status',
    fieldsN: '{n} fields',
    entriesN: '{n} entries',
    viewEntries: 'View entries',
    active: 'Active',
    draft: 'Draft',
    public: 'Public',
    private: 'CMS only',
    ed_projects: 'Projects',
    ed_editor: 'Homepage editor',
    ed_locations: 'Settings · Locations',
    usedOn: 'Used on',
    fields: 'Fields',
    fieldsText: 'The structure of every entry — key, label, type and rules.',
    addField: 'Add field',
    newField: 'New field',
    editField: 'Edit field',
    colKey: 'Key',
    colLabel: 'Label',
    colType: 'Type',
    colRules: 'Rules',
    required: 'Required',
    requiredHint: 'An entry cannot be saved without this field.',
    translatable: 'Translatable',
    translatableHint: 'A separate value for ME, SQ and EN.',
    notTranslatable: 'This type is not translated.',
    system: 'System',
    systemHint: 'A system field used by the theme — you can change its label and rules, not its key or type.',
    custom: 'Custom',
    customHint: 'Custom fields are stored in the model definition; the theme shows them once they are added to a template.',
    key: 'Key (API)',
    keyHint: 'Starts with a letter, no spaces — e.g. warranty, leadTime.',
    keyInvalid: 'The key starts with a letter and contains only letters, digits and _.',
    keyTaken: 'This key already exists in the model.',
    label: 'Field label',
    labelRequired: 'Enter the Montenegrin label.',
    type: 'Field type',
    help: 'Help text for editors',
    helpHint: 'Shown under the field in the entry form (optional).',
    maxLen: 'Max. characters',
    min: 'Minimum',
    max: 'Maximum',
    options: 'Options',
    optionsPh: 'Add an option and press Enter',
    optionsMin: 'Add at least two options.',
    multiple: 'Multiple choice',
    multipleHint: 'An entry can have several options at once.',
    refTarget: 'Refers to',
    refRequired: 'Choose what the field refers to.',
    validation: 'Validation',
    fieldSaved: 'Field saved',
    fieldAdded: 'Field added',
    fieldDeleted: 'Field removed',
    deleteField: 'Remove field',
    deleteFieldTitle: 'Remove the field “{name}”?',
    deleteFieldText: 'Values of this field in existing entries are no longer shown.',
    saveField: 'Save field',
    fixErrors: 'Fix the highlighted fields.',
    settings: 'Model settings',
    statusLabel: 'Active model',
    statusHint: 'Off = draft: the model is being prepared and entries are not shown on the site.',
    publicLabel: 'Public permission',
    publicHint: 'Entries are visible on the site and in the public API.',
    modelSaved: 'Model updated',
    entriesSample: 'Entries',
    entriesText: 'Entries are edited in the module: {where}',
    moreEntries: '+ {n} more',
    noEntries: 'No entries yet.',
    pdfNote: 'Content models separate the model definition from its entries.',
    pdfNote2: 'Functional modules such as appointments have their own logic, not just fields.',
    readOnly: 'View only — your role cannot change models.',
    noPublish: 'Status and public permission are changed by an editor or manager.',
    notFound: 'Model not found',
    empty: 'No models',
    source: 'Source',
    t_text: 'Text',
    t_number: 'Number',
    t_choice: 'Choice',
    t_image: 'Image',
    t_link: 'Link',
    t_date: 'Date',
    t_boolean: 'Yes / No',
    t_reference: 'Reference',
    td_text: 'A line or paragraph',
    td_number: 'Whole or decimal number',
    td_choice: 'Predefined options',
    td_image: 'From the media library',
    td_link: 'Path or URL',
    td_date: 'Calendar date',
    td_boolean: 'On / off switch',
    td_reference: 'Link to another record',
    v_required: 'Required',
    v_optional: 'Optional',
    v_text3: 'text in 3 languages',
    v_text1: 'text',
    v_maxLen: 'up to {n} characters',
    v_number: 'number',
    v_range: 'from {min} to {max}',
    v_min: 'at least {n}',
    v_maxN: 'at most {n}',
    v_choice: 'one of {n} options',
    v_choiceMulti: 'one or more of {n} options',
    v_image: 'JPG/PNG/WebP from the library + alt text',
    v_link: 'a /… path or https://…',
    v_date: 'date DD.MM.YYYY',
    v_boolean: 'yes / no',
    v_ref: 'link → {target}',
    r_products: 'Products',
    r_categories: 'Categories',
    r_collections: 'Collections',
    r_pages: 'Pages',
    r_services: 'Appointment services',
    r_projects: 'Projects',
    r_staff: 'Staff',
    md_projects: 'Completed projects on /projekti and the homepage.',
    md_faq: 'Frequently asked questions — a homepage section.',
    md_services: 'Service cards on the homepage and /usluge, linked to appointment services.',
    md_locations: 'Showrooms and warehouses — pickup, address, map.',
    md_custom: 'Custom content model.',
  },
});
