import { defineDict } from '@/i18n';

/** Homepage section copy that is not CMS content. `me` = Serbian (Latin), `sq` Albanian (default), `en` English. */
export const H = defineDict({
  me: {
    days: 'dana',
    hours: 'sati',
    minutes: 'min',
    seconds: 'sek',
    endsIn: 'Ponuda ističe za',
    useCode: 'Kod za novi lokal',
    copy: 'Kopiraj',
    copied: 'Kod je kopiran',
    deal: 'Akcija',
    allProducts: 'Svi proizvodi',
    productsCount: '{n} proizvoda',
    tab_bestsellers: 'Najprodavanije',
    tab_sale: 'Na akciji',
    tab_new: 'Novo',
    tab_manual: 'Izdvojeno',
    allProjects: 'Sve reference',
    readMore: 'Pročitaj',
    minRead: '{n} min čitanja',
    allPosts: 'Svi članci',
    helpTitle: 'Niste pronašli odgovor?',
    helpText: 'Pozovite nas ili pišite na WhatsApp — odgovaramo istog dana.',
    follow: 'Zapratite nas',
    benefit1: 'Potpuno besplatno, bez obaveze',
    benefit2: 'Javljamo se istog dana',
    benefit3: 'Savjet o veličinama i količinama za vaš meni',
    learnMore: 'Sve za biznis',
    step: 'Korak',
    from: 'od',
    perPiece: '/kom',
    perPack: '/ pak.',
    pcsPack: '{n} kom/pak.',
    bestseller: 'Najprodavanije',
    soonTitle: 'Uskoro u ponudi',
    soonText: 'Prijavite se i javićemo vam prvi.',
    quoteEyebrow: 'Po narudžbi · sa vašim logotipom',
    quoteTitle: 'Papir, karton i etikete *sa vašim brendom*',
    quoteText: 'Pošaljite logo — pripremamo probni dizajn i ponudu. Od 1 kartona, 7–10 radnih dana.',
    quoteCta: 'Zatraži ponudu',
    prev: 'Prethodno',
    next: 'Sljedeće',
    slide: 'Slajd {n}',
    tapeLine: 'it’s packaging',
    pickupAt: 'Preuzimanje u magacinu',
    whatsapp: 'WhatsApp',
    venues: 'za kafiće, restorane i brzu hranu',
  },
  sq: {
    days: 'ditë',
    hours: 'orë',
    minutes: 'min',
    seconds: 'sek',
    endsIn: 'Oferta përfundon për',
    useCode: 'Kodi për lokal të ri',
    copy: 'Kopjo',
    copied: 'Kodi u kopjua',
    deal: 'Ofertë',
    allProducts: 'Të gjitha produktet',
    productsCount: '{n} produkte',
    tab_bestsellers: 'Më të shiturat',
    tab_sale: 'Në ofertë',
    tab_new: 'Të reja',
    tab_manual: 'Të veçuara',
    allProjects: 'Të gjitha referencat',
    readMore: 'Lexo',
    minRead: '{n} min lexim',
    allPosts: 'Të gjitha artikujt',
    helpTitle: 'Nuk e gjetët përgjigjen?',
    helpText: 'Na telefononi ose na shkruani në WhatsApp — përgjigjemi të njëjtën ditë.',
    follow: 'Na ndiqni',
    benefit1: 'Plotësisht falas, pa asnjë detyrim',
    benefit2: 'Ju kontaktojmë të njëjtën ditë',
    benefit3: 'Këshillë për madhësitë dhe sasitë sipas menysë suaj',
    learnMore: 'Gjithçka për biznese',
    step: 'Hapi',
    from: 'nga',
    perPiece: '/copë',
    perPack: '/ pako',
    pcsPack: '{n} copë/pako',
    bestseller: 'Më i shituri',
    soonTitle: 'Së shpejti në ofertë',
    soonText: 'Regjistrohuni dhe ju njoftojmë të parët.',
    quoteEyebrow: 'Me porosi · me logon tuaj',
    quoteTitle: 'Letër, karton dhe etiketa *me markën tuaj*',
    quoteText: 'Na dërgoni logon — përgatisim provën e dizajnit dhe ofertën. Nga 1 karton, 7–10 ditë pune.',
    quoteCta: 'Kërko ofertë',
    prev: 'Para',
    next: 'Pas',
    slide: 'Sllajdi {n}',
    tapeLine: 'it’s packaging',
    pickupAt: 'Marrje në depo',
    whatsapp: 'WhatsApp',
    venues: 'për kafiteri, restorante dhe fast food',
  },
  en: {
    days: 'days',
    hours: 'hrs',
    minutes: 'min',
    seconds: 'sec',
    endsIn: 'Offer ends in',
    useCode: 'New venue code',
    copy: 'Copy',
    copied: 'Code copied',
    deal: 'Deal',
    allProducts: 'All products',
    productsCount: '{n} products',
    tab_bestsellers: 'Bestsellers',
    tab_sale: 'On sale',
    tab_new: 'New in',
    tab_manual: 'Featured',
    allProjects: 'All references',
    readMore: 'Read',
    minRead: '{n} min read',
    allPosts: 'All articles',
    helpTitle: 'Didn’t find your answer?',
    helpText: 'Call us or message us on WhatsApp — we reply the same day.',
    follow: 'Follow us',
    benefit1: 'Completely free, no obligation',
    benefit2: 'We get back to you the same day',
    benefit3: 'Advice on sizes and quantities for your menu',
    learnMore: 'Everything for business',
    step: 'Step',
    from: 'from',
    perPiece: '/pc',
    perPack: '/ pack',
    pcsPack: '{n} pcs/pack',
    bestseller: 'Bestseller',
    soonTitle: 'Coming soon',
    soonText: 'Sign up and you’ll hear first.',
    quoteEyebrow: 'Made to order · with your logo',
    quoteTitle: 'Paper, board and labels *with your brand*',
    quoteText: 'Send us your logo — we prepare a proof and a quote. From 1 carton, 7–10 working days.',
    quoteCta: 'Request a quote',
    prev: 'Previous',
    next: 'Next',
    slide: 'Slide {n}',
    tapeLine: 'it’s packaging',
    pickupAt: 'Warehouse pickup',
    whatsapp: 'WhatsApp',
    venues: 'for cafés, restaurants and fast food',
  },
});
