import { defineDict } from '@/i18n';

/** Inventory + purchase orders (PDF pp.15–16). Albanian wording follows the proposal. */
export const inv = defineDict({
  me: {
    /* ---------------- Inventory ---------------- */
    title: 'Inventar',
    subtitle: 'Fizičko stanje, rezervisano i dostupno po proizvodu. Svaka promjena ostavlja kretanje sa razlogom, dokumentom i korisnikom.',
    col_product: 'Proizvod',
    col_sku: 'SKU',
    col_onHand: 'Na stanju',
    col_committed: 'Rezervisano',
    col_unavailable: 'Blokirano',
    col_available: 'Dostupno',
    col_incoming: 'Dolazi',
    col_location: 'Lokacija',
    hint_onHand: 'Fizički na lokaciji, uključujući rezervisano',
    hint_committed: 'U narudžbama koje još nisu isporučene',
    hint_unavailable: 'Oštećeno, izloženo u salonu ili na kontroli',
    hint_available: 'Na stanju − rezervisano − blokirano',
    hint_incoming: 'Iz poslatih i djelimično primljenih nabavki',
    formula: 'Dostupno = Na stanju − Rezervisano − Blokirano',
    f_all: 'Sve',
    f_low: 'Niske zalihe',
    f_out: 'Nema na stanju',
    f_untracked: 'Bez praćenja',
    f_incoming: 'Dolazi',
    allLocations: 'Sve lokacije',
    searchPh: 'Pretraži po nazivu ili SKU…',
    untracked: 'Bez praćenja',
    untrackedHint: 'Po narudžbi — zalihe se ne prate (999)',
    lowTag: 'Nisko',
    outTag: 'Nema',
    adjust: 'Korekcija',
    adjustStock: 'Korekcija zaliha',
    history: 'Istorija',
    movements: 'Kretanja zaliha',
    allMovements: 'Sva kretanja',
    exportCsv: 'Izvoz CSV',
    exported: 'CSV je preuzet',
    newPo: 'Nova nabavka',
    kpi_value: 'Vrijednost zaliha',
    kpi_valueHint: 'po nabavnoj cijeni · {n} jed.',
    kpi_units: 'Jedinica na stanju',
    kpi_unitsHint: '{n} proizvoda sa praćenjem',
    kpi_low: 'Niske zalihe',
    kpi_lowHint: '1–{n} dostupno',
    kpi_out: 'Nema na stanju',
    kpi_outHint: 'ne mogu se prodati',
    kpi_incoming: 'Dolazi',
    kpi_incomingHint: 'iz {n} otvorenih nabavki',
    emptyTitle: 'Nema proizvoda za ovaj filter',
    emptyText: 'Promijenite pretragu, lokaciju ili filter.',
    clearFilters: 'Očisti filtere',
    showing: 'Prikazano {n} od {total}',
    archivedHidden: 'Arhivirani proizvodi nisu prikazani ({n})',
    variants: '{n} varijanti',
    draftTag: 'Nacrt',
    noPermInventory: 'Vaša uloga ne može mijenjati zalihe',
    noPermExport: 'Vaša uloga ne može izvoziti podatke',
    noPermPurchasing: 'Vaša uloga nema pristup nabavkama',
    sortBy: 'Sortiraj',
    sort_name: 'Naziv A–Š',
    sort_available: 'Najmanje dostupno',
    sort_onHand: 'Najviše na stanju',
    sort_incoming: 'Najviše dolazi',
    defaultLoc: 'glavna',

    /* ---------------- Movement reasons ---------------- */
    r_correction: 'Korekcija',
    r_received: 'Prijem robe',
    r_damaged: 'Oštećeno',
    r_return: 'Povrat',
    r_sale: 'Prodaja',
    r_count: 'Inventura',

    /* ---------------- Movements drawer ---------------- */
    mv_time: 'Vrijeme',
    mv_variant: 'Varijanta',
    mv_qty: 'Količina',
    mv_reason: 'Razlog',
    mv_doc: 'Dokument',
    mv_user: 'Korisnik',
    mv_location: 'Lokacija',
    mv_note: 'Napomena',
    mv_allVariants: 'Sve varijante',
    mv_web: 'Online prodavnica',
    mv_empty: 'Još nema kretanja',
    mv_emptyText: 'Prodaje, prijemi i korekcije pojaviće se ovdje.',
    mv_count: '{n} kretanja',
    mv_allTitle: 'Sva kretanja zaliha',
    mv_allSub: 'Posljednjih {n} promjena u svim proizvodima',
    reservedBy: 'Rezervisano u narudžbama',
    incomingFrom: 'Dolazi iz nabavki',
    expectedOn: 'očekuje se {d}',
    openProduct: 'Otvori proizvod',
    noOpenOrders: 'Nema otvorenih narudžbi sa ovim proizvodom.',
    f_mvAll: 'Sve',
    f_mvIn: 'Ulaz',
    f_mvOut: 'Izlaz',
    mv_more: 'Prikaži još',

    /* ---------------- Adjust dialog ---------------- */
    adj_desc: 'Svaka promjena kreira kretanje sa razlogom, napomenom i korisnikom.',
    adj_tabOnHand: 'Na stanju',
    adj_tabBlocked: 'Blokirano',
    adj_by: 'Promijeni za ±',
    adj_set: 'Nova količina (prebrojano)',
    adj_qtyBy: 'Količina (+ ulaz, − izlaz)',
    adj_qtySet: 'Prebrojano na stanju',
    adj_reason: 'Razlog',
    adj_note: 'Napomena',
    adj_noteOpt: 'opciono',
    adj_notePh: 'npr. Inventura — razlika u magacinu',
    adj_preview: 'Pregled promjene',
    adj_save: 'Sačuvaj korekciju',
    adj_saved: 'Zalihe ažurirane',
    adj_belowCommitted: 'Ne može ispod rezervisanog ({n}) — prvo otkažite ili isporučite narudžbu.',
    adj_noChange: 'Unesite promjenu količine',
    adj_blockedHint: 'Blokirane jedinice ostaju na stanju, ali se ne mogu prodati (oštećene, izložene u salonu, na kontroli kvaliteta).',
    adj_blockedQty: 'Blokirano jedinica',
    adj_blockedMax: 'Najviše {n} (na stanju bez rezervisanog)',
    adj_blockedSaved: 'Blokirane jedinice ažurirane',
    adj_untracked: 'Ovaj proizvod se pravi po narudžbi i zalihe se ne prate. Uključite praćenje u kartici proizvoda.',
    adj_damagedHint: 'Oštećena roba obično umanjuje zalihe — unesite negativan broj.',
    adj_movement: 'Kretanje: {reason} · {user}',

    /* ---------------- Purchase orders ---------------- */
    po_title: 'Nabavke',
    po_subtitle: 'Kupovina od dobavljača. Zalihe se mijenjaju tek kada se roba primi.',
    po_new: 'Nova nabavka',
    po_number: 'Broj',
    po_supplier: 'Dobavljač',
    po_destination: 'Odredište',
    po_status: 'Status',
    po_received: 'Primljeno',
    po_expected: 'Očekivano',
    po_total: 'Vrijednost',
    po_created: 'Kreirano',
    st_draft: 'Nacrt',
    st_sent: 'Poslato',
    st_partial: 'Djelimično primljeno',
    st_closed: 'Zatvoreno',
    po_overdue: 'Kasni',
    po_searchPh: 'Pretraži broj, dobavljača ili referencu…',
    po_kpiOpen: 'Otvorene nabavke',
    po_kpiOpenHint: 'poslate ili djelimično primljene',
    po_kpiUnits: 'Jedinica dolazi',
    po_kpiUnitsHint: 'još nije primljeno',
    po_kpiValue: 'Otvorena vrijednost',
    po_kpiValueHint: 'neprimljena roba po nabavnoj cijeni',
    po_kpiOverdue: 'Kasne',
    po_kpiOverdueHint: 'prošao je očekivani datum',
    po_emptyTitle: 'Nema nabavki',
    po_emptyText: 'Kreirajte nabavku kada naručujete robu od dobavljača.',
    po_lines: '{n} stavki',
    po_costHidden: 'Skriveno',

    /* ---------------- PO editor ---------------- */
    ed_supplierCard: 'Dobavljač i odredište',
    ed_supplierPh: 'npr. Alpe Floor GmbH',
    ed_supplierHint: 'Dobavljač nije kupac — njegove cijene vide samo uloge sa dozvolom.',
    ed_products: 'Proizvodi',
    ed_addProduct: 'Dodaj proizvod',
    ed_searchProduct: 'Pretraži proizvode za nabavku…',
    ed_noMatch: 'Nema proizvoda sa praćenjem zaliha za ovu pretragu.',
    ed_noLines: 'Dodajte proizvode koje naručujete od dobavljača.',
    ed_ordered: 'Naručeno',
    ed_received: 'Primljeno',
    ed_rejected: 'Odbijeno',
    ed_cost: 'Cijena / kom',
    ed_lineTotal: 'Ukupno',
    ed_summary: 'Pregled troškova',
    ed_subtotal: 'Vrijednost nabavke',
    ed_receivedValue: 'Primljeno po cijeni',
    ed_unitsTotal: 'Ukupno jedinica',
    ed_details: 'Detalji',
    ed_reference: 'Referenca dobavljača',
    ed_referencePh: 'npr. broj predračuna',
    ed_expected: 'Očekivani datum',
    ed_note: 'Napomena',
    ed_notePh: 'Uslovi, prevoz, napomene za prijem…',
    ed_markSent: 'Označi kao poslato',
    ed_receive: 'Primi robu',
    ed_close: 'Zatvori nabavku',
    ed_closeTitle: 'Zatvoriti nabavku bez ostatka?',
    ed_closeText: '{n} jedinica neće biti primljeno. Zalihe se ne mijenjaju, a ostatak više nije „dolazi“.',
    ed_closed: 'Nabavka je zatvorena',
    ed_sent: 'Nabavka je označena kao poslata',
    ed_created: 'Nabavka je kreirana',
    ed_saved: 'Nabavka je sačuvana',
    ed_deleteTitle: 'Obrisati nacrt {n}?',
    ed_deleted: 'Nacrt je obrisan',
    ed_saveFirst: 'Prvo sačuvajte promjene',
    ed_needLines: 'Dodajte bar jedan proizvod',
    ed_needSupplier: 'Unesite dobavljača',
    ed_needQty: 'Naručena količina mora biti veća od 0',
    ed_receipts: 'Prijemi',
    ed_receiptsEmpty: 'Roba još nije primljena.',
    ed_differences: 'Razlike',
    ed_noDifferences: 'Nema razlika — sve je primljeno kako je naručeno.',
    ed_missing: 'nedostaje {n}',
    ed_rejectedN: 'odbijeno {n}',
    ed_notReceived: 'nije primljeno {n}',
    ed_stockHint: 'Zalihe se mijenjaju samo pri prijemu robe.',
    ed_notFound: 'Nabavka nije pronađena',
    ed_notFoundText: 'Možda je obrisana. Vratite se na listu nabavki.',
    ed_progress: '{r} od {o} primljeno',
    ed_remove: 'Ukloni stavku',
    ed_lockedLine: 'Stavka sa primljenom robom se ne može ukloniti',
    ed_minOrdered: 'Najmanje {n} (već primljeno/odbijeno)',
    ed_readOnly: 'Zatvorena nabavka je samo za čitanje.',
    ed_noPermEdit: 'Vaša uloga može samo pregledati nabavke',
    ed_noPermDelete: 'Samo vlasnik može brisati nabavke',
    ed_backToList: 'Nazad na nabavke',
    ed_steps: 'Tok nabavke',
    ed_available: 'dostupno {n}',
    ed_suggest: 'Proizvodi dobavljača {v}:',
    ed_receivedOn: 'primljeno {d}',
    ed_receiveDisabled: 'Roba se prima tek kada je nabavka poslata',

    /* ---------------- Receive dialog ---------------- */
    rc_title: 'Prijem robe — {n}',
    rc_desc: 'Unesite šta je stiglo sada. Zalihe rastu samo za primljene jedinice; odbijene se bilježe kao razlika.',
    rc_remaining: 'Preostalo',
    rc_acceptNow: 'Primi sada',
    rc_rejectNow: 'Odbij',
    rc_all: 'Primi sve preostalo',
    rc_confirm: 'Potvrdi prijem',
    rc_done: 'Primljeno {n} jed. — zalihe su ažurirane',
    rc_nothing: 'Ništa novo — ovaj prijem je već evidentiran',
    rc_idempotent: 'Prijem se čuva kao kumulativni zbir po stavci: isti dokument primljen dvaput ne dodaje zalihe dvaput.',
    rc_diffTitle: 'Razlike nakon ovog prijema',
    rc_willClose: 'Sve stavke su riješene — nabavka će biti zatvorena.',
    rc_willPartial: 'Ostatak ostaje otvoren kao „dolazi“.',
    rc_tooMany: 'Više od preostalog ({n})',
    rc_stockAfter: 'na stanju poslije: {n}',
    rc_rejectedHint: 'Odbijeno ne ulazi u zalihe',
    rc_nothingEntered: 'Unesite primljenu ili odbijenu količinu',
    rc_allDone: 'Sve stavke ove nabavke su već riješene.',

    /* ---------------- Transfers ---------------- */
    tr_title: 'Transferi',
    tr_badge: 'Neaktivno · po potrebi',
    tr_text: 'Prenos robe između lokacija: porijeklo, odredište, proizvodi, datum, referenca, napomena i veza sa nabavkom. Kretanja na oba kraja dijele isti dokument i nikada ne stvaraju zalihe iz ničega.',
    tr_small: 'Za malu radnju dovoljna je jedna lokacija i korekcija zaliha sa razlogom. Transferi se uključuju kada postoji stvarna potreba — npr. salon + magacin.',
    tr_flow: 'Tok transfera',
    tr_s1: 'Nacrt',
    tr_s2: 'Spremno',
    tr_s3: 'U tranzitu',
    tr_s4: 'Djelimično primljeno',
    tr_s5: 'Zatvoreno',
    tr_locations: 'Lokacije',
    tr_ready: '{n} lokacije su podešene — transferi se mogu uključiti.',
    tr_one: 'Podešena je jedna lokacija — transferi nisu potrebni.',
    tr_manage: 'Upravljaj lokacijama',
    tr_rule: 'Transfer ne dozvoljava slanje više od raspoložive količine.',
    tr_pickup: 'preuzimanje',
  },
  sq: {
    title: 'Inventari',
    subtitle: 'Gjendja fizike, e rezervuar dhe e disponueshme për çdo produkt. Çdo ndryshim krijon lëvizje me arsye, dokument burim dhe përdorues.',
    col_product: 'Produkti',
    col_sku: 'SKU',
    col_onHand: 'Në dorë',
    col_committed: 'Të rezervuara',
    col_unavailable: 'Të bllokuara',
    col_available: 'Të disponueshme',
    col_incoming: 'Në ardhje',
    col_location: 'Lokacioni',
    hint_onHand: 'Fizikisht në lokacion, përfshirë të rezervuarat',
    hint_committed: 'Në porosi që ende nuk janë përmbushur',
    hint_unavailable: 'Të dëmtuara, në ekspozim në sallon ose në kontroll',
    hint_available: 'Në dorë − të rezervuara − të bllokuara',
    hint_incoming: 'Nga furnizimet e dërguara dhe pjesërisht të pranuara',
    formula: 'Të disponueshme = Në dorë − Të rezervuara − Të bllokuara',
    f_all: 'Të gjitha',
    f_low: 'Stok i ulët',
    f_out: 'Pa stok',
    f_untracked: 'Pa ndjekje',
    f_incoming: 'Në ardhje',
    allLocations: 'Të gjitha lokacionet',
    searchPh: 'Kërko sipas emrit ose SKU-së…',
    untracked: 'Pa ndjekje',
    untrackedHint: 'Me porosi — stoku nuk ndiqet (999)',
    lowTag: 'I ulët',
    outTag: 'Pa stok',
    adjust: 'Korrigjo',
    adjustStock: 'Korrigjo stokun',
    history: 'Historiku',
    movements: 'Lëvizjet e stokut',
    allMovements: 'Të gjitha lëvizjet',
    exportCsv: 'Eksporto CSV',
    exported: 'CSV u shkarkua',
    newPo: 'Furnizim i ri',
    kpi_value: 'Vlera e stokut',
    kpi_valueHint: 'me koston e blerjes · {n} njësi',
    kpi_units: 'Njësi në dorë',
    kpi_unitsHint: '{n} produkte me ndjekje',
    kpi_low: 'Stok i ulët',
    kpi_lowHint: '1–{n} të disponueshme',
    kpi_out: 'Pa stok',
    kpi_outHint: 'nuk mund të shiten',
    kpi_incoming: 'Në ardhje',
    kpi_incomingHint: 'nga {n} furnizime të hapura',
    emptyTitle: 'Asnjë produkt për këtë filtër',
    emptyText: 'Ndryshoni kërkimin, lokacionin ose filtrin.',
    clearFilters: 'Pastro filtrat',
    showing: 'Shfaqen {n} nga {total}',
    archivedHidden: 'Produktet e arkivuara nuk shfaqen ({n})',
    variants: '{n} variante',
    draftTag: 'Draft',
    noPermInventory: 'Roli juaj nuk mund të ndryshojë stokun',
    noPermExport: 'Roli juaj nuk mund të eksportojë të dhëna',
    noPermPurchasing: 'Roli juaj nuk ka qasje te furnizimet',
    sortBy: 'Rendit',
    sort_name: 'Emri A–Zh',
    sort_available: 'Më pak të disponueshme',
    sort_onHand: 'Më shumë në dorë',
    sort_incoming: 'Më shumë në ardhje',
    defaultLoc: 'kryesor',

    r_correction: 'Korrigjim',
    r_received: 'Pranim malli',
    r_damaged: 'E dëmtuar',
    r_return: 'Kthim',
    r_sale: 'Shitje',
    r_count: 'Numërim inventari',

    mv_time: 'Koha',
    mv_variant: 'Varianti',
    mv_qty: 'Sasia',
    mv_reason: 'Arsyeja',
    mv_doc: 'Dokumenti burim',
    mv_user: 'Përdoruesi',
    mv_location: 'Lokacioni',
    mv_note: 'Shënim',
    mv_allVariants: 'Të gjitha variantet',
    mv_web: 'Dyqani online',
    mv_empty: 'Ende nuk ka lëvizje',
    mv_emptyText: 'Shitjet, pranimet dhe korrigjimet do të shfaqen këtu.',
    mv_count: '{n} lëvizje',
    mv_allTitle: 'Të gjitha lëvizjet e stokut',
    mv_allSub: '{n} ndryshimet e fundit në të gjitha produktet',
    reservedBy: 'E rezervuar në porosi',
    incomingFrom: 'Në ardhje nga furnizimet',
    expectedOn: 'pritet më {d}',
    openProduct: 'Hap produktin',
    noOpenOrders: 'Asnjë porosi e hapur me këtë produkt.',
    f_mvAll: 'Të gjitha',
    f_mvIn: 'Hyrje',
    f_mvOut: 'Dalje',
    mv_more: 'Shfaq më shumë',

    adj_desc: 'Çdo ndryshim krijon një lëvizje me arsye, shënim dhe përdorues.',
    adj_tabOnHand: 'Në dorë',
    adj_tabBlocked: 'Të bllokuara',
    adj_by: 'Ndrysho me ±',
    adj_set: 'Sasia e re (e numëruar)',
    adj_qtyBy: 'Sasia (+ hyrje, − dalje)',
    adj_qtySet: 'Të numëruara në dorë',
    adj_reason: 'Arsyeja',
    adj_note: 'Shënim',
    adj_noteOpt: 'opsional',
    adj_notePh: 'p.sh. Numërim — diferencë në magazinë',
    adj_preview: 'Parapamja e ndryshimit',
    adj_save: 'Ruaj korrigjimin',
    adj_saved: 'Stoku u përditësua',
    adj_belowCommitted: 'Nuk mund të jetë nën të rezervuarat ({n}) — fillimisht anuloni ose përmbushni porosinë.',
    adj_noChange: 'Shkruani ndryshimin e sasisë',
    adj_blockedHint: 'Njësitë e bllokuara mbeten në dorë, por nuk mund të shiten (të dëmtuara, në ekspozim në sallon, në kontroll cilësie).',
    adj_blockedQty: 'Njësi të bllokuara',
    adj_blockedMax: 'Maksimumi {n} (në dorë pa të rezervuarat)',
    adj_blockedSaved: 'Njësitë e bllokuara u përditësuan',
    adj_untracked: 'Ky produkt bëhet me porosi dhe stoku nuk ndiqet. Aktivizoni ndjekjen te kartela e produktit.',
    adj_damagedHint: 'Malli i dëmtuar zakonisht e ul stokun — shkruani numër negativ.',
    adj_movement: 'Lëvizje: {reason} · {user}',

    po_title: 'Furnizimet',
    po_subtitle: 'Blerje nga furnitori. Stoku ndryshon vetëm kur pranohet malli.',
    po_new: 'Furnizim i ri',
    po_number: 'Numri',
    po_supplier: 'Furnitori',
    po_destination: 'Destinacioni',
    po_status: 'Statusi',
    po_received: 'Pranuar',
    po_expected: 'Pritet',
    po_total: 'Vlera',
    po_created: 'Krijuar',
    st_draft: 'Draft',
    st_sent: 'Dërguar',
    st_partial: 'Pjesërisht pranuar',
    st_closed: 'Mbyllur',
    po_overdue: 'Me vonesë',
    po_searchPh: 'Kërko numrin, furnitorin ose referencën…',
    po_kpiOpen: 'Furnizime të hapura',
    po_kpiOpenHint: 'të dërguara ose pjesërisht të pranuara',
    po_kpiUnits: 'Njësi në ardhje',
    po_kpiUnitsHint: 'ende të papranuara',
    po_kpiValue: 'Vlera e hapur',
    po_kpiValueHint: 'malli i papranuar me koston e blerjes',
    po_kpiOverdue: 'Me vonesë',
    po_kpiOverdueHint: 'ka kaluar data e pritjes',
    po_emptyTitle: 'Nuk ka furnizime',
    po_emptyText: 'Krijoni një furnizim kur porositni mall nga furnitori.',
    po_lines: '{n} artikuj',
    po_costHidden: 'E fshehur',

    ed_supplierCard: 'Furnitori dhe destinacioni',
    ed_supplierPh: 'p.sh. Alpe Floor GmbH',
    ed_supplierHint: 'Furnitori nuk është klient; kostot e tij shihen vetëm nga role me leje.',
    ed_products: 'Produktet',
    ed_addProduct: 'Shto produkt',
    ed_searchProduct: 'Kërko produkte për furnizim…',
    ed_noMatch: 'Asnjë produkt me ndjekje stoku për këtë kërkim.',
    ed_noLines: 'Shtoni produktet që po porositni nga furnitori.',
    ed_ordered: 'E porositur',
    ed_received: 'E pranuar',
    ed_rejected: 'E refuzuar',
    ed_cost: 'Kosto / copë',
    ed_lineTotal: 'Totali',
    ed_summary: 'Përmbledhje kostoje',
    ed_subtotal: 'Vlera e furnizimit',
    ed_receivedValue: 'E pranuar me kosto',
    ed_unitsTotal: 'Njësi gjithsej',
    ed_details: 'Detajet',
    ed_reference: 'Referenca e furnitorit',
    ed_referencePh: 'p.sh. numri i profaturës',
    ed_expected: 'Data e pritjes',
    ed_note: 'Shënim',
    ed_notePh: 'Kushte, transport, shënime për pranimin…',
    ed_markSent: 'Shëno si të dërguar',
    ed_receive: 'Prano mallin',
    ed_close: 'Mbyll furnizimin',
    ed_closeTitle: 'Të mbyllet furnizimi pa pjesën e mbetur?',
    ed_closeText: '{n} njësi nuk do të pranohen. Stoku nuk ndryshon dhe pjesa e mbetur nuk shfaqet më „në ardhje“.',
    ed_closed: 'Furnizimi u mbyll',
    ed_sent: 'Furnizimi u shënua si i dërguar',
    ed_created: 'Furnizimi u krijua',
    ed_saved: 'Furnizimi u ruajt',
    ed_deleteTitle: 'Të fshihet drafti {n}?',
    ed_deleted: 'Drafti u fshi',
    ed_saveFirst: 'Ruani ndryshimet fillimisht',
    ed_needLines: 'Shtoni të paktën një produkt',
    ed_needSupplier: 'Shkruani furnitorin',
    ed_needQty: 'Sasia e porositur duhet të jetë më e madhe se 0',
    ed_receipts: 'Pranimet',
    ed_receiptsEmpty: 'Malli ende nuk është pranuar.',
    ed_differences: 'Diferencat',
    ed_noDifferences: 'Pa diferenca — gjithçka u pranua siç u porosit.',
    ed_missing: 'mungojnë {n}',
    ed_rejectedN: 'refuzuar {n}',
    ed_notReceived: 'të papranuara {n}',
    ed_stockHint: 'Stoku ndryshon vetëm kur pranohet malli.',
    ed_notFound: 'Furnizimi nuk u gjet',
    ed_notFoundText: 'Mund të jetë fshirë. Kthehuni te lista e furnizimeve.',
    ed_progress: '{r} nga {o} të pranuara',
    ed_remove: 'Hiq artikullin',
    ed_lockedLine: 'Artikulli me mall të pranuar nuk mund të hiqet',
    ed_minOrdered: 'Minimumi {n} (tashmë të pranuara/refuzuara)',
    ed_readOnly: 'Furnizimi i mbyllur është vetëm për lexim.',
    ed_noPermEdit: 'Roli juaj mund vetëm t’i shikojë furnizimet',
    ed_noPermDelete: 'Vetëm pronari mund të fshijë furnizime',
    ed_backToList: 'Kthehu te furnizimet',
    ed_steps: 'Rrjedha e furnizimit',
    ed_available: '{n} të disponueshme',
    ed_suggest: 'Produktet e furnitorit {v}:',
    ed_receivedOn: 'pranuar më {d}',
    ed_receiveDisabled: 'Malli pranohet vetëm pasi furnizimi të jetë dërguar',

    rc_title: 'Prano mallin — {n}',
    rc_desc: 'Shkruani çfarë mbërriti tani. Stoku rritet vetëm për njësitë e pranuara; të refuzuarat regjistrohen si diferencë.',
    rc_remaining: 'Mbetet',
    rc_acceptNow: 'Prano tani',
    rc_rejectNow: 'Refuzo',
    rc_all: 'Prano gjithë të mbeturat',
    rc_confirm: 'Konfirmo pranimin',
    rc_done: 'U pranuan {n} njësi — stoku u përditësua',
    rc_nothing: 'Asgjë e re — ky pranim është regjistruar tashmë',
    rc_idempotent: 'Pranimi ruhet si total kumulativ për çdo artikull: i njëjti dokument i pranuar dy herë nuk e shton stokun dy herë.',
    rc_diffTitle: 'Diferencat pas këtij pranimi',
    rc_willClose: 'Të gjithë artikujt janë zgjidhur — furnizimi do të mbyllet.',
    rc_willPartial: 'Pjesa e mbetur mbetet e hapur si „në ardhje“.',
    rc_tooMany: 'Më shumë se sa mbetet ({n})',
    rc_stockAfter: 'në dorë pas: {n}',
    rc_rejectedHint: 'Të refuzuarat nuk hyjnë në stok',
    rc_nothingEntered: 'Shkruani sasinë e pranuar ose të refuzuar',
    rc_allDone: 'Të gjithë artikujt e këtij furnizimi janë zgjidhur tashmë.',

    tr_title: 'Transferimet',
    tr_badge: 'Joaktiv · sipas nevojës',
    tr_text: 'Lëvizja e mallit mes lokacioneve: origjinë, destinacion, produkte, datë, referencë, shënim dhe lidhje me furnizim. Lëvizjet në origjinë dhe destinacion ruajnë një dokument të përbashkët dhe nuk krijojnë stok nga hiçi.',
    tr_small: 'Për dyqan të vogël mjafton një lokacion dhe korrigjim stoku me arsye. Transferimet aktivizohen kur ka nevojë reale — p.sh. sallon + magazinë.',
    tr_flow: 'Rrjedha e transferimit',
    tr_s1: 'Draft',
    tr_s2: 'Gati',
    tr_s3: 'Në transit',
    tr_s4: 'Pjesërisht pranuar',
    tr_s5: 'Mbyllur',
    tr_locations: 'Lokacionet',
    tr_ready: '{n} lokacione të konfiguruara — transferimet mund të aktivizohen.',
    tr_one: 'Është konfiguruar një lokacion — transferimet nuk nevojiten.',
    tr_manage: 'Menaxho lokacionet',
    tr_rule: 'Një transferim nuk lejon të dërgohet më shumë se sasia e lejuar.',
    tr_pickup: 'marrje',
  },
  en: {
    title: 'Inventory',
    subtitle: 'Physical, committed and available stock per product. Every change leaves a movement with reason, source document and user.',
    col_product: 'Product',
    col_sku: 'SKU',
    col_onHand: 'On hand',
    col_committed: 'Committed',
    col_unavailable: 'Unavailable',
    col_available: 'Available',
    col_incoming: 'Incoming',
    col_location: 'Location',
    hint_onHand: 'Physically at the location, including committed',
    hint_committed: 'In orders that are not fulfilled yet',
    hint_unavailable: 'Damaged, on showroom display or in quality control',
    hint_available: 'On hand − committed − unavailable',
    hint_incoming: 'From sent and partially received purchase orders',
    formula: 'Available = On hand − Committed − Unavailable',
    f_all: 'All',
    f_low: 'Low stock',
    f_out: 'Out of stock',
    f_untracked: 'Not tracked',
    f_incoming: 'Incoming',
    allLocations: 'All locations',
    searchPh: 'Search by name or SKU…',
    untracked: 'Not tracked',
    untrackedHint: 'Made to order — stock is not tracked (999)',
    lowTag: 'Low',
    outTag: 'Out',
    adjust: 'Adjust',
    adjustStock: 'Adjust stock',
    history: 'History',
    movements: 'Stock movements',
    allMovements: 'All movements',
    exportCsv: 'Export CSV',
    exported: 'CSV downloaded',
    newPo: 'New purchase order',
    kpi_value: 'Stock value',
    kpi_valueHint: 'at cost · {n} units',
    kpi_units: 'Units on hand',
    kpi_unitsHint: '{n} tracked products',
    kpi_low: 'Low stock',
    kpi_lowHint: '1–{n} available',
    kpi_out: 'Out of stock',
    kpi_outHint: 'cannot be sold',
    kpi_incoming: 'Incoming',
    kpi_incomingHint: 'from {n} open purchase orders',
    emptyTitle: 'No products match this filter',
    emptyText: 'Change the search, location or filter.',
    clearFilters: 'Clear filters',
    showing: 'Showing {n} of {total}',
    archivedHidden: 'Archived products are hidden ({n})',
    variants: '{n} variants',
    draftTag: 'Draft',
    noPermInventory: 'Your role cannot change stock',
    noPermExport: 'Your role cannot export data',
    noPermPurchasing: 'Your role has no access to purchase orders',
    sortBy: 'Sort',
    sort_name: 'Name A–Z',
    sort_available: 'Least available',
    sort_onHand: 'Most on hand',
    sort_incoming: 'Most incoming',
    defaultLoc: 'default',

    r_correction: 'Correction',
    r_received: 'Received',
    r_damaged: 'Damaged',
    r_return: 'Return',
    r_sale: 'Sale',
    r_count: 'Stock count',

    mv_time: 'Time',
    mv_variant: 'Variant',
    mv_qty: 'Qty',
    mv_reason: 'Reason',
    mv_doc: 'Source document',
    mv_user: 'User',
    mv_location: 'Location',
    mv_note: 'Note',
    mv_allVariants: 'All variants',
    mv_web: 'Online store',
    mv_empty: 'No movements yet',
    mv_emptyText: 'Sales, receipts and adjustments will appear here.',
    mv_count: '{n} movements',
    mv_allTitle: 'All stock movements',
    mv_allSub: 'Latest {n} changes across all products',
    reservedBy: 'Committed in orders',
    incomingFrom: 'Incoming from purchase orders',
    expectedOn: 'expected {d}',
    openProduct: 'Open product',
    noOpenOrders: 'No open orders with this product.',
    f_mvAll: 'All',
    f_mvIn: 'In',
    f_mvOut: 'Out',
    mv_more: 'Show more',

    adj_desc: 'Every change creates a movement with reason, note and user.',
    adj_tabOnHand: 'On hand',
    adj_tabBlocked: 'Unavailable',
    adj_by: 'Adjust by ±',
    adj_set: 'New quantity (counted)',
    adj_qtyBy: 'Quantity (+ in, − out)',
    adj_qtySet: 'Counted on hand',
    adj_reason: 'Reason',
    adj_note: 'Note',
    adj_noteOpt: 'optional',
    adj_notePh: 'e.g. Stock count — warehouse difference',
    adj_preview: 'Change preview',
    adj_save: 'Save adjustment',
    adj_saved: 'Stock updated',
    adj_belowCommitted: 'Cannot go below committed ({n}) — cancel or fulfil the order first.',
    adj_noChange: 'Enter a quantity change',
    adj_blockedHint: 'Unavailable units stay on hand but cannot be sold (damaged, on showroom display, in quality control).',
    adj_blockedQty: 'Unavailable units',
    adj_blockedMax: 'At most {n} (on hand minus committed)',
    adj_blockedSaved: 'Unavailable units updated',
    adj_untracked: 'This product is made to order and stock is not tracked. Turn on tracking in the product form.',
    adj_damagedHint: 'Damaged goods usually reduce stock — enter a negative number.',
    adj_movement: 'Movement: {reason} · {user}',

    po_title: 'Purchase orders',
    po_subtitle: 'Buying from suppliers. Stock changes only when goods are received.',
    po_new: 'New purchase order',
    po_number: 'Number',
    po_supplier: 'Supplier',
    po_destination: 'Destination',
    po_status: 'Status',
    po_received: 'Received',
    po_expected: 'Expected',
    po_total: 'Value',
    po_created: 'Created',
    st_draft: 'Draft',
    st_sent: 'Sent',
    st_partial: 'Partially received',
    st_closed: 'Closed',
    po_overdue: 'Overdue',
    po_searchPh: 'Search number, supplier or reference…',
    po_kpiOpen: 'Open purchase orders',
    po_kpiOpenHint: 'sent or partially received',
    po_kpiUnits: 'Units incoming',
    po_kpiUnitsHint: 'not received yet',
    po_kpiValue: 'Open value',
    po_kpiValueHint: 'unreceived goods at cost',
    po_kpiOverdue: 'Overdue',
    po_kpiOverdueHint: 'past the expected date',
    po_emptyTitle: 'No purchase orders',
    po_emptyText: 'Create a purchase order when you order goods from a supplier.',
    po_lines: '{n} items',
    po_costHidden: 'Hidden',

    ed_supplierCard: 'Supplier & destination',
    ed_supplierPh: 'e.g. Alpe Floor GmbH',
    ed_supplierHint: 'A supplier is not a customer; its costs are visible only to permitted roles.',
    ed_products: 'Products',
    ed_addProduct: 'Add product',
    ed_searchProduct: 'Search products to order…',
    ed_noMatch: 'No stock-tracked products match this search.',
    ed_noLines: 'Add the products you are ordering from the supplier.',
    ed_ordered: 'Ordered',
    ed_received: 'Received',
    ed_rejected: 'Rejected',
    ed_cost: 'Cost / unit',
    ed_lineTotal: 'Total',
    ed_summary: 'Cost summary',
    ed_subtotal: 'Order value',
    ed_receivedValue: 'Received at cost',
    ed_unitsTotal: 'Total units',
    ed_details: 'Details',
    ed_reference: 'Supplier reference',
    ed_referencePh: 'e.g. pro-forma number',
    ed_expected: 'Expected date',
    ed_note: 'Note',
    ed_notePh: 'Terms, transport, notes for receiving…',
    ed_markSent: 'Mark as sent',
    ed_receive: 'Receive items',
    ed_close: 'Close purchase order',
    ed_closeTitle: 'Close without the remaining items?',
    ed_closeText: '{n} units will not be received. Stock does not change and the rest no longer shows as incoming.',
    ed_closed: 'Purchase order closed',
    ed_sent: 'Purchase order marked as sent',
    ed_created: 'Purchase order created',
    ed_saved: 'Purchase order saved',
    ed_deleteTitle: 'Delete draft {n}?',
    ed_deleted: 'Draft deleted',
    ed_saveFirst: 'Save your changes first',
    ed_needLines: 'Add at least one product',
    ed_needSupplier: 'Enter the supplier',
    ed_needQty: 'Ordered quantity must be greater than 0',
    ed_receipts: 'Receipts',
    ed_receiptsEmpty: 'Nothing received yet.',
    ed_differences: 'Differences',
    ed_noDifferences: 'No differences — everything arrived as ordered.',
    ed_missing: '{n} missing',
    ed_rejectedN: '{n} rejected',
    ed_notReceived: '{n} not received',
    ed_stockHint: 'Stock changes only when goods are received.',
    ed_notFound: 'Purchase order not found',
    ed_notFoundText: 'It may have been deleted. Go back to the purchase order list.',
    ed_progress: '{r} of {o} received',
    ed_remove: 'Remove item',
    ed_lockedLine: 'An item with received goods cannot be removed',
    ed_minOrdered: 'At least {n} (already received/rejected)',
    ed_readOnly: 'A closed purchase order is read-only.',
    ed_noPermEdit: 'Your role can only view purchase orders',
    ed_noPermDelete: 'Only the owner can delete purchase orders',
    ed_backToList: 'Back to purchase orders',
    ed_steps: 'Purchase order flow',
    ed_available: '{n} available',
    ed_suggest: 'Products from {v}:',
    ed_receivedOn: 'received {d}',
    ed_receiveDisabled: 'Goods can be received once the order is sent',

    rc_title: 'Receive items — {n}',
    rc_desc: 'Enter what arrived now. Stock increases only by received units; rejected units are recorded as a difference.',
    rc_remaining: 'Remaining',
    rc_acceptNow: 'Receive now',
    rc_rejectNow: 'Reject',
    rc_all: 'Receive all remaining',
    rc_confirm: 'Confirm receipt',
    rc_done: '{n} units received — stock updated',
    rc_nothing: 'Nothing new — this receipt is already recorded',
    rc_idempotent: 'Receipts are stored as cumulative totals per line: the same document received twice never adds stock twice.',
    rc_diffTitle: 'Differences after this receipt',
    rc_willClose: 'Every line is settled — the purchase order will be closed.',
    rc_willPartial: 'The rest stays open as incoming.',
    rc_tooMany: 'More than remaining ({n})',
    rc_stockAfter: 'on hand after: {n}',
    rc_rejectedHint: 'Rejected units do not enter stock',
    rc_nothingEntered: 'Enter a received or rejected quantity',
    rc_allDone: 'Every line of this purchase order is already settled.',

    tr_title: 'Transfers',
    tr_badge: 'Inactive · when needed',
    tr_text: 'Moving goods between locations: origin, destination, products, date, reference, note and a link to the purchase order. Movements at both ends share one document and never create stock from nothing.',
    tr_small: 'For a small shop one location and stock adjustments with a reason are enough. Transfers are enabled when there is a real need — e.g. showroom + warehouse.',
    tr_flow: 'Transfer flow',
    tr_s1: 'Draft',
    tr_s2: 'Ready',
    tr_s3: 'In transit',
    tr_s4: 'Partially received',
    tr_s5: 'Closed',
    tr_locations: 'Locations',
    tr_ready: '{n} locations configured — transfers can be enabled.',
    tr_one: 'One location configured — transfers are not needed.',
    tr_manage: 'Manage locations',
    tr_rule: 'A transfer never ships more than the allowed quantity.',
    tr_pickup: 'pickup',
  },
});

export type InvKey = keyof (typeof inv)['me'];
