import { defineDict } from '@/i18n';

/** Strings for the CMS product list, CSV import/export, delete dialog and product editor (SQ / EN). */
export const pd = defineDict({
  sq: {
    title: 'Produktet',
    addProduct: 'Shto produkt',
    import: 'Importo',
    export: 'Eksporto',
    tab_all: 'Të gjitha',
    tab_active: 'Aktive',
    tab_draft: 'Draft',
    tab_archived: 'Të arkivuara',
    st_active: 'Aktiv',
    st_draft: 'Draft',
    st_archived: 'I arkivuar',
    searchPh: 'Kërko sipas emrit, SKU-së, barkodit ose etiketës…',
    f_category_all: 'Kategoria',
    f_collection_all: 'Koleksioni',
    f_vendor_all: 'Furnitori',
    f_stock_all: 'Stoku',
    f_stock_in: 'Në stok',
    f_stock_low: 'Stok i ulët (≤ 5)',
    f_stock_out: 'Pa stok',
    f_stock_untracked: 'Prodhim me porosi',
    f_channel_all: 'Kanali',
    f_mode_all: 'Shitja',
    mode_cart: 'Me çmim & shportë',
    mode_quote: 'Me ofertë',
    ch_online: 'Dyqani online',
    ch_pos: 'Shitje direkte',
    ch_pos_short: 'Direkt',
    ch_none: 'Pa kanal',
    clearFilters: 'Pastro filtrat',
    sort_newest: 'Më të rejat',
    sort_updated: 'Përditësuar së fundi',
    sort_name: 'Emri A–Zh',
    sort_price_asc: 'Çmimi: më i ulëti',
    sort_price_desc: 'Çmimi: më i larti',
    sort_lead: 'Afati: më i shkurtri',
    sort_stock: 'Stoku: më i vogli',
    sort_sold: 'Më të shiturat',
    col_product: 'Produkti',
    col_status: 'Statusi',
    col_inventory: 'Inventari',
    col_category: 'Kategoria',
    col_order: 'Sasia min. · Afati',
    col_price: 'Çmimi (pa TVSH)',
    col_vendor: 'Furnitori',
    col_channels: 'Kanalet',
    col_sold: 'Shitur',
    col_cost: 'Kosto & marzha',
    col_updated: 'Përditësuar',
    columns: 'Kolonat',
    columnsHint: 'Kolonat e shfaqura',
    inv_in_one: '{n} në 1 variant',
    inv_in_many: '{n} në {v} variante',
    variantsN: '{n} variante',
    madeToOrder: 'Me porosi',
    lowStock: 'Stok i ulët',
    outOfStock: 'Pa stok',
    incomingN: '+{n} në ardhje',
    noCategory: 'Pa kategori',
    from: 'nga',
    fromPrice: 'nga {price}',
    quoteBadge: 'Me ofertë',
    quoteBadge_h: 'Në faqe çmimi dhe shporta fshihen — klienti kërkon ofertë.',
    tiersN: '{n} shkallë çmimi',
    moqShort: 'Min. {qty}',
    noMoq: 'Pa sasi minimale',
    leadShort: '{n} ditë pune',
    marginAtFirst: 'Marzha në shkallën e parë ({qty})',
    footerCount: '{n} produkte',
    footerBulkHint: 'Veprime në grup pas përzgjedhjes',
    pageOf: '{from}–{to} nga {total}',
    prevPage: 'Faqja e mëparshme',
    nextPage: 'Faqja tjetër',
    selectAll: 'Zgjidh të gjitha në faqe',
    selectRow: 'Zgjidh produktin',
    selectedN: '{n} të zgjedhur',
    selectAllFiltered: 'Zgjidh të {n} produktet sipas filtrit',
    allSelected: 'Janë zgjedhur të gjitha produktet sipas filtrit ({n}).',
    clearSelection: 'Anulo zgjedhjen',
    bulk_publish: 'Publiko',
    bulk_draft: 'Kalo në draft',
    bulk_archive: 'Arkivo',
    bulk_restore: 'Rikthe nga arkivi',
    bulk_export: 'Eksporto CSV',
    bulk_delete: 'Fshij',
    toast_published: 'U publikuan {n} produkte',
    toast_publishSkipped: '{n} nuk u publikuan — mungojnë fushat e detyrueshme',
    toast_drafted: 'U kaluan në draft: {n}',
    toast_archived: 'U arkivuan: {n}',
    toast_restored: 'U rikthyen nga arkivi si draft: {n}',
    toast_exported: 'U eksportuan {n} produkte',
    toast_status: '„{name}“ → {status}',
    noPerm: 'Roli juaj nuk e ka këtë leje',
    noPermPublish: 'Publikimi kërkon lejen „Publiko“',
    edit: 'Ndrysho',
    duplicate: 'Dupliko',
    viewOnSite: 'Shiko në faqe',
    publish: 'Publiko',
    toDraft: 'Kalo në draft',
    archive: 'Arkivo',
    restore: 'Rikthe nga arkivi',
    delete: 'Fshij',
    moreActions: 'Më shumë veprime',
    duplicated: 'Kopja u krijua si draft',
    emptyTitle: 'Asnjë produkt për këto filtra',
    emptyText: 'Ndryshoni kërkimin ose pastroni filtrat për të parë gjithë katalogun.',
    emptyArchived: 'Arkivi është bosh',
    emptyArchivedText: 'Produktet e arkivuara mbeten në porosi, por nuk shfaqen në faqe.',
    emptyCatalogTitle: 'Katalogu është ende bosh',
    emptyCatalogText: 'Shtoni produktin e parë ose importoni katalogun nga një skedar CSV.',

    del_title_one: 'Të fshihet „{name}“?',
    del_title_many: 'Të fshihen {n} produkte?',
    del_intro: 'Kontrolloni pasojat para se të konfirmoni.',
    del_willDelete: 'Fshihet përfundimisht',
    del_willArchive: 'Arkivohet në vend të fshirjes',
    del_staysArchived: 'Mbetet i arkivuar',
    del_hasOrders: 'në {n} porosi',
    del_hasDrafts: 'në {n} drafte porosish',
    del_hasQuotes: 'në {n} oferta B2B',
    del_hasPOs: 'në {n} furnizime',
    del_noHistory: 'Pa porosi dhe dokumente',
    del_usedIn: 'Gjendet',
    del_inCollections: 'Hiqet nga koleksionet: {list}',
    del_inDiscounts: 'Përmendet në zbritjet: {list}',
    del_inOffers: 'Pjesë e ofertave: {list}',
    del_note: 'Porositë ruajnë kopjen e artikullit, SKU-së, çmimit dhe taksave, prandaj produktet e shitura arkivohen. Fshirja përfundimtare regjistrohet në audit.',
    del_confirm: 'Konfirmo',
    del_confirmDelete: 'Fshij {n}',
    del_confirmArchive: 'Arkivo {n}',
    del_done: 'U fshinë: {d} · U arkivuan: {a}',

    imp_title: 'Importo produkte nga CSV',
    imp_desc: 'Mapim fushash, parapamje dhe validim para importit — asgjë nuk ndryshon pa konfirmimin tuaj.',
    imp_step1: 'Skedari',
    imp_step2: 'Mapimi',
    imp_step3: 'Parapamja & validimi',
    imp_drop: 'Tërhiqni skedarin CSV këtu ose klikoni për ta zgjedhur',
    imp_dropHint: 'Ndarësi: presje, pikëpresje ose tab · UTF-8',
    imp_formatHint: 'Çmimet sipas sasisë shkruhen „sasia:çmimi“ të ndara me „|“, p.sh. 500:0,44|1000:0,39.',
    imp_paste: 'ose ngjitni përmbajtjen CSV',
    imp_placeholder: 'Emri (SQ);SKU;Kategoria;Çmimet sipas sasisë;Sasia minimale\nKuti burgeri me dritare;PW-FD-120;Paketime ushqimore;250:0,96|1000:0,51;250',
    imp_template: 'Shkarko shabllonin',
    imp_sample: 'Ngarko shembullin',
    imp_detected: '{rows} rreshta · {cols} kolona · ndarësi „{sep}“',
    imp_noRows: 'Skedari nuk ka rreshta me të dhëna nën kokë.',
    imp_next: 'Vazhdo',
    imp_back: 'Kthehu',
    imp_csvColumn: 'Kolona në CSV',
    imp_example: 'Shembull',
    imp_field: 'Fusha në CMS',
    imp_ignore: '— Mos e importo —',
    imp_required: 'Duhet të mapohen emri dhe çmimi (ose çmimet sipas sasisë).',
    imp_existing: 'Kur SKU ekziston në katalog',
    imp_update: 'Përditëso produktin ekzistues',
    imp_skip: 'Kapërce rreshtin',
    imp_newStatus: 'Statusi i produkteve të reja',
    imp_asDraft: 'Draft (rekomandohet)',
    imp_fromColumn: 'Sipas kolonës „Statusi“',
    imp_sumNew: 'Të reja',
    imp_sumUpdate: 'Përditësime',
    imp_sumSkip: 'Kapërcehen',
    imp_sumErrors: 'Me gabime',
    imp_dupReport: 'Raporti i SKU-ve të dyfishta',
    imp_dupInFile: '{sku} përsëritet në skedar (rreshtat {a} dhe {b}) — importohet vetëm i pari.',
    imp_dupInCatalog: '{sku} ekziston: {name} — {action}.',
    imp_actUpdate: 'do të përditësohet',
    imp_actSkip: 'do të kapërcehet',
    imp_noDups: 'Nuk ka SKU të dyfishta — çdo rresht është unik.',
    imp_colLine: 'Rreshti',
    imp_colResult: 'Rezultati',
    imp_colNote: 'Shënim',
    imp_res_create: 'I ri',
    imp_res_update: 'Përditësim',
    imp_res_skip: 'Kapërcehet',
    imp_res_error: 'Gabim',
    imp_ok: 'Gati',
    imp_confirm: 'Importo {n} produkte',
    imp_nothing: 'Nuk ka rreshta për import',
    imp_done: 'U importuan: {c} të reja · {u} u përditësuan',
    imp_doneHint: 'Produktet e reja janë në draft — kontrollojini dhe publikojini.',
    imp_showDrafts: 'Shfaq draftet',
    imp_moreRows: '+ edhe {n} rreshta',
    imp_readError: 'Skedari nuk mund të lexohej',
    imp_tiersShort: '{n} shkallë',
    fld_handle: 'URL',
    fld_name_sq: 'Emri (SQ)',
    fld_name_en: 'Emri (EN)',
    fld_sku: 'SKU',
    fld_barcode: 'Barkodi',
    fld_price: 'Çmimi',
    fld_compareAt: 'Çmimi referues',
    fld_cost: 'Kosto / copë',
    fld_tiers: 'Çmimet sipas sasisë',
    fld_moq: 'Sasia minimale',
    fld_qtyStep: 'Hapi i sasisë',
    fld_artwork: 'Skedar printimi',
    fld_design: 'Dizajn & prepress (€)',
    fld_leadDays: 'Afati (ditë pune)',
    fld_category: 'Kategoria',
    fld_vendor: 'Furnitori',
    fld_tags: 'Etiketat',
    fld_stock: 'Stoku',
    fld_status: 'Statusi',
    fld_unit: 'Njësia',
    fld_channels: 'Kanalet',
    fld_template: 'Faqja e produktit',
    fld_description: 'Përshkrimi',
    fld_image: 'Imazhi (URL)',
    val_yes: 'po',
    val_no: 'jo',
    val_perPiece: '/ copë',
    issue_noName: 'Mungon emri',
    issue_noPrice: 'Mungon çmimi',
    issue_badNumber: '„{value}“ nuk është numër ({field})',
    issue_negative: 'Vlerë negative ({field})',
    issue_badTiers: 'Çmimet sipas sasisë „{value}“ nuk janë të vlefshme — sasitë në rritje, çmimet jo më të larta (p.sh. 500:0,44|1000:0,39)',
    issue_badFlag: '„{value}“ nuk kuptohet ({field}) — mbetet si ishte',
    issue_dupFile: 'SKU e dyfishtë në skedar',
    issue_exists: 'SKU ekziston në katalog',
    issue_noCategory: 'Pa kategori — mbetet draft',
    issue_unknownCategory: 'Kategoria „{value}“ nuk u gjet',
    issue_compareLow: 'Çmimi referues nuk është më i madh se çmimi — zbritja nuk shfaqet',
    issue_badStatus: 'Status i panjohur „{value}“ — draft',
    issue_notPublishable: 'Mungojnë fushat për publikim — importohet si draft',
    issue_nameFromOther: 'Emri (SQ) u mor nga anglishtja',

    newTitle: 'Produkt i ri',
    notFound: 'Produkti nuk u gjet',
    notFoundText: 'Mund të jetë fshirë ose lidhja nuk është e saktë.',
    backToList: 'Kthehu te produktet',
    createdOn: 'Krijuar më {date}',
    updatedAgo: 'përditësuar {ago}',
    soldN: 'Shitur: {n}',
    save: 'Ruaj',
    saved: 'Ndryshimet u ruajtën',
    created: 'Produkti u krijua',
    readOnly: 'Vetëm lexim — roli juaj nuk mund të ndryshojë produktet.',
    archivedBanner: 'Produkti është i arkivuar — nuk shfaqet në faqe, ndërsa porositë e ruajnë.',
    c_title: 'Titulli & përshkrimi',
    f_title: 'Titulli',
    f_short: 'Përshkrim i shkurtër',
    f_short_h: 'Një fjali nën emrin në faqen e produktit.',
    f_desc: 'Përshkrimi',
    f_desc_h: 'Materiali, printimi, finishing-u dhe përdorimi — shfaqet në faqen e produktit.',
    c_media: 'Media',
    c_media_d: 'Imazhi i parë është kopertina. Tërhiqni imazhet për të ndryshuar renditjen.',

    c_tiers: 'Çmimet sipas sasisë',
    c_tiers_d: 'Çmimi për copë, pa TVSH — vlen nga sasia e shënuar e lart.',
    tiers_switch: 'Çmime sipas sasisë',
    t_qty: 'Nga sasia',
    t_price: 'Çmimi / copë',
    t_value: 'Vlera e tirazhit',
    t_saving: 'Kursimi',
    t_base: 'bazë',
    addTier: 'Shto shkallë',
    removeTier: 'Hiq shkallën',
    sortTiers: 'Rendit sipas sasisë',
    tier_qtyMissing: 'Shënoni sasinë ose hiqeni rreshtin.',
    tier_priceMissing: 'Shënoni çmimin për copë ose hiqeni rreshtin.',
    tier_qtyOrder: 'Sasia duhet të jetë më e madhe se në rreshtin e mëparshëm.',
    tier_priceOrder: 'Çmimi për copë nuk mund të jetë më i lartë se te sasia më e vogël.',
    tiers_off_title: 'Një çmim për çdo sasi',
    tiers_off_text: 'Produkti shitet me një çmim për copë, si paketa e mostrave. Për tirazhe printimi shtoni çmime sipas sasisë.',
    tiers_off_quote: 'Produkt me ofertë — çmimi për copë shërben si orientim për ekipin e shitjes. Mund të shtoni edhe çmime sipas sasisë si referencë.',
    tiers_enable: 'Shto çmime sipas sasisë',
    tiers_baseNote: 'Shkalla e parë është çmimi bazë i produktit.',
    f_moq: 'Sasia minimale (MOQ)',
    f_moq_h: 'Bosh = sasia e shkallës së parë ({qty}).',
    f_moq_h_none: 'Bosh = pa sasi minimale.',
    moq_aboveTier: 'Sasia minimale është mbi shkallën e parë — shkallët nën {qty} nuk përdoren.',
    f_step: 'Hapi i sasisë',
    f_step_h: 'Në konfigurues sasia rritet: {seq} …',
    f_step_h_none: 'Bosh = klienti shkruan çdo sasi.',
    storefront: 'Në dyqan',
    e_tiers: 'Kontrolloni çmimet sipas sasisë',

    c_price: 'Çmimi & kosto',
    c_price_d_net: 'Çmimet janë pa TVSH — TVSH {vat}% shtohet në arkë.',
    c_price_d_gross: 'Çmimet përfshijnë TVSH {vat}%.',
    f_price: 'Çmimi / copë',
    f_basePrice: 'Çmimi bazë / copë',
    f_basePrice_h: '= shkalla e parë ({qty}). Ndryshohet te „Çmimet sipas sasisë“.',
    f_basePrice_h_empty: 'Plotësoni çmimin e shkallës së parë te „Çmimet sipas sasisë“.',
    f_compareAt: 'Çmimi referues',
    f_compareAt_h: 'Më i madh se çmimi → shfaqet zbritja.',
    f_cost: 'Kosto / copë',
    f_cost_h: 'E brendshme — klientët nuk e shohin.',
    margin: 'Marzha',
    profit: 'Fitimi',
    marginAt: 'Marzha për',
    m_price: 'Çmimi / copë',
    m_profitUnit: 'Fitimi / copë',
    m_profitRun: 'Fitimi për tirazhin',
    m_negative: 'Kostoja është mbi çmimin në këtë sasi.',
    m_noCost: 'Shënoni koston për copë për të parë marzhën.',
    price_discount: 'Klienti sheh zbritje {pct}% — kursen {amount}.',
    price_compareLow: 'Çmimi referues nuk është më i madh se çmimi — zbritja nuk do të shfaqet.',
    price_regular: 'Pa zbritje — klienti paguan çmimin e shfaqur.',
    price_tiered: 'Çmimi zbret sipas tirazhit: {from} → {to} për copë.',
    price_note: 'Çmimi promocional dhe kodi i zbritjes janë dy mekanizma të ndryshëm — kodet caktohen te „Zbritjet“.',
    price_noteTiers: 'Për ofertë të përkohshme në produkte me çmime sipas sasisë përdorni „Zbritjet“.',
    f_unit: 'Njësia e shitjes',
    unit_kom: 'Copë',
    unit_set: 'Set / paketë',

    c_variants: 'Variantet & inventari',
    c_variants_d: 'Opsionet (madhësia, kartoni, finishing-u…) krijojnë kombinime — secili ka SKU-në e vet.',
    options: 'Opsionet',
    editOptions: 'Ndrysho opsionet',
    doneOptions: 'Gati',
    f_track: 'Ndiq sasinë në stok',
    f_track_h: 'Çaktivizojeni për produktet që prodhohen me porosi — shumica e printimeve.',
    untracked_note: 'Stoku nuk ndiqet — produkti prodhohet me porosi dhe mund të porositet gjithmonë.',
    f_sku: 'SKU',
    f_sku_h: 'Baza për SKU-të e varianteve.',
    f_barcode: 'Barkodi (EAN)',
    f_stock: 'Në dispozicion',
    v_variant: 'Varianti',
    v_price: 'Çmimi / copë',
    v_sku: 'SKU',
    v_available: 'Në dispozicion',
    v_total: 'Totali',
    v_combos: '{n} kombinime · {on} në shitje',
    v_groupBy: 'Grupo sipas',
    v_noGroup: 'Pa grupim',
    v_setStock: 'Vendos stokun',
    v_apply: 'Zbato',
    v_genSku: 'Gjenero SKU',
    v_disable: 'Hiq nga shitja',
    v_enable: 'Rikthe në shitje',
    v_disabled: 'Jo në shitje',
    v_selected: '{n} të zgjedhura',
    v_selectAll: 'Zgjidh të gjitha variantet',
    v_dupSku: 'SKU e përsëritur',
    inv_incoming: 'Në ardhje: {n}',
    inv_blocked: 'E bllokuar: {n}',
    inv_link: 'Inventari & lëvizjet',
    lowStockWarn: 'Stok i ulët — është koha për rimbushje.',
    outOfStockWarn: 'Pa stok — në faqe shfaqet si „me porosi“.',
    c_shipping: 'Dërgesa',
    f_physical: 'Produkt fizik',
    f_physical_h: 'I dërgohet klientit — pesha dhe përmasat e kutisë janë opsionale.',
    f_physicalOff: 'Shërbim ose produkt digjital — pa dërgesë.',
    f_weight: 'Pesha',
    f_dims: 'Përmasat e paketimit',
    dim_l: 'Gjatësia',
    dim_w: 'Gjerësia',
    dim_h: 'Lartësia',
    optional: 'opsionale',
    c_seo: 'SEO & URL',
    c_seo_d: 'Si shfaqet produkti në kërkimin e Google.',
    f_slug: 'Adresa URL',
    slugAuto: 'Krijohet automatikisht nga emri në shqip.',
    slugManual: 'Adresë e ndryshuar manualisht.',
    slugReset: 'Rikthe adresën automatike',
    f_metaTitle: 'Titulli meta',
    f_metaTitle_h: 'Bosh = emri i produktit.',
    f_metaDesc: 'Përshkrimi meta',
    f_metaDesc_h: 'Bosh = përshkrimi i shkurtër.',
    googlePreview: 'Parapamja në kërkim',
    inStock: 'Në stok',
    redirect: 'Ridrejto adresën e vjetër /produkt/{old}',
    redirect_h: 'Lidhjet nga Google dhe rrjetet sociale vazhdojnë të funksionojnë.',
    c_status: 'Statusi',
    status_active_h: 'I dukshëm në kanalet e zgjedhura të shitjes.',
    status_draft_h: 'I fshehur — përfundojeni dhe publikojeni kur të jetë gati.',
    status_archived_h: 'I tërhequr nga shitja; porositë dhe historia ruhen.',
    ready: 'Gati për publikim',
    missingTitle: 'Për publikim mungojnë:',
    req_name: 'Titulli (SQ)',
    req_category: 'Kategoria',
    req_price: 'Çmimi mbi 0',
    req_image: 'Të paktën një imazh',
    publishBlocked: 'Publikimi u bllokua',
    publishBlockedText: 'Mungon: {list}. Plotësoni fushat ose ruajeni si draft.',
    saveAsDraft: 'Ruaj si draft',
    needPublishPerm: 'Për aktivizim nevojitet leja e publikimit.',
    translations: 'Përkthimet',
    c_publishing: 'Publikimi',
    ch_online_h: 'printwor-ks.com — katalogu, kërkimi dhe koleksionet.',
    ch_pos_h: 'Porosi në zyrë, me telefon ose nga agjentët e shitjes.',
    channelsInactive: 'Kanalet aktivizohen kur statusi është „Aktiv“.',
    noChannel: 'Pa kanal produkti nuk shfaqet askund.',
    c_org: 'Organizimi',
    f_category: 'Kategoria',
    chooseCategory: 'Zgjidhni kategorinë…',
    f_vendor: 'Furnitori i materialit',
    f_vendor_ph: 'p.sh. furnitori i kartonit',
    f_tags: 'Etiketat',
    f_tags_ph: 'Shto etiketë + Enter',
    f_collections: 'Koleksionet',
    col_manual: 'Manuale',
    col_smart: 'Automatike (me kushte)',
    col_smart_h: 'Produkti hyn vetë kur plotëson kushtet — ndjek çmimin, etiketat dhe kategorinë.',
    col_none: 'Nuk është në asnjë koleksion automatik.',
    col_noManual: 'Nuk ka koleksione manuale.',
    col_unpublished: 'i papublikuar',
    col_noPerm: 'Për të ndryshuar koleksionet nevojitet leje.',
    c_template: 'Faqja e produktit',
    tpl_standard: 'Me çmim & shportë',
    tpl_standard_h: 'Çmimet sipas sasisë, konfiguruesi dhe „Shto në shportë“.',
    tpl_quote: 'Me ofertë — „Kërko ofertë“',
    tpl_quote_h: 'Çmimi dhe shporta fshihen; klienti dërgon specifikimet për ofertë. Për kuti premium dhe projekte me porosi.',
    c_production: 'Prodhimi & skedari',
    f_lead: 'Afati i prodhimit',
    daysUnit: 'ditë pune',
    f_lead_h: 'Pas aprovimit të provës digjitale — shfaqet në faqe dhe në konfigurues.',
    f_artwork: 'Kërkon skedar printimi',
    f_artwork_h: 'Në konfigurues klienti ngarkon PDF-in, e dërgon më vonë ose zgjedh dizajnin tonë.',
    f_artworkOff_h: 'Produkt pa personalizim — p.sh. paketa e mostrave.',
    c_design: 'Dizajn profesional & prepress',
    f_design: 'Ofrojmë dizajn & prepress',
    f_design_h: 'Klienti mund ta porosisë dizajnin në konfigurues në vend që të ngarkojë skedarin.',
    f_designPrice: 'Çmimi i shërbimit',
    per_line: 'Për rresht porosie',
    per_unit: 'Për copë',
    design_line: '{price} për rresht porosie',
    design_lineHint: 'Tarifë fikse — e njëjtë për {a} ose {b}.',
    design_unit: '{price} / copë',
    design_unitHint: 'P.sh. {qty} = {total}.',
    c_display: 'Shfaqja në dyqan',
    f_badges: 'Shenjat në kartë',
    f_featured: 'Produkt i veçuar',
    f_featured_h: 'Shfaqet në seksionet e veçuara të faqes kryesore.',
    c_preview: 'Parapamja në faqe',
    c_preview_d: 'Karta ndryshon ndërsa shkruani.',
    shortcutTip: 'Këshillë: Ctrl + S ruan ndryshimet.',
    e_name: 'Shkruani titullin në shqip (SQ).',
    e_skuDup: 'SKU „{sku}“ përdoret nga „{name}“.',
    e_variantSkuDup: 'SKU-të e varianteve përsëriten.',
    fixErrors: 'Kontrolloni fushat e shënuara',
    leaveTitle: 'Të dilet pa ruajtur?',
    leaveText: 'Ndryshimet e paruajtura në këtë produkt do të humbasin.',
    leave: 'Dil',
    c_options: 'Opsionet',
    c_options_d: 'Madhësitë, materialet dhe finishing-u që zgjedh klienti.',
    addOption: 'Shto opsion',
    addValue: 'Shto vlerë',
    optionName: 'Emri i opsionit',
    type_swatch: 'Mostra',
    type_button: 'Butona',
    valueLabel: 'Vlera',
    priceDelta: 'Shtesë / copë',
    noOptions: 'Pa opsione — produkti shitet në një version të vetëm.',
    quickAdd: 'Shto shpejt',
    moveUp: 'Lëviz lart',
    moveDown: 'Lëviz poshtë',
    remove: 'Hiq',
    pickColor: 'Zgjidh ngjyrën e mostrës',
    langHint: 'Gjuha e shkrimit',
    c_specs: 'Specifikimet',
    c_specs_d: 'Të dhënat teknike në tabelën e faqes së produktit.',
    specLabel: 'Vetia',
    specValue: 'Vlera',
    addSpec: 'Shto rresht',
    noSpecs: 'Ende nuk ka specifikime — shtoni materialin, printimin, finishing-un ose afatin e prodhimit.',
  },
  en: {
    title: 'Products',
    addProduct: 'Add product',
    import: 'Import',
    export: 'Export',
    tab_all: 'All',
    tab_active: 'Active',
    tab_draft: 'Draft',
    tab_archived: 'Archived',
    st_active: 'Active',
    st_draft: 'Draft',
    st_archived: 'Archived',
    searchPh: 'Search by name, SKU, barcode or tag…',
    f_category_all: 'Category',
    f_collection_all: 'Collection',
    f_vendor_all: 'Supplier',
    f_stock_all: 'Stock',
    f_stock_in: 'In stock',
    f_stock_low: 'Low stock (≤ 5)',
    f_stock_out: 'Out of stock',
    f_stock_untracked: 'Made to order',
    f_channel_all: 'Channel',
    f_mode_all: 'Sales mode',
    mode_cart: 'Price & cart',
    mode_quote: 'Quote only',
    ch_online: 'Online store',
    ch_pos: 'Direct sales',
    ch_pos_short: 'Direct',
    ch_none: 'No channel',
    clearFilters: 'Clear filters',
    sort_newest: 'Newest first',
    sort_updated: 'Recently updated',
    sort_name: 'Name A–Z',
    sort_price_asc: 'Price: low to high',
    sort_price_desc: 'Price: high to low',
    sort_lead: 'Lead time: shortest first',
    sort_stock: 'Stock: lowest first',
    sort_sold: 'Bestselling',
    col_product: 'Product',
    col_status: 'Status',
    col_inventory: 'Inventory',
    col_category: 'Category',
    col_order: 'MOQ · Lead time',
    col_price: 'Price (excl. VAT)',
    col_vendor: 'Supplier',
    col_channels: 'Channels',
    col_sold: 'Sold',
    col_cost: 'Cost & margin',
    col_updated: 'Updated',
    columns: 'Columns',
    columnsHint: 'Visible columns',
    inv_in_one: '{n} in 1 variant',
    inv_in_many: '{n} in {v} variants',
    variantsN: '{n} variants',
    madeToOrder: 'Made to order',
    lowStock: 'Low stock',
    outOfStock: 'Out of stock',
    incomingN: '+{n} incoming',
    noCategory: 'Uncategorised',
    from: 'from',
    fromPrice: 'from {price}',
    quoteBadge: 'Quote only',
    quoteBadge_h: 'Price and cart are hidden on the website — customers request a quote.',
    tiersN: '{n} price tiers',
    moqShort: 'Min. {qty}',
    noMoq: 'No minimum',
    leadShort: '{n} working days',
    marginAtFirst: 'Margin at the first tier ({qty})',
    footerCount: '{n} products',
    footerBulkHint: 'Bulk actions after selecting',
    pageOf: '{from}–{to} of {total}',
    prevPage: 'Previous page',
    nextPage: 'Next page',
    selectAll: 'Select all on page',
    selectRow: 'Select product',
    selectedN: '{n} selected',
    selectAllFiltered: 'Select all {n} matching',
    allSelected: 'All {n} matching products are selected.',
    clearSelection: 'Clear selection',
    bulk_publish: 'Publish',
    bulk_draft: 'Set as draft',
    bulk_archive: 'Archive',
    bulk_restore: 'Restore',
    bulk_export: 'Export CSV',
    bulk_delete: 'Delete',
    toast_published: 'Published {n} products',
    toast_publishSkipped: '{n} not published — required fields missing',
    toast_drafted: 'Moved to draft: {n}',
    toast_archived: 'Archived: {n}',
    toast_restored: 'Restored as draft: {n}',
    toast_exported: 'Exported {n} products',
    toast_status: '“{name}” → {status}',
    noPerm: 'Your role does not have this permission',
    noPermPublish: 'Publishing requires the “Publish” permission',
    edit: 'Edit',
    duplicate: 'Duplicate',
    viewOnSite: 'View on site',
    publish: 'Publish',
    toDraft: 'Set as draft',
    archive: 'Archive',
    restore: 'Restore',
    delete: 'Delete',
    moreActions: 'More actions',
    duplicated: 'Copy created as a draft',
    emptyTitle: 'No products match these filters',
    emptyText: 'Change the search or clear the filters to see the full catalogue.',
    emptyArchived: 'The archive is empty',
    emptyArchivedText: 'Archived products stay in orders but are not shown on the website.',
    emptyCatalogTitle: 'The catalogue is still empty',
    emptyCatalogText: 'Add your first product or import a catalogue from a CSV file.',

    del_title_one: 'Delete “{name}”?',
    del_title_many: 'Delete {n} products?',
    del_intro: 'Review the consequences before confirming.',
    del_willDelete: 'Deleted permanently',
    del_willArchive: 'Archived instead of deleted',
    del_staysArchived: 'Stays archived',
    del_hasOrders: 'in {n} orders',
    del_hasDrafts: 'in {n} draft orders',
    del_hasQuotes: 'in {n} B2B quotes',
    del_hasPOs: 'in {n} purchase orders',
    del_noHistory: 'No orders or documents',
    del_usedIn: 'Found',
    del_inCollections: 'Removed from collections: {list}',
    del_inDiscounts: 'Referenced by discounts: {list}',
    del_inOffers: 'Part of offers: {list}',
    del_note: 'Orders keep a copy of the item, SKU, price and taxes, so sold products are archived. Permanent deletion is recorded in the audit log.',
    del_confirm: 'Confirm',
    del_confirmDelete: 'Delete {n}',
    del_confirmArchive: 'Archive {n}',
    del_done: 'Deleted: {d} · Archived: {a}',

    imp_title: 'Import products from CSV',
    imp_desc: 'Field mapping, preview and validation before importing — nothing changes until you confirm.',
    imp_step1: 'File',
    imp_step2: 'Mapping',
    imp_step3: 'Preview & validation',
    imp_drop: 'Drop a CSV file here or click to choose one',
    imp_dropHint: 'Separator: comma, semicolon or tab · UTF-8',
    imp_formatHint: 'Quantity pricing is written “qty:price” separated by “|”, e.g. 500:0.44|1000:0.39.',
    imp_paste: 'or paste the CSV content',
    imp_placeholder: 'Name (SQ),SKU,Category,Quantity pricing,Minimum order\nBurger box with window,PW-FD-120,Food packaging,250:0.96|1000:0.51,250',
    imp_template: 'Download template',
    imp_sample: 'Load sample',
    imp_detected: '{rows} rows · {cols} columns · separator “{sep}”',
    imp_noRows: 'The file has no data rows under the header.',
    imp_next: 'Continue',
    imp_back: 'Back',
    imp_csvColumn: 'CSV column',
    imp_example: 'Example',
    imp_field: 'CMS field',
    imp_ignore: '— Don’t import —',
    imp_required: 'Map at least the name and the price (or the quantity pricing).',
    imp_existing: 'When the SKU already exists',
    imp_update: 'Update the existing product',
    imp_skip: 'Skip the row',
    imp_newStatus: 'Status of new products',
    imp_asDraft: 'Draft (recommended)',
    imp_fromColumn: 'From the “Status” column',
    imp_sumNew: 'New',
    imp_sumUpdate: 'Updates',
    imp_sumSkip: 'Skipped',
    imp_sumErrors: 'With errors',
    imp_dupReport: 'Duplicate SKU report',
    imp_dupInFile: '{sku} appears twice in the file (rows {a} and {b}) — only the first is imported.',
    imp_dupInCatalog: '{sku} already exists: {name} — {action}.',
    imp_actUpdate: 'it will be updated',
    imp_actSkip: 'it will be skipped',
    imp_noDups: 'No duplicate SKUs — every row is unique.',
    imp_colLine: 'Row',
    imp_colResult: 'Result',
    imp_colNote: 'Note',
    imp_res_create: 'New',
    imp_res_update: 'Update',
    imp_res_skip: 'Skipped',
    imp_res_error: 'Error',
    imp_ok: 'Ready',
    imp_confirm: 'Import {n} products',
    imp_nothing: 'Nothing to import',
    imp_done: 'Imported: {c} new · {u} updated',
    imp_doneHint: 'New products are drafts — review and publish them.',
    imp_showDrafts: 'Show drafts',
    imp_moreRows: '+ {n} more rows',
    imp_readError: 'The file could not be read',
    imp_tiersShort: '{n} tiers',
    fld_handle: 'URL',
    fld_name_sq: 'Name (SQ)',
    fld_name_en: 'Name (EN)',
    fld_sku: 'SKU',
    fld_barcode: 'Barcode',
    fld_price: 'Price',
    fld_compareAt: 'Compare-at price',
    fld_cost: 'Cost per item',
    fld_tiers: 'Quantity pricing',
    fld_moq: 'Minimum order',
    fld_qtyStep: 'Quantity step',
    fld_artwork: 'Print file',
    fld_design: 'Design & prepress (€)',
    fld_leadDays: 'Lead time (working days)',
    fld_category: 'Category',
    fld_vendor: 'Supplier',
    fld_tags: 'Tags',
    fld_stock: 'Stock',
    fld_status: 'Status',
    fld_unit: 'Unit',
    fld_channels: 'Channels',
    fld_template: 'Product page',
    fld_description: 'Description',
    fld_image: 'Image (URL)',
    val_yes: 'yes',
    val_no: 'no',
    val_perPiece: '/ pc',
    issue_noName: 'Name missing',
    issue_noPrice: 'Price missing',
    issue_badNumber: '“{value}” is not a number ({field})',
    issue_negative: 'Negative value ({field})',
    issue_badTiers: 'Quantity pricing “{value}” is not valid — quantities ascending, prices not rising (e.g. 500:0.44|1000:0.39)',
    issue_badFlag: '“{value}” not understood ({field}) — left unchanged',
    issue_dupFile: 'Duplicate SKU in the file',
    issue_exists: 'SKU exists in the catalogue',
    issue_noCategory: 'No category — stays draft',
    issue_unknownCategory: 'Category “{value}” not found',
    issue_compareLow: 'Compare-at is not above the price — no discount shown',
    issue_badStatus: 'Unknown status “{value}” — draft',
    issue_notPublishable: 'Fields missing for publishing — imported as draft',
    issue_nameFromOther: 'Name (SQ) taken from the English name',

    newTitle: 'New product',
    notFound: 'Product not found',
    notFoundText: 'It may have been deleted, or the link is not correct.',
    backToList: 'Back to products',
    createdOn: 'Created {date}',
    updatedAgo: 'updated {ago}',
    soldN: 'Sold: {n}',
    save: 'Save',
    saved: 'Changes saved',
    created: 'Product created',
    readOnly: 'Read only — your role cannot edit products.',
    archivedBanner: 'This product is archived — hidden from the website, while orders keep showing it.',
    c_title: 'Title & description',
    f_title: 'Title',
    f_short: 'Short description',
    f_short_h: 'One sentence below the name on the product page.',
    f_desc: 'Description',
    f_desc_h: 'Material, print, finishing and use — shown on the product page.',
    c_media: 'Media',
    c_media_d: 'The first image is the cover. Drag images to reorder them.',

    c_tiers: 'Quantity pricing',
    c_tiers_d: 'Price per piece, excl. VAT — applies from the quantity shown upward.',
    tiers_switch: 'Quantity pricing',
    t_qty: 'From quantity',
    t_price: 'Price / pc',
    t_value: 'Run value',
    t_saving: 'Saving',
    t_base: 'base',
    addTier: 'Add tier',
    removeTier: 'Remove tier',
    sortTiers: 'Sort by quantity',
    tier_qtyMissing: 'Enter a quantity or remove the row.',
    tier_priceMissing: 'Enter a price per piece or remove the row.',
    tier_qtyOrder: 'The quantity must be higher than in the row above.',
    tier_priceOrder: 'The price per piece cannot be higher than at a smaller quantity.',
    tiers_off_title: 'One price for any quantity',
    tiers_off_text: 'The product is sold at a single price per piece, like the sample kit. For print runs, add quantity pricing.',
    tiers_off_quote: 'Quote-only product — the price per piece is a guide for the sales team. You can still add quantity pricing as a reference.',
    tiers_enable: 'Add quantity pricing',
    tiers_baseNote: 'The first tier is the product’s base price.',
    f_moq: 'Minimum order (MOQ)',
    f_moq_h: 'Empty = the first tier quantity ({qty}).',
    f_moq_h_none: 'Empty = no minimum.',
    moq_aboveTier: 'The minimum is above the first tier — tiers below {qty} are never used.',
    f_step: 'Quantity step',
    f_step_h: 'The configurator steps: {seq} …',
    f_step_h_none: 'Empty = customers type any quantity.',
    storefront: 'On the website',
    e_tiers: 'Please check the quantity pricing',

    c_price: 'Price & cost',
    c_price_d_net: 'Prices are excl. VAT — {vat}% VAT is added at checkout.',
    c_price_d_gross: 'All prices include {vat}% VAT.',
    f_price: 'Price / pc',
    f_basePrice: 'Base price / pc',
    f_basePrice_h: '= the first tier ({qty}). Edit it under “Quantity pricing”.',
    f_basePrice_h_empty: 'Enter the first tier price under “Quantity pricing”.',
    f_compareAt: 'Compare-at price',
    f_compareAt_h: 'Higher than the price → a discount is shown.',
    f_cost: 'Cost per piece',
    f_cost_h: 'Internal — customers never see it.',
    margin: 'Margin',
    profit: 'Profit',
    marginAt: 'Margin at',
    m_price: 'Price / pc',
    m_profitUnit: 'Profit / pc',
    m_profitRun: 'Profit on the run',
    m_negative: 'The cost is above the price at this quantity.',
    m_noCost: 'Enter the cost per piece to see the margin.',
    price_discount: 'Customers see {pct}% off — they save {amount}.',
    price_compareLow: 'The compare-at price is not above the price — no discount will show.',
    price_regular: 'No discount — customers pay the price shown.',
    price_tiered: 'The price drops with the run: {from} → {to} per piece.',
    price_note: 'A promotional price and a discount code are two different mechanisms — codes live under “Discounts”.',
    price_noteTiers: 'For a temporary offer on products with quantity pricing, use “Discounts”.',
    f_unit: 'Sold per',
    unit_kom: 'Piece (pc)',
    unit_set: 'Set / kit',

    c_variants: 'Variants & inventory',
    c_variants_d: 'Options (size, board, finish…) generate combinations — each has its own SKU.',
    options: 'Options',
    editOptions: 'Edit options',
    doneOptions: 'Done',
    f_track: 'Track stock quantity',
    f_track_h: 'Turn off for products made to order — most print products.',
    untracked_note: 'Stock is not tracked — the product is made to order and can always be ordered.',
    f_sku: 'SKU',
    f_sku_h: 'Base for the variant SKUs.',
    f_barcode: 'Barcode (EAN)',
    f_stock: 'Available',
    v_variant: 'Variant',
    v_price: 'Price / pc',
    v_sku: 'SKU',
    v_available: 'Available',
    v_total: 'Total',
    v_combos: '{n} combinations · {on} for sale',
    v_groupBy: 'Group by',
    v_noGroup: 'No grouping',
    v_setStock: 'Set stock',
    v_apply: 'Apply',
    v_genSku: 'Generate SKUs',
    v_disable: 'Remove from sale',
    v_enable: 'Put back on sale',
    v_disabled: 'Not for sale',
    v_selected: '{n} selected',
    v_selectAll: 'Select all variants',
    v_dupSku: 'Duplicate SKU',
    inv_incoming: 'Incoming: {n}',
    inv_blocked: 'Blocked: {n}',
    inv_link: 'Inventory & movements',
    lowStockWarn: 'Low stock — time to restock.',
    outOfStockWarn: 'Out of stock — shown as “made to order” on the website.',
    c_shipping: 'Shipping',
    f_physical: 'Physical product',
    f_physical_h: 'Shipped to the customer — weight and carton size are optional.',
    f_physicalOff: 'Service or digital product — nothing is shipped.',
    f_weight: 'Weight',
    f_dims: 'Package dimensions',
    dim_l: 'Length',
    dim_w: 'Width',
    dim_h: 'Height',
    optional: 'optional',
    c_seo: 'SEO & URL',
    c_seo_d: 'How the product appears in Google search.',
    f_slug: 'URL handle',
    slugAuto: 'Generated automatically from the Albanian name.',
    slugManual: 'Edited manually.',
    slugReset: 'Reset to automatic',
    f_metaTitle: 'Meta title',
    f_metaTitle_h: 'Empty = product name.',
    f_metaDesc: 'Meta description',
    f_metaDesc_h: 'Empty = short description.',
    googlePreview: 'Search preview',
    inStock: 'In stock',
    redirect: 'Redirect the old address /produkt/{old}',
    redirect_h: 'Links from Google and social media keep working.',
    c_status: 'Status',
    status_active_h: 'Visible on the selected sales channels.',
    status_draft_h: 'Hidden — finish it and publish when it is ready.',
    status_archived_h: 'Withdrawn from sale; orders and history are kept.',
    ready: 'Ready to publish',
    missingTitle: 'Missing to publish:',
    req_name: 'Title (SQ)',
    req_category: 'Category',
    req_price: 'Price above 0',
    req_image: 'At least one image',
    publishBlocked: 'Publishing blocked',
    publishBlockedText: 'Missing: {list}. Complete the fields or save as draft.',
    saveAsDraft: 'Save as draft',
    needPublishPerm: 'Activating requires the publish permission.',
    translations: 'Translations',
    c_publishing: 'Publishing',
    ch_online_h: 'printwor-ks.com — catalogue, search and collections.',
    ch_pos_h: 'Orders taken at the office, by phone or by sales reps.',
    channelsInactive: 'Channels go live when the status is “Active”.',
    noChannel: 'Without a channel the product is not shown anywhere.',
    c_org: 'Organisation',
    f_category: 'Category',
    chooseCategory: 'Choose a category…',
    f_vendor: 'Material supplier',
    f_vendor_ph: 'e.g. the board supplier',
    f_tags: 'Tags',
    f_tags_ph: 'Add a tag + Enter',
    f_collections: 'Collections',
    col_manual: 'Manual',
    col_smart: 'Automatic (rules)',
    col_smart_h: 'The product joins by itself when it meets the rules — it follows price, tags and category.',
    col_none: 'Not in any automatic collection.',
    col_noManual: 'No manual collections.',
    col_unpublished: 'unpublished',
    col_noPerm: 'Changing collections requires permission.',
    c_template: 'Product page',
    tpl_standard: 'Price & cart',
    tpl_standard_h: 'Quantity pricing, the configurator and “Add to cart”.',
    tpl_quote: 'Quote only — “Request a quote”',
    tpl_quote_h: 'Price and cart are hidden; customers send their specs for a quote. For premium boxes and custom projects.',
    c_production: 'Production & artwork',
    f_lead: 'Production time',
    daysUnit: 'working days',
    f_lead_h: 'After digital proof approval — shown on the product page and in the configurator.',
    f_artwork: 'Needs a print file',
    f_artwork_h: 'In the configurator customers upload their PDF, send it later or choose our design service.',
    f_artworkOff_h: 'Not personalised — e.g. the sample kit.',
    c_design: 'Professional design & prepress',
    f_design: 'We offer design & prepress',
    f_design_h: 'Customers can order the design in the configurator instead of uploading a file.',
    f_designPrice: 'Service price',
    per_line: 'Per order line',
    per_unit: 'Per piece',
    design_line: '{price} per order line',
    design_lineHint: 'Flat fee — the same for {a} or {b}.',
    design_unit: '{price} / pc',
    design_unitHint: 'E.g. {qty} = {total}.',
    c_display: 'Storefront display',
    f_badges: 'Card badges',
    f_featured: 'Featured product',
    f_featured_h: 'Shown in highlighted sections on the homepage.',
    c_preview: 'Storefront preview',
    c_preview_d: 'The card updates as you type.',
    shortcutTip: 'Tip: Ctrl + S saves your changes.',
    e_name: 'Enter the Albanian (SQ) title.',
    e_skuDup: 'SKU “{sku}” is already used by “{name}”.',
    e_variantSkuDup: 'Variant SKUs repeat.',
    fixErrors: 'Please check the highlighted fields',
    leaveTitle: 'Leave without saving?',
    leaveText: 'Unsaved changes to this product will be lost.',
    leave: 'Leave',
    c_options: 'Options',
    c_options_d: 'Sizes, materials and finishes the customer can choose from.',
    addOption: 'Add option',
    addValue: 'Add value',
    optionName: 'Option name',
    type_swatch: 'Swatches',
    type_button: 'Buttons',
    valueLabel: 'Value',
    priceDelta: 'Surcharge / pc',
    noOptions: 'No options — the product is sold in a single version.',
    quickAdd: 'Quick add',
    moveUp: 'Move up',
    moveDown: 'Move down',
    remove: 'Remove',
    pickColor: 'Pick the swatch colour',
    langHint: 'Editing language',
    c_specs: 'Specifications',
    c_specs_d: 'Technical data shown in the table on the product page.',
    specLabel: 'Property',
    specValue: 'Value',
    addSpec: 'Add row',
    noSpecs: 'No specifications yet — add material, print, finishing or production time.',
  },
});

export type PdKey = keyof typeof pd.sq;
