// Commercial terms of a B2B quote and the wording of the printed quote (PrintWorks letterhead).
// The document has its own language (SQ / EN) — independent of the admin language.
import { defineDict, interpolate } from '@/i18n';
import type { Lang } from '@/lib/types';
import type { DeliveryTerm, PaymentTerm, QuoteExtra } from './model';

export const QD = defineDict({
  sq: {
    pay_advance50: 'Avans 50% me konfirmimin e porosisë, pjesa tjetër para dërgesës',
    pay_advance100: 'Pagesë 100% para fillimit të prodhimit',
    pay_net15: 'Pagesë brenda 15 ditësh nga data e faturës',
    pay_net30: 'Pagesë brenda 30 ditësh nga data e faturës',
    del_delivered: 'Dërgesë në adresën e klientit',
    del_pickup: 'Marrje në fabrikë, Prishtinë',
    lead: '{n} ditë pune pas aprovimit të provës digjitale',
    tolerance: '±{n}% e sasisë së porositur — faturohet sasia e dorëzuar (praktikë standarde në printim)',
    toleranceNone: 'Sasi e saktë, pa tolerancë',
    validity: 'Oferta vlen deri më {date}',
    proof: 'Prova digjitale falas brenda 24 orësh nga konfirmimi',
    l_payment: 'Pagesa',
    l_lead: 'Afati i prodhimit',
    l_tolerance: 'Toleranca e sasisë',
    l_delivery: 'Dorëzimi',
    l_validity: 'Vlefshmëria',
    l_proof: 'Prova',
    l_notes: 'Shënime',
    prices: 'Çmimet janë në EUR, pa TVSH; TVSH {rate}% llogaritet veçmas.',
    pricesGross: 'Çmimet janë në EUR dhe përfshijnë TVSH {rate}%.',
    docTitle: 'Ofertë',
    docNo: 'Nr. {n}',
    version: 'Versioni {v}',
    issued: 'Data',
    validUntil: 'E vlefshme deri',
    preparedBy: 'Përgatiti',
    to: 'Për',
    nui: 'NUI',
    contact: 'Personi i kontaktit',
    intro: 'Përshëndetje {name}, faleminderit për kërkesën tuaj. Më poshtë gjeni ofertën tonë sipas specifikimeve të dakorduara.',
    col_no: 'Nr.',
    col_desc: 'Përshkrimi',
    col_qty: 'Sasia',
    col_price: 'Çmimi / njësi',
    col_amount: 'Shuma',
    net: 'Totali pa TVSH',
    vat: 'TVSH {rate}%',
    total: 'Totali me TVSH',
    totalGross: 'Totali',
    vatIncl: 'Nga kjo TVSH {rate}%',
    terms: 'Kushtet',
    accept: 'Pranimi i ofertës',
    acceptText: 'Me nënshkrimin e kësaj oferte konfirmoni porosinë sipas kushteve të mësipërme.',
    sign: 'Emri, data, nënshkrimi dhe vula',
    thanks: 'Faleminderit për besimin.',
    slogan: 'Printim inovativ. Paketim i jashtëzakonshëm.',
    country: 'Kosovë',
    pcs: 'copë',
  },
  en: {
    pay_advance50: '50% deposit on order confirmation, balance before delivery',
    pay_advance100: '100% payment before production starts',
    pay_net15: 'Payment within 15 days of the invoice date',
    pay_net30: 'Payment within 30 days of the invoice date',
    del_delivered: 'Delivered to the customer’s address',
    del_pickup: 'Collected from our factory in Prishtina',
    lead: '{n} working days after digital proof approval',
    tolerance: '±{n}% of the ordered quantity — the delivered quantity is invoiced (standard print practice)',
    toleranceNone: 'Exact quantity, no tolerance',
    validity: 'This quote is valid until {date}',
    proof: 'Free digital proof within 24 hours of confirmation',
    l_payment: 'Payment',
    l_lead: 'Lead time',
    l_tolerance: 'Quantity tolerance',
    l_delivery: 'Delivery',
    l_validity: 'Validity',
    l_proof: 'Proof',
    l_notes: 'Notes',
    prices: 'Prices in EUR excluding VAT; {rate}% VAT is added.',
    pricesGross: 'Prices in EUR including {rate}% VAT.',
    docTitle: 'Quotation',
    docNo: 'No. {n}',
    version: 'Version {v}',
    issued: 'Date',
    validUntil: 'Valid until',
    preparedBy: 'Prepared by',
    to: 'To',
    nui: 'Business no. (NUI)',
    contact: 'Contact person',
    intro: 'Dear {name}, thank you for your request. Please find our quotation below, based on the agreed specification.',
    col_no: 'No.',
    col_desc: 'Description',
    col_qty: 'Qty',
    col_price: 'Unit price',
    col_amount: 'Amount',
    net: 'Total excl. VAT',
    vat: 'VAT {rate}%',
    total: 'Total incl. VAT',
    totalGross: 'Total',
    vatIncl: 'Incl. VAT {rate}%',
    terms: 'Terms',
    accept: 'Acceptance',
    acceptText: 'By signing this quotation you confirm the order under the terms above.',
    sign: 'Name, date, signature and stamp',
    thanks: 'Thank you for your trust.',
    slogan: 'Innovative Printing. Exceptional Packaging.',
    country: 'Kosovo',
    pcs: 'pcs',
  },
});

export type QdKey = keyof typeof QD.sq;
export const qd = (lang: Lang, key: QdKey, vars?: Record<string, string | number>) => interpolate(QD[lang][key], vars);

export const paymentText = (p: PaymentTerm, lang: Lang) => qd(lang, `pay_${p}`);
export const deliveryText = (d: DeliveryTerm, lang: Lang) => qd(lang, `del_${d}`);

/** The commercial terms as label/text rows, in the order the customer reads them. */
export function termRows(q: Required<QuoteExtra>, lang: Lang, validUntil: string) {
  return [
    { label: qd(lang, 'l_payment'), text: paymentText(q.payment, lang) },
    { label: qd(lang, 'l_lead'), text: qd(lang, 'lead', { n: q.leadDays }) },
    { label: qd(lang, 'l_proof'), text: qd(lang, 'proof') },
    { label: qd(lang, 'l_tolerance'), text: q.tolerance > 0 ? qd(lang, 'tolerance', { n: q.tolerance }) : qd(lang, 'toleranceNone') },
    { label: qd(lang, 'l_delivery'), text: deliveryText(q.delivery, lang) },
    { label: qd(lang, 'l_validity'), text: qd(lang, 'validity', { date: validUntil }) },
  ];
}
