import { defineDict } from '@/i18n';

/** Strings shared by the storefront content pages (blog, post, CMS page, contact). */
export const C = defineDict({
  me: {
    minRead: '{n} min čitanja',
    read: 'Pročitaj',
    readArticle: 'Pročitaj članak',
    latest: 'Najnovije',
    share: 'Podijeli',
    shareArticle: 'Podijelite članak',
    copyLink: 'Kopiraj link',
    copied: 'Link je kopiran',
    copiedText: 'Pošaljite ga prijatelju ili ga sačuvajte za kasnije.',
    copyFailed: 'Kopiranje nije uspjelo — kopirajte adresu iz pregledača.',
    home: 'Početna',
    cta_eyebrow: 'Besplatno mjerenje',
    cta_title: 'Pretvorimo savjet u *gotov prostor*',
    cta_text: 'Dolazimo na vašu adresu, mjerimo, donosimo uzorke i pripremamo preciznu ponudu — bez ikakve obaveze.',
    cta_b1: 'Dolazak u roku od 48 sati',
    cta_b2: 'Uzorci materijala na licu mjesta',
    cta_b3: 'Ponuda sa ugradnjom i tačnim rokom',
    cta_button: 'Zakaži besplatno mjerenje',
    map_eyebrow: 'Salon i skladište',
    map_open: 'Otvori u Google Maps',
    map_north: 'S',
    map_scale: '200 m',
  },
  sq: {
    minRead: '{n} min lexim',
    read: 'Lexo',
    readArticle: 'Lexo artikullin',
    latest: 'Më i riu',
    share: 'Shpërndaj',
    shareArticle: 'Shpërndajeni artikullin',
    copyLink: 'Kopjo linkun',
    copied: 'Linku u kopjua',
    copiedText: 'Dërgojani një miku ose ruajeni për më vonë.',
    copyFailed: 'Kopjimi dështoi — kopjoni adresën nga shfletuesi.',
    home: 'Ballina',
    cta_eyebrow: 'Matje falas',
    cta_title: 'Ta kthejmë këshillën në *hapësirë të përfunduar*',
    cta_text: 'Vijmë në adresën tuaj, masim, sjellim mostra dhe përgatisim ofertë të saktë — pa asnjë detyrim.',
    cta_b1: 'Vijmë brenda 48 orëve',
    cta_b2: 'Mostra materialesh në vend',
    cta_b3: 'Ofertë me montim dhe afat të saktë',
    cta_button: 'Cakto matjen falas',
    map_eyebrow: 'Salloni dhe magazina',
    map_open: 'Hape në Google Maps',
    map_north: 'V',
    map_scale: '200 m',
  },
  en: {
    minRead: '{n} min read',
    read: 'Read',
    readArticle: 'Read article',
    latest: 'Latest',
    share: 'Share',
    shareArticle: 'Share this article',
    copyLink: 'Copy link',
    copied: 'Link copied',
    copiedText: 'Send it to a friend or save it for later.',
    copyFailed: 'Couldn’t copy — please copy the address from your browser.',
    home: 'Home',
    cta_eyebrow: 'Free measurement',
    cta_title: 'Turn advice into a *finished space*',
    cta_text: 'We come to your address, measure up, bring samples and prepare a precise quote — with no obligation.',
    cta_b1: 'On site within 48 hours',
    cta_b2: 'Material samples brought to you',
    cta_b3: 'Quote with installation and a firm date',
    cta_button: 'Book a free measurement',
    map_eyebrow: 'Showroom & warehouse',
    map_open: 'Open in Google Maps',
    map_north: 'N',
    map_scale: '200 m',
  },
});
