import { defineDict } from '@/i18n';

/** Strings shared by the storefront content pages (blog, post, CMS page, contact). */
export const C = defineDict({
  me: {
    minRead: '{n} min čitanja',
    read: 'Pročitaj',
    readArticle: 'Pročitaj članak',
    latest: 'Najnovije',
    share: 'Podijeli',
    shareArticle: 'Podijelite članak',
    copyLink: 'Kopiraj link',
    copied: 'Link je kopiran',
    copiedText: 'Pošaljite ga kolegi ili ga sačuvajte za kasnije.',
    copyFailed: 'Kopiranje nije uspjelo — kopirajte adresu iz pregledača.',
    home: 'Početna',
    cta_eyebrow: 'Besplatni uzorci',
    cta_title: 'Probajte ambalažu *u vašem lokalu*',
    cta_text: 'Izaberite kategorije koje vas zanimaju — pripremamo besplatne uzorke da provjerite kvalitet, zapreminu i poklopce prije narudžbe.',
    cta_b1: 'Uzorak iz svake izabrane kategorije',
    cta_b2: 'Spremno za 1–2 radna dana',
    cta_b3: 'Bez obaveze kupovine',
    cta_button: 'Zatraži besplatne uzorke',
    map_eyebrow: 'Magacin i preuzimanje',
    map_open: 'Otvori u Google Maps',
    map_north: 'S',
    map_scale: '200 m',
    map_river: 'Ibar',
  },
  sq: {
    minRead: '{n} min lexim',
    read: 'Lexo',
    readArticle: 'Lexo artikullin',
    latest: 'Më i riu',
    share: 'Shpërndaj',
    shareArticle: 'Shpërndajeni artikullin',
    copyLink: 'Kopjo linkun',
    copied: 'Linku u kopjua',
    copiedText: 'Dërgojani një kolegu ose ruajeni për më vonë.',
    copyFailed: 'Kopjimi dështoi — kopjoni adresën nga shfletuesi.',
    home: 'Ballina',
    cta_eyebrow: 'Mostra falas',
    cta_title: 'Provojeni paketimin *në lokalin tuaj*',
    cta_text: 'Zgjidhni kategoritë që ju interesojnë — përgatisim mostra falas që të kontrolloni cilësinë, kapacitetin dhe kapakët para porosisë.',
    cta_b1: 'Mostër nga çdo kategori e zgjedhur',
    cta_b2: 'Gati brenda 1–2 ditësh pune',
    cta_b3: 'Pa detyrim blerjeje',
    cta_button: 'Kërko mostra falas',
    map_eyebrow: 'Depoja & pika e marrjes',
    map_open: 'Hape në Google Maps',
    map_north: 'V',
    map_scale: '200 m',
    map_river: 'Ibri',
  },
  en: {
    minRead: '{n} min read',
    read: 'Read',
    readArticle: 'Read article',
    latest: 'Latest',
    share: 'Share',
    shareArticle: 'Share this article',
    copyLink: 'Copy link',
    copied: 'Link copied',
    copiedText: 'Send it to a colleague or save it for later.',
    copyFailed: 'Couldn’t copy — please copy the address from your browser.',
    home: 'Home',
    cta_eyebrow: 'Free samples',
    cta_title: 'Try the packaging *in your venue*',
    cta_text: 'Pick the categories you’re interested in — we prepare free samples so you can check quality, capacity and lids before you order.',
    cta_b1: 'A sample from every category you pick',
    cta_b2: 'Ready within 1–2 working days',
    cta_b3: 'No obligation to buy',
    cta_button: 'Request free samples',
    map_eyebrow: 'Warehouse & pickup',
    map_open: 'Open in Google Maps',
    map_north: 'N',
    map_scale: '200 m',
    map_river: 'Ibar',
  },
});
