import { defineDict } from '@/i18n';

/** Strings for the CMS returns area (PDF p.17 / p.24) — ME / SQ / EN. */
export const rd = defineDict({
  me: {
    description: 'Zahtjevi kupaca za povrat robe: odobrenje, prijem, odluka o zalihama i refundacija iz stvarno plaćenog iznosa.',
    create: 'Zahtjev za povrat',
    tab_all: 'Svi',
    tab_requested: 'Zahtjevi',
    tab_approved: 'Odobreni',
    tab_received: 'Primljeni',
    tab_refunded: 'Refundirani',
    tab_rejected: 'Odbijeni',
    searchPh: 'Broj povrata ili narudžbe, kupac, proizvod…',
    col_return: 'Povrat',
    col_order: 'Narudžba',
    col_customer: 'Kupac',
    col_items: 'Stavke i razlog',
    col_refund: 'Refundacija',
    col_status: 'Status',
    col_date: 'Datum',
    stat_requested: 'Čeka odobrenje',
    stat_requestedHint: 'novi zahtjevi kupaca',
    stat_approved: 'Čeka prijem robe',
    stat_approvedHint: 'odobreno, roba na putu',
    stat_received: 'Za refundaciju',
    stat_refunded: 'Refundirano (30 dana)',
    returns_one: '{n} povrat',
    returns_few: '{n} povrata',
    returns_many: '{n} povrata',
    more: '+{n} još',
    emptyTitle: 'Još nema povrata',
    emptyText: 'Kada kupac vrati robu, kreirajte zahtjev iz narudžbe — odobrenje, prijem i refundacija prate se ovdje.',
    emptyFiltered: 'Nema povrata za ovaj filter',
    emptyFilteredText: 'Promijenite pretragu ili izaberite drugi tab.',
    clearSearch: 'Očisti pretragu',
    showing: 'Prikazano {n} od {total}',
    readOnly: 'Samo pregled — vaša uloga ne može mijenjati povrate.',
    // reasons
    r_damaged: 'Oštećeno pri transportu',
    r_shade: 'Pogrešna nijansa ili model',
    r_size: 'Pogrešna mjera',
    r_surplus: 'Višak materijala',
    r_mind: 'Kupac je odustao',
    r_other: 'Drugo',
    // drawer
    step_requested: 'Zahtjev',
    step_approved: 'Odobren',
    step_received: 'Primljen',
    step_refunded: 'Refundiran',
    step_rejected: 'Odbijen',
    next_requested: 'Provjerite zahtjev i odobrite ga — kupac tada šalje ili predaje robu.',
    next_approved: 'Kada roba stigne, potvrdite prijem — zalihe se tada ažuriraju.',
    next_received: 'Roba je pregledana. Refundirajte iznos ili odbijte povrat.',
    closed_refunded: 'Povrat je zatvoren — novac je vraćen kupcu.',
    closed_rejected: 'Povrat je odbijen — bez refundacije i bez promjene zaliha.',
    order: 'Narudžba',
    openOrder: 'Otvori narudžbu',
    items: 'Stavke za povrat',
    ofQty: '{n} od {total}',
    reason: 'Razlog',
    refundTitle: 'Refundacija',
    refundBasis: 'Računa se iz neto plaćenog iznosa vraćenih stavki (nakon popusta), ne iz današnje cijene. Dostava se ne vraća.',
    gross: 'Vrijednost stavki',
    discounts: 'Popusti na stavkama',
    net: 'Neto plaćeno',
    toRefund: 'Za refundaciju',
    refundedOn: 'Refundirano {date}',
    amountLabel: 'Iznos za refundaciju',
    amountHint: 'Možete ga umanjiti (npr. zbog oštećenja), ali ne preko {max}.',
    amountCapped: 'Ograničeno na preostali plaćeni iznos narudžbe: {max}.',
    amountTooHigh: 'Najviše {max}',
    partialNote: 'Djelimična refundacija: {amount} od {max}',
    unpaid: 'Narudžba još nije plaćena — refundacija je moguća tek kada uplata postoji.',
    markOrderPaid: 'Označi kao plaćeno',
    orderPaid: 'Narudžba {n} je označena kao plaćena',
    restock: 'Vrati robu u zalihe',
    restockHint: 'Zalihe se povećavaju tek kada roba stigne. Isključite za oštećenu robu.',
    restockDone: 'Vraćeno u zalihe pri prijemu.',
    restockSkipped: 'Roba nije vraćena u zalihe (oštećena / otpis).',
    stockNow: 'stanje: {n}',
    note: 'Napomena uz korak (opciono)',
    notePh: 'npr. preuzeto na adresi, ambalaža neoštećena',
    history: 'Istorija',
    approve: 'Odobri povrat',
    receive: 'Roba je primljena',
    refund: 'Refundiraj {amount}',
    reject: 'Odbij',
    rejectTitle: 'Odbiti povrat {n}?',
    rejectText: 'Kupac ne dobija povrat novca; zalihe se ne mijenjaju.',
    rejectConfirm: 'Odbij povrat',
    done_approved: 'Povrat {n} je odobren',
    done_received: 'Roba za {n} je primljena',
    done_refunded: 'Refundirano {amount} za {n}',
    done_rejected: 'Povrat {n} je odbijen',
    noRefundPerm: 'Vaša uloga ne može da refundira',
    noOrder: 'Narudžba više ne postoji.',
    // create
    createTitle: 'Novi zahtjev za povrat',
    pickOrder: 'Narudžba',
    findOrder: 'Broj narudžbe, kupac ili telefon…',
    noOrders: 'Nema narudžbi za ovu pretragu',
    change: 'Promijeni',
    chooseItems: 'Šta kupac vraća?',
    selectAll: 'Sve',
    alreadyReturned: 'već u povratu: {n}',
    nothingLeft: 'Sve je već u povratu',
    noLines: 'Ova narudžba nema stavki koje se mogu vratiti.',
    reasonLabel: 'Razlog povrata',
    details: 'Detalji (opciono)',
    detailsPh: 'npr. 2 paketa neotvorena, fotografije stigle e-mailom',
    estimated: 'Procijenjena refundacija',
    submit: 'Kreiraj zahtjev',
    created: 'Povrat {n} je kreiran',
    needItems: 'Izaberite bar jednu stavku',
    unpaidCreate: 'Narudžba još nije plaćena — refundacija će biti moguća nakon uplate.',
  },
  sq: {
    description: 'Kërkesat e klientëve për kthim malli: miratimi, pranimi, vendimi për stokun dhe rimbursimi nga pagesa reale.',
    create: 'Kërkesë kthimi',
    tab_all: 'Të gjitha',
    tab_requested: 'Kërkesa',
    tab_approved: 'Të miratuara',
    tab_received: 'Të pranuara',
    tab_refunded: 'Të rimbursuara',
    tab_rejected: 'Të refuzuara',
    searchPh: 'Numri i kthimit ose porosisë, klienti, produkti…',
    col_return: 'Kthimi',
    col_order: 'Porosia',
    col_customer: 'Klienti',
    col_items: 'Artikujt dhe arsyeja',
    col_refund: 'Rimbursimi',
    col_status: 'Statusi',
    col_date: 'Data',
    stat_requested: 'Në pritje të miratimit',
    stat_requestedHint: 'kërkesa të reja nga klientët',
    stat_approved: 'Në pritje të mallit',
    stat_approvedHint: 'miratuar, malli në rrugë',
    stat_received: 'Për rimbursim',
    stat_refunded: 'Rimbursuar (30 ditë)',
    returns_one: '{n} kthim',
    returns_few: '{n} kthime',
    returns_many: '{n} kthime',
    more: '+{n} të tjera',
    emptyTitle: 'Ende nuk ka kthime',
    emptyText: 'Kur klienti kthen mallin, krijoni kërkesën nga porosia — miratimi, pranimi dhe rimbursimi ndiqen këtu.',
    emptyFiltered: 'Asnjë kthim për këtë filtër',
    emptyFilteredText: 'Ndryshoni kërkimin ose zgjidhni një skedë tjetër.',
    clearSearch: 'Pastro kërkimin',
    showing: 'Shfaqen {n} nga {total}',
    readOnly: 'Vetëm lexim — roli juaj nuk mund të ndryshojë kthimet.',
    r_damaged: 'Dëmtuar gjatë transportit',
    r_shade: 'Nuancë ose model i gabuar',
    r_size: 'Masë e gabuar',
    r_surplus: 'Material i tepërt',
    r_mind: 'Klienti ndryshoi mendje',
    r_other: 'Tjetër',
    step_requested: 'Kërkesë',
    step_approved: 'Miratuar',
    step_received: 'Pranuar',
    step_refunded: 'Rimbursuar',
    step_rejected: 'Refuzuar',
    next_requested: 'Kontrolloni kërkesën dhe miratojeni — pastaj klienti e dërgon ose e dorëzon mallin.',
    next_approved: 'Kur të mbërrijë malli, konfirmoni pranimin — atëherë përditësohet stoku.',
    next_received: 'Malli u kontrollua. Rimbursoni shumën ose refuzoni kthimin.',
    closed_refunded: 'Kthimi u mbyll — paratë iu kthyen klientit.',
    closed_rejected: 'Kthimi u refuzua — pa rimbursim dhe pa ndryshim stoku.',
    order: 'Porosia',
    openOrder: 'Hap porosinë',
    items: 'Artikujt për kthim',
    ofQty: '{n} nga {total}',
    reason: 'Arsyeja',
    refundTitle: 'Rimbursimi',
    refundBasis: 'Llogaritet nga pagesa neto e artikujve të kthyer (pas zbritjeve), jo nga çmimi i sotëm. Transporti nuk rimbursohet.',
    gross: 'Vlera e artikujve',
    discounts: 'Zbritjet e artikujve',
    net: 'Neto e paguar',
    toRefund: 'Për rimbursim',
    refundedOn: 'Rimbursuar më {date}',
    amountLabel: 'Shuma për rimbursim',
    amountHint: 'Mund ta ulni (p.sh. për dëmtim), por jo mbi {max}.',
    amountCapped: 'Kufizuar në shumën e mbetur të paguar të porosisë: {max}.',
    amountTooHigh: 'Maksimumi {max}',
    partialNote: 'Rimbursim i pjesshëm: {amount} nga {max}',
    unpaid: 'Porosia ende nuk është paguar — rimbursimi bëhet vetëm kur ka pagesë.',
    markOrderPaid: 'Shëno si të paguar',
    orderPaid: 'Porosia {n} u shënua si e paguar',
    restock: 'Ktheje mallin në stok',
    restockHint: 'Stoku rritet vetëm kur malli mbërrin. Çaktivizojeni për mall të dëmtuar.',
    restockDone: 'U kthye në stok gjatë pranimit.',
    restockSkipped: 'Malli nuk u kthye në stok (i dëmtuar / i shlyer).',
    stockNow: 'stoku: {n}',
    note: 'Shënim për hapin (opsional)',
    notePh: 'p.sh. u mor në adresë, paketimi i padëmtuar',
    history: 'Historiku',
    approve: 'Mirato kthimin',
    receive: 'Malli u pranua',
    refund: 'Rimburso {amount}',
    reject: 'Refuzo',
    rejectTitle: 'Të refuzohet kthimi {n}?',
    rejectText: 'Klienti nuk merr rimbursim; stoku nuk ndryshon.',
    rejectConfirm: 'Refuzo kthimin',
    done_approved: 'Kthimi {n} u miratua',
    done_received: 'Malli për {n} u pranua',
    done_refunded: 'U rimbursuan {amount} për {n}',
    done_rejected: 'Kthimi {n} u refuzua',
    noRefundPerm: 'Roli juaj nuk mund të rimbursojë',
    noOrder: 'Porosia nuk ekziston më.',
    createTitle: 'Kërkesë e re kthimi',
    pickOrder: 'Porosia',
    findOrder: 'Numri i porosisë, klienti ose telefoni…',
    noOrders: 'Asnjë porosi për këtë kërkim',
    change: 'Ndrysho',
    chooseItems: 'Çfarë kthen klienti?',
    selectAll: 'Të gjitha',
    alreadyReturned: 'tashmë në kthim: {n}',
    nothingLeft: 'Gjithçka është tashmë në kthim',
    noLines: 'Kjo porosi nuk ka artikuj që mund të kthehen.',
    reasonLabel: 'Arsyeja e kthimit',
    details: 'Detaje (opsionale)',
    detailsPh: 'p.sh. 2 pako të pahapura, fotot erdhën me e-mail',
    estimated: 'Rimbursimi i llogaritur',
    submit: 'Krijo kërkesën',
    created: 'Kthimi {n} u krijua',
    needItems: 'Zgjidhni të paktën një artikull',
    unpaidCreate: 'Porosia ende nuk është paguar — rimbursimi do të jetë i mundur pas pagesës.',
  },
  en: {
    description: 'Customer return requests: approval, receipt, the stock decision and a refund based on what was actually paid.',
    create: 'Return request',
    tab_all: 'All',
    tab_requested: 'Requested',
    tab_approved: 'Approved',
    tab_received: 'Received',
    tab_refunded: 'Refunded',
    tab_rejected: 'Rejected',
    searchPh: 'Return or order number, customer, product…',
    col_return: 'Return',
    col_order: 'Order',
    col_customer: 'Customer',
    col_items: 'Items and reason',
    col_refund: 'Refund',
    col_status: 'Status',
    col_date: 'Date',
    stat_requested: 'Awaiting approval',
    stat_requestedHint: 'new customer requests',
    stat_approved: 'Awaiting goods',
    stat_approvedHint: 'approved, goods on the way',
    stat_received: 'To refund',
    stat_refunded: 'Refunded (30 days)',
    returns_one: '{n} return',
    returns_few: '{n} returns',
    returns_many: '{n} returns',
    more: '+{n} more',
    emptyTitle: 'No returns yet',
    emptyText: 'When a customer brings goods back, create the request from the order — approval, receipt and refund are tracked here.',
    emptyFiltered: 'No returns for this filter',
    emptyFilteredText: 'Change the search or pick another tab.',
    clearSearch: 'Clear search',
    showing: 'Showing {n} of {total}',
    readOnly: 'Read only — your role cannot change returns.',
    r_damaged: 'Damaged in transit',
    r_shade: 'Wrong shade or model',
    r_size: 'Wrong size',
    r_surplus: 'Surplus material',
    r_mind: 'Customer changed their mind',
    r_other: 'Other',
    step_requested: 'Requested',
    step_approved: 'Approved',
    step_received: 'Received',
    step_refunded: 'Refunded',
    step_rejected: 'Rejected',
    next_requested: 'Check the request and approve it — the customer then sends or hands over the goods.',
    next_approved: 'When the goods arrive, confirm receipt — stock is updated at that moment.',
    next_received: 'The goods were inspected. Refund the amount or reject the return.',
    closed_refunded: 'Closed — the money was returned to the customer.',
    closed_rejected: 'Rejected — no refund and no stock change.',
    order: 'Order',
    openOrder: 'Open order',
    items: 'Items to return',
    ofQty: '{n} of {total}',
    reason: 'Reason',
    refundTitle: 'Refund',
    refundBasis: 'Based on the net amount paid for the returned items (after discounts), not today’s price. Delivery is not refunded.',
    gross: 'Items value',
    discounts: 'Item discounts',
    net: 'Net paid',
    toRefund: 'To refund',
    refundedOn: 'Refunded on {date}',
    amountLabel: 'Amount to refund',
    amountHint: 'You can lower it (e.g. for damage) but not above {max}.',
    amountCapped: 'Capped at the order’s remaining paid amount: {max}.',
    amountTooHigh: 'At most {max}',
    partialNote: 'Partial refund: {amount} of {max}',
    unpaid: 'The order has not been paid yet — a refund needs a recorded payment.',
    markOrderPaid: 'Mark as paid',
    orderPaid: 'Order {n} marked as paid',
    restock: 'Put goods back in stock',
    restockHint: 'Stock goes up only when the goods arrive. Turn off for damaged goods.',
    restockDone: 'Put back in stock on receipt.',
    restockSkipped: 'Goods were not restocked (damaged / written off).',
    stockNow: 'stock: {n}',
    note: 'Note for this step (optional)',
    notePh: 'e.g. collected at the address, packaging intact',
    history: 'History',
    approve: 'Approve return',
    receive: 'Goods received',
    refund: 'Refund {amount}',
    reject: 'Reject',
    rejectTitle: 'Reject return {n}?',
    rejectText: 'The customer gets no refund; stock stays unchanged.',
    rejectConfirm: 'Reject return',
    done_approved: 'Return {n} approved',
    done_received: 'Goods for {n} received',
    done_refunded: 'Refunded {amount} for {n}',
    done_rejected: 'Return {n} rejected',
    noRefundPerm: 'Your role cannot issue refunds',
    noOrder: 'The order no longer exists.',
    createTitle: 'New return request',
    pickOrder: 'Order',
    findOrder: 'Order number, customer or phone…',
    noOrders: 'No orders for this search',
    change: 'Change',
    chooseItems: 'What is the customer returning?',
    selectAll: 'All',
    alreadyReturned: 'already in a return: {n}',
    nothingLeft: 'Everything is already in a return',
    noLines: 'This order has no returnable items.',
    reasonLabel: 'Return reason',
    details: 'Details (optional)',
    detailsPh: 'e.g. 2 unopened packs, photos received by e-mail',
    estimated: 'Calculated refund',
    submit: 'Create request',
    created: 'Return {n} created',
    needItems: 'Select at least one item',
    unpaidCreate: 'The order has not been paid yet — a refund will be possible after payment.',
  },
});

export type RdKey = keyof typeof rd.me;
