import { defineDict } from '@/i18n';
import type { Lang } from '@/lib/types';

/** Strings for the catalogue (/produktet, /produktet/:category) and its building blocks. */
export const T = defineDict({
  sq: {
    catalog: 'Katalogu',
    allTitle: 'Paketim & printim *me porosi*',
    allSubtitle: 'Kuti, paketime ushqimore, etiketa, qese dhe materiale promovuese — konfiguroni online me çmime sipas sasisë, ose kërkoni ofertë për një projekt të veçantë.',
    statProducts: 'produkte',
    statCategories: 'kategori',
    statProof: 'provë digjitale',
    statProofValue: '24 h',
    countOne: '{n} produkt',
    countMany: '{n} produkte',
    all: 'Të gjitha',
    fromPrice: 'nga {price} / copë',
    fromMoq: 'nga {n} copë',
    fastest: 'gati për ~{n} ditë',
    customCta: 'Paketim me porosi',
    filters: 'Filtrat',
    sortBy: 'Rendit',
    sort_popular: 'Më të kërkuarat',
    sort_priceAsc: 'Çmimi për copë: në rritje',
    sort_priceDesc: 'Çmimi për copë: në zbritje',
    sort_new: 'Më të rejat',
    sort_fastest: 'Më të shpejtat',
    view: 'Pamja',
    cols3: '3 kolona',
    cols4: '4 kolona',
    clearAll: 'Pastro të gjitha',
    clear: 'Pastro',
    removeFilter: 'Hiq filtrin',
    category: 'Kategoria',
    price: 'Çmimi për copë',
    priceNote: 'Çmimi më i ulët për copë, pa TVSH.',
    b_u010: 'nën 0,10 €',
    'b_010-050': '0,10 – 0,50 €',
    'b_050-1': '0,50 – 1 €',
    b_o1: 'mbi 1 €',
    lead: 'Afati i prodhimit',
    leadUpTo: 'deri {n} ditë',
    leadPill: 'Afati ≤ {n} ditë',
    moq: 'Sasia minimale',
    moqUpTo: 'deri {n} copë',
    moqPill: 'Min. ≤ {n} copë',
    features: 'Materiali & finishing',
    f_matte: 'Mat',
    f_gloss: 'Me shkëlqim',
    f_softtouch: 'Soft-touch',
    f_spotuv: 'UV selektiv',
    f_foil: 'Folje ari/argjendi',
    f_emboss: 'Reliev',
    f_kraft: 'Kraft',
    f_eflute: 'Mikrovalë E',
    f_film: 'Film PP / transparent',
    f_food: 'Kontakt me ushqim',
    badges: 'Etiketat',
    bd_bestseller: 'Më të kërkuarat',
    bd_new: 'Të reja',
    bd_premium: 'Premium',
    bd_sale: 'Në ofertë',
    modes: 'Mënyra e blerjes',
    m_online: 'Porosi online',
    m_quote: 'Me ofertë',
    showResults: 'Shfaq {what}',
    emptyTitle: 'Asnjë produkt për këta filtra',
    emptyText: 'Hiqni ndonjë filtër — ose na tregoni çfarë ju nevojitet dhe ju dërgojmë ofertë brenda 24 orësh.',
    resetFilters: 'Rivendos filtrat',
    askQuote: 'Kërko ofertë',
    loadMore: 'Shfaq edhe {n}',
    shownOf: 'Shfaqen {a} nga {b}',
    helpEyebrow: 'Paketim me porosi',
    helpTitle: 'Nuk e gjeni *formatin e duhur?*',
    helpText: 'Çdo kuti, etiketë ose qese e prodhojmë edhe sipas përmasave dhe materialit tuaj — nga matrica e re deri te finishing-u me folje. Na dërgoni specifikimet dhe merrni ofertë brenda 24 orësh.',
    helpCta: 'Kërko ofertë',
    helpSample: 'Paketa e mostrave · 19 €',
    helpPoint1: 'Ofertë brenda 24 orësh',
    helpPoint2: 'Provë digjitale falas',
    helpPoint3: 'Mostër fizike sipas kërkesës',
    notFoundTitle: 'Kategoria nuk u gjet',
    notFoundText: 'Mund të jetë hequr ose riemërtuar. Shikoni të gjithë katalogun.',
  },
  en: {
    catalog: 'Catalogue',
    allTitle: 'Packaging & print *made to order*',
    allSubtitle: 'Boxes, food packaging, labels, bags and promotional print — configure online with quantity pricing, or request a quote for a custom project.',
    statProducts: 'products',
    statCategories: 'categories',
    statProof: 'digital proof',
    statProofValue: '24 h',
    countOne: '{n} product',
    countMany: '{n} products',
    all: 'All',
    fromPrice: 'from {price} / pc',
    fromMoq: 'from {n} pcs',
    fastest: 'ready in ~{n} days',
    customCta: 'Custom packaging',
    filters: 'Filters',
    sortBy: 'Sort',
    sort_popular: 'Most popular',
    sort_priceAsc: 'Price per piece: low to high',
    sort_priceDesc: 'Price per piece: high to low',
    sort_new: 'Newest',
    sort_fastest: 'Fastest',
    view: 'View',
    cols3: '3 columns',
    cols4: '4 columns',
    clearAll: 'Clear all',
    clear: 'Clear',
    removeFilter: 'Remove filter',
    category: 'Category',
    price: 'Price per piece',
    priceNote: 'Lowest price per piece, excl. VAT.',
    b_u010: 'under €0.10',
    'b_010-050': '€0.10 – €0.50',
    'b_050-1': '€0.50 – €1',
    b_o1: 'over €1',
    lead: 'Production time',
    leadUpTo: 'up to {n} days',
    leadPill: 'Lead time ≤ {n} days',
    moq: 'Minimum order',
    moqUpTo: 'up to {n} pcs',
    moqPill: 'MOQ ≤ {n} pcs',
    features: 'Material & finish',
    f_matte: 'Matte',
    f_gloss: 'Gloss',
    f_softtouch: 'Soft-touch',
    f_spotuv: 'Spot UV',
    f_foil: 'Gold/silver foil',
    f_emboss: 'Embossing',
    f_kraft: 'Kraft',
    f_eflute: 'E-flute',
    f_film: 'PP film / clear',
    f_food: 'Food-safe',
    badges: 'Highlights',
    bd_bestseller: 'Bestsellers',
    bd_new: 'New',
    bd_premium: 'Premium',
    bd_sale: 'On sale',
    modes: 'How to buy',
    m_online: 'Order online',
    m_quote: 'By quote',
    showResults: 'Show {what}',
    emptyTitle: 'No products match these filters',
    emptyText: 'Remove a filter — or tell us what you need and we’ll send a quote within 24 hours.',
    resetFilters: 'Reset filters',
    askQuote: 'Request a quote',
    loadMore: 'Show {n} more',
    shownOf: 'Showing {a} of {b}',
    helpEyebrow: 'Custom packaging',
    helpTitle: 'Can’t find the *right format?*',
    helpText: 'We make any box, label or bag to your size and material too — from a new cutting die to foil finishing. Send us the specs and get a quote within 24 hours.',
    helpCta: 'Request a quote',
    helpSample: 'Sample kit · €19',
    helpPoint1: 'Quote within 24 hours',
    helpPoint2: 'Free digital proof',
    helpPoint3: 'Physical sample on request',
    notFoundTitle: 'Category not found',
    notFoundText: 'It may have been removed or renamed. Browse the full catalogue instead.',
  },
});

export type ShopT = (key: keyof (typeof T)['sq'] & string, vars?: Record<string, string | number>) => string;

export function countLabel(t: ShopT, lang: Lang, n: number) {
  void lang;
  return t(n === 1 ? 'countOne' : 'countMany', { n });
}
