import { defineDict } from '@/i18n';

/** CMS v2 editorial strings shared by pages, blog, projects, media, menus and models (PDF p.36 wording). */
export const cx = defineDict({
  sq: {
    st_published: 'Publikuar',
    st_scheduled: 'Planifikuar',
    st_hidden: 'Fshehur',
    st_draft: 'Draft',
    vis_published: 'Publikuar',
    vis_publishedHint: 'E dukshme në faqe nga data e publikimit.',
    vis_hidden: 'Fshehur',
    vis_hiddenHint: 'Hapet vetëm me lidhje direkte — jo në lista, menu ose footer.',
    vis_draft: 'Draft',
    vis_draftHint: 'Në përgatitje — nuk shihet në faqe.',
    visibility: 'Dukshmëria',
    publishDate: 'Data e publikimit',
    publishDateHint: 'Datë në të ardhmen = publikim i planifikuar.',
    scheduledFor: 'Planifikuar për {date}',
    publishedOn: 'Publikuar më {date}',
    noPublishPerm: 'Roli juaj përgatit draftet — publikimin e miraton redaktori ose menaxheri.',
    noDeletePerm: 'Roli juaj nuk ka leje për fshirje.',
    readOnly: 'Vetëm shikim',
    readOnlyText: 'Roli juaj mund ta shohë përmbajtjen, por jo ta ndryshojë.',
    seo: 'Motorët e kërkimit (SEO)',
    seoHint: 'Si shfaqet faqja në kërkimin e Google.',
    seoTitle: 'Titulli SEO',
    seoDesc: 'Përshkrimi SEO',
    seoLimit: 'Rekomandohet deri në {n} karaktere',
    seoFallback: 'Bosh = përdoret titulli dhe përmbledhja.',
    organization: 'Organizimi',
    template: 'Shablloni',
    templateHint: 'Tema përdor shabllonin për paraqitjen e faqes.',
    author: 'Autori',
    tags: 'Etiketat',
    tagsPh: 'Shtoni etiketë dhe shtypni Enter',
    tagsHint: 'Etiketa të brendshme për kërkim dhe filtrim.',
    excerpt: 'Përmbledhje',
    excerptHint: 'Përshkrim i shkurtër për listat, ndarjen dhe Google (deri ~160 karaktere).',
    photo: 'Foto',
    photoHint: 'Imazhi kryesor për ndarje dhe lista.',
    tpl_page: 'Faqe standarde',
    tpl_policy: 'Politikë / kushte',
    tpl_about: 'Rreth nesh',
    tpl_contact: 'Kontakt',
    tpl_faq: 'Pyetje të shpeshta',
    tpl_landing: 'Fushatë (landing)',
    tpl_article: 'Artikull',
    tpl_guide: 'Udhëzues me përmbajtje',
    tpl_news: 'Lajm i shkurtër',
    inMenus: 'Në menutë',
    notInMenus: 'Asnjë menu nuk lidhet me këtë element.',
    addToFooter: 'Shto në footer',
    addedToFooter: 'Lidhja u shtua në menunë e footer-it',
    manageMenus: 'Menaxho menutë',
    menu_main: 'Menuja kryesore',
    menu_footer: 'Footer',
    menuIssueHidden: 'Elementi i fshehur nuk shfaqet në menu.',
    menuIssueDraft: 'Drafti nuk shfaqet në menu.',
    by: 'nga {name}',
    lastChange: 'Ndryshimi i fundit',
    words: '{n} fjalë',
    selectNone: '— Zgjidhni —',
  },
  en: {
    st_published: 'Published',
    st_scheduled: 'Scheduled',
    st_hidden: 'Hidden',
    st_draft: 'Draft',
    vis_published: 'Published',
    vis_publishedHint: 'Visible on the site from the publish date.',
    vis_hidden: 'Hidden',
    vis_hiddenHint: 'Opens only with a direct link — not in lists, menus or the footer.',
    vis_draft: 'Draft',
    vis_draftHint: 'Work in progress — not visible on the site.',
    visibility: 'Visibility',
    publishDate: 'Publish date',
    publishDateHint: 'A future date schedules the publication.',
    scheduledFor: 'Scheduled for {date}',
    publishedOn: 'Published {date}',
    noPublishPerm: 'Your role prepares drafts — an editor or manager publishes them.',
    noDeletePerm: 'Your role cannot delete.',
    readOnly: 'View only',
    readOnlyText: 'Your role can view the content but not change it.',
    seo: 'Search engines (SEO)',
    seoHint: 'How the page appears in Google search.',
    seoTitle: 'SEO title',
    seoDesc: 'SEO description',
    seoLimit: 'Recommended: up to {n} characters',
    seoFallback: 'Empty = the title and excerpt are used.',
    organization: 'Organisation',
    template: 'Template',
    templateHint: 'The theme uses the template for the page layout.',
    author: 'Author',
    tags: 'Tags',
    tagsPh: 'Add a tag and press Enter',
    tagsHint: 'Internal tags for search and filtering.',
    excerpt: 'Excerpt',
    excerptHint: 'Short description for lists, sharing and Google (up to ~160 characters).',
    photo: 'Photo',
    photoHint: 'Cover image for sharing and lists.',
    tpl_page: 'Standard page',
    tpl_policy: 'Policy / terms',
    tpl_about: 'About us',
    tpl_contact: 'Contact',
    tpl_faq: 'FAQ',
    tpl_landing: 'Campaign (landing)',
    tpl_article: 'Article',
    tpl_guide: 'Guide with contents',
    tpl_news: 'Short news',
    inMenus: 'In menus',
    notInMenus: 'No menu links to this item.',
    addToFooter: 'Add to footer',
    addedToFooter: 'Link added to the footer menu',
    manageMenus: 'Manage menus',
    menu_main: 'Main menu',
    menu_footer: 'Footer',
    menuIssueHidden: 'A hidden item is not shown in menus.',
    menuIssueDraft: 'A draft is not shown in menus.',
    by: 'by {name}',
    lastChange: 'Last change',
    words: '{n} words',
    selectNone: '— Select —',
  },
});
