import { defineDict } from '@/i18n';

/** Strings for the CMS collections list + editor (PDF p.14) — SQ / EN. */
export const cd = defineDict({
  sq: {
    title: 'Koleksionet',
    create: 'Krijo koleksion',
    tab_all: 'Të gjitha',
    tab_manual: 'Manuale',
    tab_smart: 'Me kushte',
    searchPh: 'Kërko koleksione…',
    col_title: 'Koleksioni',
    col_type: 'Lloji',
    col_conditions: 'Kushtet / përzgjedhja',
    col_products: 'Produktet',
    col_status: 'Statusi',
    col_usage: 'Përdoret',
    type_manual: 'Manual',
    type_smart: 'Me kushte',
    st_published: 'Publikuar',
    st_draft: 'Draft',
    manualCount: '{n} produkte të zgjedhura',
    matchAll: 'të gjitha kushtet',
    matchAny: 'cilido kusht',
    publicCount: '{n} publike',
    hiddenCount: '+{n} të fshehura',
    usageN: '{n}×',
    footerCount: '{n} koleksione',
    emptyTitle: 'Ende nuk ka koleksione',
    emptyText: 'Koleksionet grupojnë produktet për katalogun, ofertat dhe faqen kryesore — p.sh. „Paketime për pica“ ose „Etiketa për kozmetikë“ — manualisht ose me kushte.',
    noResults: 'Asnjë koleksion për këtë kërkim',
    noResultsText: 'Ndryshoni kërkimin ose skedën.',
    viewOnSite: 'Shiko në faqe',
    edit: 'Ndrysho',
    open: 'Hap',
    duplicate: 'Dupliko',
    duplicated: 'Kopja u krijua si draft',
    copySuffix: '(kopje)',
    delete: 'Fshij',
    moreActions: 'Më shumë veprime',
    deleteTitle: 'Të fshihet koleksioni „{name}“?',
    deleteText: 'Produktet mbeten në katalog; koleksioni zhduket nga faqja. Ky veprim nuk mund të zhbëhet.',
    deleteUsed: 'Kujdes — e përdor: {list}.',
    deleted: 'Koleksioni u fshi',
    noPerm: 'Roli juaj nuk e ka këtë leje',
    newTitle: 'Koleksion i ri',
    notFound: 'Koleksioni nuk u gjet',
    notFoundText: 'Mund të jetë fshirë ose lidhja nuk është e saktë.',
    backToList: 'Kthehu te koleksionet',
    c_title: 'Titulli & përshkrimi',
    f_title: 'Titulli',
    f_desc: 'Përshkrimi',
    f_desc_h: 'Shfaqet në krye të faqes së koleksionit.',
    c_type: 'Lloji i koleksionit',
    manual_title: 'Manual',
    manual_h: 'Ju zgjidhni produktet dhe renditjen e tyre — përzgjedhje editoriale.',
    smart_title: 'Me kushte',
    smart_h: 'Produktet që plotësojnë kushtet hyjnë vetë — dhe dalin kur ndryshon kategoria, çmimi ose tag-et.',
    copyMatches: 'Kopjo {n} produktet që përputhen tani',
    copied: 'U kopjuan {n} produkte',
    c_conditions: 'Kushtet',
    match_label: 'Produktet duhet të plotësojnë',
    match_all: 'të gjitha kushtet',
    match_any: 'cilindo kusht',
    addRule: 'Shto kusht',
    noRules: 'Shtoni të paktën një kusht — p.sh. Kategoria është Etiketa & shrink sleeve.',
    field_category: 'Kategoria',
    field_price: 'Çmimi / copë (pa TVSH)',
    field_compareAt: 'Çmimi para zbritjes',
    field_stock: 'Stoku në magazinë',
    field_status: 'Statusi i produktit',
    field_tag: 'Tag',
    field_title: 'Titulli',
    field_vendor: 'Prodhuesi / furnitori',
    field_onSale: 'Në zbritje',
    field_badge: 'Shenja në kartë',
    op_eq: 'është',
    op_neq: 'nuk është',
    op_gt: 'më i madh se',
    op_lt: 'më i vogël se',
    op_contains: 'përmban',
    yes: 'Po',
    no: 'Jo',
    valuePh: 'Vlera',
    removeRule: 'Hiq kushtin',
    liveNote: 'Ndryshimi i kategorisë, çmimit ose tag-ut të produktit e përditëson automatikisht këtë koleksion — pa shtim manual.',
    priceNote: 'Çmimi krahasohet me çmimin e listës për copë te sasia minimale (tirazhi i parë), pa TVSH. Me tirazhe më të mëdha çmimi për copë bie.',
    stockNote: 'Produktet me porosi nuk mbajnë stok dhe llogariten gjithmonë si të disponueshme.',
    c_products: 'Produktet',
    sort_label: 'Renditja',
    sort_manual: 'Manuale',
    sort_bestselling: 'Më të shiturat',
    'sort_price-asc': 'Çmimi: nga më i ulëti',
    'sort_price-desc': 'Çmimi: nga më i larti',
    sort_newest: 'Më të rejat',
    sortNote: 'Për renditje me dorë zgjidhni „Manuale“.',
    pickerSearch: 'Shto produkte — kërko sipas emrit, SKU-së ose kategorisë…',
    pickerEmpty: 'Asnjë produkt për këtë kërkim',
    added: 'Shtuar',
    manualEmpty: 'Ende nuk ka produkte — shtojini me kërkimin më sipër.',
    notPublic: 'jo publik',
    notPublicNote: 'Produktet draft/arkivuar nuk shfaqen kurrë publikisht, edhe nëse janë në koleksion ose përputhen me kushtin.',
    preview_count: '{n} produkte aktive plotësojnë kushtet',
    preview_one: '1 produkt aktiv plotëson kushtet',
    preview_hidden: 'Edhe {n} draft ose të arkivuara përputhen — nuk shfaqen publikisht.',
    preview_none: 'Asnjë produkt aktiv nuk i plotëson kushtet.',
    preview_rulesFirst: 'Shtoni një kusht për të parë parapamjen.',
    showMore: 'Shfaq edhe {n}',
    showLess: 'Shfaq më pak',
    moveUp: 'Lëviz lart',
    moveDown: 'Lëviz poshtë',
    remove: 'Hiq',
    c_publish: 'Publikimi',
    published_on: 'Publikuar në dyqanin online',
    published_h: 'E dukshme te /koleksioni/{slug} dhe e gatshme për menytë, banerët dhe ofertat.',
    unpublished_h: 'E fshehur nga faqja — mund ta përgatitni paraprakisht.',
    needPublishPerm: 'Publikimi kërkon lejen „Publiko“.',
    c_image: 'Imazhi',
    c_summary: 'Përmbledhje',
    sum_public: 'Të dukshme publikisht',
    sum_total: 'Gjithsej në koleksion',
    sum_type: 'Lloji',
    c_usage: 'Ku përdoret',
    usage_none: 'Ende nuk përdoret në zbritje, oferta apo meny.',
    usage_discount: 'Zbritje',
    usage_offer: 'Ofertë',
    usage_menu: 'Meny',
    usage_dynamic: 'Anëtarësia ndiqet dinamikisht — zbritja vlen për produktet që plotësojnë kushtet në momentin e porosisë.',
    usage_static: 'Anëtarësia ruhet si përzgjedhje — vlen vetëm për produktet e listuara në koleksion.',
    c_seo: 'SEO & URL',
    f_slug: 'Adresa URL',
    slugAuto: 'Krijohet automatikisht nga titulli në shqip.',
    slugManual: 'Adresë e ndryshuar manualisht.',
    slugReset: 'Rikthe adresën automatike',
    f_metaTitle: 'Titulli meta',
    f_metaTitle_h: 'Bosh = titulli i koleksionit.',
    f_metaDesc: 'Përshkrimi meta',
    f_metaDesc_h: 'Bosh = përshkrimi i koleksionit.',
    e_title: 'Shkruani titullin në shqip (SQ).',
    e_slug: 'Kjo adresë është tashmë e zënë.',
    e_rules: 'Çdo kusht duhet të ketë vlerë.',
    e_noRules: 'Shtoni të paktën një kusht.',
    fixErrors: 'Kontrolloni fushat e shënuara',
    saved: 'Koleksioni u ruajt',
    created: 'Koleksioni u krijua',
    leaveTitle: 'Të dilet pa ruajtur?',
    leaveText: 'Ndryshimet e paruajtura në këtë koleksion do të humbasin.',
    leave: 'Dil',
    readOnly: 'Vetëm lexim — roli juaj nuk mund të ndryshojë koleksionet.',
    description: 'Gruponi produktet e printimit dhe paketimit për katalogun, ofertat dhe faqen kryesore — manualisht ose me kushte.',
    col_sort: 'Renditja',
    hiddenTitle: '{n} draft ose të arkivuara — nuk shfaqen publikisht',
    c_preview: 'Parapamja e produkteve',
    c_preview_d: 'Produktet aktive që i plotësojnë kushtet tani, me renditjen si në faqe. Çmimet: nga çmimi më i ulët për copë, pa TVSH.',
    c_products_d: 'Produktet e zgjedhura dhe renditja e tyre në faqe. Çmimet: nga çmimi më i ulët për copë, pa TVSH.',
    dragHint: 'Tërhiqni ose përdorni shigjetat për renditjen.',
    sortedBy: 'Në faqe renditen: {sort}.',
    previewOnSite: 'Parapamje në faqe',
    shortcutTip: 'Ctrl/⌘ + S ruan ndryshimet',
    hiddenList: 'Përputhen, por nuk janë publike',
    createdOn: 'Krijuar më {date}',
    image_h: 'Shfaqet në krye të faqes së koleksionit dhe në karta.',
    seo_d: 'Si shfaqet koleksioni në kërkimin e Google.',
    googlePreview: 'Parapamja në kërkim',
    unpublishedNote: 'Pa publikuar — duket vetëm në CMS dhe në parapamje.',
    productsN: '{n} produkte',
    or: 'ose',
    quote: 'Me ofertë',
  },
  en: {
    title: 'Collections',
    create: 'Create collection',
    tab_all: 'All',
    tab_manual: 'Manual',
    tab_smart: 'Automated',
    searchPh: 'Search collections…',
    col_title: 'Collection',
    col_type: 'Type',
    col_conditions: 'Conditions / selection',
    col_products: 'Products',
    col_status: 'Status',
    col_usage: 'Used in',
    type_manual: 'Manual',
    type_smart: 'Automated',
    st_published: 'Published',
    st_draft: 'Draft',
    manualCount: '{n} hand-picked products',
    matchAll: 'all conditions',
    matchAny: 'any condition',
    publicCount: '{n} public',
    hiddenCount: '+{n} hidden',
    usageN: '{n}×',
    footerCount: '{n} collections',
    emptyTitle: 'No collections yet',
    emptyText: 'Collections group products for the catalogue, offers and the homepage — e.g. “Pizza packaging” or “Cosmetics labels” — by hand or by rules.',
    noResults: 'No collections match this search',
    noResultsText: 'Change the search or the tab.',
    viewOnSite: 'View on site',
    edit: 'Edit',
    open: 'Open',
    duplicate: 'Duplicate',
    duplicated: 'Copy created as a draft',
    copySuffix: '(copy)',
    delete: 'Delete',
    moreActions: 'More actions',
    deleteTitle: 'Delete the collection “{name}”?',
    deleteText: 'Products stay in the catalogue; the collection disappears from the website. This cannot be undone.',
    deleteUsed: 'Careful — used by: {list}.',
    deleted: 'Collection deleted',
    noPerm: 'Your role does not have this permission',
    newTitle: 'New collection',
    notFound: 'Collection not found',
    notFoundText: 'It may have been deleted, or the link is not correct.',
    backToList: 'Back to collections',
    c_title: 'Title & description',
    f_title: 'Title',
    f_desc: 'Description',
    f_desc_h: 'Shown at the top of the collection page.',
    c_type: 'Collection type',
    manual_title: 'Manual',
    manual_h: 'You pick the products and their order — an editorial selection.',
    smart_title: 'Automated',
    smart_h: 'Products that meet the rules join by themselves — and leave when the category, price or tags change.',
    copyMatches: 'Copy the {n} products that match now',
    copied: 'Copied {n} products',
    c_conditions: 'Conditions',
    match_label: 'Products must match',
    match_all: 'all conditions',
    match_any: 'any condition',
    addRule: 'Add condition',
    noRules: 'Add at least one condition — e.g. Category is Labels & shrink sleeves.',
    field_category: 'Category',
    field_price: 'Unit price (excl. VAT)',
    field_compareAt: 'Compare-at price',
    field_stock: 'Warehouse stock',
    field_status: 'Product status',
    field_tag: 'Tag',
    field_title: 'Title',
    field_vendor: 'Manufacturer / supplier',
    field_onSale: 'On sale',
    field_badge: 'Card badge',
    op_eq: 'is',
    op_neq: 'is not',
    op_gt: 'greater than',
    op_lt: 'less than',
    op_contains: 'contains',
    yes: 'Yes',
    no: 'No',
    valuePh: 'Value',
    removeRule: 'Remove condition',
    liveNote: 'Changing a product’s category, price or tag updates this collection automatically — no manual adding.',
    priceNote: 'The price is compared with the list price per piece at the minimum order (first tier), excl. VAT. Larger print runs lower the unit price.',
    stockNote: 'Made-to-order products keep no stock and always count as available.',
    c_products: 'Products',
    sort_label: 'Sort',
    sort_manual: 'Manual',
    sort_bestselling: 'Best selling',
    'sort_price-asc': 'Price: low to high',
    'sort_price-desc': 'Price: high to low',
    sort_newest: 'Newest',
    sortNote: 'Choose “Manual” to order by hand.',
    pickerSearch: 'Add products — search by name, SKU or category…',
    pickerEmpty: 'No products for this search',
    added: 'Added',
    manualEmpty: 'No products yet — add them with the search above.',
    notPublic: 'not public',
    notPublicNote: 'Draft and archived products never show publicly, even when they are in the collection or match the rules.',
    preview_count: '{n} active products match',
    preview_one: '1 active product matches',
    preview_hidden: '{n} more draft or archived products match — they never show publicly.',
    preview_none: 'No active product matches.',
    preview_rulesFirst: 'Add a condition to see the preview.',
    showMore: 'Show {n} more',
    showLess: 'Show less',
    moveUp: 'Move up',
    moveDown: 'Move down',
    remove: 'Remove',
    c_publish: 'Publishing',
    published_on: 'Published on the online store',
    published_h: 'Visible at /koleksioni/{slug} and ready for menus, banners and offers.',
    unpublished_h: 'Hidden from the website — you can prepare it in advance.',
    needPublishPerm: 'Publishing requires the “Publish” permission.',
    c_image: 'Image',
    c_summary: 'Summary',
    sum_public: 'Publicly visible',
    sum_total: 'Total in collection',
    sum_type: 'Type',
    c_usage: 'Where it is used',
    usage_none: 'Not used by discounts, offers or menus yet.',
    usage_discount: 'Discount',
    usage_offer: 'Offer',
    usage_menu: 'Menu',
    usage_dynamic: 'Membership is followed dynamically — the discount applies to products that match at the time of the order.',
    usage_static: 'Membership is a saved selection — it applies only to the products listed in the collection.',
    c_seo: 'SEO & URL',
    f_slug: 'URL handle',
    slugAuto: 'Generated automatically from the Albanian title.',
    slugManual: 'Edited manually.',
    slugReset: 'Reset to automatic',
    f_metaTitle: 'Meta title',
    f_metaTitle_h: 'Empty = collection title.',
    f_metaDesc: 'Meta description',
    f_metaDesc_h: 'Empty = collection description.',
    e_title: 'Enter the Albanian (SQ) title.',
    e_slug: 'This address is already taken.',
    e_rules: 'Every condition needs a value.',
    e_noRules: 'Add at least one condition.',
    fixErrors: 'Please check the highlighted fields',
    saved: 'Collection saved',
    created: 'Collection created',
    leaveTitle: 'Leave without saving?',
    leaveText: 'Unsaved changes to this collection will be lost.',
    leave: 'Leave',
    readOnly: 'Read only — your role cannot edit collections.',
    description: 'Group print and packaging products for the catalogue, offers and the homepage — by hand or by rules.',
    col_sort: 'Sort',
    hiddenTitle: '{n} draft or archived — not shown publicly',
    c_preview: 'Product preview',
    c_preview_d: 'Active products that match right now, in storefront order. Prices: lowest unit price, excl. VAT.',
    c_products_d: 'Selected products and their order on the website. Prices: lowest unit price, excl. VAT.',
    dragHint: 'Drag or use the arrows to reorder.',
    sortedBy: 'On the website they are sorted: {sort}.',
    previewOnSite: 'Preview on site',
    shortcutTip: 'Ctrl/⌘ + S saves changes',
    hiddenList: 'Match, but not public',
    createdOn: 'Created {date}',
    image_h: 'Shown in the collection page header and on cards.',
    seo_d: 'How the collection appears in Google search.',
    googlePreview: 'Search preview',
    unpublishedNote: 'Not published — visible only in the CMS and in preview.',
    productsN: '{n} products',
    or: 'or',
    quote: 'On quote',
  },
});

export type CdKey = keyof typeof cd.sq;
