// Strings shared by the CMS orders area: Orders, OrderDetail, Draftet, Kthimet, Invoice.
// Albanian follows the CMS proposal wording (PDF pp.17–18).
import { defineDict } from '@/i18n';

export const od = defineDict({
  sq: {
    pay_pending: 'Në pritje',
    pay_authorized: 'E autorizuar',
    pay_paid: 'E paguar',
    pay_partially_refunded: 'Pjesërisht e rimbursuar',
    pay_refunded: 'E rimbursuar',
    pay_failed: 'Pagesa dështoi',
    ful_unfulfilled: 'E papërmbushur',
    ful_partial: 'Pjesërisht e dërguar',
    ful_fulfilled: 'E dërguar',
    ful_delivered: 'E dorëzuar',
    ret_requested: 'Kërkesë',
    ret_approved: 'E miratuar',
    ret_received: 'Malli i pranuar',
    ret_refunded: 'E rimbursuar',
    ret_rejected: 'E refuzuar',
    draft_open: 'I hapur',
    draft_invoice_sent: 'Fatura e dërguar',
    draft_converted: 'I konvertuar',
    archived: 'E arkivuar',
    cancelled: 'E anuluar',
    channel_online: 'Online Store',
    channel_draft: 'Manuale (draft)',
    carrier_printworks: 'Automjeti i PrintWorks-s',
    carrier_courier: 'Shërbim korrieri',
    carrier_pickup: 'Marrje personale',
    carrier_other: 'Tjetër',
    kind_products: 'Ulje produkti',
    kind_order: 'Ulje porosie',
    kind_bxgy: 'Blej X, merr Y',
    kind_shipping: 'Ulje dërgese',
    auto: 'Automatike',
    code: 'Kod',
    rej_notfound: 'Kodi nuk ekziston',
    rej_inactive: 'Zbritja nuk është aktive (draft ose e pezulluar)',
    rej_scheduled: 'Zbritja ende nuk ka filluar',
    rej_expired: 'Zbritja ka skaduar',
    rej_minimum_amount: 'Pragu nuk arrihet — mungojnë {missing}',
    rej_minimum_qty: 'Pragu nuk arrihet — mungojnë edhe {missing} copë',
    rej_notCombinable: 'Nuk kombinohet me „{other}“ — u ruajt opsioni më i leverdishëm',
    rej_notCombinablePlain: 'Nuk kombinohet me zbritjen e aplikuar',
    rej_notEligible: 'Asnjë artikull nuk i plotëson kushtet',
    rej_usageLimit: 'Kufiri i përdorimeve është arritur',
    rej_audience: 'Klienti nuk është në segmentin e synuar',
    by_web: 'Dyqani online',
    by_admin: 'Ekipi',
    items_one: '{n} artikull',
    items_few: '{n} artikuj',
    items_many: '{n} artikuj',
    orders_one: '{n} porosi',
    orders_few: '{n} porosi',
    orders_many: '{n} porosi',
    selected: '{n} të zgjedhura',
    clearSelection: 'Hiq zgjedhjen',
    noPermission: 'Roli juaj nuk ka leje për këtë veprim',
    country: 'Kosovë',
    files_count: '{ready}/{total} skedarë',
    files_ready: 'Skedarët gati',
    files_hint: '{ready} nga {total} skedarë printimi gati',
    proof_v: 'v{n}',
  },
  en: {
    pay_pending: 'Payment pending',
    pay_authorized: 'Authorized',
    pay_paid: 'Paid',
    pay_partially_refunded: 'Partially refunded',
    pay_refunded: 'Refunded',
    pay_failed: 'Payment failed',
    ful_unfulfilled: 'Unfulfilled',
    ful_partial: 'Partially fulfilled',
    ful_fulfilled: 'Fulfilled',
    ful_delivered: 'Delivered',
    ret_requested: 'Requested',
    ret_approved: 'Approved',
    ret_received: 'Goods received',
    ret_refunded: 'Refunded',
    ret_rejected: 'Rejected',
    draft_open: 'Open',
    draft_invoice_sent: 'Invoice sent',
    draft_converted: 'Converted',
    archived: 'Archived',
    cancelled: 'Cancelled',
    channel_online: 'Online Store',
    channel_draft: 'Manual (draft)',
    carrier_printworks: 'PrintWorks van',
    carrier_courier: 'Courier service',
    carrier_pickup: 'Customer pickup',
    carrier_other: 'Other',
    kind_products: 'Product discount',
    kind_order: 'Order discount',
    kind_bxgy: 'Buy X, get Y',
    kind_shipping: 'Shipping discount',
    auto: 'Automatic',
    code: 'Code',
    rej_notfound: 'Code does not exist',
    rej_inactive: 'Discount is not active (draft or paused)',
    rej_scheduled: 'Discount has not started yet',
    rej_expired: 'Discount has expired',
    rej_minimum_amount: 'Minimum not reached — {missing} missing',
    rej_minimum_qty: 'Minimum not reached — {missing} more item(s) needed',
    rej_notCombinable: 'Does not combine with “{other}” — the better deal was kept',
    rej_notCombinablePlain: 'Does not combine with the applied discount',
    rej_notEligible: 'No item meets the conditions',
    rej_usageLimit: 'Usage limit reached',
    rej_audience: 'Customer is not in the target segment',
    by_web: 'Online shop',
    by_admin: 'Team',
    items_one: '{n} item',
    items_few: '{n} items',
    items_many: '{n} items',
    orders_one: '{n} order',
    orders_few: '{n} orders',
    orders_many: '{n} orders',
    selected: '{n} selected',
    clearSelection: 'Clear selection',
    noPermission: 'Your role is not allowed to do this',
    country: 'Kosovo',
    files_count: '{ready}/{total} files',
    files_ready: 'Files ready',
    files_hint: '{ready} of {total} print files ready',
    proof_v: 'v{n}',
  },
});
