import { defineDict } from '@/i18n';
import type { Lang } from '@/lib/types';
import { money } from '@/lib/format';

/** Strings for the storefront product page (/produkt/:slug) — the print configurator. */
export const PD = defineDict({
  sq: {
    notFoundTitle: 'Produkti nuk u gjet',
    notFoundText: 'Produkti që kërkoni nuk është më në katalog ose lidhja është e pasaktë. Shikoni produktet e ngjashme.',
    browse: 'Shiko katalogun',
    backHome: 'Në ballinë',
    sku: 'Kodi',
    exclVat: 'pa TVSH',
    inclVat: 'me TVSH',
    vatLine: '+ TVSH {rate}% {vat} · me TVSH {gross}',
    vatIncluded: 'TVSH {rate}% e përfshirë',
    step_options: 'Konfigurimi',
    step_qty: 'Sasia',
    step_art: 'Skedari i printimit',
    perPiece: '/ copë',
    unitPrice: 'Çmimi për copë',
    pieces: 'copë',
    total: 'Totali pa TVSH',
    totalGross: 'Totali',
    youSave: 'Kurseni {pct}% për copë krahasuar me tirazhin më të vogël',
    popular: 'Më e zgjedhura',
    customQty: 'Sasi tjetër',
    customQtyLabel: 'Sasia me porosi',
    qtyRule: 'Min. {min} copë · hapi {step}',
    qtyMin: 'Sasia minimale është {n} copë — e vendosëm në minimum.',
    qtySnapped: 'U rrumbullakua në {n} copë (porositet me hapa prej {step}).',
    qtyMaxStock: 'Në stok janë {n} — sasia u kufizua.',
    tiersTitle: 'Çmimet sipas sasisë',
    tierQty: 'Sasia',
    tierUnit: 'Çmimi / copë',
    tierTotal: 'Totali',
    tierSave: 'Kursimi',
    showTable: 'Tabela e plotë e çmimeve',
    tableNote: 'Çmimet janë pa TVSH, për konfigurimin e zgjedhur. Sasitë ndërmjet shkallëve marrin çmimin e shkallës më të afërt poshtë tyre.',
    tableSelect: 'Zgjidh',
    art_upload: 'Ngarko skedarin tani',
    art_uploadText: 'PDF, AI, EPS, SVG, PNG, JPG ose TIF — e kontrollojmë falas.',
    art_later: 'Dërgoj skedarin më vonë',
    art_laterText: 'Pas porosisë ju dërgojmë me e-mail lidhjen për ngarkim.',
    art_design: 'Dizajn profesional',
    art_designText: 'Dizajnerët tanë e përgatitin sipas markës suaj, me provë digjitale.',
    drop: 'Tërhiqni skedarin këtu',
    dropOr: 'ose',
    dropBrowse: 'zgjidhni nga kompjuteri',
    dropTypes: 'PDF/X · AI · EPS · SVG · PNG · JPG · TIF — deri në 500 MB',
    dropActive: 'Lëshojeni skedarin këtu',
    fileReplace: 'Ndrysho',
    fileRemove: 'Hiq skedarin',
    fileReading: 'Duke lexuar skedarin…',
    fileBadType: 'Formati „.{ext}“ nuk pranohet — përdorni PDF, AI, EPS, SVG, PNG, JPG ose TIF.',
    fileTooBig: 'Skedari kalon 500 MB — zgjidhni „Dërgoj më vonë“ dhe na e dërgoni me lidhje.',
    fileReady: 'Gati për kontrollin prepress',
    noteLabel: 'Shënim për prepress',
    optional: 'opsionale',
    notePh: 'P.sh. ngjyra e markës Pantone 2593 C, teksti në anën e pasme ndryshon sipas shijes…',
    needFile: 'Ngarkoni skedarin ose zgjidhni „Dërgoj më vonë“.',
    proofFree: 'Kontrolli prepress dhe prova digjitale janë falas.',
    designFee: 'Dizajn & prepress',
    perLine: 'tarifë e njëhershme',
    addToCart: 'Shto në shportë',
    addedShort: 'U shtua në shportë',
    added: 'U shtua në shportë',
    viewCart: 'Shiko shportën',
    wishAdd: 'Ruaje te të preferuarat',
    wishRemove: 'Hiqe nga të preferuarat',
    wishAdded: 'U ruajt te të preferuarat',
    wishRemoved: 'U hoq nga të preferuarat',
    share: 'Ndaj',
    linkCopied: 'Lidhja u kopjua',
    readyBy: 'Gati për dërgesë rreth {date}',
    readyByNote: '{days} ditë pune pas aprovimit të provës',
    shipsBy: 'Dërgohet brenda 24 orësh',
    inStock: 'Në stok',
    lowStock: 'Vetëm {n} në stok',
    quantity: 'Sasia',
    trust_proof: 'Provë digjitale falas',
    trust_proofText: 'Brenda 24 orësh, para prodhimit',
    trust_quality: 'Kontroll cilësie',
    trust_qualityText: 'Çdo tirazh kontrollohet para paketimit',
    trust_delivery: 'Transport falas nga {amount}',
    trust_deliveryText: 'Në Kosovë 1–2 ditë pas prodhimit',
    trust_pay: 'Pagesë me faturë',
    trust_payText: 'Pro-formë, kartelë ose në dorëzim',
    help: 'Pyetje për materialin apo skedarin?',
    helpText: 'Flisni drejtpërdrejt me prepress-in',
    quoteOnly: 'Çmim sipas projektit',
    quoteIndicative: 'Orientues: nga {price} / copë · min. {n} copë',
    quoteLead: 'Çdo projekt përgatitet sipas përmasave, materialit dhe finishing-ut tuaj. Na dërgoni detajet — oferta e saktë vjen brenda 24 orësh, pa detyrim.',
    quoteStep1: 'Ju na dërgoni specifikimet',
    quoteStep2: 'Ofertë e saktë brenda 24 orësh',
    quoteStep3: 'Mostër / provë, pastaj prodhim',
    rfq_title: 'Kërkesë e shpejtë për ofertë',
    requestQuote: 'Kërko ofertë',
    rfq_qty: 'Sasia (copë)',
    rfq_name: 'Emri dhe mbiemri',
    rfq_company: 'Kompania',
    rfq_email: 'E-mail',
    rfq_phone: 'Telefoni',
    rfq_msg: 'Përmasat, materiali, finishing-u',
    rfq_msgDefault: 'Përshëndetje, më intereson oferta për „{name}“.',
    rfq_send: 'Dërgo kërkesën',
    rfq_detailed: 'Kërkesë e detajuar me skedarë',
    rfq_okTitle: 'Faleminderit, {name}!',
    rfq_okText: 'Kërkesa për „{product}“ u pranua. Ju përgjigjemi brenda 24 orësh në {email}.',
    rfq_new: 'Kërkesë tjetër',
    rfq_required: 'Fushë e detyrueshme',
    rfq_email_bad: 'Shkruani një e-mail të saktë',
    rfq_phone_bad: 'Shkruani një numër telefoni të saktë',
    rfq_privacy: 'Të dhënat përdoren vetëm për t’ju dërguar ofertën.',
    tab_desc: 'Përshkrimi',
    tab_specs: 'Specifikimet',
    tab_prices: 'Çmimet',
    tab_artwork: 'Skedarët e printimit',
    tab_delivery: 'Prodhimi & dorëzimi',
    tab_faq: 'Pyetje',
    highlights: 'Shkurt',
    spec_sku: 'Kodi i produktit',
    spec_lead: 'Afati i prodhimit',
    spec_moq: 'Sasia minimale',
    spec_step: 'Hapi i sasisë',
    spec_unit: 'Njësia e shitjes',
    spec_category: 'Kategoria',
    spec_design: 'Dizajn profesional',
    spec_proof: 'Prova',
    spec_proofValue: 'Provë digjitale PDF brenda 24 orësh',
    unit_kom: 'Copë',
    unit_set: 'Set',
    daysValue: '{days} ditë pune',
    daysAfterProof: '~{n} ditë pune pas aprovimit të provës',
    pcsValue: '{n} copë',
    guideEyebrow: 'Për dizajnerët',
    guideTitle: 'Si ta përgatitni *skedarin*',
    guideIntro: 'Me këto gjashtë rregulla skedari kalon kontrollin prepress pa vonesë. Nëse diçka mungon, ju kontaktojmë para prodhimit — asgjë nuk printohet pa aprovimin tuaj.',
    g_bleed: 'Bleed 3 mm',
    g_bleedText: 'Zgjatni sfondin dhe fotot 3 mm jashtë vijës së prerjes në çdo anë.',
    g_safe: 'Zona e sigurt 3 mm',
    g_safeText: 'Tekstet dhe logot të paktën 3 mm brenda vijës së prerjes.',
    g_cmyk: 'CMYK ose Pantone',
    g_cmykText: 'Konvertoni në CMYK (FOGRA39); ngjyrat e markës si Pantone të emërtuara.',
    g_dpi: '300 dpi',
    g_dpiText: 'Fotot dhe imazhet raster në 300 dpi, në madhësinë reale të printimit.',
    g_fonts: 'Fontet në vija',
    g_fontsText: 'Konvertoni fontet në vija (outlines) ose përfshijini të plota në PDF.',
    g_pdfx: 'PDF/X-1a ose PDF/X-4',
    g_pdfxText: 'Eksportoni me bleed dhe shenja prerjeje; një faqe për çdo pamje.',
    dieline: 'Matricën (dieline) e kutisë jua dërgojmë në PDF pas porosisë — ose kërkojeni paraprakisht në {email}.',
    guideLink: 'Udhëzuesi i plotë për skedarët',
    deliveryLink: 'Transporti dhe afatet',
    d_trim: 'Vija e prerjes',
    d_bleed: 'Bleed 3 mm',
    d_safe: 'Zona e sigurt',
    zonesTitle: 'Zonat e dërgesës',
    zone: 'Zona',
    fee: 'Tarifa',
    days: 'Afati',
    freeOver: 'Transport falas për porosi nga {amount}',
    freeOverText: 'Nën këtë shumë paguani vetëm tarifën e zonës. Mallin e dorëzojmë në kuti ose paleta, të etiketuara sipas porosisë.',
    pickup: 'Marrje në fabrikë',
    pickupText: '{address} — pa kosto transporti.',
    processTitle: 'Nga porosia te *dorëzimi*',
    p1: 'Kontrolli prepress & prova digjitale',
    p1w: 'brenda 24 orësh',
    p2: 'Ju e aprovoni provën',
    p2w: 'me një klik',
    p3: 'Prodhimi',
    p3w: '~{n} ditë pune',
    p4: 'Dorëzimi',
    p4w: '1–2 ditë në Kosovë',
    faq1q: 'Çfarë ndodh nëse skedari im ka gabime?',
    faq1a: 'Ekipi ynë i prepress kontrollon çdo skedar falas — rezolucionin, bleed-in, ngjyrat dhe fontet. Nëse diçka mungon, ju kontaktojmë para prodhimit. Asgjë nuk printohet pa aprovimin tuaj të provës.',
    faq2q: 'A mund të porosis një sasi ndërmjet shkallëve të çmimit?',
    faq2a: 'Po. Çdo sasi mbi minimumin prej {min} copë, me hapa prej {step}, merr çmimin e shkallës më të afërt poshtë saj — sa më i madh tirazhi, aq më i ulët çmimi për copë.',
    faq3q: 'Sa zgjat prodhimi?',
    faq3a: 'Rreth {days} ditë pune pas aprovimit të provës digjitale, plus 1–2 ditë dërgesë në Kosovë. Për afate urgjente na telefononi — shpesh gjejmë vend në planin e makinave.',
    faq4q: 'A mund të shoh materialet para porosisë?',
    faq4a: 'Po — paketa jonë e mostrave (19 €) përmban mbi 30 kartona, etiketa dhe finishing-e. Shuma ju kthehet si zbritje në porosinë e parë mbi 250 €.',
    faq5q: 'Si paguhet porosia?',
    faq5a: 'Me transfertë bankare sipas pro-formës, me kartelë ose në dorëzim. Fatura lëshohet në emër të kompanisë suaj, me TVSH 18% të ndarë.',
    faq6q: 'A e ruani dizajnin për ribotim?',
    faq6a: 'Po. Skedarët e aprovuar dhe matricat ruhen në arkivin tonë, kështu që ribotimi nuk kërkon prepress të ri.',
    relatedEyebrow: 'Nga e njëjta kategori',
    relatedTitle: 'Shpesh porositen *bashkë*',
    recentEyebrow: 'Historiku juaj',
    recentTitle: 'Shikuar *së fundmi*',
    seeCategory: 'Gjithë kategoria',
    zoom: 'Zmadho foton',
    prev: 'E mëparshmja',
    next: 'Tjetra',
    close: 'Mbyll',
    selected: 'Zgjedhur',
  },
  en: {
    notFoundTitle: 'Product not found',
    notFoundText: 'The product you’re looking for is no longer in the catalogue or the link is broken. Have a look at similar products.',
    browse: 'Browse the catalogue',
    backHome: 'Back to home',
    sku: 'SKU',
    exclVat: 'excl. VAT',
    inclVat: 'incl. VAT',
    vatLine: '+ VAT {rate}% {vat} · incl. VAT {gross}',
    vatIncluded: 'VAT {rate}% included',
    step_options: 'Configuration',
    step_qty: 'Quantity',
    step_art: 'Print file',
    perPiece: '/ pc',
    unitPrice: 'Price per piece',
    pieces: 'pcs',
    total: 'Total excl. VAT',
    totalGross: 'Total',
    youSave: 'You save {pct}% per piece vs. the smallest run',
    popular: 'Most chosen',
    customQty: 'Other quantity',
    customQtyLabel: 'Custom quantity',
    qtyRule: 'Min. {min} pcs · step {step}',
    qtyMin: 'The minimum order is {n} pcs — we set it to the minimum.',
    qtySnapped: 'Rounded to {n} pcs (ordered in steps of {step}).',
    qtyMaxStock: '{n} in stock — quantity limited.',
    tiersTitle: 'Quantity pricing',
    tierQty: 'Quantity',
    tierUnit: 'Price / pc',
    tierTotal: 'Total',
    tierSave: 'Saving',
    showTable: 'Full price table',
    tableNote: 'Prices exclude VAT and reflect the selected configuration. Quantities between breaks get the price of the nearest break below.',
    tableSelect: 'Select',
    art_upload: 'Upload the file now',
    art_uploadText: 'PDF, AI, EPS, SVG, PNG, JPG or TIF — checked for free.',
    art_later: 'Send the file later',
    art_laterText: 'After ordering we e-mail you a link to upload it.',
    art_design: 'Professional design',
    art_designText: 'Our designers prepare it in your brand style, with a digital proof.',
    drop: 'Drag your file here',
    dropOr: 'or',
    dropBrowse: 'browse your computer',
    dropTypes: 'PDF/X · AI · EPS · SVG · PNG · JPG · TIF — up to 500 MB',
    dropActive: 'Drop the file here',
    fileReplace: 'Replace',
    fileRemove: 'Remove file',
    fileReading: 'Reading the file…',
    fileBadType: '“.{ext}” files aren’t accepted — use PDF, AI, EPS, SVG, PNG, JPG or TIF.',
    fileTooBig: 'The file is over 500 MB — choose “Send later” and share it with a link.',
    fileReady: 'Ready for the prepress check',
    noteLabel: 'Note for prepress',
    optional: 'optional',
    notePh: 'E.g. brand colour Pantone 2593 C, the back text changes per flavour…',
    needFile: 'Upload your file or choose “Send the file later”.',
    proofFree: 'The prepress check and digital proof are free.',
    designFee: 'Design & prepress',
    perLine: 'one-off fee',
    addToCart: 'Add to cart',
    addedShort: 'Added to cart',
    added: 'Added to cart',
    viewCart: 'View cart',
    wishAdd: 'Save to wishlist',
    wishRemove: 'Remove from wishlist',
    wishAdded: 'Saved to your wishlist',
    wishRemoved: 'Removed from your wishlist',
    share: 'Share',
    linkCopied: 'Link copied',
    readyBy: 'Ready to ship around {date}',
    readyByNote: '{days} working days after proof approval',
    shipsBy: 'Ships within 24 hours',
    inStock: 'In stock',
    lowStock: 'Only {n} left in stock',
    quantity: 'Quantity',
    trust_proof: 'Free digital proof',
    trust_proofText: 'Within 24 hours, before production',
    trust_quality: 'Quality control',
    trust_qualityText: 'Every run is checked before packing',
    trust_delivery: 'Free delivery from {amount}',
    trust_deliveryText: 'Kosovo, 1–2 days after production',
    trust_pay: 'Pay by invoice',
    trust_payText: 'Pro-forma, card or cash on delivery',
    help: 'Questions about materials or files?',
    helpText: 'Talk straight to prepress',
    quoteOnly: 'Priced per project',
    quoteIndicative: 'Indicative: from {price} / pc · min. {n} pcs',
    quoteLead: 'Every project is built around your size, material and finish. Send us the details — an exact quote follows within 24 hours, no obligation.',
    quoteStep1: 'You send us the specs',
    quoteStep2: 'Exact quote within 24 hours',
    quoteStep3: 'Sample / proof, then production',
    rfq_title: 'Quick quote request',
    requestQuote: 'Request a quote',
    rfq_qty: 'Quantity (pcs)',
    rfq_name: 'Full name',
    rfq_company: 'Company',
    rfq_email: 'E-mail',
    rfq_phone: 'Phone',
    rfq_msg: 'Size, material, finish',
    rfq_msgDefault: 'Hello, I’d like a quote for “{name}”.',
    rfq_send: 'Send request',
    rfq_detailed: 'Detailed request with files',
    rfq_okTitle: 'Thank you, {name}!',
    rfq_okText: 'Your request for “{product}” is in. We’ll reply within 24 hours at {email}.',
    rfq_new: 'Another request',
    rfq_required: 'Required',
    rfq_email_bad: 'Enter a valid e-mail',
    rfq_phone_bad: 'Enter a valid phone number',
    rfq_privacy: 'Your details are used only to send you the quote.',
    tab_desc: 'Description',
    tab_specs: 'Specifications',
    tab_prices: 'Pricing',
    tab_artwork: 'Print files',
    tab_delivery: 'Production & delivery',
    tab_faq: 'FAQ',
    highlights: 'At a glance',
    spec_sku: 'Product code',
    spec_lead: 'Production time',
    spec_moq: 'Minimum order',
    spec_step: 'Quantity step',
    spec_unit: 'Sold per',
    spec_category: 'Category',
    spec_design: 'Professional design',
    spec_proof: 'Proof',
    spec_proofValue: 'Digital PDF proof within 24 hours',
    unit_kom: 'Piece',
    unit_set: 'Set',
    daysValue: '{days} working days',
    daysAfterProof: '~{n} working days after proof approval',
    pcsValue: '{n} pcs',
    guideEyebrow: 'For designers',
    guideTitle: 'How to prepare your *file*',
    guideIntro: 'Follow these six rules and your file sails through prepress. If anything is missing we contact you before production — nothing is printed without your proof approval.',
    g_bleed: '3 mm bleed',
    g_bleedText: 'Extend backgrounds and images 3 mm past the trim line on every side.',
    g_safe: '3 mm safe zone',
    g_safeText: 'Keep text and logos at least 3 mm inside the trim line.',
    g_cmyk: 'CMYK or Pantone',
    g_cmykText: 'Convert to CMYK (FOGRA39); brand colours as named Pantone spots.',
    g_dpi: '300 dpi',
    g_dpiText: 'Photos and raster images at 300 dpi, at the actual print size.',
    g_fonts: 'Outlined fonts',
    g_fontsText: 'Convert fonts to outlines or embed them fully in the PDF.',
    g_pdfx: 'PDF/X-1a or PDF/X-4',
    g_pdfxText: 'Export with bleed and crop marks; one page per view.',
    dieline: 'We send the box dieline as a PDF after you order — or ask for it in advance at {email}.',
    guideLink: 'Full file preparation guide',
    deliveryLink: 'Delivery & lead times',
    d_trim: 'Trim line',
    d_bleed: '3 mm bleed',
    d_safe: 'Safe zone',
    zonesTitle: 'Delivery zones',
    zone: 'Zone',
    fee: 'Fee',
    days: 'Time',
    freeOver: 'Free delivery on orders from {amount}',
    freeOverText: 'Below that you only pay the zone fee. Goods are delivered in boxes or on pallets, labelled per order.',
    pickup: 'Pickup at the factory',
    pickupText: '{address} — no delivery charge.',
    processTitle: 'From order to *delivery*',
    p1: 'Prepress check & digital proof',
    p1w: 'within 24 hours',
    p2: 'You approve the proof',
    p2w: 'in one click',
    p3: 'Production',
    p3w: '~{n} working days',
    p4: 'Delivery',
    p4w: '1–2 days in Kosovo',
    faq1q: 'What if my file has mistakes?',
    faq1a: 'Our prepress team checks every file for free — resolution, bleed, colours and fonts. If something is missing we contact you before production. Nothing is printed without your proof approval.',
    faq2q: 'Can I order a quantity between the price breaks?',
    faq2a: 'Yes. Any quantity above the {min} pcs minimum, in steps of {step}, gets the price of the nearest break below it — the bigger the run, the lower the price per piece.',
    faq3q: 'How long does production take?',
    faq3a: 'About {days} working days after you approve the digital proof, plus 1–2 days delivery in Kosovo. For rush jobs give us a call — we can often fit you into the press schedule.',
    faq4q: 'Can I see the materials before ordering?',
    faq4a: 'Yes — our sample kit (€19) holds 30+ boards, labels and finishes. The amount comes back as a discount on your first order over €250.',
    faq5q: 'How do I pay?',
    faq5a: 'By bank transfer against a pro-forma invoice, by card or cash on delivery. Invoices are issued to your company with 18% VAT shown separately.',
    faq6q: 'Do you keep my artwork for reprints?',
    faq6a: 'Yes. Approved files and dies are archived, so a reprint needs no new prepress.',
    relatedEyebrow: 'From the same category',
    relatedTitle: 'Often ordered *together*',
    recentEyebrow: 'Your history',
    recentTitle: 'Recently *viewed*',
    seeCategory: 'Whole category',
    zoom: 'Enlarge image',
    prev: 'Previous',
    next: 'Next',
    close: 'Close',
    selected: 'Selected',
  },
});

export type PDKey = keyof (typeof PD)['sq'];

/** Money with cents only when needed ("289 €", "241,98 €"); `target` keeps the format stable while a tween runs. */
export function eur(v: number, lang: Lang, target = v) {
  return money(v, lang, { decimals: Math.round(target * 100) % 100 !== 0 });
}
