import { defineDict } from '@/i18n';

/** Request-for-quote wizard (/kerko-oferte). */
export const QT = defineDict({
  sq: {
    pageTitle: 'Kërko ofertë',
    eyebrow: 'Paketim me porosi',
    title: 'Kërkoni *ofertë* për projektin tuaj',
    subtitle: 'Kuti, paketime ushqimore, etiketa, shrink sleeve, qese apo materiale promovuese sipas përmasave tuaja. Pesë hapa të shkurtër — oferta e saktë vjen brenda 24 orësh.',
    promise1: 'Ofertë brenda 24 orësh',
    promise2: 'Provë digjitale falas',
    promise3: 'Mostër fizike sipas kërkesës',
    forProduct: 'Kërkesë për',
    change: 'Ndrysho',
    step1: 'Produkti',
    step2: 'Specifikimet',
    step3: 'Skedarët',
    step4: 'Kontakti',
    step5: 'Përmbledhja',
    stepOf: 'Hapi {n} nga {total}',
    next: 'Vazhdo',
    back: 'Kthehu',
    send: 'Dërgo kërkesën',
    edit: 'Ndrysho',
    q1: 'Çfarë dëshironi të prodhojmë?',
    q1d: 'Zgjidhni llojin më të afërt — detajet i saktësojmë bashkë.',
    k_box: 'Kuti produktesh',
    k_boxD: 'Kuti kartoni të palosshme, mailer, kuti dhuratash',
    k_food: 'Paketim ushqimor',
    k_foodD: 'Pica, takeaway, ëmbëlsira, gota dhe mbajtëse',
    k_label: 'Etiketa',
    k_labelD: 'Vetëngjitëse në rrotull ose fletë, letër ose PP',
    k_sleeve: 'Shrink sleeve',
    k_sleeveD: 'Etiketa 360° që tkurren mbi shishe dhe kanaçe',
    k_bag: 'Qese letre',
    k_bagD: 'Kraft, art letër, me dorezë litari ose shiriti',
    k_print: 'Materiale promovuese',
    k_printD: 'Katalogë, fletëpalosje, kartëvizita, POS',
    k_other: 'Diçka tjetër',
    k_otherD: 'Finishing, libra, revista ose ide e re',
    q2: 'Specifikimet',
    q2d: 'Plotësoni çfarë dini — fushat bosh i plotësojmë me rekomandimin tonë.',
    size: 'Përmasat (mm)',
    sizeBox: 'Gjatësia × Gjerësia × Lartësia',
    sizeFlat: 'Gjerësia × Lartësia',
    sizeFree: 'Formati ose përmasat',
    sizeFreePh: 'p.sh. A5, 85 × 55 mm, 210 × 297 mm',
    len: 'Gjatësia',
    wid: 'Gjerësia',
    hei: 'Lartësia',
    material: 'Materiali',
    materialAdvise: 'Nuk e di — më këshilloni',
    quantity: 'Sasia (copë)',
    quantityErr: 'Shkruani sasinë',
    colours: 'Ngjyrat e printimit',
    c_cmyk: 'CMYK (4 ngjyra)',
    c_cmykPantone: 'CMYK + Pantone',
    c_pantone: 'Vetëm Pantone',
    c_none: 'Pa printim',
    pantoneCodes: 'Kodet Pantone',
    pantonePh: 'p.sh. 2593 C, 7427 C',
    finishes: 'Finishing',
    finishesHint: 'Zgjidhni sa të doni.',
    f_matte: 'Laminim mat',
    f_gloss: 'Laminim me shkëlqim',
    f_softtouch: 'Soft-touch',
    f_spotuv: 'Llak UV selektiv',
    f_foil: 'Stampim me folje',
    f_emboss: 'Reliev',
    f_window: 'Dritare (PET)',
    deadline: 'Afati i dorëzimit',
    deadlineFlexible: 'Afati është fleksibël',
    q3: 'Skedarët dhe referencat',
    q3d: 'Dizajn, logo, matricë ekzistuese ose foto e produktit — çdo gjë që na ndihmon. Opsionale.',
    filesDrop: 'Tërhiqni skedarët këtu',
    filesOr: 'ose',
    filesBrowse: 'zgjidhni nga kompjuteri',
    filesTypes: 'PDF · AI · EPS · SVG · PNG · JPG · TIF · ZIP — deri në 10 skedarë',
    filesNone: 'Ende pa skedarë — nuk ka problem.',
    needDesign: 'Kam nevojë për ndihmë me dizajnin',
    needDesignD: 'Dizajnerët tanë përgatisin propozim sipas markës suaj.',
    needSample: 'Dëshiroj mostër fizike para prodhimit',
    needSampleD: 'Mostër e bardhë ose e printuar digjitalisht, për të provuar formën.',
    fileBad: 'Formati „.{ext}“ nuk pranohet.',
    q4: 'Ku t’jua dërgojmë ofertën?',
    q4d: 'Ju përgjigjemi brenda 24 orësh, në ditë pune.',
    company: 'Kompania',
    name: 'Emri dhe mbiemri',
    email: 'E-mail',
    phone: 'Telefoni',
    city: 'Qyteti',
    message: 'Mesazh shtesë',
    messagePh: 'P.sh. përdorimi i paketimit, linja automatike e mbushjes, referenca nga një produkt ekzistues…',
    required: 'Fushë e detyrueshme',
    emailBad: 'Shkruani një e-mail të saktë',
    phoneBad: 'Shkruani një numër telefoni të saktë',
    q5: 'Kontrolloni kërkesën',
    q5d: 'Gjithçka në rregull? Mund ta ndryshoni çdo hap para se ta dërgoni.',
    r_product: 'Produkti',
    r_specs: 'Specifikimet',
    r_files: 'Skedarët',
    r_contact: 'Kontakti',
    filesCount: '{n} skedarë',
    filesCountOne: '1 skedar',
    privacy: 'Duke dërguar, pranoni që të dhënat të përdoren vetëm për përgatitjen e ofertës.',
    sideTitle: 'Kërkesa juaj',
    sideEmpty: 'Zgjedhjet tuaja shfaqen këtu.',
    sideCall: 'Preferoni ta diskutoni?',
    sideCallText: 'Flisni drejtpërdrejt me ekipin e shitjes.',
    pcs: '{n} copë',
    okEyebrow: 'Kërkesa u dërgua',
    okTitle: 'Faleminderit, *{name}*!',
    okText: 'Kërkesa juaj për {kind} është te ekipi ynë. Do t’ju dërgojmë ofertën e saktë në {email} brenda 24 orësh — shpesh edhe më shpejt.',
    okRef: 'Referenca',
    okNext1: 'Ekspertët tanë e analizojnë kërkesën',
    okNext2: 'Ofertë me çmime sipas sasisë brenda 24 orësh',
    okNext3: 'Mostër / provë digjitale para prodhimit',
    okShop: 'Shiko produktet standarde',
    okNew: 'Kërkesë e re',
    okHome: 'Ballina',
    msgDesign: 'Kërkon ndihmë me dizajnin.',
    msgSample: 'Dëshiron mostër fizike para prodhimit.',
    msgPantone: 'Pantone: {codes}.',
    msgFlexible: 'Afati fleksibël.',
    msgDefault: 'Kërkesë për ofertë: {kind}.',
  },
  en: {
    pageTitle: 'Request a quote',
    eyebrow: 'Custom packaging',
    title: 'Request a *quote* for your project',
    subtitle: 'Boxes, food packaging, labels, shrink sleeves, bags or promotional print made to your size. Five short steps — an exact quote follows within 24 hours.',
    promise1: 'Quote within 24 hours',
    promise2: 'Free digital proof',
    promise3: 'Physical sample on request',
    forProduct: 'Request for',
    change: 'Change',
    step1: 'Product',
    step2: 'Specs',
    step3: 'Files',
    step4: 'Contact',
    step5: 'Review',
    stepOf: 'Step {n} of {total}',
    next: 'Continue',
    back: 'Back',
    send: 'Send request',
    edit: 'Edit',
    q1: 'What would you like us to make?',
    q1d: 'Pick the closest type — we’ll refine the details together.',
    k_box: 'Product boxes',
    k_boxD: 'Folding cartons, mailers, gift boxes',
    k_food: 'Food packaging',
    k_foodD: 'Pizza, takeaway, pastry, cups and holders',
    k_label: 'Labels',
    k_labelD: 'Self-adhesive on rolls or sheets, paper or PP',
    k_sleeve: 'Shrink sleeves',
    k_sleeveD: '360° labels shrunk onto bottles and cans',
    k_bag: 'Paper bags',
    k_bagD: 'Kraft, art paper, rope or ribbon handles',
    k_print: 'Promotional print',
    k_printD: 'Catalogues, leaflets, business cards, POS',
    k_other: 'Something else',
    k_otherD: 'Finishing, books, magazines or a new idea',
    q2: 'Specifications',
    q2d: 'Fill in what you know — we’ll suggest the rest.',
    size: 'Dimensions (mm)',
    sizeBox: 'Length × Width × Height',
    sizeFlat: 'Width × Height',
    sizeFree: 'Format or dimensions',
    sizeFreePh: 'e.g. A5, 85 × 55 mm, 210 × 297 mm',
    len: 'Length',
    wid: 'Width',
    hei: 'Height',
    material: 'Material',
    materialAdvise: 'Not sure — please advise',
    quantity: 'Quantity (pcs)',
    quantityErr: 'Enter a quantity',
    colours: 'Print colours',
    c_cmyk: 'CMYK (4 colours)',
    c_cmykPantone: 'CMYK + Pantone',
    c_pantone: 'Pantone only',
    c_none: 'Unprinted',
    pantoneCodes: 'Pantone codes',
    pantonePh: 'e.g. 2593 C, 7427 C',
    finishes: 'Finishes',
    finishesHint: 'Pick as many as you like.',
    f_matte: 'Matte lamination',
    f_gloss: 'Gloss lamination',
    f_softtouch: 'Soft-touch',
    f_spotuv: 'Spot UV',
    f_foil: 'Hot foil',
    f_emboss: 'Embossing',
    f_window: 'Window (PET)',
    deadline: 'Delivery deadline',
    deadlineFlexible: 'The deadline is flexible',
    q3: 'Files and references',
    q3d: 'Artwork, logo, an existing dieline or a product photo — anything that helps. Optional.',
    filesDrop: 'Drag your files here',
    filesOr: 'or',
    filesBrowse: 'browse your computer',
    filesTypes: 'PDF · AI · EPS · SVG · PNG · JPG · TIF · ZIP — up to 10 files',
    filesNone: 'No files yet — that’s fine.',
    needDesign: 'I need help with the design',
    needDesignD: 'Our designers prepare a proposal in your brand style.',
    needSample: 'I’d like a physical sample before production',
    needSampleD: 'A blank or digitally printed mock-up to test the shape.',
    fileBad: '“.{ext}” files aren’t accepted.',
    q4: 'Where should we send the quote?',
    q4d: 'We reply within 24 hours on working days.',
    company: 'Company',
    name: 'Full name',
    email: 'E-mail',
    phone: 'Phone',
    city: 'City',
    message: 'Anything else',
    messagePh: 'E.g. how the packaging is used, automatic filling line, reference from an existing product…',
    required: 'Required',
    emailBad: 'Enter a valid e-mail',
    phoneBad: 'Enter a valid phone number',
    q5: 'Check your request',
    q5d: 'All good? You can edit any step before sending.',
    r_product: 'Product',
    r_specs: 'Specifications',
    r_files: 'Files',
    r_contact: 'Contact',
    filesCount: '{n} files',
    filesCountOne: '1 file',
    privacy: 'By sending you agree that your details are used only to prepare the quote.',
    sideTitle: 'Your request',
    sideEmpty: 'Your choices appear here.',
    sideCall: 'Prefer to talk it through?',
    sideCallText: 'Speak directly to our sales team.',
    pcs: '{n} pcs',
    okEyebrow: 'Request sent',
    okTitle: 'Thank you, *{name}*!',
    okText: 'Your request for {kind} is with our team. We’ll send an exact quote to {email} within 24 hours — often sooner.',
    okRef: 'Reference',
    okNext1: 'Our specialists review your request',
    okNext2: 'Quote with quantity pricing within 24 hours',
    okNext3: 'Sample / digital proof before production',
    okShop: 'Browse standard products',
    okNew: 'New request',
    okHome: 'Home',
    msgDesign: 'Needs help with the design.',
    msgSample: 'Would like a physical sample before production.',
    msgPantone: 'Pantone: {codes}.',
    msgFlexible: 'Flexible deadline.',
    msgDefault: 'Quote request: {kind}.',
  },
});

export type QTKey = keyof (typeof QT)['sq'];
