import { defineDict } from '@/i18n';

/** Strings shared by the storefront content pages (blog, post, CMS page, contact). */
export const C = defineDict({
  sq: {
    minRead: '{n} min lexim',
    read: 'Lexo',
    readArticle: 'Lexo artikullin',
    latest: 'Më i riu',
    share: 'Shpërndaj',
    shareArticle: 'Shpërndajeni artikullin',
    copyLink: 'Kopjo linkun',
    copied: 'Linku u kopjua',
    copiedText: 'Dërgojani një kolegu ose ruajeni për më vonë.',
    copyFailed: 'Kopjimi dështoi — kopjoni adresën nga shfletuesi.',
    home: 'Ballina',
    team: 'Ekipi PrintWorks',
    cta_eyebrow: 'Nga ideja te paketimi',
    cta_title: 'Keni një produkt që meriton *paketim më të mirë*?',
    cta_text: 'Na dërgoni përmasat, sasinë dhe afatin. Ekipi ynë i prepress-it ju kthen ofertën brenda 24 orësh — me provë digjitale para çdo shtypi.',
    cta_b1: 'Ofertë brenda 24 orësh',
    cta_b2: 'Provë digjitale para shtypit',
    cta_b3: 'Paketë mostrash për €19',
    cta_button: 'Kërko ofertë',
    cta_products: 'Shiko produktet',
    map_eyebrow: 'Fabrika & zyrat',
    map_open: 'Hape në hartë',
    map_area: 'Zona e fabrikës',
    map_note: 'Adresën e saktë dhe udhëzimet jua dërgojmë me konfirmimin e takimit.',
  },
  en: {
    minRead: '{n} min read',
    read: 'Read',
    readArticle: 'Read article',
    latest: 'Latest',
    share: 'Share',
    shareArticle: 'Share this article',
    copyLink: 'Copy link',
    copied: 'Link copied',
    copiedText: 'Send it to a colleague or save it for later.',
    copyFailed: 'Couldn’t copy — please copy the address from your browser.',
    home: 'Home',
    team: 'PrintWorks team',
    cta_eyebrow: 'From idea to packaging',
    cta_title: 'Got a product that deserves *better packaging*?',
    cta_text: 'Send us the dimensions, quantity and deadline. Our prepress team comes back with a quote within 24 hours — with a digital proof before anything is printed.',
    cta_b1: 'Quote within 24 hours',
    cta_b2: 'Digital proof before print',
    cta_b3: 'Sample kit for €19',
    cta_button: 'Request a quote',
    cta_products: 'Browse products',
    map_eyebrow: 'Factory & offices',
    map_open: 'Open map',
    map_area: 'Factory area',
    map_note: 'We send the exact address and directions with your meeting confirmation.',
  },
});
