// Strings shared by the CMS orders area: Orders, OrderDetail, Draftet, Kthimet, Invoice.
// Albanian follows the CMS proposal wording (PDF pp.17–18).
import { defineDict } from '@/i18n';

export const od = defineDict({
  me: {
    // payment states (lib/orders.ts paymentOf)
    pay_pending: 'Čeka uplatu',
    pay_authorized: 'Autorizovano',
    pay_paid: 'Plaćeno',
    pay_partially_refunded: 'Djelimično refundirano',
    pay_refunded: 'Refundirano',
    pay_failed: 'Neuspjelo plaćanje',
    // fulfilment states
    ful_unfulfilled: 'Nije poslato',
    ful_partial: 'Djelimično poslato',
    ful_fulfilled: 'Poslato',
    ful_delivered: 'Isporučeno',
    // returns
    ret_requested: 'Zahtjev',
    ret_approved: 'Odobren',
    ret_received: 'Roba primljena',
    ret_refunded: 'Refundiran',
    ret_rejected: 'Odbijen',
    // drafts
    draft_open: 'Otvoren',
    draft_invoice_sent: 'Predračun poslat',
    draft_converted: 'Konvertovan',
    // lifecycle
    archived: 'Arhivirana',
    cancelled: 'Otkazana',
    channel_online: 'Online prodavnica',
    channel_draft: 'Ručna (nacrt)',
    // carriers
    carrier_selca: 'SELCA vozilo',
    carrier_courier: 'Kurirska služba',
    carrier_pickup: 'Lično preuzimanje',
    carrier_other: 'Drugo',
    // discount kinds
    kind_products: 'Popust na proizvode',
    kind_order: 'Popust na narudžbu',
    kind_bxgy: 'Kupi X, dobij Y',
    kind_shipping: 'Popust na dostavu',
    auto: 'Automatski',
    code: 'Kod',
    // engine reasons (lib/discounts.ts RejectReason)
    rej_notfound: 'Kod ne postoji',
    rej_inactive: 'Popust nije aktivan (nacrt ili pauziran)',
    rej_scheduled: 'Popust još nije počeo',
    rej_expired: 'Popust je istekao',
    rej_minimum_amount: 'Minimum nije dostignut — nedostaje {missing}',
    rej_minimum_qty: 'Minimum nije dostignut — nedostaje još {missing} kom',
    rej_notCombinable: 'Ne kombinuje se sa „{other}“ — zadržana je povoljnija opcija',
    rej_notCombinablePlain: 'Ne kombinuje se sa primijenjenim popustom',
    rej_notEligible: 'Nijedna stavka ne ispunjava uslove',
    rej_usageLimit: 'Limit korišćenja je dostignut',
    rej_audience: 'Kupac nije u ciljnom segmentu',
    // misc
    by_web: 'Web prodavnica',
    by_admin: 'Tim',
    items_one: '{n} stavka',
    items_few: '{n} stavke',
    items_many: '{n} stavki',
    orders_one: '{n} narudžba',
    orders_few: '{n} narudžbe',
    orders_many: '{n} narudžbi',
    selected: '{n} izabrano',
    clearSelection: 'Poništi izbor',
    noPermission: 'Vaša uloga nema dozvolu za ovu radnju',
    country: 'Crna Gora',
  },
  sq: {
    pay_pending: 'Në pritje',
    pay_authorized: 'E autorizuar',
    pay_paid: 'E paguar',
    pay_partially_refunded: 'Pjesërisht e rimbursuar',
    pay_refunded: 'E rimbursuar',
    pay_failed: 'Pagesa dështoi',
    ful_unfulfilled: 'E papërmbushur',
    ful_partial: 'Pjesërisht e dërguar',
    ful_fulfilled: 'E dërguar',
    ful_delivered: 'E dorëzuar',
    ret_requested: 'Kërkesë',
    ret_approved: 'E miratuar',
    ret_received: 'Malli i pranuar',
    ret_refunded: 'E rimbursuar',
    ret_rejected: 'E refuzuar',
    draft_open: 'I hapur',
    draft_invoice_sent: 'Fatura e dërguar',
    draft_converted: 'I konvertuar',
    archived: 'E arkivuar',
    cancelled: 'E anuluar',
    channel_online: 'Online Store',
    channel_draft: 'Manuale (draft)',
    carrier_selca: 'Automjeti i SELCA-s',
    carrier_courier: 'Shërbim korrieri',
    carrier_pickup: 'Marrje personale',
    carrier_other: 'Tjetër',
    kind_products: 'Ulje produkti',
    kind_order: 'Ulje porosie',
    kind_bxgy: 'Blej X, merr Y',
    kind_shipping: 'Ulje dërgese',
    auto: 'Automatike',
    code: 'Kod',
    rej_notfound: 'Kodi nuk ekziston',
    rej_inactive: 'Zbritja nuk është aktive (draft ose e pezulluar)',
    rej_scheduled: 'Zbritja ende nuk ka filluar',
    rej_expired: 'Zbritja ka skaduar',
    rej_minimum_amount: 'Pragu nuk arrihet — mungojnë {missing}',
    rej_minimum_qty: 'Pragu nuk arrihet — mungojnë edhe {missing} copë',
    rej_notCombinable: 'Nuk kombinohet me „{other}“ — u ruajt opsioni më i leverdishëm',
    rej_notCombinablePlain: 'Nuk kombinohet me zbritjen e aplikuar',
    rej_notEligible: 'Asnjë artikull nuk i plotëson kushtet',
    rej_usageLimit: 'Kufiri i përdorimeve është arritur',
    rej_audience: 'Klienti nuk është në segmentin e synuar',
    by_web: 'Dyqani online',
    by_admin: 'Ekipi',
    items_one: '{n} artikull',
    items_few: '{n} artikuj',
    items_many: '{n} artikuj',
    orders_one: '{n} porosi',
    orders_few: '{n} porosi',
    orders_many: '{n} porosi',
    selected: '{n} të zgjedhura',
    clearSelection: 'Hiq zgjedhjen',
    noPermission: 'Roli juaj nuk ka leje për këtë veprim',
    country: 'Mali i Zi',
  },
  en: {
    pay_pending: 'Payment pending',
    pay_authorized: 'Authorized',
    pay_paid: 'Paid',
    pay_partially_refunded: 'Partially refunded',
    pay_refunded: 'Refunded',
    pay_failed: 'Payment failed',
    ful_unfulfilled: 'Unfulfilled',
    ful_partial: 'Partially fulfilled',
    ful_fulfilled: 'Fulfilled',
    ful_delivered: 'Delivered',
    ret_requested: 'Requested',
    ret_approved: 'Approved',
    ret_received: 'Goods received',
    ret_refunded: 'Refunded',
    ret_rejected: 'Rejected',
    draft_open: 'Open',
    draft_invoice_sent: 'Invoice sent',
    draft_converted: 'Converted',
    archived: 'Archived',
    cancelled: 'Cancelled',
    channel_online: 'Online Store',
    channel_draft: 'Manual (draft)',
    carrier_selca: 'SELCA van',
    carrier_courier: 'Courier service',
    carrier_pickup: 'Customer pickup',
    carrier_other: 'Other',
    kind_products: 'Product discount',
    kind_order: 'Order discount',
    kind_bxgy: 'Buy X, get Y',
    kind_shipping: 'Shipping discount',
    auto: 'Automatic',
    code: 'Code',
    rej_notfound: 'Code does not exist',
    rej_inactive: 'Discount is not active (draft or paused)',
    rej_scheduled: 'Discount has not started yet',
    rej_expired: 'Discount has expired',
    rej_minimum_amount: 'Minimum not reached — {missing} missing',
    rej_minimum_qty: 'Minimum not reached — {missing} more item(s) needed',
    rej_notCombinable: 'Does not combine with “{other}” — the better deal was kept',
    rej_notCombinablePlain: 'Does not combine with the applied discount',
    rej_notEligible: 'No item meets the conditions',
    rej_usageLimit: 'Usage limit reached',
    rej_audience: 'Customer is not in the target segment',
    by_web: 'Online shop',
    by_admin: 'Team',
    items_one: '{n} item',
    items_few: '{n} items',
    items_many: '{n} items',
    orders_one: '{n} order',
    orders_few: '{n} orders',
    orders_many: '{n} orders',
    selected: '{n} selected',
    clearSelection: 'Clear selection',
    noPermission: 'Your role is not allowed to do this',
    country: 'Montenegro',
  },
});
