import { defineDict } from '@/i18n';
import type { Lang } from '@/lib/types';

/** Strings shared by the cart → checkout → confirmation flow. */
export const ck = defineDict({
  me: {
    step_cart: 'Korpa',
    step_details: 'Podaci',
    step_payment: 'Plaćanje',
    step_done: 'Potvrda',
    stepsLabel: 'Koraci kupovine',
    items_one: '{n} artikal',
    items_few: '{n} artikla',
    items_many: '{n} artikala',
    couponLabel: 'Kod za popust',
    couponHave: 'Imate kod za popust?',
    couponPh: 'Unesite kod',
    couponApply: 'Primijeni',
    couponRemove: 'Ukloni kod',
    couponSaving: 'Ušteda {amount} na ovoj narudžbi',
    couponDemo: 'Demo kod:',
    err_notfound: 'Kod „{code}“ ne postoji — provjerite da li je ispravno unijet.',
    err_inactive: 'Kod „{code}“ trenutno nije aktivan.',
    err_expired: 'Kod „{code}“ je istekao.',
    err_min: 'Kod važi za narudžbe od {amount} — dodajte još {left}.',
    err_minQty: 'Kod važi uz najmanje {amount} artikala — dodajte još {left}.',
    err_scheduled: 'Kod „{code}“ još nije počeo da važi.',
    err_notCombinable: 'Kod „{code}“ se ne može kombinovati sa popustom koji je već primijenjen — zadržali smo povoljniju opciju.',
    err_notEligible: 'Kod „{code}“ ne važi za proizvode u korpi.',
    err_usageLimit: 'Kod „{code}“ je iskorišćen do kraja.',
    err_audience: 'Kod „{code}“ važi samo za odabrane kupce.',
    free: 'Besplatno',
    from: 'od {amount}',
    shippingCalc: 'Tačan iznos nakon izbora grada',
    free_threshold: 'narudžba preko {amount}',
    free_installation: 'uz naručenu ugradnju',
    free_pickup: 'preuzimanje u salonu',
    vatNote: 'PDV ({rate}%) uračunat: {amount}',
    trust_secure: 'Sigurno plaćanje',
    trust_secureText: 'Pouzećem, uplatom na račun ili karticom preko zaštićene stranice banke.',
    trust_measure: 'Besplatno mjerenje',
    trust_measureText: 'Prije ugradnje dolazimo na adresu i provjeravamo sve mjere.',
    trust_warranty: 'Garancija i servis',
    trust_warrantyText: 'Garancija proizvođača i garancija na izvedene radove.',
    installation: 'Ugradnja',
    plusInstallation: '+ ugradnja {amount}',
    packsArea: '{packs} pak. · {area} m²',
    copied: 'Kopirano',
    copy: 'Kopiraj',
  },
  sq: {
    step_cart: 'Shporta',
    step_details: 'Të dhënat',
    step_payment: 'Pagesa',
    step_done: 'Konfirmimi',
    stepsLabel: 'Hapat e blerjes',
    items_one: '{n} artikull',
    items_few: '{n} artikuj',
    items_many: '{n} artikuj',
    couponLabel: 'Kodi i zbritjes',
    couponHave: 'Keni kod zbritjeje?',
    couponPh: 'Shkruani kodin',
    couponApply: 'Apliko',
    couponRemove: 'Hiq kodin',
    couponSaving: 'Kurseni {amount} në këtë porosi',
    couponDemo: 'Kodi demo:',
    err_notfound: 'Kodi „{code}“ nuk ekziston — kontrolloni nëse është shkruar saktë.',
    err_inactive: 'Kodi „{code}“ aktualisht nuk është aktiv.',
    err_expired: 'Kodi „{code}“ ka skaduar.',
    err_min: 'Kodi vlen për porosi nga {amount} — shtoni edhe {left}.',
    err_minQty: 'Kodi vlen me të paktën {amount} artikuj — shtoni edhe {left}.',
    err_scheduled: 'Kodi „{code}“ ende nuk ka filluar të vlejë.',
    err_notCombinable: 'Kodi „{code}“ nuk kombinohet me zbritjen e aplikuar — ruajtëm opsionin më të leverdishëm.',
    err_notEligible: 'Kodi „{code}“ nuk vlen për produktet në shportë.',
    err_usageLimit: 'Kodi „{code}“ është përdorur deri në fund.',
    err_audience: 'Kodi „{code}“ vlen vetëm për klientë të caktuar.',
    free: 'Falas',
    from: 'nga {amount}',
    shippingCalc: 'Shuma e saktë pasi të zgjidhni qytetin',
    free_threshold: 'porosi mbi {amount}',
    free_installation: 'me montimin e porositur',
    free_pickup: 'marrje në sallon',
    vatNote: 'TVSH ({rate}%) e përfshirë: {amount}',
    trust_secure: 'Pagesë e sigurt',
    trust_secureText: 'Në dorëzim, me transfertë bankare ose me kartelë në faqen e mbrojtur të bankës.',
    trust_measure: 'Matje falas',
    trust_measureText: 'Para montimit vijmë në adresë dhe kontrollojmë të gjitha masat.',
    trust_warranty: 'Garanci dhe servis',
    trust_warrantyText: 'Garanci nga prodhuesi dhe garanci për punimet e kryera.',
    installation: 'Montimi',
    plusInstallation: '+ montim {amount}',
    packsArea: '{packs} pako · {area} m²',
    copied: 'U kopjua',
    copy: 'Kopjo',
  },
  en: {
    step_cart: 'Cart',
    step_details: 'Details',
    step_payment: 'Payment',
    step_done: 'Confirmation',
    stepsLabel: 'Checkout steps',
    items_one: '{n} item',
    items_few: '{n} items',
    items_many: '{n} items',
    couponLabel: 'Discount code',
    couponHave: 'Have a discount code?',
    couponPh: 'Enter code',
    couponApply: 'Apply',
    couponRemove: 'Remove code',
    couponSaving: 'You save {amount} on this order',
    couponDemo: 'Demo code:',
    err_notfound: 'Code “{code}” doesn’t exist — please check the spelling.',
    err_inactive: 'Code “{code}” is not active at the moment.',
    err_expired: 'Code “{code}” has expired.',
    err_min: 'This code applies to orders from {amount} — add {left} more.',
    err_minQty: 'This code needs at least {amount} items — add {left} more.',
    err_scheduled: 'Code “{code}” is not valid yet.',
    err_notCombinable: 'Code “{code}” can’t be combined with the discount already applied — we kept the better deal.',
    err_notEligible: 'Code “{code}” doesn’t apply to the items in your cart.',
    err_usageLimit: 'Code “{code}” has been fully used.',
    err_audience: 'Code “{code}” is only for selected customers.',
    free: 'Free',
    from: 'from {amount}',
    shippingCalc: 'Exact amount once you pick a city',
    free_threshold: 'order over {amount}',
    free_installation: 'with installation booked',
    free_pickup: 'showroom pickup',
    vatNote: 'VAT ({rate}%) included: {amount}',
    trust_secure: 'Secure payment',
    trust_secureText: 'Cash on delivery, bank transfer or card on the bank’s protected page.',
    trust_measure: 'Free measurement',
    trust_measureText: 'Before installation we visit and double-check every measurement.',
    trust_warranty: 'Warranty & service',
    trust_warrantyText: 'Manufacturer warranty plus a warranty on our workmanship.',
    installation: 'Installation',
    plusInstallation: '+ installation {amount}',
    packsArea: '{packs} packs · {area} m²',
    copied: 'Copied',
    copy: 'Copy',
  },
});

/** Plural category for item counts (Montenegrin has one / few / many). */
export function pluralKey(n: number, lang: Lang): 'items_one' | 'items_few' | 'items_many' {
  if (lang === 'me') {
    const m10 = n % 10;
    const m100 = n % 100;
    if (m10 === 1 && m100 !== 11) return 'items_one';
    if (m10 >= 2 && m10 <= 4 && (m100 < 12 || m100 > 14)) return 'items_few';
    return 'items_many';
  }
  return n === 1 ? 'items_one' : 'items_many';
}
