import type { ComponentType } from 'react';
import { FileText, FolderTree, Layers, Link2, Megaphone, Package } from 'lucide-react';
import { defineDict } from '@/i18n';
import type { MenuItemType } from '@/lib/types';

export const TYPE_ICON: Record<MenuItemType, ComponentType<{ className?: string }>> = {
  page: FileText,
  product: Package,
  collection: Layers,
  category: FolderTree,
  offer: Megaphone,
  url: Link2,
};

/** Menu editor strings (PDF p.36 "Menu dhe media"). */
export const mn = defineDict({
  sq: {
    description: 'Navigimi i dyqanit: menuja kryesore në header (desktop, mega-menuja „Produktet“ dhe celulari) dhe kolonat e footer-it. Lidhje te faqe, produkt, koleksion, kategori, ofertë ose URL.',
    menus: 'Menutë',
    main: 'Menuja kryesore',
    mainWhere: 'Header · desktop, mega-menu dhe celular',
    footer: 'Footer',
    footerWhere: 'Kolonat në fund të faqes',
    account: 'Llogaria e klientit',
    accountWhere: 'Aktivizohet me modulin e llogarive të klientëve',
    links: '{n} lidhje',
    menuName: 'Emri i menusë',
    handle: 'Identifikuesi',
    addLink: 'Shto lidhje',
    addChild: 'Shto nënlidhje',
    newLink: 'Lidhje e re',
    editLink: 'Ndrysho lidhjen',
    label: 'Emri i lidhjes',
    labelHint: 'Shfaqet në menu — në shqip dhe anglisht.',
    useEntityName: 'Merr emrin',
    linkType: 'Lidhet me',
    target: 'Destinacioni',
    search: 'Kërko…',
    urlLabel: 'Adresa',
    urlPh: '/kontakt ose https://…',
    urlHint: 'Shteg i brendshëm (/kontakt) ose adresë e plotë (https://…). Bosh = titull kolone pa lidhje.',
    urlInvalid: 'Shkruani një shteg që fillon me / ose adresë të plotë https://…',
    targetRequired: 'Zgjidhni destinacionin.',
    labelRequired: 'Shkruani emrin në shqip.',
    apply: 'Zbato',
    resolved: 'Adresa në faqe',
    noLink: 'Pa lidhje (titull kolone)',
    hasChildren: 'Ka {n} nënlidhje — shfaqet si menu zbritëse / kolonë.',
    moveUp: 'Lëviz lart',
    moveDown: 'Lëviz poshtë',
    indent: 'Fut brenda (nënlidhje)',
    outdent: 'Nxirr në nivelin e parë',
    removeTitle: 'Të hiqet lidhja „{name}“?',
    removeText: 'Lidhja hiqet nga menuja.',
    removeTextKids: 'Hiqen edhe nënlidhjet e saj ({n}).',
    emptyMenu: 'Menuja është bosh',
    emptyMenuText: 'Shtoni lidhjen e parë — faqe, kategori, koleksion, ofertë ose URL.',
    dragHint: 'Tërhiqni për renditjen · një nivel nënlidhjesh',
    saved: 'Menuja u ruajt dhe u publikua',
    preview: 'Parapamja',
    previewText: 'Kështu shfaqet menuja në faqe (vetëm lidhjet e dukshme).',
    readOnlyMenus: 'Ndryshimet e menusë publikohen menjëherë — kërkohet leje redaktimi dhe publikimi.',
    noMenu: 'Menuja nuk ekziston',
    fallbackNote: 'Pa lidhje të dukshme, faqja shfaq menunë e paracaktuar.',
    type_page: 'Faqe',
    type_product: 'Produkt',
    type_collection: 'Koleksion',
    type_category: 'Kategori',
    type_offer: 'Ofertë',
    type_url: 'URL',
    issue_missing: 'Destinacioni nuk ekziston',
    issue_draft: 'Draft — nuk shfaqet',
    issue_hidden: 'Fshehur — nuk shfaqet',
    issue_scheduled: 'Planifikuar — shfaqet më vonë',
    issue_expired: 'Ka skaduar — nuk shfaqet',
    issue_paused: 'Pezulluar — nuk shfaqet',
    issue_archived: 'Arkivuar — nuk shfaqet',
    issue_invalid: 'URL e pavlefshme',
    nothing: 'Asnjë rezultat',
    desktop: 'Desktop',
    mobile: 'Celular',
    viewOnSite: 'Shiko në faqe',
    saveErrors: 'Rregulloni lidhjet e shënuara para ruajtjes.',
    off: 'Joaktiv',
    visibleCount: '{n} të dukshme',
    hiddenCount: '{n} nuk shfaqen',
    previewHint: 'Klikoni një element me nënlidhje për të hapur menunë zbritëse.',
    topLevel: 'Niveli i parë',
    subOf: 'Nënlidhje e „{name}“',
    quickPaths: 'Shtigje të shpejta',
    qpPages: 'Faqet e dyqanit',
    qpCategories: 'Kategoritë e produkteve',
    qp_products: 'Të gjitha produktet',
    qp_sale: 'Produktet në ofertë',
    qp_industries: 'Industritë',
    qp_technology: 'Teknologjia',
    qp_quote: 'Kërko ofertë',
    qp_projects: 'Projektet',
    qp_about: 'Rreth nesh',
    qp_blog: 'Blogu',
    qp_contact: 'Kontakt',
    qpUseHint: 'Klikoni për ta vendosur si adresë (dhe si emër, nëse emri është bosh).',
    promoSale: 'Çmime në ofertë',
    change: 'Ndrysho',
    keyboardHint: 'Alt + ↑/↓ lëviz lidhjen në fokus',
    unsavedHere: 'Pa ruajtur',
    errorsCount: '{n} për t’u rregulluar',
    shown: 'Shfaqet',
    whereShown: 'Ku shfaqet',
    moreResults: 'Edhe {n} — ngushtoni kërkimin',
    columns: '{n} kolona',
    noTarget: 'Destinacioni nuk është zgjedhur',
    dropdown: 'Menu zbritëse',
    dragItem: 'Tërhiq',
    seeAll: 'Shiko të gjitha',
    allProducts: 'Të gjitha produktet',
    home: 'Ballina',
    categories: 'Kategoritë',
    linkFixed: 'Lidhja u përditësua',
    removed: 'Lidhja u hoq',
  },
  en: {
    description: 'Store navigation: the main menu in the header (desktop, the “Products” mega menu and mobile) and the footer columns. Links go to a page, product, collection, category, offer or URL.',
    menus: 'Menus',
    main: 'Main menu',
    mainWhere: 'Header · desktop, mega menu and mobile',
    footer: 'Footer',
    footerWhere: 'Footer link columns',
    account: 'Customer account',
    accountWhere: 'Enabled with the customer accounts module',
    links: '{n} links',
    menuName: 'Menu name',
    handle: 'Handle',
    addLink: 'Add link',
    addChild: 'Add sub-link',
    newLink: 'New link',
    editLink: 'Edit link',
    label: 'Link label',
    labelHint: 'Shown in the menu — in Albanian and English.',
    useEntityName: 'Use its name',
    linkType: 'Links to',
    target: 'Destination',
    search: 'Search…',
    urlLabel: 'Address',
    urlPh: '/kontakt or https://…',
    urlHint: 'An internal path (/kontakt) or a full address (https://…). Empty = column heading without a link.',
    urlInvalid: 'Enter a path starting with / or a full https://… address',
    targetRequired: 'Choose a destination.',
    labelRequired: 'Enter the Albanian label.',
    apply: 'Apply',
    resolved: 'Address on site',
    noLink: 'No link (column heading)',
    hasChildren: 'Has {n} sub-links — shown as a dropdown / column.',
    moveUp: 'Move up',
    moveDown: 'Move down',
    indent: 'Indent (sub-link)',
    outdent: 'Move to top level',
    removeTitle: 'Remove the link “{name}”?',
    removeText: 'The link is removed from the menu.',
    removeTextKids: 'Its sub-links ({n}) are removed too.',
    emptyMenu: 'This menu is empty',
    emptyMenuText: 'Add the first link — a page, category, collection, offer or URL.',
    dragHint: 'Drag to reorder · one level of sub-links',
    saved: 'Menu saved and published',
    preview: 'Preview',
    previewText: 'How the menu appears on the site (visible links only).',
    readOnlyMenus: 'Menu changes go live immediately — edit and publish permissions are required.',
    noMenu: 'Menu not found',
    fallbackNote: 'Without visible links the site shows the default menu.',
    type_page: 'Page',
    type_product: 'Product',
    type_collection: 'Collection',
    type_category: 'Category',
    type_offer: 'Offer',
    type_url: 'URL',
    issue_missing: 'Destination not found',
    issue_draft: 'Draft — not shown',
    issue_hidden: 'Hidden — not shown',
    issue_scheduled: 'Scheduled — shown later',
    issue_expired: 'Expired — not shown',
    issue_paused: 'Paused — not shown',
    issue_archived: 'Archived — not shown',
    issue_invalid: 'Invalid URL',
    nothing: 'No results',
    desktop: 'Desktop',
    mobile: 'Mobile',
    viewOnSite: 'View on site',
    saveErrors: 'Fix the highlighted links before saving.',
    off: 'Off',
    visibleCount: '{n} visible',
    hiddenCount: '{n} not shown',
    previewHint: 'Click an item with sub-links to open its dropdown.',
    topLevel: 'Top level',
    subOf: 'Sub-link of “{name}”',
    quickPaths: 'Quick paths',
    qpPages: 'Store pages',
    qpCategories: 'Product categories',
    qp_products: 'All products',
    qp_sale: 'Products on offer',
    qp_industries: 'Industries',
    qp_technology: 'Technology',
    qp_quote: 'Request a quote',
    qp_projects: 'Projects',
    qp_about: 'About us',
    qp_blog: 'Blog',
    qp_contact: 'Contact',
    qpUseHint: 'Click to use it as the address (and as the label, if the label is empty).',
    promoSale: 'Products on offer',
    change: 'Change',
    keyboardHint: 'Alt + ↑/↓ moves the focused link',
    unsavedHere: 'Unsaved',
    errorsCount: '{n} to fix',
    shown: 'Shown',
    whereShown: 'Where it appears',
    moreResults: '{n} more — refine the search',
    columns: '{n} columns',
    noTarget: 'No destination selected',
    dropdown: 'Dropdown',
    dragItem: 'Drag',
    seeAll: 'See all',
    allProducts: 'All products',
    home: 'Home',
    categories: 'Categories',
    linkFixed: 'Link updated',
    removed: 'Link removed',
  },
});
