import { defineDict } from '@/i18n';

/** Strings for Reklamacione — complaints on printed orders (route /admin/kthimet) — SQ / EN. */
export const rd = defineDict({
  sq: {
    title: 'Reklamacione',
    description: 'Ankesat e klientëve për punët e printuara: verifikimi, vendimi — ribotim, rimbursim ose notë krediti — dhe mbyllja.',
    create: 'Reklamacion i ri',
    tab_all: 'Të gjitha',
    tab_requested: 'Kërkesa',
    tab_approved: 'Të pranuara',
    tab_received: 'Të verifikuara',
    tab_refunded: 'Të zgjidhura',
    tab_rejected: 'Të refuzuara',
    searchPh: 'Numri i reklamacionit ose porosisë, kompania, produkti…',
    col_return: 'Reklamacioni',
    col_order: 'Porosia',
    col_customer: 'Klienti',
    col_items: 'Artikujt dhe arsyeja',
    col_resolution: 'Zgjidhja',
    col_status: 'Statusi',
    col_date: 'Data',
    stat_requested: 'Kërkesa të reja',
    stat_requestedHint: 'presin vendimin e ekipit',
    stat_approved: 'Në verifikim',
    stat_approvedHint: 'malli ose fotot në kontroll',
    stat_received: 'Për t’u zgjidhur',
    stat_receivedHint: 'ribotim, rimbursim ose notë krediti',
    stat_refunded: 'Kthyer klientëve (30 ditë)',
    stat_refundedHint: '{refunds} · {reprints}',
    returns_one: '{n} reklamacion',
    returns_few: '{n} reklamacione',
    returns_many: '{n} reklamacione',
    refunds_one: '{n} rimbursim',
    refunds_few: '{n} rimbursime',
    refunds_many: '{n} rimbursime',
    reprints_one: '{n} ribotim',
    reprints_few: '{n} ribotime',
    reprints_many: '{n} ribotime',
    more: '+{n} të tjerë',
    emptyTitle: 'Ende nuk ka reklamacione',
    emptyText: 'Kur klienti ankohet për një punë të printuar, hapni reklamacionin nga porosia — verifikimi, ribotimi ose rimbursimi ndiqen këtu.',
    emptyFiltered: 'Asnjë reklamacion për këtë filtër',
    emptyFilteredText: 'Ndryshoni kërkimin ose zgjidhni një skedë tjetër.',
    clearSearch: 'Pastro kërkimin',
    showing: 'Shfaqen {n} nga {total}',
    readOnly: 'Vetëm lexim — roli juaj nuk mund të ndryshojë reklamacionet.',
    /* statuses (complaint wording) */
    st_requested: 'Kërkesë',
    st_approved: 'E pranuar',
    st_received: 'U verifikua',
    st_refunded: 'Rimbursuar',
    st_rejected: 'Refuzuar',
    st_reprint: 'Zgjidhur · ribotim',
    st_credit: 'Notë krediti',
    step_requested: 'Kërkesë',
    step_approved: 'E pranuar',
    step_received: 'U verifikua',
    step_refunded: 'Rimbursuar',
    step_reprint: 'Ribotim',
    step_credit: 'Notë krediti',
    step_rejected: 'Refuzuar',
    /* reasons */
    r_colour: 'Ngjyra nuk përputhet me provën',
    r_cutting: 'Prerje e gabuar (matrica)',
    r_short: 'Sasi më pak se e porositura',
    r_transit: 'Dëmtim gjatë transportit',
    r_defect: 'Njolla / defekt printimi',
    r_file: 'U printua skedari i gabuar',
    r_customer: 'Ndryshim i klientit pas aprovimit',
    r_other: 'Tjetër',
    /* resolutions */
    res_reprint: 'Ribotim',
    res_refund: 'Rimbursim',
    res_credit: 'Notë krediti',
    resHint_reprint: 'E printojmë sërish pa pagesë — përgatitet një draft porosie me artikujt e reklamuar, me €0.',
    resHint_refund: 'I kthehet klientit shuma e paguar për artikujt e reklamuar, me TVSH.',
    resHint_credit: 'Shuma kreditohet për porosinë e ardhshme; në porosi regjistrohet si rimbursim.',
    resolution: 'Zgjidhja',
    resolutionLabel: 'Si zgjidhet?',
    /* drawer */
    next_requested: 'Kontrolloni reklamacionin — fotot, mostrat dhe provën e aprovuar — pastaj pranojeni ose refuzojeni.',
    next_approved: 'Verifikoni mallin e kthyer ose provat. Ribotimi mund të përgatitet që tani si draft.',
    next_received_reprint: 'Malli u verifikua. Krijoni draftin e ribotimit dhe mbylleni reklamacionin.',
    next_received_refund: 'Malli u verifikua. Rimbursoni shumën me TVSH ose refuzoni reklamacionin.',
    next_received_credit: 'Malli u verifikua. Lëshoni notën e kreditit — regjistrohet si rimbursim në porosi.',
    closed_refund: 'Reklamacioni u mbyll — klientit iu kthyen paratë.',
    closed_credit: 'Reklamacioni u mbyll me notë krediti.',
    closed_reprint: 'Reklamacioni u mbyll me ribotim pa pagesë.',
    closed_rejected: 'Reklamacioni u refuzua — pa rimbursim, pa ribotim.',
    order: 'Porosia',
    openOrder: 'Hap porosinë',
    items: 'Artikujt e reklamuar',
    ofQty: '{n} nga {total}',
    reason: 'Arsyeja',
    refundTitle: 'Shuma',
    refundBasis: 'Llogaritet nga pagesa neto e artikujve të reklamuar (pas zbritjeve) plus TVSH-ja e paguar — jo nga çmimi i sotëm. Transporti nuk kthehet.',
    value: 'Vlera e artikujve (pa TVSH)',
    discounts: 'Zbritjet e artikujve',
    net: 'Neto e paguar (pa TVSH)',
    vat: 'TVSH',
    gross: 'Për kthim (me TVSH)',
    toRefund: 'Për kthim',
    refundedOn: 'Zgjidhur më {date}',
    amountLabel: 'Shuma për kthim (me TVSH)',
    amountHint: 'Mund ta ulni (p.sh. për dëmtim të pjesshëm), por jo mbi {max}.',
    amountCapped: 'Kufizuar në shumën e mbetur të paguar të porosisë: {max}.',
    partialNote: 'Kthim i pjesshëm: {amount} nga {max}',
    unpaid: 'Porosia ende nuk është paguar — rimbursimi ose nota e kreditit bëhet vetëm kur ka pagesë.',
    markOrderPaid: 'Shëno si të paguar',
    orderPaid: 'Porosia {n} u shënua si e paguar',
    noMoney: 'Pa kthim parash — ribotim pa pagesë',
    restock: 'Ktheje mallin në stok',
    restockHint: 'Produktet e printuara me porosi nuk rishiten — lëreni të çaktivizuar. Aktivizojeni vetëm për artikuj standardë (p.sh. paketa e mostrave).',
    restockDone: 'U kthye në stok gjatë verifikimit.',
    restockSkipped: 'Nuk u kthye në stok (mall i printuar me porosi / i dëmtuar).',
    stockNow: 'stoku: {n}',
    note: 'Shënim për hapin (opsional)',
    notePh: 'p.sh. fotot erdhën me e-mail, ngjyra jashtë tolerancës ΔE',
    history: 'Historiku',
    approve: 'Prano reklamacionin',
    receive: 'Malli u verifikua',
    refund: 'Rimburso {amount}',
    credit: 'Lësho notën e kreditit {amount}',
    closeReprint: 'Mbyll me ribotim',
    makeReprint: 'Krijo draftin e ribotimit',
    reprintDraft: 'Drafti i ribotimit',
    reprintOpen: 'Hap {n}',
    reprintNone: 'Ende pa draft ribotimi.',
    reprintNote: 'Ribotim · {n}',
    creditNote: 'Notë krediti',
    reject: 'Refuzo',
    rejectTitle: 'Të refuzohet reklamacioni {n}?',
    rejectText: 'Klienti nuk merr rimbursim dhe nuk bëhet ribotim; stoku nuk ndryshon.',
    rejectConfirm: 'Refuzo reklamacionin',
    done_approved: 'Reklamacioni {n} u pranua',
    done_received: 'Malli për {n} u verifikua',
    done_refunded: 'U rimbursuan {amount} për {n}',
    done_credit: 'Nota e kreditit {amount} për {n} u lëshua',
    done_reprint: 'Reklamacioni {n} u mbyll me ribotim',
    done_rejected: 'Reklamacioni {n} u refuzua',
    noRefundPerm: 'Roli juaj nuk mund të rimbursojë',
    noOrder: 'Porosia nuk ekziston më.',
    /* create */
    createTitle: 'Reklamacion i ri',
    pickOrder: 'Porosia',
    findOrder: 'Numri i porosisë, kompania ose telefoni…',
    noOrders: 'Asnjë porosi për këtë kërkim',
    change: 'Ndrysho',
    chooseItems: 'Cilët artikuj reklamohen?',
    selectAll: 'Të gjitha',
    alreadyReturned: 'tashmë në reklamacion: {n}',
    nothingLeft: 'Gjithçka është tashmë në reklamacion',
    noLines: 'Kjo porosi nuk ka artikuj që mund të reklamohen.',
    reasonLabel: 'Arsyeja e reklamacionit',
    details: 'Detaje (opsionale)',
    detailsPh: 'p.sh. 300 kuti me njolla në kapak, fotot me e-mail',
    estimated: 'Vlera e reklamuar (me TVSH)',
    estimatedReprint: 'Ribotim pa pagesë · vlera',
    submit: 'Hap reklamacionin',
    created: 'Reklamacioni {n} u hap',
    needItems: 'Zgjidhni të paktën një artikull',
    unpaidCreate: 'Porosia ende nuk është paguar — rimbursimi do të jetë i mundur pas pagesës.',
    pcs: 'copë',
  },
  en: {
    title: 'Complaints',
    description: 'Customer complaints about printed jobs: verification, the decision — reprint, refund or credit note — and closing.',
    create: 'New complaint',
    tab_all: 'All',
    tab_requested: 'Requested',
    tab_approved: 'Accepted',
    tab_received: 'Verified',
    tab_refunded: 'Resolved',
    tab_rejected: 'Rejected',
    searchPh: 'Complaint or order number, company, product…',
    col_return: 'Complaint',
    col_order: 'Order',
    col_customer: 'Customer',
    col_items: 'Items and reason',
    col_resolution: 'Resolution',
    col_status: 'Status',
    col_date: 'Date',
    stat_requested: 'New requests',
    stat_requestedHint: 'awaiting the team’s decision',
    stat_approved: 'Being verified',
    stat_approvedHint: 'goods or photos being checked',
    stat_received: 'To resolve',
    stat_receivedHint: 'reprint, refund or credit note',
    stat_refunded: 'Paid back (30 days)',
    stat_refundedHint: '{refunds} · {reprints}',
    returns_one: '{n} complaint',
    returns_few: '{n} complaints',
    returns_many: '{n} complaints',
    refunds_one: '{n} refund',
    refunds_few: '{n} refunds',
    refunds_many: '{n} refunds',
    reprints_one: '{n} reprint',
    reprints_few: '{n} reprints',
    reprints_many: '{n} reprints',
    more: '+{n} more',
    emptyTitle: 'No complaints yet',
    emptyText: 'When a customer complains about a printed job, open the complaint from the order — verification, reprint or refund are tracked here.',
    emptyFiltered: 'No complaints for this filter',
    emptyFilteredText: 'Change the search or pick another tab.',
    clearSearch: 'Clear search',
    showing: 'Showing {n} of {total}',
    readOnly: 'Read only — your role cannot change complaints.',
    st_requested: 'Requested',
    st_approved: 'Accepted',
    st_received: 'Verified',
    st_refunded: 'Refunded',
    st_rejected: 'Rejected',
    st_reprint: 'Resolved · reprint',
    st_credit: 'Credit note',
    step_requested: 'Requested',
    step_approved: 'Accepted',
    step_received: 'Verified',
    step_refunded: 'Refunded',
    step_reprint: 'Reprint',
    step_credit: 'Credit note',
    step_rejected: 'Rejected',
    r_colour: 'Colour does not match the proof',
    r_cutting: 'Cutting / die-cut error',
    r_short: 'Quantity short of the order',
    r_transit: 'Damaged in transit',
    r_defect: 'Smudges / print defect',
    r_file: 'Wrong file printed',
    r_customer: 'Customer change after approval',
    r_other: 'Other',
    res_reprint: 'Reprint',
    res_refund: 'Refund',
    res_credit: 'Credit note',
    resHint_reprint: 'We print it again at no charge — a draft order with the complained items at €0 is prepared.',
    resHint_refund: 'The customer gets back what they paid for the complained items, incl. VAT.',
    resHint_credit: 'The amount is credited towards the next order; it is recorded as a refund on the order.',
    resolution: 'Resolution',
    resolutionLabel: 'How is it resolved?',
    next_requested: 'Check the complaint — photos, samples and the approved proof — then accept or reject it.',
    next_approved: 'Verify the returned goods or the evidence. The reprint can already be prepared as a draft.',
    next_received_reprint: 'Goods verified. Create the reprint draft and close the complaint.',
    next_received_refund: 'Goods verified. Refund the amount incl. VAT or reject the complaint.',
    next_received_credit: 'Goods verified. Issue the credit note — it is recorded as a refund on the order.',
    closed_refund: 'Closed — the money was returned to the customer.',
    closed_credit: 'Closed with a credit note.',
    closed_reprint: 'Closed with a free reprint.',
    closed_rejected: 'Rejected — no refund, no reprint.',
    order: 'Order',
    openOrder: 'Open order',
    items: 'Complained items',
    ofQty: '{n} of {total}',
    reason: 'Reason',
    refundTitle: 'Amount',
    refundBasis: 'Based on the net amount paid for the complained items (after discounts) plus the VAT paid — not today’s price. Delivery is not refunded.',
    value: 'Items value (excl. VAT)',
    discounts: 'Item discounts',
    net: 'Net paid (excl. VAT)',
    vat: 'VAT',
    gross: 'To pay back (incl. VAT)',
    toRefund: 'To pay back',
    refundedOn: 'Resolved on {date}',
    amountLabel: 'Amount to pay back (incl. VAT)',
    amountHint: 'You can lower it (e.g. for partial damage) but not above {max}.',
    amountCapped: 'Capped at the order’s remaining paid amount: {max}.',
    partialNote: 'Partial: {amount} of {max}',
    unpaid: 'The order has not been paid yet — a refund or credit note needs a recorded payment.',
    markOrderPaid: 'Mark as paid',
    orderPaid: 'Order {n} marked as paid',
    noMoney: 'No money back — free reprint',
    restock: 'Put goods back in stock',
    restockHint: 'Custom-printed products cannot be resold — leave this off. Turn it on only for standard items (e.g. the sample kit).',
    restockDone: 'Put back in stock on verification.',
    restockSkipped: 'Not restocked (custom-printed / damaged goods).',
    stockNow: 'stock: {n}',
    note: 'Note for this step (optional)',
    notePh: 'e.g. photos received by e-mail, colour outside ΔE tolerance',
    history: 'History',
    approve: 'Accept complaint',
    receive: 'Goods verified',
    refund: 'Refund {amount}',
    credit: 'Issue credit note {amount}',
    closeReprint: 'Close with reprint',
    makeReprint: 'Create reprint draft',
    reprintDraft: 'Reprint draft',
    reprintOpen: 'Open {n}',
    reprintNone: 'No reprint draft yet.',
    reprintNote: 'Reprint · {n}',
    creditNote: 'Credit note',
    reject: 'Reject',
    rejectTitle: 'Reject complaint {n}?',
    rejectText: 'The customer gets no refund and no reprint; stock stays unchanged.',
    rejectConfirm: 'Reject complaint',
    done_approved: 'Complaint {n} accepted',
    done_received: 'Goods for {n} verified',
    done_refunded: 'Refunded {amount} for {n}',
    done_credit: 'Credit note of {amount} issued for {n}',
    done_reprint: 'Complaint {n} closed with a reprint',
    done_rejected: 'Complaint {n} rejected',
    noRefundPerm: 'Your role cannot issue refunds',
    noOrder: 'The order no longer exists.',
    createTitle: 'New complaint',
    pickOrder: 'Order',
    findOrder: 'Order number, company or phone…',
    noOrders: 'No orders for this search',
    change: 'Change',
    chooseItems: 'Which items are complained about?',
    selectAll: 'All',
    alreadyReturned: 'already in a complaint: {n}',
    nothingLeft: 'Everything is already in a complaint',
    noLines: 'This order has no items that can be complained about.',
    reasonLabel: 'Complaint reason',
    details: 'Details (optional)',
    detailsPh: 'e.g. 300 boxes smudged on the lid, photos by e-mail',
    estimated: 'Complained value (incl. VAT)',
    estimatedReprint: 'Free reprint · value',
    submit: 'Open complaint',
    created: 'Complaint {n} opened',
    needItems: 'Select at least one item',
    unpaidCreate: 'The order has not been paid yet — a refund will be possible after payment.',
    pcs: 'pcs',
  },
});

export type RdKey = keyof typeof rd.sq;
