import { defineDict } from '@/i18n';

/** Settings space shell: sub-navigation, section titles/descriptions and shared messages. */
export const S = defineDict({
  me: {
    invalidPrefix: 'Prefiks: 1–6 znakova (velika slova, brojevi, crtica)',
    needLocation: 'Potrebna je bar jedna lokacija, od kojih jedna podrazumijevana',
    subjectMissing: 'Svaki šablon mora imati naslov na crnogorskom',
    title: 'Podešavanja',
    navLabel: 'Sekcije podešavanja',
    chooseSection: 'Izaberite sekciju',
    opensElsewhere: 'Otvara se u posebnom modulu',
    sec_general: 'Opšte',
    sec_staff: 'Osoblje i uloge',
    sec_payments: 'Plaćanja',
    sec_checkout: 'Checkout',
    sec_shipping: 'Dostava',
    sec_locations: 'Lokacije',
    sec_languages: 'Jezici',
    sec_notifications: 'Obavještenja',
    sec_integrations: 'Integracije',
    sec_privacy: 'Privatnost',
    sec_activity: 'Aktivnost',
    sec_data: 'Demo podaci',
    sec_general_d: 'Naziv prodavnice, pravni podaci, kontakt, adresa, valuta, jedinice, vremenska zona i numeracija narudžbi.',
    sec_staff_d: 'Nalozi zaposlenih, uloge i dozvole po radnji. Dozvole na serveru su izvor istine — meni se prilagođava njima.',
    sec_payments_d: 'Online provajder, ručni načini plaćanja i politika naplate.',
    sec_checkout_d: 'Kupovina kao gost ili sa nalogom, obavezna polja i marketinška saglasnost.',
    sec_shipping_d: 'Zone i cijene dostave, lično preuzimanje i lokalna dostava.',
    sec_locations_d: 'Saloni i magacini — za zalihe, lično preuzimanje i termine.',
    sec_languages_d: 'Jezici sajta, podrazumijevani jezik i rezervni jezik kada prevod nedostaje.',
    sec_notifications_d: 'E-mailovi kupcima i osoblju: narudžba, plaćanje, dostava, povrat, kontakt i termin.',
    sec_privacy_d: 'Pravila, kolačići i saglasnosti, izvoz i brisanje podataka kupca.',
    sec_activity_d: 'Istorija važnih radnji: ko je, šta, kada i nad kojim objektom uradio.',
    sec_data_d: 'Izvoz, uvoz i vraćanje demo podataka na početno stanje.',
    readOnlyTitle: 'Samo pregled',
    readOnlyText: 'Uloga „{role}“ može da vidi podešavanja, ali ih mijenja samo vlasnik.',
    ownerOnly: 'Samo vlasnik može da mijenja ovo podešavanje',
    noPermission: 'Nemate dozvolu za ovu radnju',
    unsavedDot: 'Nesačuvane promjene',
    exampleDot: 'Sadrži demo vrijednosti',
    examplesTitle: 'Demo vrijednosti za zamjenu: {n}',
    examplesText: 'Polja označena sa „Primjer“ su privremena. Unesite stvarne podatke prije puštanja sajta u rad.',
    examplesGo: 'Prikaži polje',
    shortcut: 'Brzo čuvanje',
    open: 'Otvori',
    manage: 'Upravljaj',
    edit: 'Izmijeni',
    statusOn: 'Uključeno',
    statusOff: 'Isključeno',
  },
  sq: {
    invalidPrefix: 'Prefiksi: 1–6 karaktere (shkronja të mëdha, numra, vizë)',
    needLocation: 'Duhet të paktën një lokacion, njëri prej tyre parazgjedhur',
    subjectMissing: 'Çdo shabllon duhet të ketë titull në malazezisht',
    title: 'Konfigurimet',
    navLabel: 'Seksionet e konfigurimeve',
    chooseSection: 'Zgjidhni seksionin',
    opensElsewhere: 'Hapet në modulin e vet',
    sec_general: 'Të përgjithshme',
    sec_staff: 'Stafi & rolet',
    sec_payments: 'Pagesat',
    sec_checkout: 'Checkout',
    sec_shipping: 'Dërgesat',
    sec_locations: 'Lokacionet',
    sec_languages: 'Gjuhët',
    sec_notifications: 'Njoftimet',
    sec_integrations: 'Integrimet',
    sec_privacy: 'Privatësia',
    sec_activity: 'Aktiviteti',
    sec_data: 'Të dhënat demo',
    sec_general_d: 'Emri i dyqanit, të dhënat ligjore, kontakti, adresa, valuta, njësitë, zona kohore dhe numërimi i porosive.',
    sec_staff_d: 'Llogaritë e stafit, rolet dhe lejet sipas veprimit. Lejet në server janë burimi i së vërtetës; menuja përshtatet sipas tyre.',
    sec_payments_d: 'Ofruesi online, mënyrat manuale dhe politika e arkëtimit.',
    sec_checkout_d: 'Blerje si vizitor ose me llogari, fushat e detyrueshme dhe pëlqimi për marketing.',
    sec_shipping_d: 'Zonat dhe tarifat e dërgesës, marrja në dyqan dhe dorëzimi lokal.',
    sec_locations_d: 'Sallonet dhe magazinat — për stokun, marrjen në dyqan dhe terminet.',
    sec_languages_d: 'Gjuhët e faqes, gjuha parazgjedhur dhe gjuha rezervë kur mungon përkthimi.',
    sec_notifications_d: 'Email për klientët dhe stafin: porosi, pagesë, dërgesë, kthim, kontakt dhe termin.',
    sec_privacy_d: 'Politikat, cookies dhe pëlqimet, eksporti dhe fshirja e të dhënave të klientit.',
    sec_activity_d: 'Historiku i veprimeve të rëndësishme: aktori, veprimi, koha dhe objekti.',
    sec_data_d: 'Eksporti, importi dhe rikthimi i të dhënave demo në gjendjen fillestare.',
    readOnlyTitle: 'Vetëm lexim',
    readOnlyText: 'Roli „{role}“ mund t’i shohë konfigurimet, por vetëm Pronari mund t’i ndryshojë.',
    ownerOnly: 'Vetëm Pronari mund ta ndryshojë këtë konfigurim',
    noPermission: 'Nuk keni leje për këtë veprim',
    unsavedDot: 'Ndryshime të paruajtura',
    exampleDot: 'Përmban vlera demo',
    examplesTitle: 'Vlera demo për t’u zëvendësuar: {n}',
    examplesText: 'Fushat e shënuara me „Shembull“ janë të përkohshme. Vendosni të dhënat reale para publikimit të faqes.',
    examplesGo: 'Shfaq fushën',
    shortcut: 'Ruajtje e shpejtë',
    open: 'Hap',
    manage: 'Menaxho',
    edit: 'Ndrysho',
    statusOn: 'Aktiv',
    statusOff: 'Joaktiv',
  },
  en: {
    invalidPrefix: 'Prefix: 1–6 characters (capitals, digits, hyphen)',
    needLocation: 'At least one location is needed, one of them the default',
    subjectMissing: 'Every template needs a Montenegrin subject',
    title: 'Settings',
    navLabel: 'Settings sections',
    chooseSection: 'Choose a section',
    opensElsewhere: 'Opens in its own module',
    sec_general: 'General',
    sec_staff: 'Staff & roles',
    sec_payments: 'Payments',
    sec_checkout: 'Checkout',
    sec_shipping: 'Shipping',
    sec_locations: 'Locations',
    sec_languages: 'Languages',
    sec_notifications: 'Notifications',
    sec_integrations: 'Integrations',
    sec_privacy: 'Privacy',
    sec_activity: 'Activity',
    sec_data: 'Demo data',
    sec_general_d: 'Store name, legal details, contact, address, currency, units, time zone and order numbering.',
    sec_staff_d: 'Staff accounts, roles and per-action permissions. Server-side permissions are the source of truth; the menu adapts to them.',
    sec_payments_d: 'Online provider, manual methods and capture policy.',
    sec_checkout_d: 'Guest or account checkout, required fields and marketing consent.',
    sec_shipping_d: 'Shipping zones and rates, store pickup and local delivery.',
    sec_locations_d: 'Showrooms and warehouses — used for stock, pickup and appointments.',
    sec_languages_d: 'Site languages, the default language and the fallback when a translation is missing.',
    sec_notifications_d: 'E-mails to customers and staff: order, payment, shipping, return, contact and appointment.',
    sec_privacy_d: 'Policies, cookies and consent, customer data export and deletion.',
    sec_activity_d: 'History of important actions: actor, action, time and object.',
    sec_data_d: 'Export, import and reset the demo data.',
    readOnlyTitle: 'Read-only',
    readOnlyText: 'The “{role}” role can view settings, but only the owner can change them.',
    ownerOnly: 'Only the owner can change this setting',
    noPermission: 'You don’t have permission for this action',
    unsavedDot: 'Unsaved changes',
    exampleDot: 'Contains demo values',
    examplesTitle: 'Demo values to replace: {n}',
    examplesText: 'Fields marked “Example” are temporary. Enter the real details before the site goes live.',
    examplesGo: 'Show field',
    shortcut: 'Quick save',
    open: 'Open',
    manage: 'Manage',
    edit: 'Edit',
    statusOn: 'On',
    statusOff: 'Off',
  },
});

export type SKey = keyof typeof S.me;
