import { defineDict } from '@/i18n';

/** Settings space shell: sub-navigation, section titles/descriptions and shared messages. */
export const S = defineDict({
  sq: {
    invalidPrefix: 'Prefiksi: 1–6 karaktere (shkronja të mëdha, numra, vizë)',
    invalidVat: 'Norma e TVSH-së: vendosni një vlerë nga 0 deri në 100',
    needLocation: 'Duhet të paktën një lokacion, njëri prej tyre parazgjedhur',
    subjectMissing: 'Çdo shabllon duhet të ketë titull në shqip',
    title: 'Konfigurimet',
    navLabel: 'Seksionet e konfigurimeve',
    chooseSection: 'Zgjidhni seksionin',
    opensElsewhere: 'Hapet në modulin e vet',
    sec_general: 'Të përgjithshme',
    sec_taxes: 'Taksat (TVSH)',
    sec_staff: 'Stafi & rolet',
    sec_payments: 'Pagesat',
    sec_checkout: 'Checkout',
    sec_shipping: 'Dërgesat',
    sec_locations: 'Lokacionet',
    sec_languages: 'Gjuhët',
    sec_notifications: 'Njoftimet',
    sec_integrations: 'Integrimet',
    sec_privacy: 'Privatësia',
    sec_activity: 'Aktiviteti',
    sec_data: 'Të dhënat demo',
    sec_general_d: 'Emri i kompanisë, të dhënat ligjore (NUI, TVSH, IBAN), kontakti, adresa, orari, valuta, njësitë, zona kohore dhe numërimi i porosive.',
    sec_taxes_d: 'Norma e TVSH-së, si shfaqen çmimet në katalog (pa ose me TVSH) dhe si llogaritet totali në arkë dhe në faturë.',
    sec_staff_d: 'Llogaritë e stafit, rolet dhe lejet sipas veprimit. Lejet në server janë burimi i së vërtetës; menuja përshtatet sipas tyre.',
    sec_payments_d: 'Ofruesi online, mënyrat manuale dhe politika e arkëtimit.',
    sec_checkout_d: 'Blerje si vizitor ose me llogari, fushat e detyrueshme dhe pëlqimi për marketing.',
    sec_shipping_d: 'Zonat dhe tarifat e transportit (Kosovë dhe rajon), marrja në fabrikë dhe dorëzimi me automjetet tona.',
    sec_locations_d: 'Fabrika, depoja dhe zyrat — për stokun, marrjen e porosive dhe takimet me klientët.',
    sec_languages_d: 'Gjuhët e faqes, gjuha parazgjedhur dhe gjuha rezervë kur mungon përkthimi.',
    sec_notifications_d: 'Email për klientët dhe ekipin: porosia, prova digjitale, pagesa, dërgesa, reklamacioni, kërkesa për ofertë dhe takimi.',
    sec_privacy_d: 'Politikat, cookies dhe pëlqimet, eksporti dhe fshirja e të dhënave të klientit.',
    sec_activity_d: 'Historiku i veprimeve të rëndësishme: aktori, veprimi, koha dhe objekti.',
    sec_data_d: 'Eksporti, importi dhe rikthimi i të dhënave demo në gjendjen fillestare.',
    readOnlyTitle: 'Vetëm lexim',
    readOnlyText: 'Roli „{role}“ mund t’i shohë konfigurimet, por vetëm Pronari mund t’i ndryshojë.',
    ownerOnly: 'Vetëm Pronari mund ta ndryshojë këtë konfigurim',
    noPermission: 'Nuk keni leje për këtë veprim',
    unsavedDot: 'Ndryshime të paruajtura',
    exampleDot: 'Përmban vlera demo',
    examplesTitle: 'Vlera demo për t’u zëvendësuar: {n}',
    examplesText: 'Fushat e shënuara me „Shembull“ janë të përkohshme. Vendosni të dhënat reale para publikimit të faqes.',
    examplesGo: 'Shfaq fushën',
    shortcut: 'Ruajtje e shpejtë',
    open: 'Hap',
    manage: 'Menaxho',
    edit: 'Ndrysho',
    statusOn: 'Aktiv',
    statusOff: 'Joaktiv',
  },
  en: {
    invalidPrefix: 'Prefix: 1–6 characters (capitals, digits, hyphen)',
    invalidVat: 'VAT rate: enter a value from 0 to 100',
    needLocation: 'At least one location is needed, one of them the default',
    subjectMissing: 'Every template needs an Albanian subject',
    title: 'Settings',
    navLabel: 'Settings sections',
    chooseSection: 'Choose a section',
    opensElsewhere: 'Opens in its own module',
    sec_general: 'General',
    sec_taxes: 'Taxes (VAT)',
    sec_staff: 'Staff & roles',
    sec_payments: 'Payments',
    sec_checkout: 'Checkout',
    sec_shipping: 'Shipping',
    sec_locations: 'Locations',
    sec_languages: 'Languages',
    sec_notifications: 'Notifications',
    sec_integrations: 'Integrations',
    sec_privacy: 'Privacy',
    sec_activity: 'Activity',
    sec_data: 'Demo data',
    sec_general_d: 'Company name, legal details (business no., VAT, IBAN), contact, address, hours, currency, units, time zone and order numbering.',
    sec_taxes_d: 'The VAT rate, how catalogue prices are shown (excl. or incl. VAT) and how the total is calculated at checkout and on the invoice.',
    sec_staff_d: 'Staff accounts, roles and per-action permissions. Server-side permissions are the source of truth; the menu adapts to them.',
    sec_payments_d: 'Online provider, manual methods and capture policy.',
    sec_checkout_d: 'Guest or account checkout, required fields and marketing consent.',
    sec_shipping_d: 'Delivery zones and rates (Kosovo and the region), factory pickup and delivery with our own vans.',
    sec_locations_d: 'Factory, warehouse and offices — used for stock, order pickup and customer meetings.',
    sec_languages_d: 'Site languages, the default language and the fallback when a translation is missing.',
    sec_notifications_d: 'E-mails to customers and the team: order, digital proof, payment, shipping, complaint, quote request and meeting.',
    sec_privacy_d: 'Policies, cookies and consent, customer data export and deletion.',
    sec_activity_d: 'History of important actions: actor, action, time and object.',
    sec_data_d: 'Export, import and reset the demo data.',
    readOnlyTitle: 'Read-only',
    readOnlyText: 'The “{role}” role can view settings, but only the owner can change them.',
    ownerOnly: 'Only the owner can change this setting',
    noPermission: 'You don’t have permission for this action',
    unsavedDot: 'Unsaved changes',
    exampleDot: 'Contains demo values',
    examplesTitle: 'Demo values to replace: {n}',
    examplesText: 'Fields marked “Example” are temporary. Enter the real details before the site goes live.',
    examplesGo: 'Show field',
    shortcut: 'Quick save',
    open: 'Open',
    manage: 'Manage',
    edit: 'Edit',
    statusOn: 'On',
    statusOff: 'Off',
  },
});

export type SKey = keyof typeof S.sq;
