import { defineDict } from '@/i18n';
import type { Lang } from '@/lib/types';

/** Strings shared by the cart → checkout → confirmation flow. */
export const ck = defineDict({
  sq: {
    step_cart: 'Shporta',
    step_details: 'Të dhënat',
    step_payment: 'Pagesa',
    step_done: 'Konfirmimi',
    stepsLabel: 'Hapat e porosisë',
    items_one: '{n} artikull',
    items_many: '{n} artikuj',
    lines_one: '{n} rresht',
    lines_many: '{n} rreshta',
    couponLabel: 'Kodi i zbritjes',
    couponHave: 'Keni kod zbritjeje?',
    couponPh: 'Shkruani kodin',
    couponApply: 'Apliko',
    couponRemove: 'Hiq kodin',
    couponSaving: 'Kurseni {amount} në këtë porosi',
    couponDemo: 'Kodi demo:',
    err_notfound: 'Kodi „{code}“ nuk ekziston — kontrolloni nëse është shkruar saktë.',
    err_inactive: 'Kodi „{code}“ aktualisht nuk është aktiv.',
    err_expired: 'Kodi „{code}“ ka skaduar.',
    err_min: 'Kodi vlen për porosi nga {amount} — shtoni edhe {left}.',
    err_minQty: 'Kodi vlen me të paktën {amount} artikuj — shtoni edhe {left}.',
    err_scheduled: 'Kodi „{code}“ ende nuk ka filluar të vlejë.',
    err_notCombinable: 'Kodi „{code}“ nuk kombinohet me zbritjen e aplikuar — ruajtëm opsionin më të leverdishëm.',
    err_notEligible: 'Kodi „{code}“ nuk vlen për produktet në shportë.',
    err_usageLimit: 'Kodi „{code}“ është përdorur deri në fund.',
    err_audience: 'Kodi „{code}“ vlen vetëm për klientë të caktuar.',
    free: 'Falas',
    from: 'nga {amount}',
    shippingCalc: 'Shuma e saktë pasi të zgjidhni qytetin',
    free_threshold: 'porosi mbi {amount}',
    free_pickup: 'marrje në fabrikë',
    subtotal: 'Nëntotali',
    design: 'Dizajn & prepress',
    discounts: 'Zbritjet',
    delivery: 'Transporti',
    pickup: 'Marrje në fabrikë',
    netTotal: 'Totali pa TVSH',
    vat: 'TVSH {rate}%',
    total: 'Totali',
    vatIncluded: 'TVSH {rate}% e përfshirë: {amount}',
    freeLeft: 'Edhe {amount} deri te transporti falas',
    freeReached: 'Transporti është falas për këtë porosi',
    freeQualified: 'Kualifikoheni për transport falas në Kosovë',
    freeNote: 'Transport falas në Kosovë për porosi nga {amount} (pa TVSH).',
    trust_proof: 'Provë digjitale para prodhimit',
    trust_proofText: 'Asgjë nuk printohet pa aprovimin tuaj — kontrolli prepress është falas.',
    trust_invoice: 'Faturë me TVSH për kompaninë',
    trust_invoiceText: 'Pro-formë menjëherë; fatura përfundimtare me NUI-në tuaj.',
    trust_secure: 'Pagesë e sigurt',
    trust_secureText: 'Transfertë bankare, kartelë (3-D Secure) ose në dorëzim.',
    perPiece: '/ copë',
    pcs: 'copë',
    qtyMin: 'Minimumi: {n} copë',
    qtyStep: 'Hapi: {n} copë',
    nextTier: 'Nga {qty} copë: {price} / copë',
    nextTierCta: 'Shto {n} copë dhe kurse {pct}%',
    art_uploaded: 'Skedari u ngarkua',
    art_later: 'Skedari më vonë',
    art_design: 'Dizajn nga PrintWorks',
    art_attach: 'Bashkëngjit skedarin',
    art_orDesign: 'ose dizajn nga ne (+{price})',
    art_removeDesign: 'Do e dërgoj vetë skedarin',
    art_replace: 'Ndrysho skedarin',
    art_attached: 'Skedari u bashkëngjit',
    art_missing: '{n} rreshta presin skedarin',
    art_missingOne: '1 rresht pret skedarin',
    art_missingHint: 'Mund ta ngarkoni tani ose pas porosisë — prodhimi nis pas aprovimit të provës.',
    designFee: '+ dizajn & prepress {amount}',
    remove: 'Hiq',
    copied: 'U kopjua',
    copy: 'Kopjo',
  },
  en: {
    step_cart: 'Cart',
    step_details: 'Details',
    step_payment: 'Payment',
    step_done: 'Confirmation',
    stepsLabel: 'Order steps',
    items_one: '{n} item',
    items_many: '{n} items',
    lines_one: '{n} line',
    lines_many: '{n} lines',
    couponLabel: 'Discount code',
    couponHave: 'Have a discount code?',
    couponPh: 'Enter code',
    couponApply: 'Apply',
    couponRemove: 'Remove code',
    couponSaving: 'You save {amount} on this order',
    couponDemo: 'Demo code:',
    err_notfound: 'Code “{code}” doesn’t exist — please check the spelling.',
    err_inactive: 'Code “{code}” is not active at the moment.',
    err_expired: 'Code “{code}” has expired.',
    err_min: 'This code applies to orders from {amount} — add {left} more.',
    err_minQty: 'This code needs at least {amount} items — add {left} more.',
    err_scheduled: 'Code “{code}” is not valid yet.',
    err_notCombinable: 'Code “{code}” can’t be combined with the discount already applied — we kept the better deal.',
    err_notEligible: 'Code “{code}” doesn’t apply to the items in your cart.',
    err_usageLimit: 'Code “{code}” has been fully used.',
    err_audience: 'Code “{code}” is only for selected customers.',
    free: 'Free',
    from: 'from {amount}',
    shippingCalc: 'Exact amount once you pick a city',
    free_threshold: 'order over {amount}',
    free_pickup: 'factory pickup',
    subtotal: 'Subtotal',
    design: 'Design & prepress',
    discounts: 'Discounts',
    delivery: 'Delivery',
    pickup: 'Factory pickup',
    netTotal: 'Total excl. VAT',
    vat: 'VAT {rate}%',
    total: 'Total',
    vatIncluded: 'VAT {rate}% included: {amount}',
    freeLeft: '{amount} away from free delivery',
    freeReached: 'Delivery is free for this order',
    freeQualified: 'You qualify for free delivery in Kosovo',
    freeNote: 'Free delivery in Kosovo on orders from {amount} (excl. VAT).',
    trust_proof: 'Digital proof before production',
    trust_proofText: 'Nothing is printed without your approval — the prepress check is free.',
    trust_invoice: 'VAT invoice for your company',
    trust_invoiceText: 'Pro-forma right away; final invoice with your business number.',
    trust_secure: 'Secure payment',
    trust_secureText: 'Bank transfer, card (3-D Secure) or cash on delivery.',
    perPiece: '/ pc',
    pcs: 'pcs',
    qtyMin: 'Minimum: {n} pcs',
    qtyStep: 'Step: {n} pcs',
    nextTier: 'From {qty} pcs: {price} / pc',
    nextTierCta: 'Add {n} pcs and save {pct}%',
    art_uploaded: 'File uploaded',
    art_later: 'File to follow',
    art_design: 'Designed by PrintWorks',
    art_attach: 'Attach file',
    art_orDesign: 'or let us design it (+{price})',
    art_removeDesign: 'I’ll send my own file',
    art_replace: 'Replace file',
    art_attached: 'File attached',
    art_missing: '{n} lines are waiting for a file',
    art_missingOne: '1 line is waiting for a file',
    art_missingHint: 'Upload now or after ordering — production starts once you approve the proof.',
    designFee: '+ design & prepress {amount}',
    remove: 'Remove',
    copied: 'Copied',
    copy: 'Copy',
  },
});

export type CkKey = keyof (typeof ck)['sq'];

/** "1 artikull" / "5 artikuj" */
export function pluralKey(n: number, lang: Lang): 'items_one' | 'items_many' {
  void lang;
  return n === 1 ? 'items_one' : 'items_many';
}
