import { defineDict } from '@/i18n';
import type { Lang } from '@/lib/types';

/** Strings for the catalogue page (/proizvodi) and its building blocks. */
export const T = defineDict({
  me: {
    catalog: 'Katalog',
    allTitle: 'Svi *proizvodi*',
    allSubtitle: 'Sve za vaš dom na jednom mjestu — uz besplatno mjerenje, dostavu na adresu i stručnu ugradnju.',
    saleEyebrow: 'Akcija',
    saleTitle: 'Proizvodi na *akciji*',
    saleSubtitle: 'Uštedite do {pct}% na odabranim proizvodima — akcijske cijene važe dok traju zalihe.',
    upTo: 'do',
    statProducts: 'proizvoda u ponudi',
    statCategories: 'kategorija',
    statSale: 'na akciji',
    countOne: '{n} proizvod',
    countMany: '{n} proizvoda',
    saleCount: '{n} na akciji',
    all: 'Sve',
    fromPrice: 'Već od {price}',
    installAvail: 'Stručna ugradnja',
    filters: 'Filteri',
    sortBy: 'Sortiraj',
    sort_popular: 'Popularno',
    sort_new: 'Najnovije',
    sort_priceAsc: 'Cijena: rastuće',
    sort_priceDesc: 'Cijena: opadajuće',
    sort_name: 'Naziv: A–Z',
    view: 'Prikaz',
    cols3: '3 kolone',
    cols4: '4 kolone',
    clearAll: 'Očisti sve',
    clear: 'Očisti',
    removeFilter: 'Ukloni filter',
    category: 'Kategorija',
    price: 'Cijena',
    priceMin: 'Od',
    priceMax: 'Do',
    priceNote: 'Cijene sa PDV-om. Podovi i pločice — cijena po m².',
    availability: 'Dostupnost',
    inStock: 'Na stanju',
    toOrder: 'Po narudžbi',
    offer: 'Ponuda',
    onSale: 'Na akciji',
    withInstall: 'Sa ugradnjom',
    colour: 'Boja i dekor',
    colourPill: 'Boja: {c}',
    unit: 'Način prodaje',
    unit_piece: 'Po komadu',
    unit_area: 'Po m²',
    unit_length: 'Po metru',
    showResults: 'Prikaži {what}',
    emptyTitle: 'Nema proizvoda za izabrane filtere',
    emptyText: 'Probajte da proširite raspon cijena ili uklonite neki od filtera.',
    emptySaleTitle: 'Trenutno nema akcija u ovoj kategoriji',
    emptySaleText: 'Pogledajte kompletnu ponudu kategorije ili sve proizvode na akciji.',
    allInCategory: 'Cijela kategorija',
    allOnSale: 'Sve akcije',
    resetFilters: 'Poništi filtere',
    loadMore: 'Prikaži još {n}',
    shownOf: 'Prikazano {a} od {b}',
    helpEyebrow: 'Savjet stručnjaka',
    helpTitle: 'Niste sigurni *šta da izaberete?*',
    helpText: 'Naš savjetnik dolazi besplatno na mjerenje, donosi uzorke i pomaže vam da odaberete rješenje koje odgovara vašem prostoru i budžetu.',
    helpCta: 'Zakaži besplatno mjerenje',
    helpPoint1: 'Uzorci na licu mjesta',
    helpPoint2: 'Precizna ponuda za 24h',
    helpPoint3: 'Bez obaveze kupovine',
    helpCardTitle: 'Besplatno mjerenje',
    helpCardText: 'Dolazimo u roku od 48 sati',
    notFoundTitle: 'Kategorija nije pronađena',
    notFoundText: 'Moguće je da je uklonjena ili preimenovana. Pogledajte kompletnu ponudu.',
    c_white: 'Bijela',
    c_cream: 'Krem i bež',
    c_grey: 'Siva',
    c_anthracite: 'Antracit',
    c_black: 'Crna',
    c_lightwood: 'Svijetlo drvo',
    c_darkwood: 'Tamno drvo',
    c_gold: 'Zlato i mesing',
    c_metal: 'Hrom i inox',
    c_green: 'Zelena',
    c_blue: 'Plava',
    c_red: 'Crvena',
  },
  sq: {
    catalog: 'Katalogu',
    allTitle: 'Të gjitha *produktet*',
    allSubtitle: 'Gjithçka për shtëpinë tuaj në një vend — me matje falas, dorëzim në adresë dhe montim profesional.',
    saleEyebrow: 'Ofertë',
    saleTitle: 'Produkte në *ofertë*',
    saleSubtitle: 'Kurseni deri në {pct}% në produktet e zgjedhura — çmimet e ofertës vlejnë deri në shterim të stokut.',
    upTo: 'deri',
    statProducts: 'produkte në ofertë',
    statCategories: 'kategori',
    statSale: 'në ofertë',
    countOne: '{n} produkt',
    countMany: '{n} produkte',
    saleCount: '{n} në ofertë',
    all: 'Të gjitha',
    fromPrice: 'Që nga {price}',
    installAvail: 'Montim profesional',
    filters: 'Filtrat',
    sortBy: 'Rendit',
    sort_popular: 'Më të kërkuarat',
    sort_new: 'Më të rejat',
    sort_priceAsc: 'Çmimi: në rritje',
    sort_priceDesc: 'Çmimi: në zbritje',
    sort_name: 'Emri: A–Z',
    view: 'Pamja',
    cols3: '3 kolona',
    cols4: '4 kolona',
    clearAll: 'Pastro të gjitha',
    clear: 'Pastro',
    removeFilter: 'Hiq filtrin',
    category: 'Kategoria',
    price: 'Çmimi',
    priceMin: 'Nga',
    priceMax: 'Deri',
    priceNote: 'Çmimet me TVSH. Dyshemetë dhe pllakat — çmimi për m².',
    availability: 'Disponueshmëria',
    inStock: 'Në stok',
    toOrder: 'Me porosi',
    offer: 'Oferta',
    onSale: 'Në ofertë',
    withInstall: 'Me montim',
    colour: 'Ngjyra dhe dekori',
    colourPill: 'Ngjyra: {c}',
    unit: 'Mënyra e shitjes',
    unit_piece: 'Për copë',
    unit_area: 'Për m²',
    unit_length: 'Për metër',
    showResults: 'Shfaq {what}',
    emptyTitle: 'Nuk ka produkte për filtrat e zgjedhur',
    emptyText: 'Provoni të zgjeroni gamën e çmimeve ose hiqni ndonjë filtër.',
    emptySaleTitle: 'Aktualisht nuk ka oferta në këtë kategori',
    emptySaleText: 'Shikoni të gjithë kategorinë ose të gjitha produktet në ofertë.',
    allInCategory: 'E gjithë kategoria',
    allOnSale: 'Të gjitha ofertat',
    resetFilters: 'Rivendos filtrat',
    loadMore: 'Shfaq edhe {n}',
    shownOf: 'Shfaqen {a} nga {b}',
    helpEyebrow: 'Këshilla e ekspertit',
    helpTitle: 'Nuk jeni të sigurt *çfarë të zgjidhni?*',
    helpText: 'Këshilltari ynë vjen falas për matje, sjell mostra dhe ju ndihmon të zgjidhni zgjidhjen që i përshtatet hapësirës dhe buxhetit tuaj.',
    helpCta: 'Caktoni matjen falas',
    helpPoint1: 'Mostra në vend',
    helpPoint2: 'Ofertë e saktë brenda 24 orëve',
    helpPoint3: 'Pa detyrim blerjeje',
    helpCardTitle: 'Matje falas',
    helpCardText: 'Vijmë brenda 48 orëve',
    notFoundTitle: 'Kategoria nuk u gjet',
    notFoundText: 'Mund të jetë hequr ose riemërtuar. Shikoni të gjithë ofertën.',
    c_white: 'E bardhë',
    c_cream: 'Krem dhe bezhë',
    c_grey: 'Gri',
    c_anthracite: 'Antracit',
    c_black: 'E zezë',
    c_lightwood: 'Dru i çelët',
    c_darkwood: 'Dru i errët',
    c_gold: 'Ari dhe tunxh',
    c_metal: 'Krom dhe inoks',
    c_green: 'E gjelbër',
    c_blue: 'Blu',
    c_red: 'E kuqe',
  },
  en: {
    catalog: 'Catalogue',
    allTitle: 'All *products*',
    allSubtitle: 'Everything for your home in one place — with free measuring, delivery to your door and expert installation.',
    saleEyebrow: 'Sale',
    saleTitle: 'Products on *sale*',
    saleSubtitle: 'Save up to {pct}% on selected products — sale prices apply while stocks last.',
    upTo: 'up to',
    statProducts: 'products in range',
    statCategories: 'categories',
    statSale: 'on sale',
    countOne: '{n} product',
    countMany: '{n} products',
    saleCount: '{n} on sale',
    all: 'All',
    fromPrice: 'From {price}',
    installAvail: 'Expert installation',
    filters: 'Filters',
    sortBy: 'Sort',
    sort_popular: 'Most popular',
    sort_new: 'Newest',
    sort_priceAsc: 'Price: low to high',
    sort_priceDesc: 'Price: high to low',
    sort_name: 'Name: A–Z',
    view: 'View',
    cols3: '3 columns',
    cols4: '4 columns',
    clearAll: 'Clear all',
    clear: 'Clear',
    removeFilter: 'Remove filter',
    category: 'Category',
    price: 'Price',
    priceMin: 'Min',
    priceMax: 'Max',
    priceNote: 'Prices incl. VAT. Flooring and tiles are priced per m².',
    availability: 'Availability',
    inStock: 'In stock',
    toOrder: 'Made to order',
    offer: 'Offer',
    onSale: 'On sale',
    withInstall: 'With installation',
    colour: 'Colour & finish',
    colourPill: 'Colour: {c}',
    unit: 'Sold by',
    unit_piece: 'Per piece',
    unit_area: 'Per m²',
    unit_length: 'Per metre',
    showResults: 'Show {what}',
    emptyTitle: 'No products match these filters',
    emptyText: 'Try widening the price range or removing a filter.',
    emptySaleTitle: 'No sale items in this category right now',
    emptySaleText: 'Browse the whole category or everything that’s on sale.',
    allInCategory: 'Whole category',
    allOnSale: 'All sale items',
    resetFilters: 'Reset filters',
    loadMore: 'Show {n} more',
    shownOf: 'Showing {a} of {b}',
    helpEyebrow: 'Expert advice',
    helpTitle: 'Not sure *what to choose?*',
    helpText: 'Our adviser comes out to measure for free, brings samples and helps you pick the solution that suits your space and budget.',
    helpCta: 'Book a free measurement',
    helpPoint1: 'Samples brought to you',
    helpPoint2: 'Precise quote within 24h',
    helpPoint3: 'No obligation to buy',
    helpCardTitle: 'Free measurement',
    helpCardText: 'We visit within 48 hours',
    notFoundTitle: 'Category not found',
    notFoundText: 'It may have been removed or renamed. Browse the full range instead.',
    c_white: 'White',
    c_cream: 'Cream & beige',
    c_grey: 'Grey',
    c_anthracite: 'Anthracite',
    c_black: 'Black',
    c_lightwood: 'Light wood',
    c_darkwood: 'Dark wood',
    c_gold: 'Gold & brass',
    c_metal: 'Chrome & steel',
    c_green: 'Green',
    c_blue: 'Blue',
    c_red: 'Red',
  },
});

export type ShopT = (key: keyof (typeof T)['me'] & string, vars?: Record<string, string | number>) => string;

/** "1 proizvod / 2 proizvoda / 21 proizvod" — Montenegrin singular for …1 (except …11). */
export function countLabel(t: ShopT, lang: Lang, n: number) {
  const one = lang === 'me' ? n % 10 === 1 && n % 100 !== 11 : n === 1;
  return t(one ? 'countOne' : 'countMany', { n });
}
