import { defineDict } from '@/i18n';
import type { Lang } from '@/lib/types';

/** Strings for the catalogue page (/produktet, /produktet/:category) and its building blocks. */
export const T = defineDict({
  me: {
    catalog: 'Katalog',
    allTitle: 'Sva *ambalaža*',
    allSubtitle: 'Čaše, poklopci, posude, pribor i slamke za kafiće, restorane i poslastičarnice — po pakovanju ili kartonu, uz veleprodajne cijene koje se same obračunavaju.',
    saleEyebrow: 'Akcija',
    saleTitle: 'Ambalaža na *akciji*',
    saleSubtitle: 'Uštedite do {pct}% na odabranim proizvodima — akcijske cijene važe dok traju zalihe.',
    upTo: 'do',
    statProducts: 'proizvoda',
    statCategories: 'kategorija',
    statCarton: 'popust na karton',
    countOne: '{n} proizvod',
    countMany: '{n} proizvoda',
    saleCount: '{n} na akciji',
    all: 'Sve',
    soon: 'Uskoro',
    fromPrice: 'Od {price} / pak.',
    fromPiece: 'od {price}/kom',
    stickerFrom: 'već od',
    stickerUnit: 'kom',
    logoAvail: 'Štampa logotipa',
    tierPill: 'Do −{pct}% uz karton',
    customPill: 'Izrada sa vašim logom',
    filters: 'Filteri',
    sortBy: 'Sortiraj',
    sort_popular: 'Najprodavanije',
    sort_new: 'Najnovije',
    sort_priceAsc: 'Cijena: rastuće',
    sort_priceDesc: 'Cijena: opadajuće',
    sort_name: 'Naziv: A–Z',
    view: 'Prikaz',
    cols3: '3 kolone',
    cols4: '4 kolone',
    clearAll: 'Očisti sve',
    clear: 'Očisti',
    removeFilter: 'Ukloni filter',
    category: 'Kategorija',
    price: 'Cijena po pakovanju',
    priceMin: 'Od',
    priceMax: 'Do',
    priceNote: 'Cijene sa PDV-om, po pakovanju. Cijena po komadu je na svakom proizvodu.',
    availability: 'Dostupnost',
    inStock: 'Na stanju',
    offer: 'Ponuda',
    onSale: 'Na akciji',
    withLogo: 'Moguća štampa logotipa',
    showResults: 'Prikaži {what}',
    emptyTitle: 'Nema proizvoda za izabrane filtere',
    emptyText: 'Probajte da proširite raspon cijena ili uklonite neki od filtera.',
    emptySaleTitle: 'Trenutno nema akcija u ovoj kategoriji',
    emptySaleText: 'Pogledajte kompletnu kategoriju ili sve proizvode na akciji.',
    allInCategory: 'Cijela kategorija',
    allOnSale: 'Sve akcije',
    resetFilters: 'Poništi filtere',
    loadMore: 'Prikaži još {n}',
    shownOf: 'Prikazano {a} od {b}',
    helpEyebrow: 'Besplatni uzorci',
    helpTitle: 'Probajte prije nego *naručite*',
    helpText: 'Šaljemo besplatne uzorke čaša, poklopaca i posuda za vaš lokal — i pomažemo da izaberete prave veličine i količine za vaš meni.',
    helpCta: 'Zatražite uzorke',
    helpQuote: 'Veleprodajna ponuda',
    helpPoint1: 'Uzorci na adresu lokala',
    helpPoint2: 'Ponuda za veleprodaju za 24 h',
    helpPoint3: 'Bez obaveze kupovine',
    helpCardTitle: 'Besplatni uzorci',
    helpCardText: 'Za kafiće, restorane i poslastičarnice',
    notFoundTitle: 'Kategorija nije pronađena',
    notFoundText: 'Moguće je da je uklonjena ili preimenovana. Pogledajte kompletan asortiman.',
    soonBadge: 'Uskoro',
    soonTitle: '{name} stiže *uskoro*',
    soonText: 'Pripremamo ovu liniju ambalaže. Ostavite kontakt i javićemo vam prvi — sa cijenama za veleprodaju i besplatnim uzorcima.',
    soonPoint1: 'Prvi saznajete kada stigne na stanje',
    soonPoint2: 'Veleprodajne cijene od prvog dana',
    soonPoint3: 'Besplatni uzorci za vaš lokal',
    soonFormTitle: 'Obavijestite me',
    soonFormText: 'Bez spama — samo jedna poruka kada linija bude dostupna.',
    soonName: 'Ime i prezime',
    soonPhone: 'Telefon',
    soonEmail: 'Email',
    soonBusiness: 'Lokal / firma (opciono)',
    soonQty: 'Okvirna mjesečna količina (opciono)',
    soonQtyPh: 'npr. 500 posuda mjesečno',
    soonSubmit: 'Obavijestite me',
    soonRequired: 'Obavezno polje',
    soonPhoneOrEmail: 'Upišite telefon ili email',
    soonThanksTitle: 'Hvala, {name}!',
    soonThanksText: 'Javićemo vam čim „{cat}“ stigne na stanje.',
    soonAnother: 'Nova prijava',
    soonMsg: 'Obavijestite me kada stigne: {cat}.',
    soonMeanwhile: 'U međuvremenu',
    soonMeanwhileTitle: 'Najprodavanije iz *ponude*',
    soonOther: 'Pogledajte i',
  },
  sq: {
    catalog: 'Katalogu',
    allTitle: 'I gjithë *paketimi*',
    allSubtitle: 'Gota, kapakë, enë, takëm dhe shkopinj për kafiteri, restorante dhe pastiçeri — me pako ose me karton, me çmime shumice që llogariten vetë.',
    saleEyebrow: 'Ofertë',
    saleTitle: 'Paketim në *ofertë*',
    saleSubtitle: 'Kurseni deri në {pct}% në produktet e zgjedhura — çmimet e ofertës vlejnë deri në shterim të stokut.',
    upTo: 'deri',
    statProducts: 'produkte',
    statCategories: 'kategori',
    statCarton: 'zbritje me karton',
    countOne: '{n} produkt',
    countMany: '{n} produkte',
    saleCount: '{n} në ofertë',
    all: 'Të gjitha',
    soon: 'Së shpejti',
    fromPrice: 'Nga {price} / pako',
    fromPiece: 'nga {price}/copë',
    stickerFrom: 'që nga',
    stickerUnit: 'copë',
    logoAvail: 'Printim me logo',
    tierPill: 'Deri −{pct}% me karton',
    customPill: 'Me logon tuaj, me porosi',
    filters: 'Filtrat',
    sortBy: 'Rendit',
    sort_popular: 'Më të shiturat',
    sort_new: 'Më të rejat',
    sort_priceAsc: 'Çmimi: në rritje',
    sort_priceDesc: 'Çmimi: në zbritje',
    sort_name: 'Emri: A–Z',
    view: 'Pamja',
    cols3: '3 kolona',
    cols4: '4 kolona',
    clearAll: 'Pastro të gjitha',
    clear: 'Pastro',
    removeFilter: 'Hiq filtrin',
    category: 'Kategoria',
    price: 'Çmimi për pako',
    priceMin: 'Nga',
    priceMax: 'Deri',
    priceNote: 'Çmimet me TVSH, për pako. Çmimi për copë shfaqet te çdo produkt.',
    availability: 'Disponueshmëria',
    inStock: 'Në stok',
    offer: 'Oferta',
    onSale: 'Në ofertë',
    withLogo: 'Mundësi printimi me logo',
    showResults: 'Shfaq {what}',
    emptyTitle: 'Nuk ka produkte për filtrat e zgjedhur',
    emptyText: 'Provoni të zgjeroni gamën e çmimeve ose hiqni ndonjë filtër.',
    emptySaleTitle: 'Aktualisht nuk ka oferta në këtë kategori',
    emptySaleText: 'Shikoni të gjithë kategorinë ose të gjitha produktet në ofertë.',
    allInCategory: 'E gjithë kategoria',
    allOnSale: 'Të gjitha ofertat',
    resetFilters: 'Rivendos filtrat',
    loadMore: 'Shfaq edhe {n}',
    shownOf: 'Shfaqen {a} nga {b}',
    helpEyebrow: 'Mostra falas',
    helpTitle: 'Provojini para se të *porositni*',
    helpText: 'Ju dërgojmë mostra falas të gotave, kapakëve dhe enëve për lokalin tuaj — dhe ju ndihmojmë të zgjidhni madhësitë dhe sasitë e duhura për menynë tuaj.',
    helpCta: 'Kërkoni mostra',
    helpQuote: 'Ofertë shumice',
    helpPoint1: 'Mostra në adresën e lokalit',
    helpPoint2: 'Ofertë shumice brenda 24 orëve',
    helpPoint3: 'Pa detyrim blerjeje',
    helpCardTitle: 'Mostra falas',
    helpCardText: 'Për kafiteri, restorante dhe pastiçeri',
    notFoundTitle: 'Kategoria nuk u gjet',
    notFoundText: 'Mund të jetë hequr ose riemërtuar. Shikoni të gjithë katalogun.',
    soonBadge: 'Së shpejti',
    soonTitle: '{name} vjen *së shpejti*',
    soonText: 'Po e përgatisim këtë linjë paketimi. Lini kontaktin dhe ju njoftojmë të parët — me çmime shumice dhe mostra falas.',
    soonPoint1: 'E mësoni të parët kur të vijë në stok',
    soonPoint2: 'Çmime shumice që nga dita e parë',
    soonPoint3: 'Mostra falas për lokalin tuaj',
    soonFormTitle: 'Më njoftoni',
    soonFormText: 'Pa spam — vetëm një mesazh kur linja të jetë në dispozicion.',
    soonName: 'Emri dhe mbiemri',
    soonPhone: 'Telefoni',
    soonEmail: 'Email',
    soonBusiness: 'Lokali / biznesi (opsionale)',
    soonQty: 'Sasia e përafërt mujore (opsionale)',
    soonQtyPh: 'p.sh. 500 enë në muaj',
    soonSubmit: 'Më njoftoni',
    soonRequired: 'Fushë e detyrueshme',
    soonPhoneOrEmail: 'Shkruani telefonin ose emailin',
    soonThanksTitle: 'Faleminderit, {name}!',
    soonThanksText: 'Ju njoftojmë sapo „{cat}“ të vijë në stok.',
    soonAnother: 'Regjistrim i ri',
    soonMsg: 'Më njoftoni kur të vijë: {cat}.',
    soonMeanwhile: 'Ndërkohë',
    soonMeanwhileTitle: 'Më të shiturat nga *oferta*',
    soonOther: 'Shikoni edhe',
  },
  en: {
    catalog: 'Catalogue',
    allTitle: 'All *packaging*',
    allSubtitle: 'Cups, lids, containers, cutlery and straws for cafés, restaurants and pastry shops — by the pack or the carton, with wholesale prices that apply themselves.',
    saleEyebrow: 'Sale',
    saleTitle: 'Packaging on *sale*',
    saleSubtitle: 'Save up to {pct}% on selected products — sale prices apply while stocks last.',
    upTo: 'up to',
    statProducts: 'products',
    statCategories: 'categories',
    statCarton: 'off per carton',
    countOne: '{n} product',
    countMany: '{n} products',
    saleCount: '{n} on sale',
    all: 'All',
    soon: 'Coming soon',
    fromPrice: 'From {price} / pack',
    fromPiece: 'from {price}/pc',
    stickerFrom: 'from',
    stickerUnit: 'piece',
    logoAvail: 'Logo print',
    tierPill: 'Up to −{pct}% per carton',
    customPill: 'Made to order with your logo',
    filters: 'Filters',
    sortBy: 'Sort',
    sort_popular: 'Bestselling',
    sort_new: 'Newest',
    sort_priceAsc: 'Price: low to high',
    sort_priceDesc: 'Price: high to low',
    sort_name: 'Name: A–Z',
    view: 'View',
    cols3: '3 columns',
    cols4: '4 columns',
    clearAll: 'Clear all',
    clear: 'Clear',
    removeFilter: 'Remove filter',
    category: 'Category',
    price: 'Price per pack',
    priceMin: 'Min',
    priceMax: 'Max',
    priceNote: 'Prices incl. VAT, per pack. Every product also shows its price per piece.',
    availability: 'Availability',
    inStock: 'In stock',
    offer: 'Offer',
    onSale: 'On sale',
    withLogo: 'Logo print available',
    showResults: 'Show {what}',
    emptyTitle: 'No products match these filters',
    emptyText: 'Try widening the price range or removing a filter.',
    emptySaleTitle: 'No sale items in this category right now',
    emptySaleText: 'Browse the whole category or everything that’s on sale.',
    allInCategory: 'Whole category',
    allOnSale: 'All sale items',
    resetFilters: 'Reset filters',
    loadMore: 'Show {n} more',
    shownOf: 'Showing {a} of {b}',
    helpEyebrow: 'Free samples',
    helpTitle: 'Try it before you *order*',
    helpText: 'We send free samples of cups, lids and containers to your venue — and help you pick the right sizes and quantities for your menu.',
    helpCta: 'Request samples',
    helpQuote: 'Wholesale quote',
    helpPoint1: 'Samples delivered to your venue',
    helpPoint2: 'Wholesale quote within 24 h',
    helpPoint3: 'No obligation to buy',
    helpCardTitle: 'Free samples',
    helpCardText: 'For cafés, restaurants and pastry shops',
    notFoundTitle: 'Category not found',
    notFoundText: 'It may have been removed or renamed. Browse the full range instead.',
    soonBadge: 'Coming soon',
    soonTitle: '{name} is coming *soon*',
    soonText: 'We’re preparing this packaging range. Leave your details and you’ll hear first — with wholesale prices and free samples.',
    soonPoint1: 'Be the first to know when it’s in stock',
    soonPoint2: 'Wholesale prices from day one',
    soonPoint3: 'Free samples for your venue',
    soonFormTitle: 'Notify me',
    soonFormText: 'No spam — just one message when the range is available.',
    soonName: 'Full name',
    soonPhone: 'Phone',
    soonEmail: 'Email',
    soonBusiness: 'Venue / company (optional)',
    soonQty: 'Rough monthly quantity (optional)',
    soonQtyPh: 'e.g. 500 containers a month',
    soonSubmit: 'Notify me',
    soonRequired: 'Required',
    soonPhoneOrEmail: 'Enter a phone number or email',
    soonThanksTitle: 'Thank you, {name}!',
    soonThanksText: 'We’ll let you know as soon as “{cat}” is in stock.',
    soonAnother: 'New sign-up',
    soonMsg: 'Please notify me when this arrives: {cat}.',
    soonMeanwhile: 'Meanwhile',
    soonMeanwhileTitle: 'Bestsellers from the *range*',
    soonOther: 'See also',
  },
});

export type ShopT = (key: keyof (typeof T)['me'] & string, vars?: Record<string, string | number>) => string;

/** "1 proizvod / 2 proizvoda / 21 proizvod" — Serbian singular for …1 (except …11). */
export function countLabel(t: ShopT, lang: Lang, n: number) {
  const one = lang === 'me' ? n % 10 === 1 && n % 100 !== 11 : n === 1;
  return t(one ? 'countOne' : 'countMany', { n });
}
