import { defineDict } from '@/i18n';
import type { Lang } from '@/lib/types';
import { money, moneyPiece } from '@/lib/format';

/**
 * Strings for the storefront product page (/produkt/:slug), the product card and the price component.
 * `me` = Serbian (Latin), `sq` = Albanian (default), `en` = English.
 */
export const PD = defineDict({
  me: {
    notFoundTitle: 'Proizvod nije pronađen',
    notFoundText: 'Proizvod koji tražite više nije u ponudi ili je link neispravan. Pogledajte sličnu ambalažu u našem asortimanu.',
    browse: 'Pogledaj asortiman',
    backHome: 'Na početnu',
    sku: 'Šifra',
    share: 'Podijeli',
    linkCopied: 'Link je kopiran',
    vatIncl: 'PDV uračunat · cijena po pakovanju',
    vatInclPiece: 'PDV uračunat',
    perPiece: '{price}/kom',
    packOf: '{n} kom/pak.',
    cartonInfo: 'Karton: {packs} pak. · {pieces}',
    save: 'Uštedite {amount}',
    inStock: 'Na stanju',
    inStockN: 'Na stanju · {n} pak.',
    lowStock: 'Još samo {n} pak. na stanju',
    outStock: 'Trenutno nema na stanju',
    unitsInStock: 'Na stanju · {n} kom',
    madeToOrder: 'Po narudžbi',
    // quantity
    qtyLabel: 'Količina',
    qtyPacks: 'pakovanja',
    addCarton: '+ 1 karton',
    addCartonHint: 'Dodaj cijeli karton ({packs} pak.)',
    equals: '= {pieces}',
    breakdown: '{full} {cw} + {rest} pak.',
    breakdownFull: '{full} {cw}',
    maxStock: 'Maksimalno {n} pak. — koliko imamo na stanju',
    calcTitle: 'Koliko komada vam treba?',
    calcText: 'Upišite broj komada — preračunaćemo u pakovanja.',
    calcPh: 'npr. 1200',
    calcResult: '{packs} pak. = {pieces}',
    calcExtra: '+{n} kom rezerve',
    calcExact: 'tačno',
    calcUse: 'Uzmi {packs} pak.',
    // tiers
    tiersTitle: 'Veleprodajne cijene',
    tiersText: 'Popust se obračunava automatski u korpi, po proizvodu.',
    tierQty: 'Količina',
    tierPrice: 'Cijena / pak.',
    tierPiece: 'Po komadu',
    tierRange: '{a}–{b} pak.',
    tierFrom: '{a}+ pak.',
    tierCarton: '{n} {cw}',
    tierBase: 'osnovna',
    nextTier: 'Još {n} pak. → −{pct}%',
    nextTierAdd: 'Dodaj {n}',
    tierReached: 'Ostvarili ste najveći popust −{pct}%',
    // logo print
    installTitle: 'Štampa vašeg logotipa',
    installText: 'Vaš logo odštampan na svakom komadu — za kafiće, barove i take-away.',
    installMin: 'Min. 1 karton ({packs} pak. · {pieces})',
    installLead: 'Izrada 7–10 radnih dana',
    installContact: 'Nakon narudžbe javljamo vam se za fajl logotipa (PDF, AI, SVG ili PNG).',
    installRaised: 'Količina je povećana na 1 karton — minimum za štampu.',
    perPack: '/ pak.',
    // summary
    total: 'Ukupno',
    tierBadge: 'veleprodaja −{pct}%',
    logoLine: 'Štampa logotipa · {qty} × {price}',
    piecesLine: '{pieces} · {price}/kom',
    youSave: 'Ušteda {amount}',
    addToCart: 'Dodaj u korpu',
    addedShort: 'Dodato u korpu',
    added: 'Dodato u korpu',
    viewCart: 'Pogledaj korpu',
    wishAdd: 'Sačuvaj u omiljeno',
    wishRemove: 'Ukloni iz omiljenog',
    wishAdded: 'Sačuvano u omiljeno',
    wishRemoved: 'Uklonjeno iz omiljenog',
    // out of stock
    oosTitle: 'Privremeno nema na stanju',
    oosText: 'Zalihe dopunjavamo — ostavite kontakt i javićemo vam čim stigne, ili vam predložiti zamjenu.',
    oosCta: 'Kontaktirajte nas',
    oosAlt: 'Pogledaj zamjene',
    contactTitle: 'Kontaktirajte nas',
    contactText: 'Ostavite broj — javljamo se čim proizvod ponovo bude na stanju.',
    stockMsg: 'Javite mi kada bude ponovo na stanju: {name} ({sku}).',
    // delivery promise
    deliveryTitle: 'Dostava',
    deliveryFast: '{zone}: za 24 h',
    deliveryZone: '{zone}: {days} radna dana',
    deliveryKosovo: 'Cijelo Kosovo: {days} radna dana',
    freeOver: 'Besplatna dostava od {amount}',
    freeLeft: 'Još {amount} do besplatne dostave',
    freeReached: 'Uz ovu narudžbu dostava je besplatna',
    pickupLine: 'Besplatno preuzimanje u magacinu',
    printNoFree: 'Štampa ne utiče na cijenu dostave.',
    // help + trust
    help: 'Trebate veću količinu?',
    helpText: 'Pozovite nas ili pišite na WhatsApp',
    trust_samples: 'Besplatni uzorci',
    trust_samplesText: 'Probajte prije narudžbe',
    trust_returns: 'Povrat 5 dana',
    trust_returnsText: 'Nekorišćeno, u originalnom pakovanju',
    trust_cod: 'Plaćanje pouzećem',
    trust_codText: 'Platite kad preuzmete robu',
    trust_invoice: 'Račun za firme',
    trust_invoiceText: 'Sa NUI i PDV brojem',
    // compatible
    fitsTitle: 'Odgovara uz',
    fitsAll: 'Sve',
    quickAdd: 'Dodaj 1 pak.',
    // quote template
    quoteBadge: 'Po narudžbi',
    quoteOnly: 'Cijena na upit',
    quotePriceNote: 'Cijena zavisi od količine, veličine i broja boja.',
    quoteStepsTitle: 'Kako funkcioniše',
    quoteStep1: 'Pošaljite logo i količinu',
    quoteStep1Text: 'Dovoljna je i skica — pomažemo oko pripreme.',
    quoteStep2: 'Ponuda i probni dizajn za 48 h',
    quoteStep2Text: 'Bez obaveze, sa tačnim cijenama po komadu.',
    quoteStep3: 'Izrada i dostava',
    quoteStep3Text: 'Oko {days} dana od odobrenja dizajna.',
    requestQuote: 'Zatraži ponudu',
    quoteTitle: 'Zahtjev za ponudu',
    quoteText: 'Ostavite kontakt — javljamo se istog dana sa ponudom.',
    quoteMsg: 'Zanima me ponuda za: {name}{opts}.',
    formEyebrow: 'Ponuda bez obaveze',
    formTitle: 'Zatražite *ponudu*',
    formText: 'Recite nam šta vam treba — pripremamo ponudu i probni dizajn u roku od 48 sati.',
    formPoint1: 'Logo (PDF, AI, SVG ili PNG)',
    formPoint2: 'Približna količina i veličine',
    formPoint3: 'Grad isporuke i rok',
    formEmail: 'Ili pišite na',
    leadTime: 'Rok izrade',
    leadValue: '~{n} dana',
    // tabs
    tab_desc: 'Opis',
    tab_specs: 'Specifikacije',
    tab_shipping: 'Dostava i povrat',
    tab_faq: 'Česta pitanja',
    highlights: 'Ukratko',
    spec_sku: 'Šifra proizvoda',
    spec_category: 'Kategorija',
    spec_unit: 'Prodajna jedinica',
    spec_pack: 'Komada u pakovanju',
    spec_carton: 'Pakovanja u kartonu',
    spec_cartonPieces: 'Komada u kartonu',
    spec_piecePrice: 'Cijena po komadu',
    spec_packPrice: 'Cijena po pakovanju',
    spec_tiers: 'Veleprodaja',
    spec_logo: 'Štampa logotipa',
    spec_logoValue: '+{price} / pak. · min. 1 karton · 7–10 radnih dana',
    spec_logoNo: 'Nije dostupna za ovaj proizvod',
    spec_lead: 'Spremno za slanje',
    unit_pack: 'Pakovanje od {n} kom',
    unit_kom: 'Komad',
    unit_set: 'Set',
    unit_m: 'Metar',
    daysApprox: '~{n} dana',
    daysWork: '{n} radna dana',
    tierLine: '{qty}: −{pct}%',
    zonesTitle: 'Zone dostave',
    daysValue: '{days} radna dana',
    freeOverText: 'Ispod tog iznosa plaćate samo cijenu zone. Dostavljamo do vrata lokala.',
    pickup: 'Preuzimanje u magacinu',
    pickupText: '{address} — bez troškova dostave.',
    logoShipTitle: 'Narudžbe sa štampom',
    logoShipText: 'Štampa traje 7–10 radnih dana; dostava se plaća po zoni.',
    returnsTitle: 'Povrat robe',
    returns1: 'U roku od 5 dana od prijema',
    returns2: 'Nekorišćeno i u originalnom pakovanju',
    returns3: 'Proizvodi sa štampom logotipa se ne vraćaju',
    returnsText: 'Pišite na {email} sa brojem narudžbe — javljamo se sa uputstvom.',
    returnsAddress: 'Adresa za povrat: {address}',
    payTitle: 'Plaćanje',
    payText: 'Pouzećem, uplatom na račun ili karticom. Firmama izdajemo račun sa PDV-om.',
    faq1q: 'Mogu li kupiti pojedinačne komade?',
    faq1a: 'Prodajemo po pakovanju od {n} kom — tako je cijena po komadu najniža ({price}/kom). Za veće količine birajte cijeli karton.',
    faq1aUnit: 'Ovaj proizvod se prodaje po komadu. Za veće količine pošaljite upit — pripremamo ponudu.',
    faq2q: 'Kako rade veleprodajne cijene?',
    faq2a: 'Popust se obračunava automatski u korpi za svaki proizvod: {tiers}. Ne treba vam kod.',
    faq2aNone: 'Za veće količine i redovne narudžbe pripremamo posebnu ponudu — pošaljite upit.',
    faq3q: 'Za koliko stiže dostava?',
    faq3a: 'Mitrovica i okolina za 24 h, ostatak Kosova za 1–3 radna dana. Dostava je besplatna za narudžbe od {amount}.',
    faq4q: 'Možete li odštampati naš logo?',
    faq4a: 'Da — štampa logotipa košta {price} po pakovanju, minimum je 1 karton, a izrada traje 7–10 radnih dana.',
    faq4aNo: 'Za ovaj proizvod ne, ali štampamo logo na čaše F95, čaše Bodega, papirne čaše i kartonske kutije — pošaljite upit.',
    faq5q: 'Imate li besplatne uzorke?',
    faq5a: 'Da. Za lokale šaljemo besplatne uzorke ili ih donosimo — zatražite ih na stranici „Za biznis“.',
    faq6q: 'Kako mogu vratiti robu?',
    faq6a: 'U roku od 5 dana od prijema, nekorišćeno i u originalnom pakovanju — pišite na {email}.',
    // rails
    compatEyebrow: 'Dopunite narudžbu',
    compatTitle: '*Odgovara* uz',
    relatedEyebrow: 'Iz iste kategorije',
    relatedTitle: 'Slični *proizvodi*',
    recentEyebrow: 'Vaša istorija',
    recentTitle: 'Nedavno *pregledano*',
    seeCategory: 'Cijela kategorija',
    // gallery
    zoom: 'Uvećaj sliku',
    prev: 'Prethodna',
    next: 'Sljedeća',
    close: 'Zatvori',
    // card
    card_add: 'Dodaj 1 pakovanje u korpu',
    card_quote: 'Zatraži ponudu',
    card_contact: 'Kontakt',
    card_out: 'Nema na stanju',
    card_logo: 'Logo',
    card_logoTitle: 'Moguća štampa logotipa',
    card_onRequest: 'Na upit',
    card_options: 'Izaberi',
  },
  sq: {
    notFoundTitle: 'Produkti nuk u gjet',
    notFoundText: 'Produkti që kërkoni nuk është më në ofertë ose lidhja është e pasaktë. Shikoni paketime të ngjashme në katalogun tonë.',
    browse: 'Shiko katalogun',
    backHome: 'Në ballinë',
    sku: 'Kodi',
    share: 'Ndaj',
    linkCopied: 'Lidhja u kopjua',
    vatIncl: 'TVSH e përfshirë · çmimi për pako',
    vatInclPiece: 'TVSH e përfshirë',
    perPiece: '{price}/copë',
    packOf: '{n} copë/pako',
    cartonInfo: 'Karton: {packs} pako · {pieces}',
    save: 'Kurseni {amount}',
    inStock: 'Në stok',
    inStockN: 'Në stok · {n} pako',
    lowStock: 'Vetëm {n} pako në stok',
    outStock: 'Përkohësisht jashtë stoku',
    unitsInStock: 'Në stok · {n} copë',
    madeToOrder: 'Me porosi',
    qtyLabel: 'Sasia',
    qtyPacks: 'pako',
    addCarton: '+ 1 karton',
    addCartonHint: 'Shto një karton të plotë ({packs} pako)',
    equals: '= {pieces}',
    breakdown: '{full} {cw} + {rest} pako',
    breakdownFull: '{full} {cw}',
    maxStock: 'Maksimumi {n} pako — sa kemi në stok',
    calcTitle: 'Sa copë ju duhen?',
    calcText: 'Shkruani numrin e copëve — e llogarisim në pako.',
    calcPh: 'p.sh. 1200',
    calcResult: '{packs} pako = {pieces}',
    calcExtra: '+{n} copë rezervë',
    calcExact: 'saktësisht',
    calcUse: 'Merr {packs} pako',
    tiersTitle: 'Çmime shumice',
    tiersText: 'Zbritja llogaritet automatikisht në shportë, për çdo produkt.',
    tierQty: 'Sasia',
    tierPrice: 'Çmimi / pako',
    tierPiece: 'Për copë',
    tierRange: '{a}–{b} pako',
    tierFrom: '{a}+ pako',
    tierCarton: '{n} {cw}',
    tierBase: 'bazë',
    nextTier: 'Edhe {n} pako → −{pct}%',
    nextTierAdd: 'Shto {n}',
    tierReached: 'Keni zbritjen më të madhe −{pct}%',
    installTitle: 'Printim me logon tuaj',
    installText: 'Logoja juaj e printuar në çdo copë — ideale për kafiteri, bare dhe take-away.',
    installMin: 'Min. 1 karton ({packs} pako · {pieces})',
    installLead: 'Gati për 7–10 ditë pune',
    installContact: 'Pas porosisë ju kontaktojmë për skedarin e logos (PDF, AI, SVG ose PNG).',
    installRaised: 'Sasia u rrit në 1 karton — minimumi për printim.',
    perPack: '/ pako',
    total: 'Totali',
    tierBadge: 'shumicë −{pct}%',
    logoLine: 'Printim me logo · {qty} × {price}',
    piecesLine: '{pieces} · {price}/copë',
    youSave: 'Kurseni {amount}',
    addToCart: 'Shto në shportë',
    addedShort: 'U shtua në shportë',
    added: 'U shtua në shportë',
    viewCart: 'Shiko shportën',
    wishAdd: 'Ruaj te të preferuarat',
    wishRemove: 'Hiq nga të preferuarat',
    wishAdded: 'U ruajt te të preferuarat',
    wishRemoved: 'U hoq nga të preferuarat',
    oosTitle: 'Përkohësisht jashtë stoku',
    oosText: 'Po e rimbushim stokun — lini kontaktin dhe ju njoftojmë sapo të vijë, ose ju sugjerojmë një alternativë.',
    oosCta: 'Na kontaktoni',
    oosAlt: 'Shiko alternativat',
    contactTitle: 'Na kontaktoni',
    contactText: 'Lini numrin — ju njoftojmë sapo produkti të jetë sërish në stok.',
    stockMsg: 'Më njoftoni kur të jetë sërish në stok: {name} ({sku}).',
    deliveryTitle: 'Dërgesa',
    deliveryFast: '{zone}: brenda 24 orësh',
    deliveryZone: '{zone}: {days} ditë pune',
    deliveryKosovo: 'Gjithë Kosova: {days} ditë pune',
    freeOver: 'Transport falas mbi {amount}',
    freeLeft: 'Edhe {amount} deri te transporti falas',
    freeReached: 'Me këtë porosi transporti është falas',
    pickupLine: 'Marrje falas në depo',
    printNoFree: 'Printimi nuk ndikon në çmimin e transportit.',
    help: 'Ju duhen sasi më të mëdha?',
    helpText: 'Na telefononi ose na shkruani në WhatsApp',
    trust_samples: 'Mostra falas',
    trust_samplesText: 'Provojini para porosisë',
    trust_returns: 'Kthim brenda 5 ditëve',
    trust_returnsText: 'E papërdorur, në paketim origjinal',
    trust_cod: 'Pagesë në dorëzim',
    trust_codText: 'Paguani kur ta merrni mallin',
    trust_invoice: 'Faturë për biznese',
    trust_invoiceText: 'Me NUI dhe numër TVSH',
    fitsTitle: 'Përshtatet me',
    fitsAll: 'Të gjitha',
    quickAdd: 'Shto 1 pako',
    quoteBadge: 'Me porosi',
    quoteOnly: 'Çmimi sipas kërkesës',
    quotePriceNote: 'Çmimi varet nga sasia, madhësia dhe numri i ngjyrave.',
    quoteStepsTitle: 'Si funksionon',
    quoteStep1: 'Na dërgoni logon dhe sasinë',
    quoteStep1Text: 'Mjafton edhe një skicë — ju ndihmojmë me përgatitjen.',
    quoteStep2: 'Ofertë dhe dizajn provë për 48 orë',
    quoteStep2Text: 'Pa detyrim, me çmime të sakta për copë.',
    quoteStep3: 'Prodhim dhe dërgesë',
    quoteStep3Text: 'Rreth {days} ditë nga aprovimi i dizajnit.',
    requestQuote: 'Kërko ofertë',
    quoteTitle: 'Kërkesë për ofertë',
    quoteText: 'Lini kontaktin — ju kthejmë përgjigje të njëjtën ditë me ofertën.',
    quoteMsg: 'Më intereson oferta për: {name}{opts}.',
    formEyebrow: 'Ofertë pa detyrim',
    formTitle: 'Kërkoni *ofertën*',
    formText: 'Na tregoni çfarë ju nevojitet — ju përgatisim ofertën dhe dizajnin provë brenda 48 orëve.',
    formPoint1: 'Logoja (PDF, AI, SVG ose PNG)',
    formPoint2: 'Sasia e përafërt dhe madhësitë',
    formPoint3: 'Qyteti i dërgesës dhe afati',
    formEmail: 'Ose na shkruani në',
    leadTime: 'Afati i prodhimit',
    leadValue: '~{n} ditë',
    tab_desc: 'Përshkrimi',
    tab_specs: 'Specifikimet',
    tab_shipping: 'Dërgesa & kthimet',
    tab_faq: 'Pyetje të shpeshta',
    highlights: 'Shkurt',
    spec_sku: 'Kodi i produktit',
    spec_category: 'Kategoria',
    spec_unit: 'Njësia e shitjes',
    spec_pack: 'Copë në pako',
    spec_carton: 'Pako në karton',
    spec_cartonPieces: 'Copë në karton',
    spec_piecePrice: 'Çmimi për copë',
    spec_packPrice: 'Çmimi për pako',
    spec_tiers: 'Shumicë',
    spec_logo: 'Printim me logo',
    spec_logoValue: '+{price} / pako · min. 1 karton · 7–10 ditë pune',
    spec_logoNo: 'Nuk ofrohet për këtë produkt',
    spec_lead: 'Gati për dërgesë',
    unit_pack: 'Pako me {n} copë',
    unit_kom: 'Copë',
    unit_set: 'Set',
    unit_m: 'Metër',
    daysApprox: '~{n} ditë',
    daysWork: '{n} ditë pune',
    tierLine: '{qty}: −{pct}%',
    zonesTitle: 'Zonat e dërgesës',
    daysValue: '{days} ditë pune',
    freeOverText: 'Nën këtë shumë paguani vetëm çmimin e zonës. Dorëzojmë deri te dera e lokalit.',
    pickup: 'Marrje në depo',
    pickupText: '{address} — pa kosto transporti.',
    logoShipTitle: 'Porositë me printim',
    logoShipText: 'Printimi zgjat 7–10 ditë pune; transporti paguhet sipas zonës.',
    returnsTitle: 'Kthimi i mallit',
    returns1: 'Brenda 5 ditëve nga pranimi',
    returns2: 'I papërdorur dhe në paketimin origjinal',
    returns3: 'Produktet me logo të printuar nuk kthehen',
    returnsText: 'Na shkruani në {email} me numrin e porosisë — ju dërgojmë udhëzimet.',
    returnsAddress: 'Adresa e kthimit: {address}',
    payTitle: 'Pagesa',
    payText: 'Në dorëzim, me transfertë bankare ose me kartelë. Bizneseve u lëshojmë faturë me TVSH.',
    faq1q: 'A mund të blej me copë?',
    faq1a: 'Shesim me pako me {n} copë — kështu çmimi për copë është më i ulëti ({price}/copë). Për sasi më të mëdha zgjidhni kartonin e plotë.',
    faq1aUnit: 'Ky produkt shitet me copë. Për sasi më të mëdha na dërgoni kërkesë — ju përgatisim ofertën.',
    faq2q: 'Si funksionojnë çmimet e shumicës?',
    faq2a: 'Zbritja llogaritet automatikisht në shportë për çdo produkt: {tiers}. Nuk ju duhet kod.',
    faq2aNone: 'Për sasi të mëdha dhe porosi të rregullta përgatisim ofertë të veçantë — na dërgoni kërkesë.',
    faq3q: 'Sa shpejt vjen dërgesa?',
    faq3a: 'Mitrovica dhe rrethina brenda 24 orësh, pjesa tjetër e Kosovës për 1–3 ditë pune. Transporti është falas për porositë mbi {amount}.',
    faq4q: 'A mund ta printoni logon tonë?',
    faq4a: 'Po — printimi me logo kushton {price} për pako, minimumi është 1 karton dhe prodhimi zgjat 7–10 ditë pune.',
    faq4aNo: 'Për këtë produkt jo, por printojmë logo në gotat F95, gotat Bodega, gotat e letrës dhe kutitë e kartonit — na dërgoni kërkesë.',
    faq5q: 'A keni mostra falas?',
    faq5a: 'Po. Për lokalet dërgojmë ose sjellim mostra falas — kërkojini te faqja „Për biznese“.',
    faq6q: 'Si mund ta kthej mallin?',
    faq6a: 'Brenda 5 ditëve nga pranimi, i papërdorur dhe në paketim origjinal — na shkruani në {email}.',
    compatEyebrow: 'Plotësoni porosinë',
    compatTitle: '*Përshtatet* me',
    relatedEyebrow: 'Nga e njëjta kategori',
    relatedTitle: 'Produkte të *ngjashme*',
    recentEyebrow: 'Historiku juaj',
    recentTitle: 'Shikuar *së fundmi*',
    seeCategory: 'Gjithë kategoria',
    zoom: 'Zmadho foton',
    prev: 'E mëparshmja',
    next: 'Tjetra',
    close: 'Mbyll',
    card_add: 'Shto 1 pako në shportë',
    card_quote: 'Kërko ofertë',
    card_contact: 'Na kontaktoni',
    card_out: 'Jashtë stoku',
    card_logo: 'Logo',
    card_logoTitle: 'Mund të printohet me logo',
    card_onRequest: 'Sipas kërkesës',
    card_options: 'Zgjidh',
  },
  en: {
    notFoundTitle: 'Product not found',
    notFoundText: 'The product you’re looking for is no longer available or the link is broken. Have a look at similar packaging in our range.',
    browse: 'Browse the range',
    backHome: 'Back to home',
    sku: 'SKU',
    share: 'Share',
    linkCopied: 'Link copied',
    vatIncl: 'VAT included · price per pack',
    vatInclPiece: 'VAT included',
    perPiece: '{price}/pc',
    packOf: '{n} pcs/pack',
    cartonInfo: 'Carton: {packs} packs · {pieces}',
    save: 'You save {amount}',
    inStock: 'In stock',
    inStockN: 'In stock · {n} packs',
    lowStock: 'Only {n} packs left',
    outStock: 'Temporarily out of stock',
    unitsInStock: 'In stock · {n} pcs',
    madeToOrder: 'Made to order',
    qtyLabel: 'Quantity',
    qtyPacks: 'packs',
    addCarton: '+ 1 carton',
    addCartonHint: 'Add a full carton ({packs} packs)',
    equals: '= {pieces}',
    breakdown: '{full} {cw} + {rest} packs',
    breakdownFull: '{full} {cw}',
    maxStock: 'Up to {n} packs — that’s what we have in stock',
    calcTitle: 'How many pieces do you need?',
    calcText: 'Type the number of pieces — we’ll work out the packs.',
    calcPh: 'e.g. 1200',
    calcResult: '{packs} packs = {pieces}',
    calcExtra: '+{n} pcs spare',
    calcExact: 'exact',
    calcUse: 'Use {packs} packs',
    tiersTitle: 'Wholesale prices',
    tiersText: 'The discount is applied automatically in the cart, per product.',
    tierQty: 'Quantity',
    tierPrice: 'Price / pack',
    tierPiece: 'Per piece',
    tierRange: '{a}–{b} packs',
    tierFrom: '{a}+ packs',
    tierCarton: '{n} {cw}',
    tierBase: 'base',
    nextTier: '{n} more packs → −{pct}%',
    nextTierAdd: 'Add {n}',
    tierReached: 'You’ve reached the best price −{pct}%',
    installTitle: 'Print your logo',
    installText: 'Your logo printed on every piece — made for cafés, bars and take-away.',
    installMin: 'Min. 1 carton ({packs} packs · {pieces})',
    installLead: 'Ready in 7–10 working days',
    installContact: 'After you order we’ll contact you for the logo file (PDF, AI, SVG or PNG).',
    installRaised: 'Quantity raised to 1 carton — the minimum for printing.',
    perPack: '/ pack',
    total: 'Total',
    tierBadge: 'wholesale −{pct}%',
    logoLine: 'Logo print · {qty} × {price}',
    piecesLine: '{pieces} · {price}/pc',
    youSave: 'You save {amount}',
    addToCart: 'Add to cart',
    addedShort: 'Added to cart',
    added: 'Added to cart',
    viewCart: 'View cart',
    wishAdd: 'Save to favourites',
    wishRemove: 'Remove from favourites',
    wishAdded: 'Saved to favourites',
    wishRemoved: 'Removed from favourites',
    oosTitle: 'Temporarily out of stock',
    oosText: 'We’re restocking — leave your details and we’ll let you know as soon as it arrives, or suggest an alternative.',
    oosCta: 'Contact us',
    oosAlt: 'See alternatives',
    contactTitle: 'Contact us',
    contactText: 'Leave your number — we’ll tell you as soon as it’s back in stock.',
    stockMsg: 'Please let me know when this is back in stock: {name} ({sku}).',
    deliveryTitle: 'Delivery',
    deliveryFast: '{zone}: within 24 h',
    deliveryZone: '{zone}: {days} working days',
    deliveryKosovo: 'All of Kosovo: {days} working days',
    freeOver: 'Free delivery over {amount}',
    freeLeft: '{amount} more for free delivery',
    freeReached: 'Delivery is free with this order',
    pickupLine: 'Free warehouse pickup',
    printNoFree: 'Logo printing doesn’t change the delivery fee.',
    help: 'Need larger quantities?',
    helpText: 'Call us or message us on WhatsApp',
    trust_samples: 'Free samples',
    trust_samplesText: 'Try before you order',
    trust_returns: '5-day returns',
    trust_returnsText: 'Unused, in original packaging',
    trust_cod: 'Cash on delivery',
    trust_codText: 'Pay when your order arrives',
    trust_invoice: 'Business invoices',
    trust_invoiceText: 'With business and VAT number',
    fitsTitle: 'Fits with',
    fitsAll: 'All',
    quickAdd: 'Add 1 pack',
    quoteBadge: 'Made to order',
    quoteOnly: 'Price on request',
    quotePriceNote: 'The price depends on quantity, size and number of colours.',
    quoteStepsTitle: 'How it works',
    quoteStep1: 'Send us your logo and quantity',
    quoteStep1Text: 'A sketch is enough — we help with the artwork.',
    quoteStep2: 'Quote and proof in 48 h',
    quoteStep2Text: 'No obligation, with exact per-piece prices.',
    quoteStep3: 'Production and delivery',
    quoteStep3Text: 'About {days} days from proof approval.',
    requestQuote: 'Request a quote',
    quoteTitle: 'Request a quote',
    quoteText: 'Leave your details — we’ll get back to you the same day with a quote.',
    quoteMsg: 'I’d like a quote for: {name}{opts}.',
    formEyebrow: 'No-obligation quote',
    formTitle: 'Request your *quote*',
    formText: 'Tell us what you need — we’ll prepare a quote and a proof within 48 hours.',
    formPoint1: 'Your logo (PDF, AI, SVG or PNG)',
    formPoint2: 'Rough quantity and sizes',
    formPoint3: 'Delivery city and deadline',
    formEmail: 'Or email us at',
    leadTime: 'Production time',
    leadValue: '~{n} days',
    tab_desc: 'Description',
    tab_specs: 'Specifications',
    tab_shipping: 'Delivery & returns',
    tab_faq: 'FAQ',
    highlights: 'At a glance',
    spec_sku: 'Product code',
    spec_category: 'Category',
    spec_unit: 'Sold per',
    spec_pack: 'Pieces per pack',
    spec_carton: 'Packs per carton',
    spec_cartonPieces: 'Pieces per carton',
    spec_piecePrice: 'Price per piece',
    spec_packPrice: 'Price per pack',
    spec_tiers: 'Wholesale',
    spec_logo: 'Logo print',
    spec_logoValue: '+{price} / pack · min. 1 carton · 7–10 working days',
    spec_logoNo: 'Not available for this product',
    spec_lead: 'Ready to ship',
    unit_pack: 'Pack of {n} pcs',
    unit_kom: 'Piece',
    unit_set: 'Set',
    unit_m: 'Metre',
    daysApprox: '~{n} days',
    daysWork: '{n} working days',
    tierLine: '{qty}: −{pct}%',
    zonesTitle: 'Delivery zones',
    daysValue: '{days} working days',
    freeOverText: 'Below that you only pay the zone fee. We deliver to your venue’s door.',
    pickup: 'Warehouse pickup',
    pickupText: '{address} — no delivery charge.',
    logoShipTitle: 'Orders with logo print',
    logoShipText: 'Printing takes 7–10 working days; delivery is charged per zone.',
    returnsTitle: 'Returns',
    returns1: 'Within 5 days of delivery',
    returns2: 'Unused and in the original packaging',
    returns3: 'Logo-printed items can’t be returned',
    returnsText: 'Email {email} with your order number — we’ll send you the instructions.',
    returnsAddress: 'Return address: {address}',
    payTitle: 'Payment',
    payText: 'Cash on delivery, bank transfer or card. Businesses get a VAT invoice.',
    faq1q: 'Can I buy single pieces?',
    faq1a: 'We sell in packs of {n} — that keeps the price per piece low ({price}/pc). For larger amounts, pick a full carton.',
    faq1aUnit: 'This product is sold per piece. For larger amounts send us a request — we’ll prepare a quote.',
    faq2q: 'How do wholesale prices work?',
    faq2a: 'The discount is applied automatically in the cart for each product: {tiers}. No code needed.',
    faq2aNone: 'For large quantities and regular orders we prepare a custom quote — send us a request.',
    faq3q: 'How fast is delivery?',
    faq3a: 'Mitrovica and surroundings within 24 h, the rest of Kosovo in 1–3 working days. Delivery is free on orders over {amount}.',
    faq4q: 'Can you print our logo?',
    faq4a: 'Yes — logo printing costs {price} per pack, the minimum is 1 carton and production takes 7–10 working days.',
    faq4aNo: 'Not on this product, but we print logos on F95 cups, Bodega cups, paper cups and cardboard boxes — send us a request.',
    faq5q: 'Do you have free samples?',
    faq5a: 'Yes. We send or bring free samples to venues — request them on the “For business” page.',
    faq6q: 'How do I return an order?',
    faq6a: 'Within 5 days of delivery, unused and in the original packaging — email {email}.',
    compatEyebrow: 'Complete your order',
    compatTitle: '*Fits* with',
    relatedEyebrow: 'From the same category',
    relatedTitle: 'Similar *products*',
    recentEyebrow: 'Your history',
    recentTitle: 'Recently *viewed*',
    seeCategory: 'Whole category',
    zoom: 'Enlarge image',
    prev: 'Previous',
    next: 'Next',
    close: 'Close',
    card_add: 'Add 1 pack to cart',
    card_quote: 'Request a quote',
    card_contact: 'Contact us',
    card_out: 'Out of stock',
    card_logo: 'Logo',
    card_logoTitle: 'Logo print available',
    card_onRequest: 'On request',
    card_options: 'Choose',
  },
});

export type PdKey = keyof (typeof PD)['me'] & string;

/** Money with cents only when needed ("3 €", "2,38 €"); `target` keeps the format stable while a tween runs. */
export function eur(v: number, lang: Lang, target = v) {
  return money(v, lang, { decimals: Math.round(target * 100) % 100 !== 0 });
}

/** Prices on a packaging shop always show cents: "2,50 €". */
export const eur2 = (v: number, lang: Lang) => money(v, lang);

/** "−10%" (EN) / "−10 %" (SQ, SR). */
export const pctOff = (pct: number, lang: Lang) => (lang === 'en' ? `−${pct}%` : `−${pct} %`);

/** Per-piece price text: "0,05 €/copë". */
export const piecePriceText = (v: number, lang: Lang, t: (k: 'perPiece', vars: Record<string, string>) => string) => t('perPiece', { price: moneyPiece(v, lang) });
