import { defineDict } from '@/i18n';
import type { Lang } from '@/lib/types';
import { money } from '@/lib/format';

/** Strings for the storefront product page (/proizvod/:slug). */
export const PD = defineDict({
  me: {
    notFoundTitle: 'Proizvod nije pronađen',
    notFoundText: 'Proizvod koji tražite više nije u ponudi ili je link neispravan. Pogledajte slične proizvode u našem asortimanu.',
    browse: 'Pogledaj ponudu',
    backHome: 'Na početnu',
    sku: 'Šifra',
    vatIncl: 'PDV uračunat',
    perPack: '{price} po paketu od {size} m²',
    regular: 'Redovna cijena',
    save: 'Uštedite {amount}',
    inStock: 'Na stanju',
    lowStock: 'Još samo {n} na stanju',
    madeToOrder: 'Po narudžbi · izrada ~{days} dana',
    delivery: 'Isporuka za ~{days} dana',
    quantity: 'Količina',
    length: 'Dužina',
    lengthHint: 'Sječemo po mjeri, u dužnim metrima.',
    calcTitle: 'Kalkulator potrošnje',
    calcText: 'Unesite površinu prostorije — izračunaćemo broj paketa.',
    area: 'Površina',
    areaPh: 'npr. 24',
    packsLabel: 'Broj paketa',
    waste: '+10% rezerve za sječenje',
    wasteHint: 'Preporučeno zbog sječenja i uklapanja šare.',
    pack_one: 'paket',
    pack_many: 'paketa',
    covers: 'pokriva vaših {area} m² + rezervu',
    coversNoWaste: 'pokriva vaših {area} m²',
    tooFew: 'Nedovoljno za {area} m² — dodajte pakete',
    manual: 'ručno podešeno',
    installTitle: 'Stručna ugradnja',
    installText: 'Montira naš tim, sa svim potrebnim materijalom. Odnosimo ambalažu i ostavljamo čist prostor.',
    installFree: 'Uz ugradnju je dostava besplatna',
    installAdd: 'Dodaj',
    total: 'Ukupno',
    goods: 'Proizvod',
    installation: 'Ugradnja',
    addToCart: 'Dodaj u korpu',
    addedShort: 'Dodato u korpu',
    added: 'Dodato u korpu',
    viewCart: 'Pogledaj korpu',
    wishAdd: 'Dodaj na listu želja',
    wishRemove: 'Ukloni sa liste želja',
    wishAdded: 'Sačuvano na listi želja',
    wishRemoved: 'Uklonjeno sa liste želja',
    share: 'Podijeli',
    linkCopied: 'Link je kopiran',
    quoteOnly: 'Cijena po mjeri',
    quoteFrom: 'Cijena po mjeri — od {price}',
    quoteLead: 'Svaki projekat izrađujemo po vašim mjerama. Pošaljite upit i dobićete preciznu ponudu u roku od 48 sati — bez obaveze.',
    quoteStep1: 'Besplatno mjerenje na vašoj adresi',
    quoteStep2: 'Projekat i precizna ponuda za 48 h',
    quoteStep3: 'Izrada i stručna ugradnja',
    requestQuote: 'Zatraži ponudu',
    quoteTitle: 'Zahtjev za ponudu',
    quoteText: 'Ostavite kontakt — javljamo se istog dana sa terminom mjerenja.',
    quoteMsg: 'Zanima me ponuda za: {name}{opts}.',
    help: 'Trebate savjet?',
    helpText: 'Pozovite nas ili pišite na WhatsApp',
    trust_measure: 'Besplatno mjerenje',
    trust_measureText: 'Dolazimo na adresu, bez obaveze',
    trust_warranty: 'Garancija {n} god.',
    trust_warrantyText: 'Pisana garancija i servis',
    trust_delivery: 'Dostava i ugradnja',
    trust_deliveryText: 'Širom Crne Gore, besplatno od {amount}',
    trust_cod: 'Plaćanje pouzećem',
    trust_codText: 'Platite tek kad preuzmete robu',
    trust_bank: 'Sigurno plaćanje',
    trust_bankText: 'Uplata na račun ili karticom',
    tab_desc: 'Opis',
    tab_specs: 'Specifikacije',
    tab_shipping: 'Dostava i ugradnja',
    highlights: 'Ukratko',
    spec_sku: 'Šifra proizvoda',
    spec_warranty: 'Garancija',
    spec_lead: 'Rok isporuke',
    spec_unit: 'Prodajna jedinica',
    spec_category: 'Kategorija',
    years: '{n} god.',
    daysApprox: '~{n} dana',
    unit_kom: 'Komad',
    unit_set: 'Set',
    unit_m: 'Dužni metar',
    unit_m2: 'Paket od {size} m²',
    zonesTitle: 'Zone dostave',
    zone: 'Zona',
    fee: 'Cijena',
    days: 'Rok',
    daysValue: '{days} radna dana',
    freeOver: 'Besplatna dostava za narudžbe od {amount}',
    freeOverText: 'Ispod tog iznosa plaćate samo cijenu zone. Dostavljamo do ulaza, a uz ugradnju i u prostoriju.',
    pickup: 'Preuzimanje u salonu',
    pickupText: '{address} — bez troškova dostave.',
    installHowTitle: 'Kako izgleda ugradnja',
    installHow1: 'Besplatno mjerenje i provjera podloge ili otvora',
    installHow2: 'Dogovor termina — dolazimo sa svim materijalom',
    installHow3: 'Montaža, čišćenje i odvoz ambalaže',
    installPrice: 'Cijena ugradnje: {price} / {unit}',
    installIncluded: 'Ugradnja je uključena u ponudu po mjeri.',
    installNone: 'Proizvod se isporučuje spreman za montažu, sa detaljnim uputstvom. Rado ćemo preporučiti provjerenog majstora.',
    payTitle: 'Plaćanje',
    payText: 'Pouzećem, uplatom na račun ili platnom karticom. Za veće narudžbe moguće je plaćanje u ratama.',
    relatedEyebrow: 'Iz iste kategorije',
    relatedTitle: 'Možda vam se *dopadne*',
    recentEyebrow: 'Vaša istorija',
    recentTitle: 'Nedavno *pregledano*',
    seeCategory: 'Sve iz kategorije',
    zoom: 'Uvećaj sliku',
    prev: 'Prethodna',
    next: 'Sljedeća',
    close: 'Zatvori',
    selected: 'Izabrano',
  },
  sq: {
    notFoundTitle: 'Produkti nuk u gjet',
    notFoundText: 'Produkti që kërkoni nuk është më në ofertë ose lidhja është e pasaktë. Shikoni produkte të ngjashme në asortimentin tonë.',
    browse: 'Shiko ofertën',
    backHome: 'Në ballinë',
    sku: 'Kodi',
    vatIncl: 'TVSH e përfshirë',
    perPack: '{price} për pako prej {size} m²',
    regular: 'Çmimi i rregullt',
    save: 'Kurseni {amount}',
    inStock: 'Në stok',
    lowStock: 'Vetëm {n} në stok',
    madeToOrder: 'Me porosi · prodhim ~{days} ditë',
    delivery: 'Dorëzim për ~{days} ditë',
    quantity: 'Sasia',
    length: 'Gjatësia',
    lengthHint: 'E presim sipas masës, në metra linearë.',
    calcTitle: 'Llogaritësi i sasisë',
    calcText: 'Shkruani sipërfaqen e dhomës — ne llogarisim numrin e pakove.',
    area: 'Sipërfaqja',
    areaPh: 'p.sh. 24',
    packsLabel: 'Numri i pakove',
    waste: '+10% rezervë për prerje',
    wasteHint: 'E rekomanduar për prerjet dhe përputhjen e motivit.',
    pack_one: 'pako',
    pack_many: 'pako',
    covers: 'mbulon {area} m² tuaja + rezervën',
    coversNoWaste: 'mbulon {area} m² tuaja',
    tooFew: 'Nuk mjafton për {area} m² — shtoni pako',
    manual: 'rregulluar manualisht',
    installTitle: 'Montim profesional',
    installText: 'Monton ekipi ynë, me të gjithë materialin e nevojshëm. Marrim ambalazhin dhe e lëmë hapësirën të pastër.',
    installFree: 'Me montim transporti është falas',
    installAdd: 'Shto',
    total: 'Totali',
    goods: 'Produkti',
    installation: 'Montimi',
    addToCart: 'Shto në shportë',
    addedShort: 'U shtua në shportë',
    added: 'U shtua në shportë',
    viewCart: 'Shiko shportën',
    wishAdd: 'Shto te të preferuarat',
    wishRemove: 'Hiq nga të preferuarat',
    wishAdded: 'U ruajt te të preferuarat',
    wishRemoved: 'U hoq nga të preferuarat',
    share: 'Ndaj',
    linkCopied: 'Lidhja u kopjua',
    quoteOnly: 'Çmim sipas masës',
    quoteFrom: 'Çmim sipas masës — nga {price}',
    quoteLead: 'Çdo projekt e prodhojmë sipas masave tuaja. Dërgoni kërkesën dhe merrni ofertë të saktë brenda 48 orëve — pa detyrim.',
    quoteStep1: 'Matje falas në adresën tuaj',
    quoteStep2: 'Projekt dhe ofertë e saktë për 48 orë',
    quoteStep3: 'Prodhim dhe montim profesional',
    requestQuote: 'Kërko ofertë',
    quoteTitle: 'Kërkesë për ofertë',
    quoteText: 'Lini kontaktin — ju telefonojmë të njëjtën ditë për terminin e matjes.',
    quoteMsg: 'Më intereson oferta për: {name}{opts}.',
    help: 'Ju duhet këshillë?',
    helpText: 'Na telefononi ose na shkruani në WhatsApp',
    trust_measure: 'Matje falas',
    trust_measureText: 'Vijmë në adresë, pa detyrim',
    trust_warranty: 'Garanci {n} vjet',
    trust_warrantyText: 'Garanci me shkrim dhe servis',
    trust_delivery: 'Transport dhe montim',
    trust_deliveryText: 'Në gjithë Malin e Zi, falas nga {amount}',
    trust_cod: 'Pagesë në dorëzim',
    trust_codText: 'Paguani kur ta merrni mallin',
    trust_bank: 'Pagesë e sigurt',
    trust_bankText: 'Transfertë bankare ose kartelë',
    tab_desc: 'Përshkrimi',
    tab_specs: 'Specifikimet',
    tab_shipping: 'Transporti dhe montimi',
    highlights: 'Shkurt',
    spec_sku: 'Kodi i produktit',
    spec_warranty: 'Garancia',
    spec_lead: 'Afati i dorëzimit',
    spec_unit: 'Njësia e shitjes',
    spec_category: 'Kategoria',
    years: '{n} vjet',
    daysApprox: '~{n} ditë',
    unit_kom: 'Copë',
    unit_set: 'Set',
    unit_m: 'Metër linear',
    unit_m2: 'Pako prej {size} m²',
    zonesTitle: 'Zonat e transportit',
    zone: 'Zona',
    fee: 'Çmimi',
    days: 'Afati',
    daysValue: '{days} ditë pune',
    freeOver: 'Transport falas për porosi nga {amount}',
    freeOverText: 'Nën këtë shumë paguani vetëm çmimin e zonës. Dorëzojmë deri te hyrja, e me montim edhe brenda në dhomë.',
    pickup: 'Marrje në sallon',
    pickupText: '{address} — pa kosto transporti.',
    installHowTitle: 'Si bëhet montimi',
    installHow1: 'Matje falas dhe kontroll i bazës ose hapjes',
    installHow2: 'Caktojmë terminin — vijmë me gjithë materialin',
    installHow3: 'Montim, pastrim dhe largim i ambalazhit',
    installPrice: 'Çmimi i montimit: {price} / {unit}',
    installIncluded: 'Montimi është i përfshirë në ofertën sipas masës.',
    installNone: 'Produkti dorëzohet gati për montim, me udhëzime të detajuara. Me kënaqësi ju rekomandojmë një mjeshtër të besuar.',
    payTitle: 'Pagesa',
    payText: 'Në dorëzim, me transfertë bankare ose me kartelë. Për porosi më të mëdha mundësohet pagesa me këste.',
    relatedEyebrow: 'Nga e njëjta kategori',
    relatedTitle: 'Mund t’ju *pëlqejë*',
    recentEyebrow: 'Historiku juaj',
    recentTitle: 'Shikuar *së fundmi*',
    seeCategory: 'Gjithë kategoria',
    zoom: 'Zmadho foton',
    prev: 'E mëparshmja',
    next: 'Tjetra',
    close: 'Mbyll',
    selected: 'Zgjedhur',
  },
  en: {
    notFoundTitle: 'Product not found',
    notFoundText: 'The product you’re looking for is no longer available or the link is broken. Have a look at similar products in our range.',
    browse: 'Browse the range',
    backHome: 'Back to home',
    sku: 'SKU',
    vatIncl: 'VAT included',
    perPack: '{price} per pack of {size} m²',
    regular: 'Regular price',
    save: 'You save {amount}',
    inStock: 'In stock',
    lowStock: 'Only {n} left in stock',
    madeToOrder: 'Made to order · ~{days} days',
    delivery: 'Delivered in ~{days} days',
    quantity: 'Quantity',
    length: 'Length',
    lengthHint: 'Cut to measure, sold per running metre.',
    calcTitle: 'Coverage calculator',
    calcText: 'Enter the room area — we’ll work out how many packs you need.',
    area: 'Area',
    areaPh: 'e.g. 24',
    packsLabel: 'Packs',
    waste: '+10% extra for cutting',
    wasteHint: 'Recommended for cuts and pattern matching.',
    pack_one: 'pack',
    pack_many: 'packs',
    covers: 'covers your {area} m² + allowance',
    coversNoWaste: 'covers your {area} m²',
    tooFew: 'Not enough for {area} m² — add packs',
    manual: 'adjusted manually',
    installTitle: 'Expert installation',
    installText: 'Fitted by our own team with all materials included. We take the packaging away and leave the room clean.',
    installFree: 'Delivery is free with installation',
    installAdd: 'Add',
    total: 'Total',
    goods: 'Product',
    installation: 'Installation',
    addToCart: 'Add to cart',
    addedShort: 'Added to cart',
    added: 'Added to cart',
    viewCart: 'View cart',
    wishAdd: 'Add to wishlist',
    wishRemove: 'Remove from wishlist',
    wishAdded: 'Saved to your wishlist',
    wishRemoved: 'Removed from your wishlist',
    share: 'Share',
    linkCopied: 'Link copied',
    quoteOnly: 'Made-to-measure price',
    quoteFrom: 'Made to measure — from {price}',
    quoteLead: 'Every project is built to your measurements. Send a request and get a precise quote within 48 hours — no obligation.',
    quoteStep1: 'Free measurement at your address',
    quoteStep2: 'Design and a precise quote in 48 h',
    quoteStep3: 'Production and expert installation',
    requestQuote: 'Request a quote',
    quoteTitle: 'Request a quote',
    quoteText: 'Leave your details — we’ll call you the same day to book a measurement.',
    quoteMsg: 'I’d like a quote for: {name}{opts}.',
    help: 'Need advice?',
    helpText: 'Call us or message us on WhatsApp',
    trust_measure: 'Free measurement',
    trust_measureText: 'We come to you, no obligation',
    trust_warranty: '{n}-year warranty',
    trust_warrantyText: 'Written warranty and service',
    trust_delivery: 'Delivery & fitting',
    trust_deliveryText: 'Across Montenegro, free from {amount}',
    trust_cod: 'Cash on delivery',
    trust_codText: 'Pay when your order arrives',
    trust_bank: 'Secure payment',
    trust_bankText: 'Bank transfer or card',
    tab_desc: 'Description',
    tab_specs: 'Specifications',
    tab_shipping: 'Delivery & installation',
    highlights: 'At a glance',
    spec_sku: 'Product code',
    spec_warranty: 'Warranty',
    spec_lead: 'Lead time',
    spec_unit: 'Sold per',
    spec_category: 'Category',
    years: '{n} years',
    daysApprox: '~{n} days',
    unit_kom: 'Piece',
    unit_set: 'Set',
    unit_m: 'Running metre',
    unit_m2: 'Pack of {size} m²',
    zonesTitle: 'Delivery zones',
    zone: 'Zone',
    fee: 'Price',
    days: 'Time',
    daysValue: '{days} working days',
    freeOver: 'Free delivery on orders from {amount}',
    freeOverText: 'Below that you only pay the zone fee. We deliver to your door — and right into the room when we install.',
    pickup: 'Showroom pickup',
    pickupText: '{address} — no delivery charge.',
    installHowTitle: 'How installation works',
    installHow1: 'Free measurement and a check of the subfloor or opening',
    installHow2: 'We book a date and arrive with all materials',
    installHow3: 'Fitting, clean-up and packaging removal',
    installPrice: 'Installation price: {price} / {unit}',
    installIncluded: 'Installation is included in the made-to-measure quote.',
    installNone: 'Supplied ready to fit, with detailed instructions. We’re happy to recommend a trusted installer.',
    payTitle: 'Payment',
    payText: 'Cash on delivery, bank transfer or card. Instalment payments are available for larger orders.',
    relatedEyebrow: 'From the same category',
    relatedTitle: 'You might also *like*',
    recentEyebrow: 'Your history',
    recentTitle: 'Recently *viewed*',
    seeCategory: 'Whole category',
    zoom: 'Enlarge image',
    prev: 'Previous',
    next: 'Next',
    close: 'Close',
    selected: 'Selected',
  },
});

/** "1 paket / 2 paketa", "1 pako", "1 pack / 2 packs". */
export function packWord(n: number, lang: Lang, one: string, many: string) {
  if (lang === 'en') return n === 1 ? one : many;
  if (lang === 'me') return n % 10 === 1 && n % 100 !== 11 ? one : many;
  return one;
}

/** Money with cents only when needed ("289 €", "241,98 €"); `target` keeps the format stable while a tween runs. */
export function eur(v: number, lang: Lang, target = v) {
  return money(v, lang, { decimals: Math.round(target * 100) % 100 !== 0 });
}
